var annotated_dup =
[
    [ "org", null, [
      [ "gnu", null, [
        [ "pilotlink", "namespaceorg_1_1gnu_1_1pilotlink.html", [
          [ "AddressAppInfo", "classorg_1_1gnu_1_1pilotlink_1_1AddressAppInfo.html", "classorg_1_1gnu_1_1pilotlink_1_1AddressAppInfo" ],
          [ "AddressRecord", "classorg_1_1gnu_1_1pilotlink_1_1AddressRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1AddressRecord" ],
          [ "AppInfo", "classorg_1_1gnu_1_1pilotlink_1_1AppInfo.html", "classorg_1_1gnu_1_1pilotlink_1_1AppInfo" ],
          [ "DatabaseExistsException", "classorg_1_1gnu_1_1pilotlink_1_1DatabaseExistsException.html", "classorg_1_1gnu_1_1pilotlink_1_1DatabaseExistsException" ],
          [ "DatabaseNotFoundException", "classorg_1_1gnu_1_1pilotlink_1_1DatabaseNotFoundException.html", "classorg_1_1gnu_1_1pilotlink_1_1DatabaseNotFoundException" ],
          [ "DatebookAppInfo", "classorg_1_1gnu_1_1pilotlink_1_1DatebookAppInfo.html", "classorg_1_1gnu_1_1pilotlink_1_1DatebookAppInfo" ],
          [ "DatebookRecord", "classorg_1_1gnu_1_1pilotlink_1_1DatebookRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1DatebookRecord" ],
          [ "DBInfo", "classorg_1_1gnu_1_1pilotlink_1_1DBInfo.html", "classorg_1_1gnu_1_1pilotlink_1_1DBInfo" ],
          [ "FTB3CostCatRecord", "classorg_1_1gnu_1_1pilotlink_1_1FTB3CostCatRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1FTB3CostCatRecord" ],
          [ "FTB3TripRecord", "classorg_1_1gnu_1_1pilotlink_1_1FTB3TripRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1FTB3TripRecord" ],
          [ "FTB3VehicleRecord", "classorg_1_1gnu_1_1pilotlink_1_1FTB3VehicleRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1FTB3VehicleRecord" ],
          [ "MemoRecord", "classorg_1_1gnu_1_1pilotlink_1_1MemoRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1MemoRecord" ],
          [ "MidiRecord", "classorg_1_1gnu_1_1pilotlink_1_1MidiRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1MidiRecord" ],
          [ "PilotLink", "classorg_1_1gnu_1_1pilotlink_1_1PilotLink.html", "classorg_1_1gnu_1_1pilotlink_1_1PilotLink" ],
          [ "PilotLinkException", "classorg_1_1gnu_1_1pilotlink_1_1PilotLinkException.html", "classorg_1_1gnu_1_1pilotlink_1_1PilotLinkException" ],
          [ "RawAppInfo", "classorg_1_1gnu_1_1pilotlink_1_1RawAppInfo.html", "classorg_1_1gnu_1_1pilotlink_1_1RawAppInfo" ],
          [ "RawRecord", "classorg_1_1gnu_1_1pilotlink_1_1RawRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1RawRecord" ],
          [ "Record", "classorg_1_1gnu_1_1pilotlink_1_1Record.html", "classorg_1_1gnu_1_1pilotlink_1_1Record" ],
          [ "SysInfo", "classorg_1_1gnu_1_1pilotlink_1_1SysInfo.html", "classorg_1_1gnu_1_1pilotlink_1_1SysInfo" ],
          [ "ToDoRecord", "classorg_1_1gnu_1_1pilotlink_1_1ToDoRecord.html", "classorg_1_1gnu_1_1pilotlink_1_1ToDoRecord" ],
          [ "User", "classorg_1_1gnu_1_1pilotlink_1_1User.html", "classorg_1_1gnu_1_1pilotlink_1_1User" ],
          [ "Version", "classorg_1_1gnu_1_1pilotlink_1_1Version.html", "classorg_1_1gnu_1_1pilotlink_1_1Version" ]
        ] ]
      ] ]
    ] ],
    [ "pisock", "namespacepisock.html", [
      [ "_object", "classpisock_1_1__object.html", null ],
      [ "CardInfo", "classpisock_1_1CardInfo.html", "classpisock_1_1CardInfo" ],
      [ "CardInfoPtr", "classpisock_1_1CardInfoPtr.html", "classpisock_1_1CardInfoPtr" ],
      [ "DBInfo", "classpisock_1_1DBInfo.html", "classpisock_1_1DBInfo" ],
      [ "DBInfoPtr", "classpisock_1_1DBInfoPtr.html", "classpisock_1_1DBInfoPtr" ],
      [ "DBSizeInfo", "classpisock_1_1DBSizeInfo.html", "classpisock_1_1DBSizeInfo" ],
      [ "DBSizeInfoPtr", "classpisock_1_1DBSizeInfoPtr.html", "classpisock_1_1DBSizeInfoPtr" ],
      [ "NetSyncInfo", "classpisock_1_1NetSyncInfo.html", "classpisock_1_1NetSyncInfo" ],
      [ "NetSyncInfoPtr", "classpisock_1_1NetSyncInfoPtr.html", "classpisock_1_1NetSyncInfoPtr" ],
      [ "pi_socket_list_t", "classpisock_1_1pi__socket__list__t.html", "classpisock_1_1pi__socket__list__t" ],
      [ "pi_socket_list_tPtr", "classpisock_1_1pi__socket__list__tPtr.html", "classpisock_1_1pi__socket__list__tPtr" ],
      [ "pi_socket_t", "classpisock_1_1pi__socket__t.html", "classpisock_1_1pi__socket__t" ],
      [ "pi_socket_tPtr", "classpisock_1_1pi__socket__tPtr.html", "classpisock_1_1pi__socket__tPtr" ],
      [ "PilotUser", "classpisock_1_1PilotUser.html", "classpisock_1_1PilotUser" ],
      [ "PilotUserPtr", "classpisock_1_1PilotUserPtr.html", "classpisock_1_1PilotUserPtr" ],
      [ "SysInfo", "classpisock_1_1SysInfo.html", "classpisock_1_1SysInfo" ],
      [ "SysInfoPtr", "classpisock_1_1SysInfoPtr.html", "classpisock_1_1SysInfoPtr" ],
      [ "VFSAnyMountParam", "classpisock_1_1VFSAnyMountParam.html", "classpisock_1_1VFSAnyMountParam" ],
      [ "VFSAnyMountParamPtr", "classpisock_1_1VFSAnyMountParamPtr.html", "classpisock_1_1VFSAnyMountParamPtr" ],
      [ "VFSDirInfo", "classpisock_1_1VFSDirInfo.html", "classpisock_1_1VFSDirInfo" ],
      [ "VFSDirInfoPtr", "classpisock_1_1VFSDirInfoPtr.html", "classpisock_1_1VFSDirInfoPtr" ],
      [ "VFSInfo", "classpisock_1_1VFSInfo.html", "classpisock_1_1VFSInfo" ],
      [ "VFSInfoPtr", "classpisock_1_1VFSInfoPtr.html", "classpisock_1_1VFSInfoPtr" ],
      [ "VFSSlotMountParam", "classpisock_1_1VFSSlotMountParam.html", "classpisock_1_1VFSSlotMountParam" ],
      [ "VFSSlotMountParamPtr", "classpisock_1_1VFSSlotMountParamPtr.html", "classpisock_1_1VFSSlotMountParamPtr" ]
    ] ],
    [ "pisocktests", "namespacepisocktests.html", [
      [ "OfflineTestCase", "classpisocktests_1_1OfflineTestCase.html", "classpisocktests_1_1OfflineTestCase" ],
      [ "OnlineTestCase", "classpisocktests_1_1OnlineTestCase.html", "classpisocktests_1_1OnlineTestCase" ]
    ] ],
    [ "_RecordQueue", "struct__RecordQueue.html", "struct__RecordQueue" ],
    [ "_RecordQueueList", "struct__RecordQueueList.html", "struct__RecordQueueList" ],
    [ "AcceptCallback", "structAcceptCallback.html", "structAcceptCallback" ],
    [ "adrtest", "classadrtest.html", "classadrtest" ],
    [ "cardreport_s", "structcardreport__s.html", "structcardreport__s" ],
    [ "Command", "structCommand.html", "structCommand" ],
    [ "datebooktst", "classdatebooktst.html", "classdatebooktst" ],
    [ "db", "structdb.html", "structdb" ],
    [ "filename_array", "structfilename__array.html", "structfilename__array" ],
    [ "klsi_port_settings", "structklsi__port__settings.html", "structklsi__port__settings" ],
    [ "MainDBImgRecord", "structMainDBImgRecord.html", "structMainDBImgRecord" ],
    [ "MidiMgr", "classMidiMgr.html", "classMidiMgr" ],
    [ "Packer", "structPacker.html", "structPacker" ],
    [ "palm_ext_connection_info", "structpalm__ext__connection__info.html", "structpalm__ext__connection__info" ],
    [ "PalmPixState_pi_file", "structPalmPixState__pi__file.html", "structPalmPixState__pi__file" ],
    [ "PalmPixState_pi_socket", "structPalmPixState__pi__socket.html", "structPalmPixState__pi__socket" ],
    [ "pdb_t", "structpdb__t.html", "structpdb__t" ],
    [ "PisockState", "structPisockState.html", "structPisockState" ],
    [ "PySwigObject", "structPySwigObject.html", "structPySwigObject" ],
    [ "PySwigPacked", "structPySwigPacked.html", "structPySwigPacked" ],
    [ "recInfo_t", "structrecInfo__t.html", "structrecInfo__t" ],
    [ "record", "structrecord.html", "structrecord" ],
    [ "ss_state", "structss__state.html", "structss__state" ],
    [ "STR_EXTSETBAUDRATE", "structSTR__EXTSETBAUDRATE.html", "structSTR__EXTSETBAUDRATE" ],
    [ "svc_info_t", "structsvc__info__t.html", "structsvc__info__t" ],
    [ "swig_cast_info", "structswig__cast__info.html", "structswig__cast__info" ],
    [ "swig_const_info", "structswig__const__info.html", "structswig__const__info" ],
    [ "swig_globalvar", "structswig__globalvar.html", "structswig__globalvar" ],
    [ "swig_module_info", "structswig__module__info.html", "structswig__module__info" ],
    [ "swig_type_info", "structswig__type__info.html", "structswig__type__info" ],
    [ "swig_varlinkobject", "structswig__varlinkobject.html", "structswig__varlinkobject" ],
    [ "tcl_e", "structtcl__e.html", "structtcl__e" ],
    [ "test", "classtest.html", "classtest" ],
    [ "TestTodos", "classTestTodos.html", "classTestTodos" ],
    [ "usb_connection_t", "structusb__connection__t.html", "structusb__connection__t" ],
    [ "visor_connection_info", "structvisor__connection__info.html", "structvisor__connection__info" ]
];