pilot-link: libpisock/appinfo.c File Reference
appinfo.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pi-macros.h"
#include "pi-appinfo.h"
Functions
int pack_CategoryAppInfo (const CategoryAppInfo_t *ai, unsigned char *record, size_t len)
int unpack_CategoryAppInfo (CategoryAppInfo_t *ai, const unsigned char *record, size_t len)
Function Documentation
pack_CategoryAppInfo()
int pack_CategoryAppInfo (const CategoryAppInfo_t * ai, unsigned char * record, size_t len)
{
    int     i,
        rec;
    unsigned char *start = record;
    if (!record) {
        return 2 + 16 * 16 + 16 + 4;
    }
    if (len < (2 + 16 * 16 + 16 + 4))
        return 0;   /* not enough room */
    rec = 0;
    for (i = 0; i < 16; i++) {
        if (ai->renamed[i])
            rec |= (1 << i);
    }
    set_short(record, rec);
    record += 2;
    for (i = 0; i < 16; i++) {
        memcpy(record, ai->name[i], 16);
        record += 16;
    }
    memcpy(record, ai->ID, 16);
    record += 16;
    set_byte(record, ai->lastUniqueID);
    record++;
    set_byte(record, 0);        /* gapfill */
    set_short(record + 1, 0);   /* gapfill */
    record += 3;
    return (record - start);
}
Referenced by pack_AddressAppInfo(), pack_AppointmentAppInfo(), pack_CalendarAppInfo(), pack_ContactAppInfo(), pack_ExpenseAppInfo(), pack_HiNoteAppInfo(), pack_MailAppInfo(), pack_MemoAppInfo(), pack_MoneyAppInfo(), pack_NotePadAppInfo(), pack_ToDoAppInfo(), and pack_VeoAppInfo().
unpack_CategoryAppInfo()
int unpack_CategoryAppInfo (CategoryAppInfo_t * ai, const unsigned char * record, size_t len)
{
    int     i,
        rec;
    if (len < 2 + 16 * 16 + 16 + 4)
        return 0;
    rec = get_short(record);
    for (i = 0; i < 16; i++) {
        if (rec & (1 << i))
            ai->renamed[i] = 1;
        else
            ai->renamed[i] = 0;
    }
    record += 2;
    for (i = 0; i < 16; i++) {
        memcpy(ai->name[i], record, 16);
        record += 16;
    }
    memcpy(ai->ID, record, 16);
    record += 16;
    ai->lastUniqueID = get_byte(record);
    record += 4;
    return 2 + 16 * 16 + 16 + 4;
}
Referenced by unpack_AddressAppInfo(), unpack_AppointmentAppInfo(), unpack_CalendarAppInfo(), unpack_ContactAppInfo(), unpack_ExpenseAppInfo(), unpack_HiNoteAppInfo(), unpack_MailAppInfo(), unpack_MemoAppInfo(), unpack_MoneyAppInfo(), unpack_NotePadAppInfo(), unpack_ToDoAppInfo(), unpack_VeoAppInfo(), and unpack_VersaMailAppInfo().