pilot-link: libpisock/blob.c File Reference
blob.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include "pi-macros.h"
#include "pi-blob.h"
Functions
Blob_t * dup_Blob (const Blob_t *blob)
void free_Blob (Blob_t *blob)
int pack_Blob (const Blob_t *blob, pi_buffer_t *buf)
int unpack_Blob_p (Blob_t *blob, const unsigned char *data, const size_t position)
Function Documentation
dup_Blob()
Blob_t * dup_Blob (const Blob_t * blob)
{
    if(NULL == blob) {
        return NULL;
    }
    Blob_t *retval = (Blob_t*)malloc(sizeof(Blob_t));
    if(NULL == retval) {
        errno = ENOMEM;
        return NULL;
    }
    memcpy(retval->type, blob->type, 4);
    retval->length = blob->length;
    if(blob->length > 0) {
        retval->data = (uint8_t *)malloc(blob->length);
        if(NULL == retval->data) {
            errno = ENOMEM;
            return NULL;
        } else {
            memcpy(retval->data, blob->data, blob->length);
        }
    } else {
        retval->data = NULL;
    }
    return retval;
}
References uint8_t.
Referenced by copy_CalendarEvent().
free_Blob()
void free_Blob (Blob_t * blob)
{
    if(NULL != blob->data) {
        free(blob->data);
        blob->data = NULL;
    }
}
Referenced by free_CalendarEvent().
pack_Blob()
int pack_Blob (const Blob_t * blob, pi_buffer_t * buf)
{
    size_t offset;
    offset = buf->used;
    pi_buffer_expect(buf, buf->used + 6 + blob->length);
    buf->used = buf->used + 6 + blob->length;
    memcpy(buf->data+offset, blob->type, 4);
    offset += 4;
    set_short(buf->data+offset, blob->length);
    offset += 2;
    memcpy(buf->data+offset, blob->data, blob->length);
    offset += blob->length;
    return 0;
}
References buf, and pi_buffer_expect().
Referenced by pack_CalendarEvent().
unpack_Blob_p()
int unpack_Blob_p (Blob_t * blob, const unsigned char * data, const size_t position)
{
    size_t localPosition = position;
    memcpy(blob->type, (char *)data+localPosition, 4);
    localPosition += 4;
    //printf("blob->type = %c %c %c %c\n", blob->type[0], blob->type[1], blob->type[2], blob->type[3]);
    blob->length = get_short(data+localPosition);
    localPosition += 2;
    if(blob->length > 0) {
        //printf("blob->length = %d\n", blob->length);
        blob->data = (uint8_t *)malloc(blob->length);
        if(NULL == blob->data) {
            printf("Malloc failed!\n");
            return -1;
        } else {
            memcpy(blob->data, data+localPosition, blob->length);
        }
        localPosition += blob->length;
    }
    return localPosition - position;
}
References uint8_t.
Referenced by unpack_CalendarEvent().