pilot-link: libpisock/bluetooth.c File Reference
bluetooth.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <bluetooth/bluetooth.h>
#include <bluetooth/rfcomm.h>
#include <bluetooth/hci.h>
#include <bluetooth/hci_lib.h>
#include "pi-debug.h"
#include "pi-source.h"
#include "pi-socket.h"
#include "pi-bluetooth.h"
#include "pi-cmp.h"
#include "pi-net.h"
#include "pi-error.h"
#include "pi-serial.h"
#include "pi-util.h"
#include <bluetooth/sdp.h>
#include <bluetooth/sdp_lib.h>
Data Structures
struct svc_info_t
Macros
#define HOTSYNC_CHANNEL 22
Functions
static int add_hotsync (sdp_session_t *session, sdp_record_t *rec, bdaddr_t *interface, svc_info_t *si, uint32_t *handle, int *channel_ret)
static int deregister_sdp (uint32_t handle, sdp_session_t *sess)
static int pi_bluetooth_accept (pi_socket_t *ps, struct sockaddr *addr, size_t *addrlen)
static int pi_bluetooth_accept_rfcomm (struct pi_socket *ps, const char *device, struct sockaddr_rc *peeraddr, unsigned int *peeraddrlen)
static int pi_bluetooth_bind (pi_socket_t *ps, struct sockaddr *addr, size_t addrlen)
static int pi_bluetooth_close (pi_socket_t *ps)
static int pi_bluetooth_connect (pi_socket_t *ps, struct sockaddr *addr, size_t addrlen)
pi_device_t * pi_bluetooth_device (int type)
static void pi_bluetooth_device_free (pi_device_t *dev)
static int pi_bluetooth_flush (pi_socket_t *ps, int flags)
static int pi_bluetooth_getsockopt (pi_socket_t *ps, int level, int option_name, void *option_value, size_t *option_len)
static int pi_bluetooth_listen (pi_socket_t *ps, int backlog)
static int pi_bluetooth_open (struct pi_socket *ps, struct pi_sockaddr *addr, int addrlen)
static pi_protocol_t * pi_bluetooth_protocol (pi_device_t *dev)
static pi_protocol_t * pi_bluetooth_protocol_dup (pi_protocol_t *prot)
static void pi_bluetooth_protocol_free (pi_protocol_t *prot)
static ssize_t pi_bluetooth_read (struct pi_socket *ps, pi_buffer_t *buf, size_t len, int flags)
static void pi_bluetooth_register_hotsync_sdp (struct pi_bluetooth_data *data)
static int pi_bluetooth_setsockopt (pi_socket_t *ps, int level, int option_name, const void *option_value, size_t *option_len)
static void pi_bluetooth_unregister_hotsync_sdp (struct pi_bluetooth_data *data)
static ssize_t pi_bluetooth_write (struct pi_socket *ps, const unsigned char *buf, size_t len, int flags)
int pi_socket_init (pi_socket_t *ps)
static int register_sdp (uint32_t *handle, int *channel, sdp_session_t **sess)
Variables
static unsigned char hotsync_uuid []
Macro Definition Documentation
HOTSYNC_CHANNEL
#define HOTSYNC_CHANNEL 22
Referenced by add_hotsync().
Function Documentation
add_hotsync()
static int add_hotsync (sdp_session_t * session, sdp_record_t * rec, bdaddr_t * interface, svc_info_t * si, uint32_t * handle, int * channel_ret) static
{
    sdp_record_t record;
    sdp_list_t *root, *svclass, *proto;
    uuid_t root_uuid, svclass_uuid, l2cap_uuid, rfcomm_uuid;
    uint8_t channel = HOTSYNC_CHANNEL;
    memset(&record, 0, sizeof(record));
    record.handle = 0xffffffff;
    sdp_uuid16_create(&root_uuid, PUBLIC_BROWSE_GROUP);
    root = sdp_list_append(NULL, &root_uuid);
    sdp_set_browse_groups(&record, root);
    sdp_uuid16_create(&l2cap_uuid, L2CAP_UUID);
    proto = sdp_list_append(NULL, sdp_list_append(NULL, &l2cap_uuid));
    sdp_uuid16_create(&rfcomm_uuid, RFCOMM_UUID);
    proto = sdp_list_append(proto, sdp_list_append(
    sdp_list_append(NULL, &rfcomm_uuid), sdp_data_alloc(SDP_UINT8, &channel)));
    sdp_set_access_protos(&record, sdp_list_append(NULL, proto));
    sdp_uuid128_create(&svclass_uuid, (void *) hotsync_uuid);
    svclass = sdp_list_append(NULL, &svclass_uuid);
    sdp_set_service_classes(&record, svclass);
    sdp_set_info_attr(&record, "PalmOS HotSync", NULL, NULL);
    if (sdp_device_record_register(session, interface, &record, 0) < 0) {
        LOG((PI_DBG_DEV, PI_DBG_LVL_ERR,
            "bluetooth: service record registration failed\n"));
        return -1;
    }
    *handle = record.handle;
    *channel_ret = HOTSYNC_CHANNEL;
    return 0;
}
References HOTSYNC_CHANNEL, hotsync_uuid, and uint8_t.
Referenced by register_sdp().
deregister_sdp()
static int deregister_sdp (uint32_t handle, sdp_session_t * sess) static
{
    uint32_t range = 0x0000ffff;
    sdp_list_t *attr;
    sdp_record_t *rec;
    bdaddr_t interface;
    if (!sess)
        return 0;
    bacpy(&interface, BDADDR_ANY);
    attr = sdp_list_append(0, &range);
    rec = sdp_service_attr_req(sess, handle, SDP_ATTR_REQ_RANGE, attr);
    sdp_list_free(attr, 0);
    if (!rec) {
        LOG((PI_DBG_DEV, PI_DBG_LVL_ERR,
            "bluetooth: service record not found\n"));
        sdp_close(sess);
        return -1;
    }
    if (sdp_record_unregister(sess, rec)) {
        LOG((PI_DBG_DEV, PI_DBG_LVL_ERR,
            "bluetooth: failed to unregister service record: %s\n",
            strerror(errno)));
        sdp_close(sess);
        return -1;
    }
    LOG((PI_DBG_DEV, PI_DBG_LVL_INFO, "bluetooth: service record deleted\n"));
    sdp_close(sess);
    return 0;
}
References uint32_t.
Referenced by pi_bluetooth_unregister_hotsync_sdp().
pi_bluetooth_accept()
static int pi_bluetooth_accept (pi_socket_t * ps, struct sockaddr * addr, size_t * addrlen) static
{
    struct pi_bluetooth_data *data =
        (struct  pi_bluetooth_data *)ps->device->data;
    struct sockaddr_rc peeraddr;
    unsigned int peeraddrlen = sizeof(peeraddr);
    int sd;
    /* Wait for data */
    sd = pi_bluetooth_accept_rfcomm(ps, data->device, &peeraddr, &peeraddrlen);
    if (sd < 0) {
        pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
        return -1;
    }
    if (pi_socket_setsd(ps, sd) < 0)
        return -1;
    pi_socket_init(ps);
    if (ps->type == PI_SOCK_STREAM) {
        switch (ps->cmd) {
        case PI_CMD_CMP:
            if (cmp_rx_handshake(ps, 0, 0) < 0)
                return -1;
            break;
        case PI_CMD_NET:
            if (net_rx_handshake(ps) < 0)
                return -1;
            break;
        }
        ps->dlprecord = 0;
    }
    data->timeout = 0;
    ps->command = 0;
    ps->state = PI_SOCK_CONN_ACCEPT;
    return ps->sd;
}
References cmp_rx_handshake(), net_rx_handshake(), pi_bluetooth_accept_rfcomm(), pi_set_error(), pi_socket_init(), pi_socket_setsd(), and sd.
Referenced by pi_bluetooth_device().
pi_bluetooth_accept_rfcomm()
static int pi_bluetooth_accept_rfcomm (struct pi_socket * ps, const char * device, struct sockaddr_rc * peeraddr, unsigned int * peeraddrlen) static
{
    int rfcommfd;
    rfcommfd = accept(ps->sd, (struct sockaddr *)peeraddr, peeraddrlen);
    if (rfcommfd < 0) {
        pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
        return -1;
    }
    /* Check whether we need to really accept this connection */
    if (device[0] != '\0' && strcmp (device, "any") != 0) {
        bdaddr_t tmp;
        if (str2ba (device, &tmp) < 0) {
            close (rfcommfd);
            return -1;
        }
        if (bacmp (&tmp, &(peeraddr->rc_bdaddr)) != 0) {
            close (rfcommfd);
            return -1;
        }
    }
    return rfcommfd;
}
References pi_set_error().
Referenced by pi_bluetooth_accept().
pi_bluetooth_bind()
static int pi_bluetooth_bind (pi_socket_t * ps, struct sockaddr * addr, size_t addrlen) static
{
    struct pi_sockaddr *pa = (struct pi_sockaddr *) addr;
    struct pi_bluetooth_data *data =
        (struct pi_bluetooth_data *)ps->device->data;
    char *device = pa->pi_device;
    struct sockaddr_rc bindaddr;
    if (pi_bluetooth_open(ps, pa, addrlen) == -1)
        return -1;      /* errno already set */
    data->device = strdup (device);
    bindaddr.rc_family = AF_BLUETOOTH;
    bacpy(&bindaddr.rc_bdaddr, BDADDR_ANY);
    bindaddr.rc_channel = data->channel;
    if (bind(ps->sd, (struct sockaddr *)&bindaddr, sizeof(bindaddr)) < 0) {
        pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
        return -1;
    }
    ps->laddr       = malloc(addrlen);
    memcpy(ps->laddr, addr, addrlen);
    ps->laddrlen    = addrlen;
        return 0;
}
References pi_bluetooth_open(), pi_set_error(), and strdup().
Referenced by pi_bluetooth_device().
pi_bluetooth_close()
static int pi_bluetooth_close (pi_socket_t * ps) static
{
    if (ps->laddr) {
        free(ps->laddr);
        ps->laddr = NULL;
    }
    if (ps->raddr) {
        free(ps->raddr);
        ps->raddr = NULL;
    }
    return 0;
}
Referenced by pi_bluetooth_device().
pi_bluetooth_connect()
static int pi_bluetooth_connect (pi_socket_t * ps, struct sockaddr * addr, size_t addrlen) static
{
    ps->raddr       = malloc(addrlen);
    memcpy(ps->raddr, addr, addrlen);
    ps->raddrlen    = addrlen;
    ps->laddr       = malloc(addrlen);
    memcpy(ps->laddr, addr, addrlen);
    ps->laddrlen    = addrlen;
    if ((   ps->type == PI_SOCK_STREAM &&
            ps->cmd  == PI_CMD_CMP) &&
            cmp_tx_handshake(ps) < 0)
    {
        pi_close(ps->sd);
        return -1;
    }
    ps->state = PI_SOCK_CONN_INIT;
    ps->command = 0;
    return 0;
}
References cmp_tx_handshake(), and pi_close().
Referenced by pi_bluetooth_device().
pi_bluetooth_device()
pi_device_t * pi_bluetooth_device (int type)
{
    pi_device_t *dev;
    struct  pi_bluetooth_data *data;
    dev = (pi_device_t *) malloc(sizeof (pi_device_t));
    if (dev == NULL)
        return NULL;
    data = (struct pi_bluetooth_data *) malloc(sizeof (struct pi_bluetooth_data));
    if (data == NULL) {
        free(dev);
        return NULL;
    }
    dev->free       = pi_bluetooth_device_free;
    dev->protocol   = pi_bluetooth_protocol;
    dev->bind       = pi_bluetooth_bind;
    dev->listen     = pi_bluetooth_listen;
    dev->accept     = pi_bluetooth_accept;
    dev->connect    = pi_bluetooth_connect;
    dev->close      = pi_bluetooth_close;
    data->timeout   = 0;
    dev->data       = data;
    return dev;
}
References pi_bluetooth_accept(), pi_bluetooth_bind(), pi_bluetooth_close(), pi_bluetooth_connect(), pi_bluetooth_device_free(), pi_bluetooth_listen(), and pi_bluetooth_protocol().
Referenced by pi_devsocket().
pi_bluetooth_device_free()
static void pi_bluetooth_device_free (pi_device_t * dev) static
{
    struct pi_bluetooth_data *data;
    ASSERT (dev != NULL);
    if (dev->data) {
        data = dev->data;
        pi_bluetooth_unregister_hotsync_sdp (data);
        if (data->device)
        free (data->device);
        free(dev->data);
    }
    free(dev);
}
References pi_bluetooth_unregister_hotsync_sdp().
Referenced by pi_bluetooth_device().
pi_bluetooth_flush()
static int pi_bluetooth_flush (pi_socket_t * ps, int flags) static
{
    char buf[256];
    int fl;
    if (flags & PI_FLUSH_INPUT) {
        if ((fl = fcntl(ps->sd, F_GETFL, 0)) != -1) {
            fcntl(ps->sd, F_SETFL, fl | O_NONBLOCK);
            while (read(ps->sd, buf, sizeof(buf)) > 0)
                ;
            fcntl(ps->sd, F_SETFL, fl);
        }
    }
    return 0;
}
References buf, flags, and O_NONBLOCK.
Referenced by pi_bluetooth_protocol().
pi_bluetooth_getsockopt()
static int pi_bluetooth_getsockopt (pi_socket_t * ps, int level, int option_name, void * option_value, size_t * option_len) static
{
    struct pi_bluetooth_data *data =
        (struct pi_bluetooth_data *)ps->device->data;
    if (option_name == PI_DEV_TIMEOUT) {
        if (*option_len < sizeof (data->timeout)) {
            pi_set_error(ps->sd, PI_ERR_GENERIC_ARGUMENT);
            return -1;
        }
        memcpy (option_value, &data->timeout, sizeof (data->timeout));
        *option_len = sizeof (data->timeout);
    }
    return 0;
}
References pi_set_error().
Referenced by pi_bluetooth_protocol().
pi_bluetooth_listen()
static int pi_bluetooth_listen (pi_socket_t * ps, int backlog) static
{
    // FIXME: no result is actually being taken into account
        listen(ps->sd, 10);
        ps->state = PI_SOCK_LISTEN;
        return 0;
}
Referenced by pi_bluetooth_device().
pi_bluetooth_open()
static int pi_bluetooth_open (struct pi_socket * ps, struct pi_sockaddr * addr, int addrlen) static
{
    int     fd, flags;
    struct  pi_bluetooth_data *data = ps->device->data;
    pi_bluetooth_register_hotsync_sdp (data);
    /* If we didn't manage to create an SDP record, force channel 22 and try
     * again */
    if (data->channel < 0) {
        fprintf (stderr, "didn't manage to get a channel\n");
        data->channel = 22;
    }
    if ((fd = socket(AF_BLUETOOTH, SOCK_STREAM, BTPROTO_RFCOMM)) < 0)
        return -1;
    if ((flags = fcntl(fd, F_GETFL, 0)) != -1) {
        flags &= ~O_NONBLOCK;
        fcntl(fd, F_SETFL, flags);
    }
    if (pi_socket_setsd(ps, fd) < 0)
        return -1;
    return 0;
}
References flags, pi_bluetooth_register_hotsync_sdp(), and pi_socket_setsd().
Referenced by pi_bluetooth_bind().
pi_bluetooth_protocol()
static pi_protocol_t * pi_bluetooth_protocol (pi_device_t * dev) static
{
    pi_protocol_t *prot;
    struct pi_bluetooth_data *data;
    ASSERT (dev != NULL);
    prot = (pi_protocol_t *) malloc(sizeof (pi_protocol_t));
    data = (struct pi_bluetooth_data *)(dev->data);
    if (prot != NULL) {
        prot->level         = PI_LEVEL_DEV;
        prot->dup       = pi_bluetooth_protocol_dup;
        prot->free      = pi_bluetooth_protocol_free;
        prot->read      = pi_bluetooth_read;
        prot->write         = pi_bluetooth_write;
        prot->flush     = pi_bluetooth_flush;
        prot->getsockopt    = pi_bluetooth_getsockopt;
        prot->setsockopt    = pi_bluetooth_setsockopt;
        prot->data      = NULL;
    }
    return prot;
}
References pi_bluetooth_flush(), pi_bluetooth_getsockopt(), pi_bluetooth_protocol_dup(), pi_bluetooth_protocol_free(), pi_bluetooth_read(), pi_bluetooth_setsockopt(), and pi_bluetooth_write().
Referenced by pi_bluetooth_device().
pi_bluetooth_protocol_dup()
static pi_protocol_t * pi_bluetooth_protocol_dup (pi_protocol_t * prot) static
{
    pi_protocol_t *new_prot;
    ASSERT (prot != NULL);
    new_prot = (pi_protocol_t *) malloc(sizeof (pi_protocol_t));
    if (new_prot != NULL) {
        new_prot->level     = prot->level;
        new_prot->dup       = prot->dup;
        new_prot->free      = prot->free;
        new_prot->read      = prot->read;
        new_prot->write     = prot->write;
        new_prot->flush     = prot->flush;
        new_prot->getsockopt    = prot->getsockopt;
        new_prot->setsockopt    = prot->setsockopt;
        new_prot->data      = NULL;
    }
    return new_prot;
}
Referenced by pi_bluetooth_protocol().
pi_bluetooth_protocol_free()
static void pi_bluetooth_protocol_free (pi_protocol_t * prot) static
{
    ASSERT (prot != NULL);
    if (prot != NULL)
        free(prot);
}
Referenced by pi_bluetooth_protocol().
pi_bluetooth_read()
static ssize_t pi_bluetooth_read (struct pi_socket * ps, pi_buffer_t * buf, size_t len, int flags) static
{
    int     rbuf;
    struct  pi_bluetooth_data *data = (struct pi_bluetooth_data *)ps->device->data;
    struct  timeval t;
    fd_set  ready;
    if (pi_buffer_expect (buf, len) == NULL)
        return pi_set_error(ps->sd, PI_ERR_GENERIC_MEMORY);
    FD_ZERO(&ready);
    FD_SET(ps->sd, &ready);
    /* If timeout == 0, wait forever for packet, otherwise wait till
       timeout milliseconds */
    if (data->timeout == 0)
        select(ps->sd + 1, &ready, 0, 0, 0);
    else {
        t.tv_sec        = data->timeout / 1000;
        t.tv_usec       = (data->timeout % 1000) * 1000;
        select(ps->sd + 1, &ready, 0, 0, &t);
    }
        /* If data is available in time, read it */
        if (FD_ISSET(ps->sd, &ready)) {
        if (flags == PI_MSG_PEEK && len > 256)
                len = 256;
        rbuf = read(ps->sd, buf->data + buf->used, len);
        } else {
        LOG((PI_DBG_DEV, PI_DBG_LVL_WARN, "DEV RX BlueTooth timeout\n"));
        pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
        return -1;
        }
        buf->used += rbuf;
        LOG((PI_DBG_DEV, PI_DBG_LVL_INFO, "DEV RX bluetooth %d bytes\n", rbuf));
        return rbuf;
}
References buf, flags, pi_buffer_expect(), and pi_set_error().
Referenced by pi_bluetooth_protocol().
pi_bluetooth_register_hotsync_sdp()
static void pi_bluetooth_register_hotsync_sdp (struct pi_bluetooth_data * data) static
{
    if (register_sdp (&data->handle, &data->channel, &data->sess) < 0) {
        data->channel = -1;
        data->handle = 0;
        data->sess = NULL;
    }
}
References register_sdp().
Referenced by pi_bluetooth_open().
pi_bluetooth_setsockopt()
static int pi_bluetooth_setsockopt (pi_socket_t * ps, int level, int option_name, const void * option_value, size_t * option_len) static
{
    struct pi_bluetooth_data *data =
        (struct pi_bluetooth_data *)ps->device->data;
    if (option_name == PI_DEV_TIMEOUT) {
        if (*option_len != sizeof (data->timeout)) {
            pi_set_error(ps->sd, PI_ERR_GENERIC_ARGUMENT);
            return -1;
        }
        memcpy (&data->timeout, option_value, sizeof (data->timeout));
    }
    return 0;
}
References pi_set_error().
Referenced by pi_bluetooth_protocol().
pi_bluetooth_unregister_hotsync_sdp()
static void pi_bluetooth_unregister_hotsync_sdp (struct pi_bluetooth_data * data) static
{
    if (data->handle != 0)
        deregister_sdp (data->handle, data->sess);
}
References deregister_sdp().
Referenced by pi_bluetooth_device_free().
pi_bluetooth_write()
static ssize_t pi_bluetooth_write (struct pi_socket * ps, const unsigned char * buf, size_t len, int flags) static
{
        int     total,
            nwrote;
        struct  pi_bluetooth_data *data = (struct pi_bluetooth_data *)ps->device->data;
        struct  timeval t;
        fd_set  ready;
        FD_ZERO(&ready);
        FD_SET(ps->sd, &ready);
        total = len;
        while (total > 0) {
        if (data->timeout == 0)
                select(ps->sd + 1, 0, &ready, 0, 0);
        else {
                t.tv_sec        = data->timeout / 1000;
                t.tv_usec       = (data->timeout % 1000) * 1000;
                select(ps->sd + 1, 0, &ready, 0, &t);
        }
        if (!FD_ISSET(ps->sd, &ready)) {
                pi_set_error(ps->sd, PI_ERR_SOCK_IO);
                return -1;
        }
        nwrote = write(ps->sd, buf, len);
        if (nwrote < 0) {
                pi_set_error(ps->sd, PI_ERR_SOCK_IO);
                return -1;
        }
        total -= nwrote;
        }
        LOG((PI_DBG_DEV, PI_DBG_LVL_INFO, "DEV TX bluetooth %d bytes\n", len));
        return len;
}
References buf, and pi_set_error().
Referenced by pi_bluetooth_protocol().
pi_socket_init()
int pi_socket_init (pi_socket_t * ps) extern
{
    protocol_queue_build (ps, 1);
    return 0;
}
References protocol_queue_build().
Referenced by pi_bluetooth_accept().
register_sdp()
static int register_sdp (uint32_t * handle, int * channel, sdp_session_t ** sess) static
{
    svc_info_t si;
    bdaddr_t interface;
    bacpy (&interface, BDADDR_ANY);
    *sess = sdp_connect (&interface, BDADDR_LOCAL, 0);
    if (*sess == NULL)
        return -1;
    memset (&si, 0, sizeof(si));
    si.name = "HOTSYNC";
    return add_hotsync (*sess, 0, &interface, &si, handle, channel);
}
References add_hotsync(), and svc_info_t::name.
Referenced by pi_bluetooth_register_hotsync_sdp().
Variable Documentation
hotsync_uuid
unsigned char hotsync_uuid[] static
Initial value:
= {
    0xD8, 0x0C, 0xF9, 0xEA, 0x13, 0x4C, 0x11, 0xD5,
    0x83, 0xCE, 0x00, 0x30, 0x65, 0x7C, 0x54, 0x3C
}
{
    0xD8, 0x0C, 0xF9, 0xEA, 0x13, 0x4C, 0x11, 0xD5,
    0x83, 0xCE, 0x00, 0x30, 0x65, 0x7C, 0x54, 0x3C
};
Referenced by add_hotsync().