pilot-link: AddressRecord Class Reference
AddressRecord Class Reference
Public Member Functions
AddressRecord ()
AddressRecord (Record r)
byte[] getBuffer ()
String getField (int idx)
int getLabelId (int idx)
int getSize ()
void setBuffer (byte buf[])
void setField (String cont, int idx)
void setLabelId (int id, int idx)
Public Member Functions inherited from Record
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Package Attributes
String fields []
int[] labelIds
int showPhone
Private Member Functions
int hi (byte b)
int lo (byte b)
Additional Inherited Members
Static Public Member Functions inherited from Record
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Static Public Attributes inherited from Record
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Protected Attributes inherited from Record
int attribs
int category
long id
int size
Detailed Description
Constructor & Destructor Documentation
AddressRecord() [1/2]
AddressRecord (Record r) inline
{
        super(r);
    }
AddressRecord() [2/2]
AddressRecord () inline
{
        labelIds=new int[5];
        fields=new String[20];
    }
References AddressRecord.fields, and AddressRecord.labelIds.
Member Function Documentation
getBuffer()
byte[] getBuffer () inline
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented from Record.
{
        //throw new NullPointerException("NOT IMPLEMENTED YET, SORRY! dont call me");
        //return new byte[1];
        int size=9; //size of the flags etc.
        for (int i=0; i<fields.length; i++) {
            if (fields[i]==null) {
                continue;
            }
            size+=fields[i].length()+1; //null termination
        }
        byte buffer[]=new byte[size];
        //  System.out.println("Getbuffer (AddressRecord): created buffer of size "+size);
        buffer[1]=(byte)(((byte)showPhone <<4)|(byte)labelIds[4]);
        buffer[2]=(byte)((labelIds[3]<<4)|(byte)labelIds[2]);
        buffer[3]=(byte)((labelIds[1]<<4)|(byte)labelIds[0]);
        int p=9;
        long contents=0;
        for (int i=0; i<19; i++) {
            if (fields[i]!=null) {
                contents|=(1<<i);
                int len=fields[i].length()+1;
                Record.setStringAt(buffer,fields[i],p);
                p+=len;
            }
        }
        setLongAt(buffer,contents,4);
        return buffer;
    }
References buffer, AddressRecord.fields, AddressRecord.labelIds, Record.setLongAt(), Record.setStringAt(), AddressRecord.showPhone, and Record.size.
Referenced by AddressRecord.getSize(), AddressRecord.setField(), and AddressRecord.setLabelId().
getField()
String getField (int idx) inline
{
        return fields[idx];
    }
References AddressRecord.fields.
Referenced by adrtest.main().
getLabelId()
int getLabelId (int idx) inline
{
        if (idx>5) {
            return 0;
        }
        return labelIds[idx];
    }
References AddressRecord.labelIds.
getSize()
int getSize () inline
Gets the size attribute of the Record object
Returns
The size value
Reimplemented from Record.
{
        return getBuffer().length;
    }
References AddressRecord.getBuffer().
hi()
int hi (byte b) inline private
{
        return (b&0xf0)>>4;
    }
lo()
int lo (byte b) inline private
{
        return (b&0x0f);
    }
setBuffer()
void setBuffer (byte buf[]) inline
Sets the buffer attribute of the Record object
Parameters
buf The new buffer value
Reimplemented from Record.
{
        labelIds=new int[5];
        fields=new String[20];
        if (buf.length<5) {
            System.out.println("Wrong sized buffer for address...");
            return;
        }
        showPhone=hi(buf[1]);
        labelIds[4]=lo(buf[1]);
        labelIds[3]=hi(buf[2]);
        labelIds[2]=lo(buf[2]);
        labelIds[1]=hi(buf[3]);
        labelIds[0]=lo(buf[3]);
        long contents=buf[4]*256*256*256+buf[5]*256*256+buf[6]*256+buf[7];
        int len=buf.length-9;
        int offset=9;
        for (int i=0; i<19; i++) {
            if ((contents & (1<<i))!=0) {
                if (len<1) {
                    return;
                }
                fields[i]=getStringAt(buf,offset);
                len-=fields[i].length()+1;
                offset+=fields[i].length()+1;
            } else {
                fields[i]=null;
            }
        }
        setSize(buf.length);
    }
References buf, AddressRecord.fields, Record.getStringAt(), hi, AddressRecord.labelIds, lo, Record.setSize(), and AddressRecord.showPhone.
setField()
void setField (String cont, int idx) inline
{
        if (idx>19) {
            return;
        }
        fields[idx]=cont;
        setSize(getBuffer().length);
    }
References AddressRecord.fields, AddressRecord.getBuffer(), and Record.setSize().
setLabelId()
void setLabelId (int id, int idx) inline
{
        if (idx>5) {
            return;
        }
        labelIds[idx]=id;
        setSize(getBuffer().length);
    }
References AddressRecord.getBuffer(), Record.id, AddressRecord.labelIds, and Record.setSize().
Field Documentation
fields
String fields[] package
Referenced by AddressRecord.AddressRecord(), AddressRecord.getBuffer(), AddressRecord.getField(), AddressRecord.setBuffer(), and AddressRecord.setField().
labelIds
int [] labelIds package
Referenced by AddressRecord.AddressRecord(), AddressRecord.getBuffer(), AddressRecord.getLabelId(), AddressRecord.setBuffer(), and AddressRecord.setLabelId().
showPhone
int showPhone package
Referenced by AddressRecord.getBuffer(), and AddressRecord.setBuffer().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/AddressRecord.java