pilot-link: MemoRecord Class Reference
MemoRecord Class Reference
Public Member Functions
MemoRecord (Record r)
MemoRecord (String txt)
byte[] getBuffer ()
String getText ()
void setBuffer (byte dat[])
void setText (String m)
Public Member Functions inherited from Record
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
int getSize ()
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Package Attributes
String memo
Additional Inherited Members
Static Public Member Functions inherited from Record
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Static Public Attributes inherited from Record
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Protected Attributes inherited from Record
int attribs
int category
long id
int size
Detailed Description
Constructor & Destructor Documentation
MemoRecord() [1/2]
MemoRecord (Record r) inline
Calls the constructor of Record which calles setBuffer, do not call setBuffer directly
{
        super(r);
    }
MemoRecord() [2/2]
MemoRecord (String txt) inline
{
        memo=txt+'\0';
        setSize(memo.length());
    }
References MemoRecord.memo, and Record.setSize().
Member Function Documentation
getBuffer()
byte[] getBuffer () inline
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented from Record.
{
        //Trying to write a Memo!
        //String str="Eine TestNachricht!";
        //byte a[]=str.getBytes();
        //Record r=new Record(a,a.length,64,2);
        //pl.writeRecord(dbh,r);
        return memo.getBytes();
    }
References MemoRecord.memo.
getText()
String getText () inline
{
        return memo;
    }
References MemoRecord.memo.
Referenced by test.main().
setBuffer()
void setBuffer (byte dat[]) inline
usually called by the Constructor of Record
Reimplemented from Record.
{
        memo=new String(dat)+'\0';
        setSize(memo.length()+1);
    }
References MemoRecord.memo, and Record.setSize().
setText()
void setText (String m) inline
{
        memo=m;
        setSize(m.length()+1);
    }
References MemoRecord.memo, and Record.setSize().
Field Documentation
memo
String memo package
Referenced by MemoRecord.MemoRecord(), MemoRecord.getBuffer(), MemoRecord.getText(), MemoRecord.setBuffer(), and MemoRecord.setText().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/MemoRecord.java