pilot-link: SysInfo Class Reference
SysInfo Class Reference
Public Member Functions
SysInfo (String pID, long rv, long lc, short mav, short miv, short cmav, short cmiv, long maxr)
long getCompatMajorVersion ()
long getCompatMinorVersion ()
long getLocale ()
long getMajorVersion ()
long getMaxRecSize ()
long getMinorVersion ()
String getProdID ()
long getRomVersion ()
Private Attributes
short compatMajorVersion
short compatMinorVersion
short dlpMajorVersion
short dlpMinorVersion
long locale
long maxRecSize
String prodID
long romVersion
Detailed Description
Constructor & Destructor Documentation
SysInfo()
SysInfo (String pID, long rv, long lc, short mav, short miv, short cmav, short cmiv, long maxr) inline
{
    romVersion=rv;
    locale=lc;
    prodID=pID;
    dlpMajorVersion=mav;
    dlpMinorVersion=miv;
    compatMajorVersion=cmav;
    compatMinorVersion=cmiv;
    maxRecSize=maxr;
   }
References SysInfo.compatMajorVersion, SysInfo.compatMinorVersion, SysInfo.dlpMajorVersion, SysInfo.dlpMinorVersion, SysInfo.locale, SysInfo.maxRecSize, SysInfo.prodID, and SysInfo.romVersion.
Member Function Documentation
getCompatMajorVersion()
long getCompatMajorVersion () inline
{
    return compatMajorVersion;
   }
References SysInfo.compatMajorVersion.
getCompatMinorVersion()
long getCompatMinorVersion () inline
{
    return compatMinorVersion;
   }
References SysInfo.compatMinorVersion.
getLocale()
long getLocale () inline
{
    return locale;
   }
References SysInfo.locale.
getMajorVersion()
long getMajorVersion () inline
{
        return dlpMajorVersion;
   }
References SysInfo.dlpMajorVersion.
getMaxRecSize()
long getMaxRecSize () inline
{
    return maxRecSize;
   }
References SysInfo.maxRecSize.
getMinorVersion()
long getMinorVersion () inline
{
    return dlpMinorVersion;
   }
References SysInfo.dlpMinorVersion.
getProdID()
String getProdID () inline
{
    return prodID;
   }
References SysInfo.prodID.
Referenced by adrtest.main(), MidiMgr.main(), test.main(), and TestTodos.main().
getRomVersion()
long getRomVersion () inline
{
    return romVersion;
   }
References SysInfo.romVersion.
Referenced by adrtest.main(), MidiMgr.main(), test.main(), and TestTodos.main().
Field Documentation
compatMajorVersion
short compatMajorVersion private
Referenced by SysInfo.SysInfo(), and SysInfo.getCompatMajorVersion().
compatMinorVersion
short compatMinorVersion private
Referenced by SysInfo.SysInfo(), and SysInfo.getCompatMinorVersion().
dlpMajorVersion
short dlpMajorVersion private
Referenced by SysInfo.SysInfo(), and SysInfo.getMajorVersion().
dlpMinorVersion
short dlpMinorVersion private
Referenced by SysInfo.SysInfo(), and SysInfo.getMinorVersion().
locale
long locale private
Referenced by SysInfo.SysInfo(), and SysInfo.getLocale().
maxRecSize
long maxRecSize private
Referenced by SysInfo.SysInfo(), and SysInfo.getMaxRecSize().
prodID
String prodID private
Referenced by SysInfo.SysInfo(), and SysInfo.getProdID().
romVersion
long romVersion private
Referenced by SysInfo.SysInfo(), and SysInfo.getRomVersion().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/SysInfo.java