pilot-link: MidiRecord Class Reference
MidiRecord Class Reference
Public Member Functions
MidiRecord ()
MidiRecord (Record r)
byte[] getBuffer ()
byte[] getMidi ()
String getName ()
void setBuffer (byte[] buf)
void setMidi (byte b[])
void setName (String n)
Public Member Functions inherited from Record
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
int getSize ()
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Private Attributes
byte midi []
String name
Static Private Attributes
static String id ="PMrc"
Additional Inherited Members
Static Public Member Functions inherited from Record
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Static Public Attributes inherited from Record
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Protected Attributes inherited from Record
int attribs
int category
long id
int size
Detailed Description
Author
stephan
To change the template for this generated type comment go to Window>Preferences>Java>Code Generation>Code and Comments
Constructor & Destructor Documentation
MidiRecord() [1/2]
MidiRecord () inline
{
        midi=new byte[1]; //avoid nullpointer exception
        name="";
    }
References MidiRecord.midi, and MidiRecord.name.
MidiRecord() [2/2]
MidiRecord (Record r) inline
Parameters
r
{
        super(r);
    }
Member Function Documentation
getBuffer()
byte[] getBuffer () inline
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented from Record.
{
        // TODO Auto-generated method stub
        int offset=name.length()+1+6;
        byte buf[]=new byte[offset+midi.length];
        setStringAt(buf,id,0);
        buf[4]=(byte)offset;
        buf[5]=0;
        setStringAt(buf,name,6);
        for (int i=0; i<midi.length;i++) {
            buf[offset+i]=midi[i];
        }
        return buf;
    }
References buf, MidiRecord.midi, MidiRecord.name, and Record.setStringAt().
getMidi()
byte[] getMidi () inline
{
        return midi;
    }
References MidiRecord.midi.
Referenced by MidiMgr.main().
getName()
String getName () inline
{
        return name;
    }
References MidiRecord.name.
Referenced by MidiMgr.main().
setBuffer()
void setBuffer (byte[] buf) inline
Sets the buffer attribute of the Record object
Parameters
buf The new buffer value
Reimplemented from Record.
{
        // TODO Auto-generated method stub
        name=getStringAt(buf,6);
        int offset=buf[4];
        midi=new byte[buf.length-offset];
        for (int i=0;i<midi.length;i++) {
            midi[i]=buf[i+offset];
        }
        setSize(buf.length);
    }
References buf, Record.getStringAt(), MidiRecord.midi, MidiRecord.name, and Record.setSize().
setMidi()
void setMidi (byte b[]) inline
{
        midi=b;
        setSize(midi.length+2+id.length()+name.length()+1);
    }
References MidiRecord.midi, MidiRecord.name, and Record.setSize().
Referenced by MidiMgr.main().
setName()
void setName (String n) inline
{
        name=n;
        setSize(midi.length+2+id.length()+name.length()+1);
    }
References MidiRecord.midi, MidiRecord.name, and Record.setSize().
Referenced by MidiMgr.main().
Field Documentation
id
String id ="PMrc" static private
midi
byte midi[] private
Referenced by MidiRecord.MidiRecord(), MidiRecord.getBuffer(), MidiRecord.getMidi(), MidiRecord.setBuffer(), MidiRecord.setMidi(), and MidiRecord.setName().
name
String name private
Referenced by MidiRecord.MidiRecord(), MidiRecord.getBuffer(), MidiRecord.getName(), MidiRecord.setBuffer(), MidiRecord.setMidi(), and MidiRecord.setName().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/MidiRecord.java