pilot-link: FTB3VehicleRecord Class Reference
FTB3VehicleRecord Class Reference
Public Member Functions
FTB3VehicleRecord ()
FTB3VehicleRecord (int i, int att, int cat, int sz)
FTB3VehicleRecord (Record r)
byte[] getBuffer ()
String getName ()
String getNote ()
String getPlate ()
void setBuffer (byte[] buf)
void setName (String name)
void setNote (String note)
void setPlate (String plate)
String toString ()
Public Member Functions inherited from Record
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
int getSize ()
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Private Attributes
double monthlyCost
String name
String note
String plate
Additional Inherited Members
Static Public Member Functions inherited from Record
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Static Public Attributes inherited from Record
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Protected Attributes inherited from Record
int attribs
int category
long id
int size
Detailed Description
Author
stephan
To change the template for this generated type comment go to Window>Preferences>Java>Code Generation>Code and Comments
Constructor & Destructor Documentation
FTB3VehicleRecord() [1/3]
FTB3VehicleRecord () inline
{
        super();
    }
FTB3VehicleRecord() [2/3]
FTB3VehicleRecord (int i, int att, int cat, int sz) inline
Parameters
i
att
cat
sz
{
        super(i, att, cat, sz);
    }
FTB3VehicleRecord() [3/3]
FTB3VehicleRecord (Record r) inline
Parameters
r
{
        super(r);
    }
Member Function Documentation
getBuffer()
byte[] getBuffer () inline
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented from Record.
{
        byte buf[]=new byte[0x70];
        setStringAt(buf,name,0x08);
        setStringAt(buf,plate,0x18);
        setStringAt(buf,note,0x30);
        return buf;
    }
References buf, FTB3VehicleRecord.name, FTB3VehicleRecord.note, FTB3VehicleRecord.plate, and Record.setStringAt().
Referenced by FTB3VehicleRecord.setName(), FTB3VehicleRecord.setNote(), and FTB3VehicleRecord.setPlate().
getName()
String getName () inline
Returns
Returns the name.
{
        return name;
    }
References FTB3VehicleRecord.name.
getNote()
String getNote () inline
Returns
Returns the note.
{
        return note;
    }
References FTB3VehicleRecord.note.
getPlate()
String getPlate () inline
Returns
Returns the plate.
{
        return plate;
    }
References FTB3VehicleRecord.plate.
setBuffer()
void setBuffer (byte[] buf) inline
Sets the buffer attribute of the Record object
Parameters
buf The new buffer value
Reimplemented from Record.
{
        name=getStringAt(buf,0x08);
        plate=getStringAt(buf,0x18);
        //TODO: parse monthly cost as float at 0x28
        monthlyCost=getDoubleAt(buf,0x28);
        note=getStringAt(buf,0x30);
        setSize(buf.length);
    }
References buf, Record.getDoubleAt(), Record.getStringAt(), FTB3VehicleRecord.monthlyCost, FTB3VehicleRecord.name, FTB3VehicleRecord.note, FTB3VehicleRecord.plate, and Record.setSize().
setName()
void setName (String name) inline
Parameters
name The name to set.
{
        this.name= name;
        setSize(getBuffer().length);
    }
References FTB3VehicleRecord.getBuffer(), FTB3VehicleRecord.name, and Record.setSize().
setNote()
void setNote (String note) inline
Parameters
note The note to set.
{
        this.note= note;
        setSize(getBuffer().length);
    }
References FTB3VehicleRecord.getBuffer(), FTB3VehicleRecord.note, and Record.setSize().
setPlate()
void setPlate (String plate) inline
Parameters
plate The plate to set.
{
        this.plate= plate;
        setSize(getBuffer().length);
    }
References FTB3VehicleRecord.getBuffer(), FTB3VehicleRecord.plate, and Record.setSize().
toString()
String toString () inline
{
        return "Vehicle: "+name+" ("+plate+")  - "+note+ " Cost: "+monthlyCost;
    }
References FTB3VehicleRecord.monthlyCost, FTB3VehicleRecord.name, FTB3VehicleRecord.note, and FTB3VehicleRecord.plate.
Field Documentation
monthlyCost
double monthlyCost private
Referenced by FTB3VehicleRecord.setBuffer(), and FTB3VehicleRecord.toString().
name
String name private
Referenced by FTB3VehicleRecord.getBuffer(), FTB3VehicleRecord.getName(), FTB3VehicleRecord.setBuffer(), FTB3VehicleRecord.setName(), and FTB3VehicleRecord.toString().
note
String note private
Referenced by FTB3VehicleRecord.getBuffer(), FTB3VehicleRecord.getNote(), FTB3VehicleRecord.setBuffer(), FTB3VehicleRecord.setNote(), and FTB3VehicleRecord.toString().
plate
String plate private
Referenced by FTB3VehicleRecord.getBuffer(), FTB3VehicleRecord.getPlate(), FTB3VehicleRecord.setBuffer(), FTB3VehicleRecord.setPlate(), and FTB3VehicleRecord.toString().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/FTB3VehicleRecord.java