pilot-link: DatebookRecord Class Reference
DatebookRecord Class Reference
Public Member Functions
DatebookRecord ()
DatebookRecord (Date sd, Date ed, String descr, String n)
DatebookRecord (Record raw)
int getAlarmAdvance ()
int getAlarmUnits ()
byte[] getBuffer ()
String getDescription ()
Date getEndDate ()
String getNote ()
int getRepAdvance ()
int getRepDay ()
boolean[] getRepDays ()
Date getRepeatEnd ()
Date[] getRepExceptions ()
int getRepType ()
int getRepWeekstart ()
Date getStartDate ()
boolean hasAlarm ()
boolean hasDescription ()
boolean hasExceptions ()
boolean hasNote ()
boolean hasTime ()
boolean isRepeated ()
boolean repeatForever ()
Date repeatUntil ()
void setAlarm (boolean a)
void setAlarmAdvance (int alarmAdvance)
void setAlarmUnits (int alarmUnits)
void setBuffer (byte arr[])
void setDescription (String description)
void setEndDate (Date endDate)
void setNote (String note)
void setRepAdvance (int repAdvance)
void setRepDay (int repDay)
void setRepDays (boolean[] repDays)
void setRepeated (boolean r)
void setRepeatEnd (Date repeatEnd)
void setRepeatForever (boolean r)
void setRepExceptions (Date repExceptions[])
void setRepType (int repType)
void setRepWeekstart (int repWeekstart)
void setStartDate (Date startDate)
Public Member Functions inherited from Record
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
int getSize ()
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Static Public Attributes
static final int ALARM_DAYS =2
static final int ALARM_HOURS =1
static final int ALARM_MINUTES =0
static final int ALARM_NONE =3
static final int NO_REP =0
static final int REP_DAYLY =1
static final int REP_MONTHLY_BY_DATE =4
static final int REP_MONTHLY_BY_DAY =3
static final int REP_NONE =6
static final int REP_WEEKLY =2
static final int REP_YEARLY =5
Static Public Attributes inherited from Record
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Package Attributes
byte buffer [] =new byte[65535]
Private Member Functions
void resetVars ()
Private Attributes
int alarmAdvance
int alarmUnits
String description
int dist
Date endDate
boolean hasAlarm
boolean hasDescription
boolean hasExceptions
boolean hasNote
boolean hasTime
boolean isRepeated
String note
int repAdvance
int repDay
boolean[] repDays
Date repeatEnd
boolean repeatForever
Date repExceptions []
int repType
int repWeekstart
Date startDate
Additional Inherited Members
Static Public Member Functions inherited from Record
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Protected Attributes inherited from Record
int attribs
int category
long id
int size
Detailed Description
Constructor & Destructor Documentation
DatebookRecord() [1/3]
DatebookRecord (Date sd, Date ed, String descr, String n) inline
{
        resetVars();
        startDate = sd;
        endDate=ed;
        description=descr;
        note=n;
        if (n!=null && n.length()!=0) {
            hasNote=true;
        }
        if (descr!=null && descr.length()!=0) {
            hasDescription=true;
        }
        GregorianCalendar cal=new GregorianCalendar();
        cal.setTime(sd);
        if (cal.get(GregorianCalendar.HOUR_OF_DAY)!=0 && cal.get(GregorianCalendar.MINUTE)!=0) {
            hasTime=true;
        }
        //CLUMSY: getting buffer once to calc size
        //getBuffer();
    setSize(getBuffer().length);
    }
References DatebookRecord.description, DatebookRecord.endDate, DatebookRecord.getBuffer(), DatebookRecord.hasDescription, DatebookRecord.hasNote, DatebookRecord.hasTime, DatebookRecord.note, DatebookRecord.resetVars(), sd, Record.setSize(), and DatebookRecord.startDate.
DatebookRecord() [2/3]
DatebookRecord (Record raw) inline
{
        super(raw);
    }
DatebookRecord() [3/3]
DatebookRecord () inline
{
        startDate=new Date();
        resetVars();
        endDate=new Date();
    }
References DatebookRecord.endDate, DatebookRecord.resetVars(), and DatebookRecord.startDate.
Member Function Documentation
getAlarmAdvance()
int getAlarmAdvance () inline
{
        return alarmAdvance;
    }
References DatebookRecord.alarmAdvance.
getAlarmUnits()
int getAlarmUnits () inline
{
        return alarmUnits;
    }
References DatebookRecord.alarmUnits.
getBuffer()
byte[] getBuffer () inline
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented from Record.
{
        int bytecount=0;
        if (!hasTime) {
            buffer[0]=(byte)0xff;
            buffer[1]=(byte)0xff;
            buffer[2]=(byte)0xff;
            buffer[3]=(byte)0xff;
            Record.setDateAt(buffer,startDate,4);
        } else {
            Record.setDateTimeAt(buffer,startDate,4,0);
            Record.setDateTimeAt(buffer,endDate,4,2);
        }
        int flags=0;
        if (hasAlarm) flags=flags|64;
        if (isRepeated) flags=flags|32;
        if (hasExceptions) flags=flags|8;
        if (hasNote) flags=flags|16;
        if (hasDescription) flags=flags|4;
        buffer[6]=(byte)flags;
        bytecount=8;
        if (hasAlarm) {
            buffer[bytecount]=(byte)alarmAdvance;
            bytecount++;
            buffer[bytecount]=(byte)alarmUnits;
            bytecount++;
        }
        if (isRepeated) {
            buffer[bytecount]=(byte)repType;
            bytecount+=2;
            if (repeatForever) {
                buffer[bytecount]=(byte)0xff;
                buffer[bytecount+1]=(byte)0xff;
            } else {
                Record.setIntAt(buffer,dist-1, bytecount);
            }
            bytecount+=2;
            buffer[bytecount]=(byte)repAdvance;
            bytecount++;
            if (repType==REP_MONTHLY_BY_DAY) {
                buffer[bytecount]=(byte)repDay;
            } else {
                int days=0;
                for (int i=0; i<7; i++) {
                    if (repDays[i]) {
                        days=days|(1<<i);
                    }
                }
            }
            bytecount++;
            buffer[bytecount]=(byte)repWeekstart;
            bytecount+=2;
        }
        if (hasExceptions) {
            buffer[bytecount]=(byte)repExceptions.length;
            bytecount+=2;
            for (int i=0;i<repExceptions.length;i++, bytecount+=2) {
                Record.setDateAt(buffer,repExceptions[i],bytecount);
            }
        }
        //bytecount=16; //cant set exceptions on my palm...
        if (hasDescription) {
            bytecount=Record.setStringAt(buffer,description,bytecount);
        }
        if (hasNote) {
            bytecount=Record.setStringAt(buffer,note,bytecount);
        }
        byte ret[]=new byte[bytecount];
        for (int i=0; i<bytecount; i++) {
            ret[i]=buffer[i];
        }
        return ret;
    }
References DatebookRecord.alarmAdvance, DatebookRecord.alarmUnits, DatebookRecord.buffer, days, DatebookRecord.description, DatebookRecord.dist, DatebookRecord.endDate, flags, DatebookRecord.hasAlarm, DatebookRecord.hasDescription, DatebookRecord.hasExceptions, DatebookRecord.hasNote, DatebookRecord.hasTime, DatebookRecord.isRepeated, DatebookRecord.note, DatebookRecord.REP_MONTHLY_BY_DAY, DatebookRecord.repAdvance, DatebookRecord.repDay, DatebookRecord.repDays, DatebookRecord.repeatForever, DatebookRecord.repExceptions, DatebookRecord.repType, DatebookRecord.repWeekstart, Record.setDateAt(), Record.setDateTimeAt(), Record.setIntAt(), Record.setStringAt(), and DatebookRecord.startDate.
Referenced by DatebookRecord.DatebookRecord(), datebooktst.main(), test.main(), DatebookRecord.setAlarmAdvance(), DatebookRecord.setAlarmUnits(), DatebookRecord.setDescription(), DatebookRecord.setEndDate(), DatebookRecord.setNote(), DatebookRecord.setRepAdvance(), DatebookRecord.setRepDay(), DatebookRecord.setRepDays(), DatebookRecord.setRepeatEnd(), DatebookRecord.setRepExceptions(), DatebookRecord.setRepType(), DatebookRecord.setRepWeekstart(), and DatebookRecord.setStartDate().
getDescription()
String getDescription () inline
{
        return description;
    }
References DatebookRecord.description.
Referenced by datebooktst.main(), and test.main().
getEndDate()
Date getEndDate () inline
{
        return endDate;
    }
References DatebookRecord.endDate.
Referenced by datebooktst.main(), and test.main().
getNote()
String getNote () inline
{
        return note;
    }
References DatebookRecord.note.
Referenced by datebooktst.main(), and test.main().
getRepAdvance()
int getRepAdvance () inline
{
        return repAdvance;
    }
References DatebookRecord.repAdvance.
getRepDay()
int getRepDay () inline
{
        return repDay;
    }
References DatebookRecord.repDay.
getRepDays()
boolean[] getRepDays () inline
{
        return repDays;
    }
References DatebookRecord.repDays.
getRepeatEnd()
Date getRepeatEnd () inline
{
        return repeatEnd;
    }
References DatebookRecord.repeatEnd.
getRepExceptions()
Date[] getRepExceptions () inline
{
        return repExceptions;
    }
References DatebookRecord.repExceptions.
getRepType()
int getRepType () inline
{
        return repType;
    }
References DatebookRecord.repType.
getRepWeekstart()
int getRepWeekstart () inline
{
        return repWeekstart;
    }
References DatebookRecord.repWeekstart.
getStartDate()
Date getStartDate () inline
{
        return startDate;
    }
References DatebookRecord.startDate.
Referenced by datebooktst.main(), and test.main().
hasAlarm()
boolean hasAlarm () inline
{
        return hasAlarm;
    }
References DatebookRecord.hasAlarm.
hasDescription()
boolean hasDescription () inline
{
        return hasDescription;
    }
References DatebookRecord.hasDescription.
hasExceptions()
boolean hasExceptions () inline
{
        return hasExceptions;
    }
References DatebookRecord.hasExceptions.
hasNote()
boolean hasNote () inline
{
        return hasNote;
    }
References DatebookRecord.hasNote.
hasTime()
boolean hasTime () inline
{
        return hasTime;
    }
References DatebookRecord.hasTime.
isRepeated()
boolean isRepeated () inline
{
        return isRepeated;
    }
References DatebookRecord.isRepeated.
repeatForever()
boolean repeatForever () inline
{
        return repeatForever;
    }
References DatebookRecord.repeatForever.
repeatUntil()
Date repeatUntil () inline
{
        return repeatEnd;
    }
References DatebookRecord.repeatEnd.
resetVars()
void resetVars () inline private
{
        description="";
        note="";
        alarmAdvance=0;
        alarmUnits=ALARM_NONE;
        repAdvance=0;
        repType=REP_NONE;
        repDay=0;
        repWeekstart=0;
        repAdvance=0;
        dist=0;
        repDays= new boolean[] { false, false ,false, false, false, false, false };
        hasNote=false;
        hasAlarm=false;
        hasTime=false;
        isRepeated=false;
        hasDescription=false;
        hasExceptions=false;
        repeatForever=false;
    }
References DatebookRecord.ALARM_NONE, DatebookRecord.alarmAdvance, DatebookRecord.alarmUnits, DatebookRecord.description, DatebookRecord.dist, false, DatebookRecord.hasAlarm, DatebookRecord.hasDescription, DatebookRecord.hasExceptions, DatebookRecord.hasNote, DatebookRecord.hasTime, DatebookRecord.isRepeated, DatebookRecord.note, DatebookRecord.REP_NONE, DatebookRecord.repAdvance, DatebookRecord.repDay, DatebookRecord.repDays, DatebookRecord.repeatForever, DatebookRecord.repType, and DatebookRecord.repWeekstart.
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.DatebookRecord(), and DatebookRecord.setBuffer().
setAlarm()
void setAlarm (boolean a) inline
{
        hasAlarm=a;
    }
References DatebookRecord.hasAlarm.
setAlarmAdvance()
void setAlarmAdvance (int alarmAdvance) inline
{
        this.alarmAdvance = alarmAdvance;
    setSize(getBuffer().length);
    }
References DatebookRecord.alarmAdvance, DatebookRecord.getBuffer(), and Record.setSize().
setAlarmUnits()
void setAlarmUnits (int alarmUnits) inline
{
        this.alarmUnits = alarmUnits;
    setSize(getBuffer().length);
    }
References DatebookRecord.alarmUnits, DatebookRecord.getBuffer(), and Record.setSize().
setBuffer()
void setBuffer (byte buf[]) inline
Sets the buffer attribute of the Record object
Parameters
buf The new buffer value
Reimplemented from Record.
{
        //buffer=raw.getBuffer();
        resetVars();
        if (arr[0]==(byte)0xff && arr[1]==(byte)0xff) {
            //keine Zeit festgelegt
            hasTime=false;
            startDate=Record.getDateAt(arr,4);
            endDate=startDate;
        } else {
            hasTime=true;
            startDate=Record.getDateTimeAt(arr,4,0);
            endDate=Record.getDateTimeAt(arr,4,2);
        }
        //Parsing flags
        int flags=arr[6];
        if ((flags & 64) != 0) {
            hasAlarm=true;
        }
        if ((flags & 32) != 0) {
            isRepeated=true;
        }
        if ((flags & 8) !=0) {
            hasExceptions=true;
        }
        if ((flags & 16) !=0) {
            hasNote=true;
        }
        if ((flags & 4) != 0) {
            hasDescription=true;
        }
        int idx=8;
        //getting data
        if (hasAlarm) {
            alarmAdvance=arr[idx];
            idx++;
            alarmUnits=arr[idx];
            idx++;
        }
        if (isRepeated) {
            repType=arr[idx];
            idx+=2;
            dist=256*arr[idx]+arr[idx]+1;
            if (dist==0xffff) {
                repeatForever=true;
            } else {
                repeatEnd=Record.getDateAt(arr,idx);
            }
            idx+=2;
            repAdvance=arr[idx];
            idx++;
            int on=arr[idx];
            if (repType==REP_MONTHLY_BY_DAY) {
                repDay=on;
            } else {
                for (int i=0; i<7;i++) {
                    //repDays[i]=((on&(1<<i))!=0);
                }
            }
            idx++;
            repWeekstart=arr[idx];
            idx+=2;
        }
        if (hasExceptions) {
            repExceptions=new Date[arr[idx]];
            idx+=2;
            for (int i=0; i<repExceptions.length; i++, idx+=2) {
                repExceptions[i]=Record.getDateAt(arr,idx);
            }
        }
        //idx=0x10; //always at idx 16? cant set exceptions on my palm
        if (hasDescription) {
            description=Record.getStringAt(arr,idx);
            idx+=description.length()+1;
        }
        if (hasNote) {
            note=Record.getStringAt(arr,idx);
            idx+=note.length()+1;
        }
        setSize(idx);
    }
References DatebookRecord.alarmAdvance, DatebookRecord.alarmUnits, DatebookRecord.description, DatebookRecord.dist, DatebookRecord.endDate, flags, Record.getDateAt(), Record.getDateTimeAt(), Record.getStringAt(), DatebookRecord.hasAlarm, DatebookRecord.hasDescription, DatebookRecord.hasExceptions, DatebookRecord.hasNote, DatebookRecord.hasTime, DatebookRecord.isRepeated, DatebookRecord.note, DatebookRecord.REP_MONTHLY_BY_DAY, DatebookRecord.repAdvance, DatebookRecord.repDay, DatebookRecord.repeatEnd, DatebookRecord.repeatForever, DatebookRecord.repExceptions, DatebookRecord.repType, DatebookRecord.repWeekstart, DatebookRecord.resetVars(), Record.setSize(), and DatebookRecord.startDate.
setDescription()
void setDescription (String description) inline
{
        this.description = description;
    if (description!=null) {
        hasDescription=true;
    } else {
        hasDescription=false;
    }
    setSize(getBuffer().length);
    }
References DatebookRecord.description, DatebookRecord.getBuffer(), DatebookRecord.hasDescription, and Record.setSize().
setEndDate()
void setEndDate (Date endDate) inline
{
        this.endDate = endDate;
    if (endDate!=null)
        hasTime=true;
    setSize(getBuffer().length);
    }
References DatebookRecord.endDate, DatebookRecord.getBuffer(), DatebookRecord.hasTime, and Record.setSize().
setNote()
void setNote (String note) inline
{
        this.note = note;
    if (note!=null) {
        hasNote=true;
    } else {
        hasNote=false;
    }
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.hasNote, DatebookRecord.note, and Record.setSize().
setRepAdvance()
void setRepAdvance (int repAdvance) inline
{
        this.repAdvance = repAdvance;
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.repAdvance, and Record.setSize().
setRepDay()
void setRepDay (int repDay) inline
{
        this.repDay = repDay;
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.repDay, and Record.setSize().
setRepDays()
void setRepDays (boolean[] repDays) inline
{
        this.repDays = repDays;
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.repDays, and Record.setSize().
setRepeated()
void setRepeated (boolean r) inline
{
        isRepeated=r;
    }
References DatebookRecord.isRepeated.
setRepeatEnd()
void setRepeatEnd (Date repeatEnd) inline
{
        this.repeatEnd = repeatEnd;
    if (repeatEnd!=null) {
        setRepeatForever(false);
    }
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.repeatEnd, DatebookRecord.setRepeatForever(), and Record.setSize().
setRepeatForever()
void setRepeatForever (boolean r) inline
{
        repeatForever=r;
    }
References DatebookRecord.repeatForever.
Referenced by DatebookRecord.setRepeatEnd().
setRepExceptions()
void setRepExceptions (Date repExceptions[]) inline
{
        this.repExceptions = repExceptions;
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.repExceptions, and Record.setSize().
setRepType()
void setRepType (int repType) inline
{
        this.repType = repType;
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.repType, and Record.setSize().
setRepWeekstart()
void setRepWeekstart (int repWeekstart) inline
{
        this.repWeekstart = repWeekstart;
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), DatebookRecord.repWeekstart, and Record.setSize().
setStartDate()
void setStartDate (Date startDate) inline
{
        this.startDate = startDate;
    setSize(getBuffer().length);
    }
References DatebookRecord.getBuffer(), Record.setSize(), and DatebookRecord.startDate.
Field Documentation
ALARM_DAYS
final int ALARM_DAYS =2 static
ALARM_HOURS
final int ALARM_HOURS =1 static
ALARM_MINUTES
final int ALARM_MINUTES =0 static
ALARM_NONE
final int ALARM_NONE =3 static
Referenced by DatebookRecord.resetVars().
alarmAdvance
int alarmAdvance private
Referenced by DatebookRecord.getAlarmAdvance(), DatebookRecord.getBuffer(), DatebookRecord.resetVars(), DatebookRecord.setAlarmAdvance(), and DatebookRecord.setBuffer().
alarmUnits
int alarmUnits private
Referenced by DatebookRecord.getAlarmUnits(), DatebookRecord.getBuffer(), DatebookRecord.resetVars(), DatebookRecord.setAlarmUnits(), and DatebookRecord.setBuffer().
buffer
byte buffer[] =new byte[65535] package
Referenced by DatebookRecord.getBuffer().
description
String description private
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.getBuffer(), DatebookRecord.getDescription(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setDescription().
dist
int dist private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.resetVars(), and DatebookRecord.setBuffer().
endDate
Date endDate private
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.DatebookRecord(), DatebookRecord.getBuffer(), DatebookRecord.getEndDate(), DatebookRecord.setBuffer(), and DatebookRecord.setEndDate().
hasAlarm
boolean hasAlarm private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.hasAlarm(), datebooktst.main(), test.main(), DatebookRecord.resetVars(), DatebookRecord.setAlarm(), and DatebookRecord.setBuffer().
hasDescription
boolean hasDescription private
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.getBuffer(), DatebookRecord.hasDescription(), datebooktst.main(), test.main(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setDescription().
hasExceptions
boolean hasExceptions private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.hasExceptions(), DatebookRecord.resetVars(), and DatebookRecord.setBuffer().
hasNote
boolean hasNote private
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.getBuffer(), DatebookRecord.hasNote(), datebooktst.main(), test.main(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setNote().
hasTime
boolean hasTime private
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.getBuffer(), DatebookRecord.hasTime(), datebooktst.main(), test.main(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setEndDate().
isRepeated
boolean isRepeated private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.isRepeated(), datebooktst.main(), test.main(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setRepeated().
NO_REP
final int NO_REP =0 static
note
String note private
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.getBuffer(), DatebookRecord.getNote(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setNote().
REP_DAYLY
final int REP_DAYLY =1 static
REP_MONTHLY_BY_DATE
final int REP_MONTHLY_BY_DATE =4 static
REP_MONTHLY_BY_DAY
final int REP_MONTHLY_BY_DAY =3 static
Referenced by DatebookRecord.getBuffer(), and DatebookRecord.setBuffer().
REP_NONE
final int REP_NONE =6 static
Referenced by DatebookRecord.resetVars().
REP_WEEKLY
final int REP_WEEKLY =2 static
REP_YEARLY
final int REP_YEARLY =5 static
repAdvance
int repAdvance private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.getRepAdvance(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setRepAdvance().
repDay
int repDay private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.getRepDay(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setRepDay().
repDays
boolean [] repDays private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.getRepDays(), DatebookRecord.resetVars(), and DatebookRecord.setRepDays().
repeatEnd
Date repeatEnd private
Referenced by DatebookRecord.getRepeatEnd(), DatebookRecord.repeatUntil(), DatebookRecord.setBuffer(), and DatebookRecord.setRepeatEnd().
repeatForever
boolean repeatForever private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.repeatForever(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setRepeatForever().
repExceptions
Date repExceptions[] private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.getRepExceptions(), DatebookRecord.setBuffer(), and DatebookRecord.setRepExceptions().
repType
int repType private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.getRepType(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setRepType().
repWeekstart
int repWeekstart private
Referenced by DatebookRecord.getBuffer(), DatebookRecord.getRepWeekstart(), DatebookRecord.resetVars(), DatebookRecord.setBuffer(), and DatebookRecord.setRepWeekstart().
startDate
Date startDate private
Referenced by DatebookRecord.DatebookRecord(), DatebookRecord.DatebookRecord(), DatebookRecord.getBuffer(), DatebookRecord.getStartDate(), DatebookRecord.setBuffer(), and DatebookRecord.setStartDate().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/DatebookRecord.java