pilot-link: Record Class Reference
Record Class Reference abstract
Public Member Functions
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
abstract byte[] getBuffer ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
int getSize ()
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
abstract void setBuffer (byte buf[])
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Static Public Member Functions
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Static Public Attributes
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Protected Attributes
int attribs
int category
long id
int size
Detailed Description
Description of the Class
Author
stephan @created 5. Dezember 2004
Constructor & Destructor Documentation
Record() [1/3]
Record () inline
Constructor for the Record object
                    {
        id = 0;
        attribs = 0;
        category = 0;
        size = 0;
    }
References Record.attribs, Record.category, and Record.size.
Record() [2/3]
Record (int i, int att, int cat, int sz) inline
Constructor for the Record object
Parameters
i Description of the Parameter
att Description of the Parameter
cat Description of the Parameter
sz Description of the Parameter
{
        size = sz;
        id = i;
        attribs = att;
        category = cat;
    }
References Record.attribs, Record.category, and Record.size.
Record() [3/3]
Record (Record r) inline
Constructor for the Record object
Parameters
r Description of the Parameter
{
        size = r.getSize();
        id = r.getId();
        attribs = r.getAttribs();
        category = r.getCategory();
        setBuffer(r.getBuffer());
    }
References Record.attribs, Record.category, Record.getAttribs(), Record.getBuffer(), Record.getCategory(), Record.getId(), Record.getSize(), Record.setBuffer(), and Record.size.
Member Function Documentation
getAttribs()
int getAttribs () inline
Gets the attribs attribute of the Record object
Returns
The attribs value
{
        return attribs;
    }
References Record.attribs.
Referenced by Record.Record(), datebooktst.main(), and test.main().
getBuffer()
abstract byte[] getBuffer () abstract
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented in AddressRecord, DatebookRecord, FTB3CostCatRecord, FTB3TripRecord, FTB3VehicleRecord, MemoRecord, MidiRecord, RawRecord, and ToDoRecord.
Referenced by Record.Record(), Record.getDateAt(), Record.getDateTimeAt(), Record.getIntAt(), Record.getStringAt(), adrtest.main(), datebooktst.main(), test.main(), and TestTodos.main().
getCategory()
int getCategory () inline
Gets the category attribute of the Record object
Returns
The category value
{
        return category;
    }
References Record.category.
Referenced by Record.Record(), datebooktst.main(), and test.main().
getDateAt() [1/2]
static Date getDateAt (byte buffer[], int idx) inline static
Gets the dateAt attribute of the Record class
Parameters
buffer Description of the Parameter
idx Description of the Parameter
Returns
The dateAt value
{
        int binary = (buffer[idx] & 0xff) * 256 + (buffer[idx + 1] & 0xff);
        int year = binary & 0xfe00;
        year = year >> 9;
        year += 1904;
        int month = binary & 0x01e0;
        month = month >> 5;
        month--;
        int day = binary & 0x001f;
        //System.out.println("Y: "+year+" M:"+month+" D: "+day);
        GregorianCalendar cal = new GregorianCalendar(year, month, day);
        return cal.getTime();
    }
References buffer.
getDateAt() [2/2]
Date getDateAt (int idx) inline
Gets the dateAt attribute of the Record object
Parameters
idx Description of the Parameter
Returns
The dateAt value
{
        return getDateAt(getBuffer(), idx);
    }
References Record.getBuffer(), and Record.getDateAt().
Referenced by Record.getDateAt(), DatebookRecord.setBuffer(), and ToDoRecord.setBuffer().
getDateTimeAt() [1/2]
static Date getDateTimeAt (byte buffer[], int idx, int tidx) inline static
Gets the dateTimeAt attribute of the Record class
Parameters
buffer Description of the Parameter
idx Description of the Parameter
tidx Description of the Parameter
Returns
The dateTimeAt value
{
        int binary = (buffer[idx] & 0xff) * 256 + (buffer[idx + 1] & 0xff);
        int year = binary & 0xfe00;
        year = year >> 9;
        year += 1904;
        int month = binary & 0x01e0;
        month = month >> 5;
        month--;
        int day = binary & 0x001f;
        //System.out.println("Y: "+year+" M:"+month+" D: "+day);
        int hour = buffer[tidx] & 0xff;
        int min = buffer[tidx + 1] & 0xff;
        GregorianCalendar cal = new GregorianCalendar(year, month, day, hour, min, 0);
        return cal.getTime();
    }
References buffer, and min.
getDateTimeAt() [2/2]
Date getDateTimeAt (int idx, int tidx) inline
Gets the dateTimeAt attribute of the Record object
Parameters
idx Description of the Parameter
tidx Description of the Parameter
Returns
The dateTimeAt value
{
        return getDateTimeAt(getBuffer(), idx, tidx);
    }
References Record.getBuffer(), and Record.getDateTimeAt().
Referenced by Record.getDateTimeAt(), DatebookRecord.setBuffer(), and FTB3TripRecord.setBuffer().
getDoubleAt()
static double getDoubleAt (byte buffer[], int idx) inline static
Gets the doubleAt attribute of the Record class
Parameters
buffer Description of the Parameter
idx Description of the Parameter
Returns
The doubleAt value
{
        long l = getDoubleLongAt(buffer, idx);
        return Double.longBitsToDouble(l);
    }
References buffer, and Record.getDoubleLongAt().
Referenced by FTB3TripRecord.setBuffer(), and FTB3VehicleRecord.setBuffer().
getDoubleLongAt()
static long getDoubleLongAt (byte buffer[], int idx) inline static
Gets the doubleLongAt attribute of the Record class
Parameters
buffer Description of the Parameter
idx Description of the Parameter
Returns
The doubleLongAt value
{
        long value = 0;
        //A clumsy hack, but quick
        //could not think of a better version
        //java makes is impossible to convert large bytes to chars wihtout
        //losing information
        for (int octet = 0; octet < 8; octet++) {
            for (int bit = 0; bit < 8; bit++) {
                if ((buffer[octet + idx] & (1 << bit)) != 0) {
                    value |= (1L << (56 - octet * 8 + bit));
                }
            }
        }
        return value;
    }
References buffer.
Referenced by Record.getDoubleAt().
getId()
long getId () inline
Gets the id attribute of the Record object
Returns
The id value
{
        return id;
    }
References Record.id.
Referenced by Record.Record(), adrtest.main(), datebooktst.main(), MidiMgr.main(), and test.main().
getIntAt() [1/2]
static int getIntAt (byte buffer[], int idx) inline static
Gets the intAt attribute of the Record class
Parameters
buffer Description of the Parameter
idx Description of the Parameter
Returns
The intAt value
{
        return ((buffer[idx] & 0xff) << 8) + (buffer[idx + 1] & 0xff);
    }
References buffer.
getIntAt() [2/2]
int getIntAt (int idx) inline
Gets the intAt attribute of the Record object
Parameters
idx Description of the Parameter
Returns
The intAt value
{
        return getIntAt(getBuffer(), idx);
    }
References Record.getBuffer(), and Record.getIntAt().
Referenced by Record.getIntAt(), AddressAppInfo.setBuffer(), and ToDoRecord.setBuffer().
getLongAt()
static long getLongAt (byte buffer[], int idx) inline static
Gets the longAt attribute of the Record class
Parameters
buffer Description of the Parameter
idx Description of the Parameter
Returns
The longAt value
{
        long value = 0;
        //A clumsy hack, but quick
        //could not think of a better version
        //java makes is impossible to convert large bytes to chars wihtout
        //losing information
        for (int octet = 0; octet < 4; octet++) {
            for (int bit = 0; bit < 8; bit++) {
                if ((buffer[octet + idx] & (1 << bit)) != 0) {
                    value |= (1L << (24 - octet * 8 + bit));
                }
            }
        }
        return value;
    }
References buffer.
Referenced by AppInfo.parseCategories(), AddressAppInfo.setBuffer(), and FTB3TripRecord.setBuffer().
getSize()
int getSize () inline
Gets the size attribute of the Record object
Returns
The size value
Reimplemented in AddressRecord.
{
        return size;
    }
References Record.size.
Referenced by Record.Record(), datebooktst.main(), MidiMgr.main(), and test.main().
getStringAt() [1/2]
static String getStringAt (byte buffer[], int idx) inline static
Gets the stringAt attribute of the Record class
Parameters
buffer Description of the Parameter
idx Description of the Parameter
Returns
The stringAt value
{
        String str = "";
        while (idx < buffer.length && buffer[idx] != 0) {
            if (buffer[idx] + 256 == 252) {
                str += "\ufffd";
            } else if (buffer[idx] + 256 == 246) {
                str += "\ufffd";
            } else if (buffer[idx] + 256 == 228) {
                str += "\ufffd";
            } else if (buffer[idx] + 256 == 223) {
                str += "\ufffd";
            } else if (buffer[idx] + 256 == 196) {
                str += "\ufffd";
            } else if (buffer[idx] + 256 == 220) {
                str += "\ufffd";
            } else if (buffer[idx] + 256 == 214) {
                str += "\ufffd";
            } else {
                str += (char) buffer[idx];
            }
            idx++;
        }
        return str;
    }
References buffer.
getStringAt() [2/2]
String getStringAt (int idx) inline
Gets the stringAt attribute of the Record object
Parameters
idx Description of the Parameter
Returns
The stringAt value
{
        return getStringAt(getBuffer(), idx);
    }
References Record.getBuffer(), and Record.getStringAt().
Referenced by Record.getStringAt(), AddressAppInfo.setBuffer(), AddressRecord.setBuffer(), DatebookRecord.setBuffer(), FTB3CostCatRecord.setBuffer(), FTB3TripRecord.setBuffer(), FTB3VehicleRecord.setBuffer(), MidiRecord.setBuffer(), and ToDoRecord.setBuffer().
isArchived()
boolean isArchived () inline
Gets the archived attribute of the Record object
Returns
The archived value
{
        return (attribs & ARCHIVED) != 0;
    }
References Record.ARCHIVED, and Record.attribs.
Referenced by datebooktst.main(), and test.main().
isBusy()
boolean isBusy () inline
Gets the busy attribute of the Record object
Returns
The busy value
{
        return (attribs & BUSY) != 0;
    }
References Record.attribs, and Record.BUSY.
isDeleted()
boolean isDeleted () inline
Gets the deleted attribute of the Record object
Returns
The deleted value
{
        return (attribs & DELETED) != 0;
    }
References Record.attribs, and Record.DELETED.
Referenced by adrtest.main(), datebooktst.main(), and test.main().
isDirty()
boolean isDirty () inline
Gets the dirty attribute of the Record object
Returns
The dirty value
{
        return (attribs & DIRTY) != 0;
    }
References Record.attribs, and Record.DIRTY.
Referenced by datebooktst.main(), and test.main().
isSecret()
boolean isSecret () inline
Gets the secret attribute of the Record object
Returns
The secret value
{
        return (attribs & SECRET) != 0;
    }
References Record.attribs, and Record.SECRET.
setArchived()
void setArchived (boolean a) inline
Sets the archived attribute of the Record object
Parameters
a The new archived value
{
        if (a) {
            attribs = attribs | ARCHIVED;
        } else {
            attribs = attribs & (~ARCHIVED);
        }
    }
References Record.ARCHIVED, and Record.attribs.
setAttribs()
void setAttribs (int a) inline
Sets the attribs attribute of the Record object
Parameters
a The new attribs value
{
        attribs = a;
    }
References Record.attribs.
Referenced by RawRecord.RawRecord().
setBuffer()
abstract void setBuffer (byte buf[]) abstract
Sets the buffer attribute of the Record object
Parameters
buf The new buffer value
Reimplemented in AddressRecord, DatebookRecord, FTB3CostCatRecord, FTB3TripRecord, FTB3VehicleRecord, MemoRecord, MidiRecord, RawRecord, and ToDoRecord.
Referenced by Record.Record().
setCategory()
void setCategory (int c) inline
Sets the category attribute of the Record object
Parameters
c The new category value
{
        category = c;
    }
References Record.category.
Referenced by RawRecord.RawRecord().
setDateAt()
static void setDateAt (byte buffer[], Date d, int idx) inline static
Sets the dateAt attribute of the Record class
Parameters
buffer The new dateAt value
d The new dateAt value
idx The new dateAt value
{
        GregorianCalendar cal = new GregorianCalendar();
        //System.out.println("Setting date "+d+" at: "+idx);
        cal.setTime(d);
        int binary = 0;
        int year = cal.get(GregorianCalendar.YEAR);
        int month = cal.get(GregorianCalendar.MONTH);
        int day = cal.get(GregorianCalendar.DAY_OF_MONTH);
        year -= 1904;
        year = year << 9;
        month++;
        month = month << 5;
        binary = year | month | day;
        buffer[idx + 1] = (byte) (binary & 0x00ff);
        buffer[idx] = (byte) ((binary & 0xff00) >> 8);
    }
References buffer.
Referenced by DatebookRecord.getBuffer(), ToDoRecord.getBuffer(), and Record.setDateTimeAt().
setDateTimeAt()
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx) inline static
Sets the dateTimeAt attribute of the Record class
Parameters
buffer The new dateTimeAt value
d The new dateTimeAt value
idx The new dateTimeAt value
tidx The new dateTimeAt value
{
        setDateAt(buffer, d, idx);
        GregorianCalendar cal = new GregorianCalendar();
        cal.setTime(d);
        int h = cal.get(GregorianCalendar.HOUR_OF_DAY);
        int m = cal.get(GregorianCalendar.MINUTE);
        buffer[tidx] = (byte) h;
        buffer[tidx + 1] = (byte) m;
    }
References buffer, and Record.setDateAt().
Referenced by DatebookRecord.getBuffer(), and FTB3TripRecord.getBuffer().
setDirty()
void setDirty (boolean d) inline
Sets the dirty attribute of the Record object
Parameters
d The new dirty value
{
        if (d) {
            attribs = attribs | DIRTY;
        } else {
            attribs = attribs & (~DIRTY);
        }
    }
References Record.attribs, and Record.DIRTY.
Referenced by datebooktst.main(), and test.main().
setDoubleAt()
static void setDoubleAt (byte buffer[], double v, int idx) inline static
Sets the doubleAt attribute of the Record class
Parameters
buffer The new doubleAt value
v The new doubleAt value
idx The new doubleAt value
{
        long l = Double.doubleToLongBits(v);
        setDoubleLongAt(buffer, l, idx);
    }
References buffer, and Record.setDoubleLongAt().
Referenced by FTB3TripRecord.getBuffer().
setDoubleLongAt()
static void setDoubleLongAt (byte buffer[], long v, int idx) inline static
Sets the doubleLongAt attribute of the Record class
Parameters
buffer The new doubleLongAt value
v The new doubleLongAt value
idx The new doubleLongAt value
{
        buffer[idx + 0] = (byte) ((v & 0xff00000000000000L) >> 56);
        buffer[idx + 1] = (byte) ((v & 0x00ff000000000000L) >> 48);
        buffer[idx + 2] = (byte) ((v & 0x0000ff0000000000L) >> 40);
        buffer[idx + 3] = (byte) ((v & 0x000000ff00000000L) >> 32);
        buffer[idx + 4] = (byte) ((v & 0x00000000ff000000L) >> 24);
        buffer[idx + 5] = (byte) ((v & 0x0000000000ff0000L) >> 16);
        buffer[idx + 6] = (byte) ((v & 0x000000000000ff00L) >> 8);
        buffer[idx + 7] = (byte) ((v & 0x00000000000000ffL));
    }
References buffer.
Referenced by Record.setDoubleAt().
setId()
void setId (long i) inline
Sets the id attribute of the Record object
Parameters
i The new id value
{
        id = i;
    }
Referenced by RawRecord.RawRecord().
setIntAt()
static void setIntAt (byte buffer[], int i, int idx) inline static
Sets the intAt attribute of the Record class
Parameters
buffer The new intAt value
i The new intAt value
idx The new intAt value
{
        buffer[idx + 1] = (byte) (i & 0x00ff);
        buffer[idx] = (byte) ((i & 0xff00) >> 8);
    }
References buffer.
Referenced by AddressAppInfo.getBuffer(), and DatebookRecord.getBuffer().
setLongAt()
static void setLongAt (byte buffer[], long v, int idx) inline static
Sets the longAt attribute of the Record class
Parameters
buffer The new longAt value
v The new longAt value
idx The new longAt value
{
        buffer[idx + 0] = (byte) ((v & 0x00000000ff000000L) >> 24);
        buffer[idx + 1] = (byte) ((v & 0x0000000000ff0000L) >> 16);
        buffer[idx + 2] = (byte) ((v & 0x000000000000ff00L) >> 8);
        buffer[idx + 3] = (byte) ((v & 0x00000000000000ffL));
    }
References buffer.
Referenced by AddressRecord.getBuffer(), and FTB3TripRecord.getBuffer().
setSecret()
void setSecret (boolean b) inline
{
        if (b) {
            attribs |=SECRET;
        } else {
            attribs &=(~SECRET);
        }
    }
References Record.attribs, and Record.SECRET.
setSize()
void setSize (int s) inline
Sets the size attribute of the Record object
Parameters
s The new size value
{
        size = s;
    }
References Record.size.
Referenced by DatebookRecord.DatebookRecord(), MemoRecord.MemoRecord(), RawRecord.RawRecord(), DatebookRecord.setAlarmAdvance(), DatebookRecord.setAlarmUnits(), AddressRecord.setBuffer(), DatebookRecord.setBuffer(), FTB3TripRecord.setBuffer(), FTB3VehicleRecord.setBuffer(), MemoRecord.setBuffer(), MidiRecord.setBuffer(), ToDoRecord.setBuffer(), FTB3TripRecord.setCarID(), FTB3TripRecord.setCat(), FTB3TripRecord.setCost(), FTB3TripRecord.setCost(), DatebookRecord.setDescription(), ToDoRecord.setDescription(), FTB3TripRecord.setDestLocation(), ToDoRecord.setDueDate(), DatebookRecord.setEndDate(), FTB3TripRecord.setEndMileage(), AddressRecord.setField(), FTB3TripRecord.setFuel(), FTB3TripRecord.setFuelCost(), AddressRecord.setLabelId(), MidiRecord.setMidi(), FTB3VehicleRecord.setName(), MidiRecord.setName(), DatebookRecord.setNote(), FTB3TripRecord.setNote(), FTB3VehicleRecord.setNote(), ToDoRecord.setNote(), FTB3VehicleRecord.setPlate(), FTB3TripRecord.setPriv(), DatebookRecord.setRepAdvance(), DatebookRecord.setRepDay(), DatebookRecord.setRepDays(), DatebookRecord.setRepeatEnd(), DatebookRecord.setRepExceptions(), DatebookRecord.setRepType(), DatebookRecord.setRepWeekstart(), DatebookRecord.setStartDate(), FTB3TripRecord.setStartLocation(), FTB3TripRecord.setStartMileage(), FTB3TripRecord.setStartTime(), FTB3TripRecord.setStorno(), FTB3TripRecord.setSum(), and MemoRecord.setText().
setStringAt()
static int setStringAt (byte buffer[], String s, int idx) inline static
Sets the stringAt attribute of the Record class
Parameters
buffer The new stringAt value
s The new stringAt value
idx The new stringAt value
Returns
Description of the Return Value
{
        if (s == null) {
            return idx;
        }
        byte str[];
        str = s.getBytes();
        for (int i = 0; i < str.length; i++) {
            if (s.charAt(i) == '\ufffd') {
                buffer[idx + i] = (byte) 252;
            } else if (s.charAt(i) == '\ufffd') {
                buffer[idx + i] = (byte) 246;
            } else if (s.charAt(i) == '\ufffd') {
                buffer[idx + i] = (byte) 228;
            } else if (s.charAt(i) == '\ufffd') {
                buffer[idx + i] = (byte) 223;
            } else if (s.charAt(i) == '\ufffd') {
                buffer[idx + i] = (byte) 196;
            } else if (s.charAt(i) == '\ufffd') {
                buffer[idx + i] = (byte) 220;
            } else if (s.charAt(i) == '\ufffd') {
                buffer[idx + i] = (byte) 214;
            } else {
                buffer[idx + i] = str[i];
            }
        }
        //System.out.println();
        buffer[idx + str.length] = 0;
        return (idx + str.length + 1);
    }
References buffer.
Referenced by AddressAppInfo.getBuffer(), AddressRecord.getBuffer(), DatebookRecord.getBuffer(), FTB3CostCatRecord.getBuffer(), FTB3TripRecord.getBuffer(), FTB3VehicleRecord.getBuffer(), MidiRecord.getBuffer(), and ToDoRecord.getBuffer().
Field Documentation
ARCHIVED
final int ARCHIVED = 0x8 static
Description of the Field
Referenced by Record.isArchived(), and Record.setArchived().
attribs
int attribs protected
Description of the Field
Referenced by Record.Record(), Record.Record(), Record.Record(), Record.getAttribs(), Record.isArchived(), Record.isBusy(), Record.isDeleted(), Record.isDirty(), Record.isSecret(), Record.setArchived(), Record.setAttribs(), Record.setDirty(), and Record.setSecret().
BUSY
final int BUSY = 0x20 static
Description of the Field
Referenced by Record.isBusy().
category
int category protected
Description of the Field
Referenced by Record.Record(), Record.Record(), Record.Record(), Record.getCategory(), and Record.setCategory().
DELETED
final int DELETED = 0x80 static
Description of the Field
Referenced by Record.isDeleted().
DIRTY
final int DIRTY = 0x40 static
Description of the Field
Referenced by Record.isDirty(), and Record.setDirty().
id
long id protected
Description of the Field
Referenced by Record.getId(), and AddressRecord.setLabelId().
SECRET
final int SECRET = 0x10 static
Description of the Field
Referenced by Record.isSecret(), and Record.setSecret().
size
int size protected
Description of the Field
Referenced by Record.Record(), Record.Record(), Record.Record(), AddressRecord.getBuffer(), ToDoRecord.getBuffer(), Record.getSize(), and Record.setSize().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/Record.java