pilot-link: PilotLink Class Reference
PilotLink Class Reference
Public Member Functions
PilotLink (String port) throws IOException, PilotLinkException
void close ()
void closeDB (int dbh) throws PilotLinkException
int createDB (String dbn, String creator, String type) throws PilotLinkException
int createDB (String dbn, String creator, String type, int flags, int version) throws PilotLinkException
int deleteDB (String dbn) throws PilotLinkException
void deleteRecordById (int dbhandle, long id)
void endSync () throws PilotLinkException
RawAppInfo getAppInfo (int db) throws PilotLinkException
RawAppInfo getAppInfoBlock (String dbname)
Record getRecordByIndex (int dbh, int idx) throws PilotLinkException
int getRecordCount (int dbhandle) throws PilotLinkException
RawRecord getResourceByIndex (int dbhandle, int idx) throws PilotLinkException
SysInfo getSysInfo () throws PilotLinkException
User getUserInfo () throws PilotLinkException
boolean isConnected ()
void openConduit () throws PilotLinkException
int openDB (String dbn) throws PilotLinkException
DBInfo readDBList (int cardno, int flags, int start) throws PilotLinkException
void resetSystem () throws PilotLinkException
int writeAppBlock (byte[] data, int dbhandle) throws PilotLinkException
int writeNewRecord (int dbhandle, Record r) throws PilotLinkException
boolean writeRecord (int dbh, Record r) throws PilotLinkException
void writeResource (int dbhandle, RawRecord r) throws PilotLinkException
void writeUserInfo (User u) throws PilotLinkException
Static Package Functions
[static initializer]
Private Member Functions
native void close (int handle)
native void closeDB (int handle, int dbhandle) throws PilotLinkException
native int connect (String port) throws IOException, PilotLinkException
native int createDB (int handle, long creator, String dbname, long type) throws PilotLinkException
native int createDB (int handle, long creator, String dbname, long type, int flags, int version) throws PilotLinkException
native int deleteDB (int handle, String dbname) throws PilotLinkException
native int deleteRecordById (int handle, int dbhandle, long id)
native void endSync (int handle) throws PilotLinkException
native RawAppInfo getAppInfoBlock (int h, String dbnmae)
native RawRecord getRecordByIndex (int handle, int dbhandle, int idx) throws PilotLinkException
native int getRecordCount (int handle, int dbhandle) throws PilotLinkException
native RawRecord getResourceByIndex (int handle, int dbhandle, int idx) throws PilotLinkException
native void openConduit (int handle) throws PilotLinkException
native int openDB (int handle, String dbname) throws PilotLinkException
native RawAppInfo readAppInfo (int h, int db) throws PilotLinkException
native DBInfo readDBList (int handle, int cardno, int flags, int start) throws PilotLinkException
native SysInfo readSysInfo (int handle) throws PilotLinkException
native User readUserInfo (int handle) throws PilotLinkException
native void resetSystem (int handle) throws PilotLinkException
long toLong (char[] charArray)
native int writeAppBlock (int handle, int dbhandle, byte[] data, int length) throws PilotLinkException
native int writeRecord (int handle, int dbhandle, Record r) throws PilotLinkException
native void writeResource (int handle, int dbhandle, RawRecord r) throws PilotLinkException
native void writeUserInfo (int h, User u) throws PilotLinkException
Private Attributes
int handle
Detailed Description
Constructor & Destructor Documentation
PilotLink()
PilotLink (String port) throws IOException, PilotLinkException inline
{
        System.out.println("Initialising Pilot-Link-Java-Bindings V"+Version.VERSION+" build #"+Version.BUILD);
        handle = connect(port);
    }
References Version.BUILD, PilotLink.connect(), PilotLink.handle, port, and Version.VERSION.
Member Function Documentation
[static initializer]()
[static initializer] inline static package
close() [1/2]
void close () inline
{
        close(handle);
        handle = 0;
    }
References PilotLink.close(), and PilotLink.handle.
Referenced by PilotLink.close(), adrtest.main(), datebooktst.main(), MidiMgr.main(), test.main(), and TestTodos.main().
close() [2/2]
native void close (int handle) private
closeDB() [1/2]
void closeDB (int dbh) throws PilotLinkException inline
{
        closeDB(handle, dbh);
        dbh = 0;
    }
References PilotLink.closeDB(), and PilotLink.handle.
Referenced by PilotLink.closeDB(), datebooktst.main(), MidiMgr.main(), and test.main().
closeDB() [2/2]
native void closeDB (int handle, int dbhandle) throws PilotLinkException private
connect()
native int connect (String port) throws IOException, PilotLinkException private
Referenced by PilotLink.PilotLink().
createDB() [1/4]
native int createDB (int handle, long creator, String dbname, long type) throws PilotLinkException private
createDB() [2/4]
native int createDB (int handle, long creator, String dbname, long type, int flags, int version) throws PilotLinkException private
createDB() [3/4]
int createDB (String dbn, String creator, String type) throws PilotLinkException inline
{
        //      System.out.println("Creating new database...");
        long longCreator = toLong(creator.toCharArray());
        long longType = toLong(type.toCharArray());
        return createDB(handle, longCreator, dbn, longType, 0, 1);
    }
References PilotLink.createDB(), PilotLink.handle, and PilotLink.toLong().
Referenced by PilotLink.createDB(), PilotLink.createDB(), and test.main().
createDB() [4/4]
int createDB (String dbn, String creator, String type, int flags, int version) throws PilotLinkException inline
{
        long longCreator = toLong(creator.toCharArray());
        long longType = toLong(type.toCharArray());
        return createDB(handle, longCreator, dbn, longType, flags, version);
    }
References PilotLink.createDB(), flags, PilotLink.handle, and PilotLink.toLong().
deleteDB() [1/2]
native int deleteDB (int handle, String dbname) throws PilotLinkException private
deleteDB() [2/2]
int deleteDB (String dbn) throws PilotLinkException inline
{
        //      System.out.println("Deleting database " + dbn);
        return deleteDB(handle, dbn);
    }
References PilotLink.deleteDB(), and PilotLink.handle.
Referenced by PilotLink.deleteDB(), and test.main().
deleteRecordById() [1/2]
void deleteRecordById (int dbhandle, long id) inline
{
        deleteRecordById(handle, dbhandle, id);
    }
References PilotLink.deleteRecordById(), and PilotLink.handle.
Referenced by PilotLink.deleteRecordById(), adrtest.main(), datebooktst.main(), MidiMgr.main(), and test.main().
deleteRecordById() [2/2]
native int deleteRecordById (int handle, int dbhandle, long id) private
endSync() [1/2]
void endSync () throws PilotLinkException inline
{
        endSync(handle);
    }
References PilotLink.endSync(), and PilotLink.handle.
Referenced by PilotLink.endSync(), adrtest.main(), datebooktst.main(), MidiMgr.main(), test.main(), and TestTodos.main().
endSync() [2/2]
native void endSync (int handle) throws PilotLinkException private
getAppInfo()
RawAppInfo getAppInfo (int db) throws PilotLinkException inline
Deprecated
{
        return readAppInfo(handle, db);
    }
References PilotLink.handle, and PilotLink.readAppInfo().
getAppInfoBlock() [1/2]
native RawAppInfo getAppInfoBlock (int h, String dbnmae) private
getAppInfoBlock() [2/2]
RawAppInfo getAppInfoBlock (String dbname) inline
{
        return getAppInfoBlock(handle,dbname);
    }
References PilotLink.getAppInfoBlock(), and PilotLink.handle.
Referenced by PilotLink.getAppInfoBlock(), adrtest.main(), and test.main().
getRecordByIndex() [1/2]
Record getRecordByIndex (int dbh, int idx) throws PilotLinkException inline
{
        return getRecordByIndex(handle, dbh, idx);
    }
References PilotLink.getRecordByIndex(), and PilotLink.handle.
Referenced by PilotLink.getRecordByIndex(), adrtest.main(), datebooktst.main(), MidiMgr.main(), test.main(), and TestTodos.main().
getRecordByIndex() [2/2]
native RawRecord getRecordByIndex (int handle, int dbhandle, int idx) throws PilotLinkException private
getRecordCount() [1/2]
int getRecordCount (int dbhandle) throws PilotLinkException inline
{
        return getRecordCount(handle, dbhandle);
    }
References PilotLink.getRecordCount(), and PilotLink.handle.
Referenced by PilotLink.getRecordCount(), adrtest.main(), datebooktst.main(), MidiMgr.main(), test.main(), and TestTodos.main().
getRecordCount() [2/2]
native int getRecordCount (int handle, int dbhandle) throws PilotLinkException private
getResourceByIndex() [1/2]
RawRecord getResourceByIndex (int dbhandle, int idx) throws PilotLinkException inline
{
        return getResourceByIndex(handle, dbhandle, idx);
    }
References PilotLink.getResourceByIndex(), and PilotLink.handle.
getResourceByIndex() [2/2]
native RawRecord getResourceByIndex (int handle, int dbhandle, int idx) throws PilotLinkException private
Referenced by PilotLink.getResourceByIndex().
getSysInfo()
SysInfo getSysInfo () throws PilotLinkException inline
{
        //      System.out.println("Getting Sysinfo...");
        SysInfo si = readSysInfo(handle);
        return si;
    }
References PilotLink.handle, and PilotLink.readSysInfo().
Referenced by adrtest.main(), MidiMgr.main(), test.main(), and TestTodos.main().
getUserInfo()
User getUserInfo () throws PilotLinkException inline
{
        User u = readUserInfo(handle);
        return u;
    }
References PilotLink.handle, and PilotLink.readUserInfo().
Referenced by adrtest.main(), datebooktst.main(), MidiMgr.main(), test.main(), and TestTodos.main().
isConnected()
boolean isConnected () inline
{
        return handle >= 0;
    }
References PilotLink.handle.
Referenced by adrtest.main(), datebooktst.main(), MidiMgr.main(), test.main(), and TestTodos.main().
openConduit() [1/2]
void openConduit () throws PilotLinkException inline
{
        openConduit(handle);
    }
References PilotLink.handle, and PilotLink.openConduit().
Referenced by PilotLink.openConduit().
openConduit() [2/2]
native void openConduit (int handle) throws PilotLinkException private
openDB() [1/2]
native int openDB (int handle, String dbname) throws PilotLinkException private
openDB() [2/2]
int openDB (String dbn) throws PilotLinkException inline
{
        return openDB(handle, dbn);
    }
References PilotLink.handle, and PilotLink.openDB().
Referenced by adrtest.main(), datebooktst.main(), MidiMgr.main(), test.main(), TestTodos.main(), and PilotLink.openDB().
readAppInfo()
native RawAppInfo readAppInfo (int h, int db) throws PilotLinkException private
Referenced by PilotLink.getAppInfo().
readDBList() [1/2]
DBInfo readDBList (int cardno, int flags, int start) throws PilotLinkException inline
{
        return readDBList(handle, cardno, flags, start);
    }
References flags, PilotLink.handle, and PilotLink.readDBList().
readDBList() [2/2]
native DBInfo readDBList (int handle, int cardno, int flags, int start) throws PilotLinkException private
Referenced by PilotLink.readDBList().
readSysInfo()
native SysInfo readSysInfo (int handle) throws PilotLinkException private
Referenced by PilotLink.getSysInfo().
readUserInfo()
native User readUserInfo (int handle) throws PilotLinkException private
Referenced by PilotLink.getUserInfo().
resetSystem() [1/2]
void resetSystem () throws PilotLinkException inline
{
        resetSystem(handle);
    }
References PilotLink.handle, and PilotLink.resetSystem().
Referenced by PilotLink.resetSystem().
resetSystem() [2/2]
native void resetSystem (int handle) throws PilotLinkException private
toLong()
long toLong (char[] charArray) inline private
{
        int length = charArray.length;
        long result = 0;
        for (int i = 0; i < length - 1; i++) {
            result |= charArray[i];
            result <<= 8;
        }
        result |= charArray[length - 1];
        return result;
    }
Referenced by PilotLink.createDB(), and PilotLink.createDB().
writeAppBlock() [1/2]
int writeAppBlock (byte[] data, int dbhandle) throws PilotLinkException inline
{
        return writeAppBlock(handle, dbhandle, data, data.length);
    }
References PilotLink.handle, and PilotLink.writeAppBlock().
Referenced by PilotLink.writeAppBlock().
writeAppBlock() [2/2]
native int writeAppBlock (int handle, int dbhandle, byte[] data, int length) throws PilotLinkException private
writeNewRecord()
int writeNewRecord (int dbhandle, Record r) throws PilotLinkException inline
{
        return writeRecord(handle, dbhandle, r);
    }
References PilotLink.handle, and PilotLink.writeRecord().
Referenced by MidiMgr.main().
writeRecord() [1/2]
boolean writeRecord (int dbh, Record r) throws PilotLinkException inline
{
        return writeRecord(handle, dbh, r) > 0;
    }
References PilotLink.handle, and PilotLink.writeRecord().
Referenced by datebooktst.main(), test.main(), PilotLink.writeNewRecord(), and PilotLink.writeRecord().
writeRecord() [2/2]
native int writeRecord (int handle, int dbhandle, Record r) throws PilotLinkException private
writeResource() [1/2]
void writeResource (int dbhandle, RawRecord r) throws PilotLinkException inline
{
        writeResource(handle, dbhandle, r);
    }
References PilotLink.handle, and PilotLink.writeResource().
writeResource() [2/2]
native void writeResource (int handle, int dbhandle, RawRecord r) throws PilotLinkException private
Referenced by PilotLink.writeResource().
writeUserInfo() [1/2]
native void writeUserInfo (int h, User u) throws PilotLinkException private
writeUserInfo() [2/2]
void writeUserInfo (User u) throws PilotLinkException inline
{
        writeUserInfo(handle, u);
    }
References PilotLink.handle, and PilotLink.writeUserInfo().
Referenced by PilotLink.writeUserInfo().
Field Documentation
handle
int handle private
Referenced by PilotLink.PilotLink(), PilotLink.close(), PilotLink.closeDB(), PilotLink.createDB(), PilotLink.createDB(), PilotLink.deleteDB(), PilotLink.deleteRecordById(), PilotLink.endSync(), PilotLink.getAppInfo(), PilotLink.getAppInfoBlock(), PilotLink.getRecordByIndex(), PilotLink.getRecordCount(), PilotLink.getResourceByIndex(), PilotLink.getSysInfo(), PilotLink.getUserInfo(), PilotLink.isConnected(), PilotLink.openConduit(), PilotLink.openDB(), PilotLink.readDBList(), PilotLink.resetSystem(), PilotLink.writeAppBlock(), PilotLink.writeNewRecord(), PilotLink.writeRecord(), PilotLink.writeResource(), and PilotLink.writeUserInfo().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/PilotLink.java