pilot-link: FTB3TripRecord Class Reference
FTB3TripRecord Class Reference
Public Member Functions
FTB3TripRecord ()
FTB3TripRecord (int i, int att, int cat, int sz)
FTB3TripRecord (Record r)
Date getArrivalTime ()
byte[] getBuffer ()
long getCarID ()
long[] getCat ()
double[] getCost ()
String getDestLocation ()
long getEndMileage ()
double getFuel ()
double getFuelCost ()
String getNote ()
String getStartLocation ()
long getStartMileage ()
Date getStartTime ()
double getSum ()
boolean isCost ()
boolean isPriv ()
boolean isStorno ()
void setArrivalTime (Date arrivalTime)
void setBuffer (byte[] buf)
void setCarID (long carID)
void setCat (long[] cat)
void setCost (boolean isCost)
void setCost (double[] cost)
void setDestLocation (String destLocation)
void setEndMileage (long endMileage)
void setFuel (double fuel)
void setFuelCost (float fuelCost)
void setNote (String note)
void setPriv (boolean priv)
void setStartLocation (String startLocation)
void setStartMileage (long startMileage)
void setStartTime (Date startTime)
void setStorno (boolean storno)
void setSum (double sum)
String toString ()
Public Member Functions inherited from Record
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
int getSize ()
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Private Attributes
Date arrivalTime
long carID
long[] cat
double[] cost
String destLocation
long endMileage
double fuel
double fuelCost
boolean isCost
String note
boolean priv
String startLocation
long startMileage
Date startTime
boolean storno
double sum
Additional Inherited Members
Static Public Member Functions inherited from Record
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Static Public Attributes inherited from Record
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Protected Attributes inherited from Record
int attribs
int category
long id
int size
Detailed Description
Author
stephan
To change the template for this generated type comment go to Window>Preferences>Java>Code Generation>Code and Comments
Constructor & Destructor Documentation
FTB3TripRecord() [1/3]
FTB3TripRecord () inline
{
        super();
    }
FTB3TripRecord() [2/3]
FTB3TripRecord (int i, int att, int cat, int sz) inline
Parameters
i
att
cat
sz
{
        super(i, att, cat, sz);
    }
References FTB3TripRecord.cat.
FTB3TripRecord() [3/3]
FTB3TripRecord (Record r) inline
Parameters
r
{
        super(r);
    }
Member Function Documentation
getArrivalTime()
Date getArrivalTime () inline
Returns
Returns the arrivalTime.
{
        return arrivalTime;
    }
References FTB3TripRecord.arrivalTime.
getBuffer()
byte[] getBuffer () inline
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented from Record.
{
        byte buffer[]=new byte[65535];
        Record.setStringAt(buffer,startLocation,0x28);
        Record.setStringAt(buffer,destLocation,0x68);
        Record.setDateTimeAt(buffer,startTime,0x12,0x16);
        Record.setDateTimeAt(buffer,arrivalTime,0x14,0x18);
        Record.setStringAt(buffer,note,0xa8);
        Record.setLongAt(buffer,startMileage*10,0x1a);
        Record.setLongAt(buffer,carID,0x0a);
        if (!priv) buffer[0x101]=1;
        if (storno) buffer[0x102]=1;
        if (isCost) {
            Record.setLongAt(buffer,0,0x1e);
            //Cost
            isCost=true;
            Record.setDoubleAt(buffer,sum,0x28);
            Record.setDoubleAt(buffer,fuel,0x30);
            Record.setDoubleAt(buffer,fuelCost,0x38);
            for (int i=0; i<4; i++) {
                Record.setLongAt(buffer,cat[i],0x40+i*4);
                setDoubleAt(buffer,cost[i],0x50+i*8);
            }
        } else {
            Record.setLongAt(buffer,endMileage*10,0x1e);
        }
        return buffer;
    }
References FTB3TripRecord.arrivalTime, buffer, FTB3TripRecord.carID, FTB3TripRecord.cat, FTB3TripRecord.cost, FTB3TripRecord.destLocation, FTB3TripRecord.endMileage, FTB3TripRecord.fuel, FTB3TripRecord.fuelCost, FTB3TripRecord.isCost, FTB3TripRecord.note, FTB3TripRecord.priv, Record.setDateTimeAt(), Record.setDoubleAt(), Record.setLongAt(), Record.setStringAt(), FTB3TripRecord.startLocation, FTB3TripRecord.startMileage, FTB3TripRecord.startTime, FTB3TripRecord.storno, and FTB3TripRecord.sum.
Referenced by FTB3TripRecord.setCarID(), FTB3TripRecord.setCat(), FTB3TripRecord.setCost(), FTB3TripRecord.setCost(), FTB3TripRecord.setDestLocation(), FTB3TripRecord.setEndMileage(), FTB3TripRecord.setFuel(), FTB3TripRecord.setFuelCost(), FTB3TripRecord.setNote(), FTB3TripRecord.setPriv(), FTB3TripRecord.setStartLocation(), FTB3TripRecord.setStartMileage(), FTB3TripRecord.setStartTime(), FTB3TripRecord.setStorno(), and FTB3TripRecord.setSum().
getCarID()
long getCarID () inline
Returns
Returns the carID.
{
        return carID;
    }
References FTB3TripRecord.carID.
getCat()
long[] getCat () inline
Returns
Returns the cat.
{
        return cat;
    }
References FTB3TripRecord.cat.
getCost()
double[] getCost () inline
Returns
Returns the cost.
{
        return cost;
    }
References FTB3TripRecord.cost.
getDestLocation()
String getDestLocation () inline
Returns
Returns the destLocation.
{
        return destLocation;
    }
References FTB3TripRecord.destLocation.
Referenced by FTB3TripRecord.toString().
getEndMileage()
long getEndMileage () inline
Returns
Returns the endMileage.
{
        return endMileage;
    }
References FTB3TripRecord.endMileage.
Referenced by FTB3TripRecord.toString().
getFuel()
double getFuel () inline
Returns
Returns the fuel.
{
        return fuel;
    }
References FTB3TripRecord.fuel.
getFuelCost()
double getFuelCost () inline
Returns
Returns the fuelCost.
{
        return fuelCost;
    }
References FTB3TripRecord.fuelCost.
getNote()
String getNote () inline
Returns
Returns the note.
{
        return note;
    }
References FTB3TripRecord.note.
getStartLocation()
String getStartLocation () inline
Returns
Returns the startLocation.
{
        return startLocation;
    }
References FTB3TripRecord.startLocation.
Referenced by FTB3TripRecord.toString().
getStartMileage()
long getStartMileage () inline
Returns
Returns the startMileage.
{
        return startMileage;
    }
References FTB3TripRecord.startMileage.
Referenced by FTB3TripRecord.toString().
getStartTime()
Date getStartTime () inline
Returns
Returns the startTime.
{
        return startTime;
    }
References FTB3TripRecord.startTime.
getSum()
double getSum () inline
Returns
Returns the sum.
{
        return sum;
    }
References FTB3TripRecord.sum.
Referenced by FTB3TripRecord.toString().
isCost()
boolean isCost () inline
Returns
Returns the isCost.
{
        return isCost;
    }
References FTB3TripRecord.isCost.
isPriv()
boolean isPriv () inline
Returns
Returns the priv.
{
        return priv;
    }
References FTB3TripRecord.priv.
isStorno()
boolean isStorno () inline
Returns
Returns the storno.
{
        return storno;
    }
References FTB3TripRecord.storno.
setArrivalTime()
void setArrivalTime (Date arrivalTime) inline
Parameters
arrivalTime The arrivalTime to set.
{
        this.arrivalTime= arrivalTime;
    }
References FTB3TripRecord.arrivalTime.
setBuffer()
void setBuffer (byte[] buf) inline
Sets the buffer attribute of the Record object
Parameters
buf The new buffer value
Reimplemented from Record.
{
        this.cat=new long[4];
        cost=new double[4];
        startLocation=Record.getStringAt(buf,0x28);
        destLocation=Record.getStringAt(buf,0x68);
        startTime=Record.getDateTimeAt(buf,0x12,0x16);
        arrivalTime=Record.getDateTimeAt(buf,0x14,0x18);
        note=Record.getStringAt(buf,0xa8);
        startMileage=Record.getLongAt(buf,0x1a)/10;
        endMileage=Record.getLongAt(buf,0x1e)/10;
        carID=Record.getLongAt(buf,0x0a);
        priv=(buf[0x101]==0);
        storno=(buf[0x102]==1);
        if (endMileage==0) {
            //Cost
            isCost=true;
            sum=Record.getDoubleAt(buf,0x28);
            fuel=Record.getDoubleAt(buf,0x30);
            fuelCost=Record.getDoubleAt(buf,0x38);
            for (int i=0; i<4; i++) {
                cat[i]=Record.getLongAt(buf,0x40+i*4);
                cost[i]=getDoubleAt(buf,0x50+i*8);
            }
        }
        setSize(buf.length);
    }
References FTB3TripRecord.arrivalTime, buf, FTB3TripRecord.carID, FTB3TripRecord.cat, FTB3TripRecord.cost, FTB3TripRecord.destLocation, FTB3TripRecord.endMileage, FTB3TripRecord.fuel, FTB3TripRecord.fuelCost, Record.getDateTimeAt(), Record.getDoubleAt(), Record.getLongAt(), Record.getStringAt(), FTB3TripRecord.isCost, FTB3TripRecord.note, FTB3TripRecord.priv, Record.setSize(), FTB3TripRecord.startLocation, FTB3TripRecord.startMileage, FTB3TripRecord.startTime, FTB3TripRecord.storno, and FTB3TripRecord.sum.
setCarID()
void setCarID (long carID) inline
Parameters
carID The carID to set.
{
        this.carID= carID;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.carID, FTB3TripRecord.getBuffer(), and Record.setSize().
setCat()
void setCat (long[] cat) inline
Parameters
cat The cat to set.
{
        this.cat= cat;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.cat, FTB3TripRecord.getBuffer(), and Record.setSize().
setCost() [1/2]
void setCost (boolean isCost) inline
Parameters
isCost The isCost to set.
{
        this.isCost= isCost;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), FTB3TripRecord.isCost, and Record.setSize().
setCost() [2/2]
void setCost (double[] cost) inline
Parameters
cost The cost to set.
{
        this.cost= cost;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.cost, FTB3TripRecord.getBuffer(), and Record.setSize().
setDestLocation()
void setDestLocation (String destLocation) inline
Parameters
destLocation The destLocation to set.
{
        this.destLocation= destLocation;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.destLocation, FTB3TripRecord.getBuffer(), and Record.setSize().
setEndMileage()
void setEndMileage (long endMileage) inline
Parameters
endMileage The endMileage to set.
{
        this.endMileage= endMileage;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.endMileage, FTB3TripRecord.getBuffer(), and Record.setSize().
setFuel()
void setFuel (double fuel) inline
Parameters
fuel The fuel to set.
{
        this.fuel= fuel;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.fuel, FTB3TripRecord.getBuffer(), and Record.setSize().
setFuelCost()
void setFuelCost (float fuelCost) inline
Parameters
fuelCost The fuelCost to set.
{
        this.fuelCost= fuelCost;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.fuelCost, FTB3TripRecord.getBuffer(), and Record.setSize().
setNote()
void setNote (String note) inline
Parameters
note The note to set.
{
        this.note= note;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), FTB3TripRecord.note, and Record.setSize().
setPriv()
void setPriv (boolean priv) inline
Parameters
priv The priv to set.
{
        this.priv= priv;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), FTB3TripRecord.priv, and Record.setSize().
setStartLocation()
void setStartLocation (String startLocation) inline
Parameters
startLocation The startLocation to set.
{
        this.startLocation= startLocation;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), Record.setSize(), and FTB3TripRecord.startLocation.
setStartMileage()
void setStartMileage (long startMileage) inline
Parameters
startMileage The startMileage to set.
{
        this.startMileage= startMileage;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), Record.setSize(), and FTB3TripRecord.startMileage.
setStartTime()
void setStartTime (Date startTime) inline
Parameters
startTime The startTime to set.
{
        this.startTime= startTime;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), Record.setSize(), and FTB3TripRecord.startTime.
setStorno()
void setStorno (boolean storno) inline
Parameters
storno The storno to set.
{
        this.storno= storno;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), Record.setSize(), and FTB3TripRecord.storno.
setSum()
void setSum (double sum) inline
Parameters
sum The sum to set.
{
        this.sum= sum;
        setSize(getBuffer().length);
    }
References FTB3TripRecord.getBuffer(), Record.setSize(), and FTB3TripRecord.sum.
toString()
String toString () inline
{
        String out="";
        if (isCost) {
            out="cost "+getSum();
        } else {
            out="trip "+getStartLocation()+" ("+getStartMileage()+"km) ->"+getDestLocation()+"("+getEndMileage()+")";
        }
        return out;
    }
References FTB3TripRecord.getDestLocation(), FTB3TripRecord.getEndMileage(), FTB3TripRecord.getStartLocation(), FTB3TripRecord.getStartMileage(), FTB3TripRecord.getSum(), and FTB3TripRecord.isCost.
Field Documentation
arrivalTime
Date arrivalTime private
Referenced by FTB3TripRecord.getArrivalTime(), FTB3TripRecord.getBuffer(), FTB3TripRecord.setArrivalTime(), and FTB3TripRecord.setBuffer().
carID
long carID private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getCarID(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setCarID().
cat
long [] cat private
Referenced by FTB3TripRecord.FTB3TripRecord(), FTB3TripRecord.getBuffer(), FTB3TripRecord.getCat(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setCat().
cost
double [] cost private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getCost(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setCost().
destLocation
String destLocation private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getDestLocation(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setDestLocation().
endMileage
long endMileage private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getEndMileage(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setEndMileage().
fuel
double fuel private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getFuel(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setFuel().
fuelCost
double fuelCost private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getFuelCost(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setFuelCost().
isCost
boolean isCost private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.isCost(), FTB3TripRecord.setBuffer(), FTB3TripRecord.setCost(), and FTB3TripRecord.toString().
note
String note private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getNote(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setNote().
priv
boolean priv private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.isPriv(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setPriv().
startLocation
String startLocation private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getStartLocation(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setStartLocation().
startMileage
long startMileage private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getStartMileage(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setStartMileage().
startTime
Date startTime private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getStartTime(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setStartTime().
storno
boolean storno private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.isStorno(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setStorno().
sum
double sum private
Referenced by FTB3TripRecord.getBuffer(), FTB3TripRecord.getSum(), FTB3TripRecord.setBuffer(), and FTB3TripRecord.setSum().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/FTB3TripRecord.java