pilot-link: ToDoRecord Class Reference
ToDoRecord Class Reference
Public Member Functions
ToDoRecord ()
ToDoRecord (Record r)
byte[] getBuffer ()
String getDescription ()
boolean getDone ()
Date getDueDate ()
String getNote ()
int getPriority ()
void setBuffer (byte[] buf)
void setDescription (String d)
void setDone (boolean d)
void setDueDate (Date dd)
void setNote (String n)
void setPriority (int i)
String toString ()
Public Member Functions inherited from Record
Record ()
Record (int i, int att, int cat, int sz)
Record (Record r)
int getAttribs ()
int getCategory ()
Date getDateAt (int idx)
Date getDateTimeAt (int idx, int tidx)
long getId ()
int getIntAt (int idx)
int getSize ()
String getStringAt (int idx)
boolean isArchived ()
boolean isBusy ()
boolean isDeleted ()
boolean isDirty ()
boolean isSecret ()
void setArchived (boolean a)
void setAttribs (int a)
void setCategory (int c)
void setDirty (boolean d)
void setId (long i)
void setSecret (boolean b)
void setSize (int s)
Private Attributes
String description
boolean done
Date dueDate
String note
byte priority
Additional Inherited Members
Static Public Member Functions inherited from Record
static Date getDateAt (byte buffer[], int idx)
static Date getDateTimeAt (byte buffer[], int idx, int tidx)
static double getDoubleAt (byte buffer[], int idx)
static long getDoubleLongAt (byte buffer[], int idx)
static int getIntAt (byte buffer[], int idx)
static long getLongAt (byte buffer[], int idx)
static String getStringAt (byte buffer[], int idx)
static void setDateAt (byte buffer[], Date d, int idx)
static void setDateTimeAt (byte buffer[], Date d, int idx, int tidx)
static void setDoubleAt (byte buffer[], double v, int idx)
static void setDoubleLongAt (byte buffer[], long v, int idx)
static void setIntAt (byte buffer[], int i, int idx)
static void setLongAt (byte buffer[], long v, int idx)
static int setStringAt (byte buffer[], String s, int idx)
Static Public Attributes inherited from Record
static final int ARCHIVED = 0x8
static final int BUSY = 0x20
static final int DELETED = 0x80
static final int DIRTY = 0x40
static final int SECRET = 0x10
Protected Attributes inherited from Record
int attribs
int category
long id
int size
Detailed Description
Author
stephan
TODO To change the template for this generated type comment go to Window - Preferences - Java - Code Style - Code Templates
Constructor & Destructor Documentation
ToDoRecord() [1/2]
ToDoRecord (Record r) inline
{
        super(r);
    }
ToDoRecord() [2/2]
ToDoRecord () inline
{
    }
Member Function Documentation
getBuffer()
byte[] getBuffer () inline
Gets the buffer attribute of the Record object
Returns
The buffer value
Reimplemented from Record.
{
        int size=3;
        if (note!=null) {
            size+=note.length()+1;
        } else {
            size++;
        }
        if (description!=null)  {
            size+=description.length()+1;
        } else {
            size++;
        }
        byte buf[]=new byte[size];
        System.out.println("Size: "+size);
        if (dueDate!=null) {
            Record.setDateAt(buf,dueDate,0);
        } else {
            buf[0]=(byte)0xff; buf[1]=(byte)0xff;
        }
        buf[2]=priority;
        if(done) {
            buf[2]|=0x80;
        }
        int offset=3;
        if (description!=null) {
            offset=Record.setStringAt(buf,description,offset);
        } else {
            buf[offset++]=0;
        }
        if (note!=null) {
            Record.setStringAt(buf,note,offset);
        } else {
            buf[offset++]=0;
        }
        return buf;
    }
References buf, ToDoRecord.description, ToDoRecord.done, ToDoRecord.dueDate, ToDoRecord.note, ToDoRecord.priority, Record.setDateAt(), Record.setStringAt(), and Record.size.
Referenced by TestTodos.main(), ToDoRecord.setDescription(), ToDoRecord.setDueDate(), and ToDoRecord.setNote().
getDescription()
String getDescription () inline
{
        return description;
    }
References ToDoRecord.description.
getDone()
boolean getDone () inline
{
        return done;
    }
References ToDoRecord.done.
getDueDate()
Date getDueDate () inline
{
        return dueDate;
    }
References ToDoRecord.dueDate.
getNote()
String getNote () inline
{
        return note;
    }
References ToDoRecord.note.
getPriority()
int getPriority () inline
{
        return priority;
    }
References ToDoRecord.priority.
setBuffer()
void setBuffer (byte[] buf) inline
Sets the buffer attribute of the Record object
Parameters
buf The new buffer value
Reimplemented from Record.
{
        if (Record.getIntAt(buf,0) != 0xffff) {
            //due-date set
            System.out.println("\n\nReading in due-date..."+(buf[0]&0xff)+"  "+(buf[1]&0xff)+" getInt "+Record.getIntAt(buf,0)+" "+Record.getDateAt(buf,0));
            dueDate=Record.getDateAt(buf,0);
        }
        priority=buf[2];
        if ((priority & 0x80) > 0) {
            //Completed
            priority&=0x7f;
            done=true;
        } else {
            done=false;
        }
        if (buf.length <= 3) {
            return;
        }
        int pos=3;
        description=Record.getStringAt(buf,3);
        if (buf.length<=3+description.length()) {
            return;
        }
        note=Record.getStringAt(buf,3+description.length());
        setSize(buf.length);
    }
References buf, ToDoRecord.description, ToDoRecord.done, ToDoRecord.dueDate, Record.getDateAt(), Record.getIntAt(), Record.getStringAt(), ToDoRecord.note, ToDoRecord.priority, and Record.setSize().
setDescription()
void setDescription (String d) inline
{
        description=d;
        setSize(getBuffer().length);
    }
References ToDoRecord.description, ToDoRecord.getBuffer(), and Record.setSize().
setDone()
void setDone (boolean d) inline
{
        done=d;
    }
References ToDoRecord.done.
setDueDate()
void setDueDate (Date dd) inline
{
        dueDate=dd;
        setSize(getBuffer().length);
    }
References ToDoRecord.dueDate, ToDoRecord.getBuffer(), and Record.setSize().
setNote()
void setNote (String n) inline
{
        note=n;
        setSize(getBuffer().length);
    }
References ToDoRecord.getBuffer(), ToDoRecord.note, and Record.setSize().
setPriority()
void setPriority (int i) inline
{
        if (i>255)
            throw new IllegalArgumentException("Invalid priority");
        priority=(byte)i;
    }
References ToDoRecord.priority.
toString()
String toString () inline
{
        return "P"+priority+": "+description+" Done: "+done+" due to: "+dueDate+" note: "+note;
    }
References ToDoRecord.description, ToDoRecord.done, ToDoRecord.dueDate, ToDoRecord.note, and ToDoRecord.priority.
Field Documentation
description
String description private
Referenced by ToDoRecord.getBuffer(), ToDoRecord.getDescription(), ToDoRecord.setBuffer(), ToDoRecord.setDescription(), and ToDoRecord.toString().
done
boolean done private
Referenced by ToDoRecord.getBuffer(), ToDoRecord.getDone(), ToDoRecord.setBuffer(), ToDoRecord.setDone(), and ToDoRecord.toString().
dueDate
Date dueDate private
Referenced by ToDoRecord.getBuffer(), ToDoRecord.getDueDate(), ToDoRecord.setBuffer(), ToDoRecord.setDueDate(), and ToDoRecord.toString().
note
String note private
Referenced by ToDoRecord.getBuffer(), ToDoRecord.getNote(), ToDoRecord.setBuffer(), ToDoRecord.setNote(), and ToDoRecord.toString().
priority
byte priority private
Referenced by ToDoRecord.getBuffer(), ToDoRecord.getPriority(), ToDoRecord.setBuffer(), ToDoRecord.setPriority(), and ToDoRecord.toString().
The documentation for this class was generated from the following file:
bindings/Java/org/gnu/pilotlink/ToDoRecord.java