pilot-link: libpisock/connect.c File Reference
connect.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/stat.h>
#include "pi-socket.h"
#include "pi-dlp.h"
#include "pi-header.h"
Functions
int pilot_connect (const char *port)
Function Documentation
pilot_connect()
int pilot_connect (const char * port)
{
    int     sd  = -1,   /* Socket, formerly parent/client_socket */
        result;
    struct  SysInfo sys_info;
    fprintf(stderr, "\n");
    fprintf(stderr,"   DEPRECATED: The application is calling pilot_connect()\n");
    if ((sd = pi_socket(PI_AF_PILOT,
            PI_SOCK_STREAM, PI_PF_DLP)) < 0) {
        fprintf(stderr, "\n   Unable to create socket '%s'\n", port);
        return -1;
    }
    result = pi_bind(sd, port);
    if (result < 0) {
        if (port == NULL)
            fprintf(stderr, "   No port specified\n");
        else
            fprintf(stderr, "   Unable to bind to port: %s\n", port);
        fprintf(stderr, "   Please use --help for more information\n\n");
        return result;
    }
    if (isatty(fileno(stdout))) {
        printf("\n   Listening for incoming connection on %s... ",
            port);
        fflush(stdout);
    }
    if (pi_listen(sd, 1) < 0) {
        fprintf(stderr, "\n   Error listening on %s\n", port);
        pi_close(sd);
        return -1;
    }
    sd = pi_accept(sd, 0, 0);
    if (sd < 0) {
        fprintf(stderr, "\n   Error accepting data on %s\n", port);
        pi_close(sd);
        return -1;
    }
    if (isatty(fileno(stdout))) {
        printf("connected!\n\n");
    }
    if (dlp_ReadSysInfo(sd, &sys_info) < 0) {
        fprintf(stderr, "\n   Error read system info on %s\n", port);
        pi_close(sd);
        return -1;
    }
    dlp_OpenConduit(sd);
    return sd;
}
References dlp_OpenConduit(), dlp_ReadSysInfo(), pi_accept(), pi_bind(), pi_close(), pi_listen(), pi_socket(), port, and sd.