pilot-link: libpisock/debug.c File Reference
debug.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include "pi-debug.h"
#include "pi-threadsafe.h"
Functions
void dumpdata (const char *buf, size_t len)
void dumpline (const char *buf, size_t len, unsigned int addr)
int pi_debug_get_level (void)
int pi_debug_get_types (void)
void pi_debug_set_file (const char *path)
void pi_debug_set_level (int level)
void pi_debug_set_types (int types)
void pi_dumpdata (const char *buf, size_t len)
void pi_dumpline (const char *buf, size_t len, unsigned int addr)
void pi_log (int type, int level, const char *format,...)
static PI_MUTEX_DEFINE (logfile_mutex)
Variables
static FILE * debug_file = NULL
static int debug_level = PI_DBG_LVL_NONE
static int debug_types = PI_DBG_NONE
Function Documentation
dumpdata()
void dumpdata (const char * buf, size_t len)
{
    /* this function will be removed in 0.13. Use pi_dumpdata() instead */
    pi_dumpdata(buf, len);
}
References buf, and pi_dumpdata().
dumpline()
void dumpline (const char * buf, size_t len, unsigned int addr)
{
    /* this function will be removed in 0.13. Use pi_dumpline() instead. */
    pi_dumpline(buf, len, addr);
}
References buf, and pi_dumpline().
pi_debug_get_level()
int pi_debug_get_level (void)
{
    return debug_level;
}
References debug_level.
pi_debug_get_types()
int pi_debug_get_types (void)
{
    return debug_types;
}
References debug_types.
pi_debug_set_file()
void pi_debug_set_file (const char * path)
{
    pi_mutex_lock(&logfile_mutex);
    if (debug_file != NULL && debug_file != stderr)
        fclose (debug_file);
    debug_file = fopen (path, "a");
    if (debug_file == NULL)
        debug_file = stderr;
    pi_mutex_unlock(&logfile_mutex);
}
References debug_file, pi_mutex_lock(), and pi_mutex_unlock().
Referenced by env_dbgcheck().
pi_debug_set_level()
void pi_debug_set_level (int level)
{
    pi_mutex_lock(&logfile_mutex);
    debug_level = level;
    pi_mutex_unlock(&logfile_mutex);
}
References debug_level, pi_mutex_lock(), and pi_mutex_unlock().
Referenced by env_dbgcheck().
pi_debug_set_types()
void pi_debug_set_types (int types)
{
    debug_types = types;
}
References debug_types, and types.
Referenced by env_dbgcheck().
pi_dumpdata()
void pi_dumpdata (const char * buf, size_t len)
{
    unsigned int i;
    for (i = 0; i < len; i += 16)
        pi_dumpline(buf + i, ((len - i) > 16) ? 16 : len - i, i);
}
References buf, and pi_dumpline().
Referenced by decode_generic_connection_information(), dlp_CallApplication(), dlp_ReadAppBlock(), dlp_ReadAppPreference(), dlp_ReadNextRecInCategory(), dlp_ReadRecordIDList(), dlp_ReadResourceByIndex(), dlp_ReadResourceByType(), dlp_ReadSortBlock(), dlp_response_read(), do_get_ram(), do_read(), dumpdata(), find_interfaces(), main(), main(), net_dump(), net_rx(), net_tx(), padp_dump(), read_pilot(), read_visor_connection_information(), slp_dump(), slp_rx(), sys_dump(), u_read(), and u_write().
pi_dumpline()
void pi_dumpline (const char * buf, size_t len, unsigned int addr)
{
    unsigned int i;
    int offset;
    char line[256];
    offset = sprintf(line, "  %.4x  ", addr);
    for (i = 0; i < 16; i++) {
        if (i < len)
            offset += sprintf(line+offset, "%.2x ",
                   0xff & (unsigned int) buf[i]);
        else {
            strcpy(line+offset, "   ");
            offset += 3;
        }
    }
    strcpy(line+offset, "  ");
    offset += 2;
    for (i = 0; i < len; i++) {
        if (buf[i] == '%') {
            /* since we're going through pi_log, we need to
             * properly escape % characters
             */
            line[offset++] = '%';
            line[offset++] = '%';
        } else if (isprint(buf[i]) && buf[i] >= 32 && buf[i] <= 126)
            line[offset++] = buf[i];
        else
            line[offset++] = '.';
    }
    strcpy(line+offset,"\n");
    LOG((PI_DBG_ALL, PI_DBG_LVL_NONE, line));
}
References buf, and line.
Referenced by dumpline(), and pi_dumpdata().
pi_log()
void pi_log (int type, int level, const char * format, ...)
{
    va_list ap;
    if (!(debug_types & type) && type != PI_DBG_ALL)
        return;
    if (debug_level < level)
        return;
    pi_mutex_lock(&logfile_mutex);
    if (debug_file == NULL)
        debug_file = stderr;
#if HAVE_PTHREAD
    fprintf(debug_file, "[thread 0x%08lx] ", pi_thread_id());
#endif
    va_start(ap, format);
    vfprintf(debug_file, format, ap);
    va_end(ap);
    fflush(debug_file);
    pi_mutex_unlock(&logfile_mutex);
}
References debug_file, debug_level, debug_types, pi_mutex_lock(), pi_mutex_unlock(), and pi_thread_id().
PI_MUTEX_DEFINE()
static PI_MUTEX_DEFINE (logfile_mutex) static
Variable Documentation
debug_file
FILE* debug_file = NULL static
Referenced by pi_debug_set_file(), and pi_log().
debug_level
int debug_level = PI_DBG_LVL_NONE static
Referenced by pi_debug_get_level(), pi_debug_set_level(), and pi_log().
debug_types
int debug_types = PI_DBG_NONE static
Referenced by pi_debug_get_types(), pi_debug_set_types(), and pi_log().