pilot-link: libpisock/expense.c File Reference
expense.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "pi-macros.h"
#include "pi-expense.h"
Functions
void free_Expense (Expense_t *expense)
int pack_Expense (Expense_t *expense, unsigned char *record, int len)
int pack_ExpenseAppInfo (ExpenseAppInfo_t *appinfo, unsigned char *record, size_t len)
int pack_ExpensePref (ExpensePref_t *p, unsigned char *record, int len)
int unpack_Expense (Expense_t *expense, unsigned char *buffer, int len)
int unpack_ExpenseAppInfo (ExpenseAppInfo_t *appinfo, unsigned char *record, size_t len)
int unpack_ExpensePref (ExpensePref_t *pref, unsigned char *record, int len)
Variables
char * ExpenseDistanceNames [] = { "Miles", "Kilometers", NULL }
char * ExpensePaymentNames []
char * ExpenseSortNames [] = { "Date", "Type", NULL }
char * ExpenseTypeNames []
Function Documentation
free_Expense()
void free_Expense (Expense_t * expense)
{
    if (expense->note != NULL) {
        free(expense->note);
        expense->note = NULL;
    }
    if (expense->amount != NULL) {
        free(expense->amount);
        expense->amount = NULL;
    }
    if (expense->city != NULL) {
        free(expense->city);
        expense->city = NULL;
    }
    if (expense->vendor != NULL) {
        free(expense->vendor);
        expense->vendor = NULL;
    }
    if (expense->attendees != NULL) {
        free(expense->attendees);
        expense->attendees = NULL;
    }
}
Referenced by main().
pack_Expense()
int pack_Expense (Expense_t * expense, unsigned char * record, int len)
{
    int     destlen = 6 + 1 + 1 + 1 + 1 + 1;
    unsigned char *buf = record;
    if (expense->amount)
        destlen += strlen(expense->amount);
    if (expense->vendor)
        destlen += strlen(expense->vendor);
    if (expense->city)
        destlen += strlen(expense->city);
    if (expense->attendees)
        destlen += strlen(expense->attendees);
    if (expense->note)
        destlen += strlen(expense->note);
    if (!record)
        return destlen;
    if (len < destlen)
        return 0;
    set_short(buf,
          ((expense->date.tm_year - 4) << 9) | ((expense->date.tm_mon +
                           1) << 5) | expense->date.
          tm_mday);
    buf += 2;
    set_byte(buf, expense->type);
    set_byte(buf + 1, expense->payment);
    set_byte(buf + 2, expense->currency);
    set_byte(buf + 3, 0);   /* gapfill */
    buf += 4;
    if (expense->amount) {
        strcpy((char *)buf, expense->amount);
        buf += strlen((char *)buf);
    } else {
        set_byte(buf, 0);
    }
    buf++;
    if (expense->vendor) {
        strcpy((char *)buf, expense->vendor);
        buf += strlen((char *)buf);
    } else {
        set_byte(buf, 0);
    }
    buf++;
    if (expense->city) {
        strcpy((char *)buf, expense->city);
        buf += strlen((char *)buf);
    } else {
        set_byte(buf, 0);
    }
    buf++;
    if (expense->attendees) {
        strcpy((char *)buf, expense->attendees);
        buf += strlen((char *)buf);
    } else {
        set_byte(buf, 0);
    }
    buf++;
    if (expense->note) {
        strcpy((char *)buf, expense->note);
        buf += strlen((char *)buf);
    } else {
        set_byte(buf, 0);
    }
    buf++;
    return (buf - record);
}
References buf.
Referenced by main().
pack_ExpenseAppInfo()
int pack_ExpenseAppInfo (ExpenseAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int     i,
        destlen = 2 + (16 + 4 + 8) * 4;
    unsigned char *start = record;
    i = pack_CategoryAppInfo(&appinfo->category, record, len);
    if (!record)
        return i + destlen;
    if (!i)
        return i;
    record  += i;
    len     -= i;
    if (len < destlen)
        return 0;
    set_byte(record, appinfo->sortOrder);
    set_byte(record + 1, 0);    /* gapfill */
    record += 2;
    for (i = 0; i < 4; i++) {
        memcpy(record, appinfo->currencies[i].name, 16);
        record += 16;
        memcpy(record, appinfo->currencies[i].symbol, 4);
        record += 4;
        memcpy(record, appinfo->currencies[i].rate, 8);
        record += 8;
    }
    return (record - start);
}
References pack_CategoryAppInfo().
Referenced by main().
pack_ExpensePref()
int pack_ExpensePref (ExpensePref_t * p, unsigned char * record, int len)
{
    int     i;
    unsigned char *start = record;
    (void) len;
    set_short(record, p->currentCategory);
    record += 2;
    set_short(record, p->defaultCurrency);
    record += 2;
    set_byte(record, p->attendeeFont);
    record++;
    set_byte(record, p->showAllCategories);
    record++;
    set_byte(record, p->showCurrency);
    record++;
    set_byte(record, p->saveBackup);
    record++;
    set_byte(record, p->allowQuickFill);
    record++;
    set_byte(record, p->unitOfDistance);
    record++;
    for (i = 0; i < 5; i++) {
        set_byte(record, p->currencies[i]);
        record++;
    }
    /* Unknown values */
    set_byte(record, 0xff);
    record++;
    set_byte(record, 0xff);
    record++;
    set_byte(record, p->noteFont);
    record++;
    return record - start;
}
Referenced by main().
unpack_Expense()
int unpack_Expense (Expense_t * expense, unsigned char * buffer, int len)
{
    unsigned long d;
    unsigned char *start = buffer;
    if (len < 6)
        return 0;
    d = (unsigned short int) get_short(buffer);
    expense->date.tm_year   = (d >> 9) + 4;
    expense->date.tm_mon    = ((d >> 5) & 15) - 1;
    expense->date.tm_mday   = d & 31;
    expense->date.tm_hour   = 0;
    expense->date.tm_min    = 0;
    expense->date.tm_sec    = 0;
    expense->date.tm_isdst  = -1;
    mktime(&expense->date);
    expense->type   = (enum ExpenseType) get_byte(buffer + 2);
    expense->payment = (enum ExpensePayment) get_byte(buffer + 3);
    expense->currency = get_byte(buffer + 4);
    buffer  += 6;
    len     -= 6;
    if (len < 1)
        return 0;
    if (*buffer) {
        expense->amount = strdup((char *)buffer);
        buffer += strlen(expense->amount);
        len -= strlen(expense->amount);
    } else {
        expense->amount = 0;
    }
    buffer++;
    len--;
    if (len < 1)
        return 0;
    if (*buffer) {
        expense->vendor = strdup((char *)buffer);
        buffer += strlen(expense->vendor);
        len -= strlen(expense->vendor);
    } else {
        expense->vendor = 0;
    }
    buffer++;
    len--;
    if (len < 1)
        return 0;
    if (*buffer) {
        expense->city = strdup((char *)buffer);
        buffer += strlen(expense->city);
        len -= strlen(expense->city);
    } else {
        expense->city = 0;
    }
    buffer++;
    len--;
    if (len < 1)
        return 0;
    if (*buffer) {
        expense->attendees = strdup((char *)buffer);
        buffer += strlen(expense->attendees);
        len -= strlen(expense->attendees);
    } else {
        expense->attendees = 0;
    }
    buffer++;
    len--;
    if (len < 1)
        return 0;
    if (*buffer) {
        expense->note = strdup((char *)buffer);
        buffer += strlen(expense->note);
        len -= strlen(expense->note);
    } else {
        expense->note = 0;
    }
    buffer++;
    len--;
    return (buffer - start);
}
References buffer, and strdup().
Referenced by main().
unpack_ExpenseAppInfo()
int unpack_ExpenseAppInfo (ExpenseAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int     i;
    unsigned char *start = record;
    i = unpack_CategoryAppInfo(&appinfo->category, record, len);
    if (!i)
        return 0;
    record += i;
    len -= i;
    appinfo->sortOrder = (enum ExpenseSort) get_byte(record);
    record += 2;
    for (i = 0; i < 4; i++) {
        memcpy(appinfo->currencies[i].name, record, 16);
        record += 16;
        memcpy(appinfo->currencies[i].symbol, record, 4);
        record += 4;
        memcpy(appinfo->currencies[i].rate, record, 8);
        record += 8;
    }
    return (record - start);
}
References unpack_CategoryAppInfo().
Referenced by main().
unpack_ExpensePref()
int unpack_ExpensePref (ExpensePref_t * pref, unsigned char * record, int len)
{
    int     i;
    unsigned char *start = record;
    (void) len;
    pref->currentCategory   = get_short(record);
    record += 2;
    pref->defaultCurrency   = get_short(record);
    record += 2;
    pref->attendeeFont      = get_byte(record);
    record++;
    pref->showAllCategories = get_byte(record);
    record++;
    pref->showCurrency  = get_byte(record);
    record++;
    pref->saveBackup    = get_byte(record);
    record++;
    pref->allowQuickFill    = get_byte(record);
    record++;
    pref->unitOfDistance    = (enum ExpenseDistance) get_byte(record);
    record++;
    for (i = 0; i < 5; i++) {
        pref->currencies[i] = get_byte(record);
        record++;
    }
    for (i = 0; i < 2; i++) {
        pref->unknown[i] = get_byte(record);
        record++;
    }
    pref->noteFont = get_byte(record);
    record++;
    return (record - start);
}
Referenced by main().
Variable Documentation
ExpenseDistanceNames
char* ExpenseDistanceNames[] = { "Miles", "Kilometers", NULL }
{ "Miles", "Kilometers", NULL };
ExpensePaymentNames
char* ExpensePaymentNames[]
Initial value:
=
    {   "AmEx", "Cash", "Check", "CreditCard", "MasterCard", "Prepaid",
    "VISA", "Unfiled"
}
    {   "AmEx", "Cash", "Check", "CreditCard", "MasterCard", "Prepaid",
    "VISA", "Unfiled"
};
Referenced by main().
ExpenseSortNames
char* ExpenseSortNames[] = { "Date", "Type", NULL }
{ "Date", "Type", NULL };
ExpenseTypeNames
char* ExpenseTypeNames[]
Initial value:
=
    {   "Airfare", "Breakfast", "Bus", "Business Meals", "Car Rental",
    "Dinner", "Entertainment", "Fax", "Gas", "Gifts", "Hotel",
    "Incidentals", "Laundry", "Limo", "Lodging", "Lunch", "Mileage",
    "Other", "Parking", "Postage", "Snack", "Subway", "Supplies",
    "Taxi", "Telephone", "Tips", "Tolls", "Train"
}
    {   "Airfare", "Breakfast", "Bus", "Business Meals", "Car Rental",
    "Dinner", "Entertainment", "Fax", "Gas", "Gifts", "Hotel",
    "Incidentals", "Laundry", "Limo", "Lodging", "Lunch", "Mileage",
    "Other", "Parking", "Postage", "Snack", "Subway", "Supplies",
    "Taxi", "Telephone", "Tips", "Tolls", "Train"
};
Referenced by main().