pilot-link: libpisock/hinote.c File Reference
hinote.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pi-hinote.h"
Functions
void free_HiNoteNote (HiNoteNote_t *hinote)
int pack_HiNoteAppInfo (HiNoteAppInfo_t *appinfo, unsigned char *record, size_t len)
int pack_HiNoteNote (HiNoteNote_t *hinote, unsigned char *buffer, int len)
int unpack_HiNoteAppInfo (HiNoteAppInfo_t *appinfo, unsigned char *record, size_t len)
int unpack_HiNoteNote (HiNoteNote_t *hinote, unsigned char *buffer, int len)
Function Documentation
free_HiNoteNote()
void free_HiNoteNote (HiNoteNote_t * hinote)
{
    if (hinote->text != NULL) {
        free(hinote->text);
        hinote->text = NULL;
    }
}
pack_HiNoteAppInfo()
int pack_HiNoteAppInfo (HiNoteAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int     i,
        idx;
    unsigned char *start = record;
    i = pack_CategoryAppInfo(&appinfo->category, record, len);
    if (i == 0)     /* category pack failed */
        return 0;
    if (!record)
        return i + 48;
    record += i;
    len -= i;
    if (len < 48)
        return (record - start);
    for (idx = 0; i < 48; i++)
        *record++ = appinfo->reserved[i];
    return (record - start);
}
References pack_CategoryAppInfo().
pack_HiNoteNote()
int pack_HiNoteNote (HiNoteNote_t * hinote, unsigned char * buffer, int len)
{
    int     destlen;
    destlen = 3;
    if (hinote->text)
        destlen += strlen(hinote->text);
    if (!buffer)
        return destlen;
    if (len < destlen)
        return 0;
    buffer[0] = hinote->flags;
    buffer[1] = hinote->level;
    if (hinote->text)
        strcpy((char *) &buffer[2], hinote->text);
    else {
        buffer[2] = 0;
    }
    return destlen;
}
References buffer.
Referenced by main().
unpack_HiNoteAppInfo()
int unpack_HiNoteAppInfo (HiNoteAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int     i,
        idx;
    unsigned char *start;
    start = record;
    i = unpack_CategoryAppInfo(&appinfo->category, record, len);
    if (!i)
        return i;
    record += i;
    len -= i;
    if (len < 48)
        return 0;
    for (idx = 0; i < 48; i++)
        appinfo->reserved[i] = *record++;
    return (record - start);
}
References unpack_CategoryAppInfo().
Referenced by main(), and main().
unpack_HiNoteNote()
int unpack_HiNoteNote (HiNoteNote_t * hinote, unsigned char * buffer, int len)
{
    if (len < 3)
        return 0;
    hinote->flags   = buffer[0];
    hinote->level   = buffer[1];
    hinote->text    = strdup((char *) &buffer[2]);
    return strlen((char *) &buffer[2]) + 3;
}
References buffer, and strdup().
Referenced by main().