pilot-link: bindings/Java/libjpisock.h File Reference
libjpisock.h File Reference
#include <jni.h>
Functions
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_close (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_closeDB (JNIEnv *, jobject, jint, jint)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_connect (JNIEnv *, jobject, jstring)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2J (JNIEnv *, jobject, jint, jlong, jstring, jlong)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2JII (JNIEnv *, jobject, jint, jlong, jstring, jlong, jint, jint)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_deleteDB (JNIEnv *, jobject, jint, jstring)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_deleteRecordById (JNIEnv *, jobject, jint, jint, jlong)
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_endSync (JNIEnv *, jobject, jint)
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getAppInfoBlock (JNIEnv *, jobject, jint, jstring)
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getRecordByIndex (JNIEnv *, jobject, jint, jint, jint)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_getRecordCount (JNIEnv *, jobject, jint, jint)
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getResourceByIndex (JNIEnv *, jobject, jint, jint, jint)
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_openConduit (JNIEnv *, jobject, jint)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_openDB (JNIEnv *, jobject, jint, jstring)
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readAppInfo (JNIEnv *, jobject, jint, jint)
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readDBList (JNIEnv *, jobject, jint, jint, jint, jint)
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readSysInfo (JNIEnv *, jobject, jint)
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readUserInfo (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_resetSystem (JNIEnv *, jobject, jint)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_writeAppBlock (JNIEnv *, jobject, jint, jint, jbyteArray, jint)
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_writeRecord (JNIEnv *, jobject, jint, jint, jobject)
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_writeResource (JNIEnv *, jobject, jint, jint, jobject)
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_writeUserInfo (JNIEnv *, jobject, jint, jobject)
Function Documentation
Java_org_gnu_pilotlink_PilotLink_close()
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_close (JNIEnv * env, jobject obj, jint sd)
{
    pi_close(sd);
}
References pi_close(), and sd.
Java_org_gnu_pilotlink_PilotLink_closeDB()
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_closeDB (JNIEnv * env, jobject obj, jint han, jint db)
{
    int bException = 0;
    int ret=dlp_CleanUpDatabase(han, db);
    if (ret<0) {
//       printf("Error cleaning up! %d\n",ret);
        postPilotLinkException(env, "Unable to clean up before database close",
            ret, errno);
        bException = 1;
    }
    ret=dlp_CloseDB(han, db);
    if (ret < 0 && !bException) {
//       printf("Error closing DB: %d\n",ret);
        postPilotLinkException(env, "Unable to close database",
            ret, errno);
    }
}
References dlp_CleanUpDatabase(), dlp_CloseDB(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_connect()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_connect (JNIEnv * env, jobject obj, jstring jprt)
{
    jint iResult = 0;
    const char * port = NULL;
    char * prt = NULL;
    /* Get working copy of port name */
    port = env->GetStringUTFChars(jprt, NULL);
    prt = (char *)malloc(strlen(port) + 1);
    if (prt != NULL) strcpy(prt, port);
    env->ReleaseStringUTFChars(jprt, port);
    iResult = pilot_connect(env, prt);
    if (prt != NULL) free(prt);
    return iResult;
}
References pilot_connect(), and port.
Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2J()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2J (JNIEnv * , jobject , jint , jlong , jstring , jlong)
Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2JII()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2JII (JNIEnv * , jobject , jint , jlong , jstring , jlong , jint , jint)
Java_org_gnu_pilotlink_PilotLink_deleteDB()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_deleteDB (JNIEnv * env, jobject obj, jint handle, jstring jdbname)
{
    int ret = 0;
    /* Get working copy of database name */
    const char * dbname = env->GetStringUTFChars(jdbname,NULL);
    char * dbn = (char*)malloc(strlen(dbname)+1);
    if (dbn != NULL) strcpy(dbn,dbname);
    env->ReleaseStringUTFChars(jdbname, dbname);
    if (dbn != NULL) {
        ret = dlp_DeleteDB(handle,0,dbn);
        if (ret < 0) {
        /* debug message replaced by Java exception */
/*
            printf("Error deleting db %s %d:\n",dbn,ret);
*/
            postPilotLinkException(env, "Could not delete database",
                ret, errno);
        }
        free(dbn);
    } else {
        /* Unable to create copy - memory heap may be corrupted */
        postJavaException(env,
            "org/gnu/pilotlink/PilotLinkException",
            "Unable to create working copy of database name");
    }
    return ret;
}
References dlp_DeleteDB(), postJavaException(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_deleteRecordById()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_deleteRecordById (JNIEnv * env, jobject obj, jint handle, jint db, jlong id)
{
      int ret=dlp_DeleteRecord(handle,db,0,id);
      if (ret<0) {
          postPilotLinkException(env,"Deletition not possible!",ret,errno);
      }
      return ret;
}
References dlp_DeleteRecord(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_endSync()
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_endSync (JNIEnv * env, jobject obj, jint sd)
{
    int iResult = dlp_EndOfSync(sd, dlpEndCodeNormal);
    if (iResult < 0) postPilotLinkException(env, "Unable to signal endSync",
        iResult, errno);
}
References dlp_EndOfSync(), postPilotLinkException(), and sd.
Java_org_gnu_pilotlink_PilotLink_getAppInfoBlock()
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getAppInfoBlock (JNIEnv * env, jobject obj, jint handle, jstring jdbname)
{
    int db;
        const char * dbname = env->GetStringUTFChars(jdbname, NULL);
        char * dbn = (char *)malloc(strlen(dbname) + 1);
        if (dbn != NULL) strcpy(dbn, dbname);
        env->ReleaseStringUTFChars(jdbname, dbname);
    if (dlp_OpenDB(handle,0,0x80|0x40,dbn,&db)<0) {
        printf("Fehler!");
        return NULL;
    }
    jbyte buff[0xffff];
    int l=dlp_ReadAppBlock(handle,db,0,0xffff,(pi_buffer_t*)&buff);
    printf("read app-Block of size %d\n",l);
    fflush(stdout);
    jclass      jClass_appInfo = NULL;
    jobject     jObject_appInfo = NULL;
    jmethodID   jMethod_appInfo = NULL;
    int bProceed = 1;
    int iNumBytesRead = 0;
    if (bProceed) {
        /* Look up RawAppInfo class */
        jClass_appInfo = env->FindClass("org/gnu/pilotlink/RawAppInfo");
        if (jClass_appInfo == NULL) {
            /* pending ClassNotFoundException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Look up constructor method with byte array argument */
        jMethod_appInfo = env->GetMethodID(jClass_appInfo, "<init>","([B)V");
        if (jMethod_appInfo == NULL) {
            /* pending NoSuchMethodException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        jbyteArray jArray_buffer = env->NewByteArray(l);
        env->SetByteArrayRegion(jArray_buffer, 0, (jint)l, buff);
        jObject_appInfo = env->NewObject(jClass_appInfo, jMethod_appInfo, jArray_buffer);
    }
    dlp_CloseDB(handle,db);
    return jObject_appInfo;
}
References dlp_CloseDB(), dlp_OpenDB(), and dlp_ReadAppBlock().
Java_org_gnu_pilotlink_PilotLink_getRecordByIndex()
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getRecordByIndex (JNIEnv * env, jobject obj, jint handle, jint db, jint idx)
{
    jbyte buffer[MAX_RESOURCE_SIZE];
    recordid_t id;
    jint size, attr, category;
    //printf("Getting record..\n");
    int ret = dlp_ReadRecordByIndex(handle, db, idx, (pi_buffer_t*)buffer,
        &id, &attr, &category);
    if (ret<0) {
        postPilotLinkException(env,"Error reading database by index",ret,errno);
        return NULL;
    }
      //printf("getting class!\n");
      jclass rcls=env->FindClass("org/gnu/pilotlink/RawRecord");
      if (rcls==NULL) {
          return NULL;
      }
      jmethodID rid=env->GetMethodID(rcls,"<init>","([BJIII)V");
      if (rid==NULL) {
          printf("jmethodID is null!\n");
          return NULL;
      }
      jbyteArray array=env->NewByteArray(size);
      env->SetByteArrayRegion(array,0,size,buffer);
      jobject record=env->NewObject(rcls, rid, array, (jlong)id,size,attr,category );
      return record;
    /*jbyte * buffer;
    jobject jObject_RawRecord = NULL;
    if ((buffer = (jbyte *)malloc(MAX_RESOURCE_SIZE)) != NULL) {
        recordid_t id;
        jint iRecSize, iRecAttr, iRecCategory;
        jclass jClass_RawRecord;
        jmethodID jMethod_RawRecord;
        int iResult = dlp_ReadRecordByIndex(handle, db, idx, buffer,
            &id, &iRecSize, &iRecAttr, &iRecCategory);
        if (iResult < 0) {
            postPilotLinkException(env, "Could not read database record by index",
                iResult, errno);
        } else if ((jClass_RawRecord = env->FindClass(
            "org/gnu/pilotlink/RawRecord")) == NULL) {
        } else if ((jMethod_RawRecord = env->GetMethodID(jClass_RawRecord,
            "<init>", "([BJIII)V")) == NULL) {
        } else {
            jbyteArray jArray_buffer = env->NewByteArray(iRecSize);
            env->SetByteArrayRegion(jArray_buffer, 0, iRecSize, buffer);
            jObject_RawRecord = env->NewObject(jClass_RawRecord, jMethod_RawRecord,
                jArray_buffer, (jlong)id, (jint)iRecSize, (jint)iRecAttr, (jint)iRecCategory);
        }
        free(buffer);
    } else {
        postJavaException(env,
            "org/gnu/pilotlink/PilotLinkException",
            "Unable to allocate buffer for record data");
    }
    return jObject_RawRecord;*/
}
References buffer, dlp_ReadRecordByIndex(), MAX_RESOURCE_SIZE, postPilotLinkException(), and size.
Java_org_gnu_pilotlink_PilotLink_getRecordCount()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_getRecordCount (JNIEnv * env, jobject obj, jint handle, jint dbh)
{
     jint num;
     int iResult;
     iResult = dlp_ReadOpenDBInfo(handle,dbh,&num);
     if (iResult < 0) {
        postPilotLinkException(env, "Could not get record count for database",
                iResult, errno);
     }
     return num;
}
References dlp_ReadOpenDBInfo(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_getResourceByIndex()
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getResourceByIndex (JNIEnv * env, jobject obj, jint iSockHandle, jint iDBHandle, jint iRsrcIndex)
{
    unsigned long iRsrcType;    /* Resource type */
    int iRsrcID;                /* Resource ID */
    int iRsrcSize;              /* Actual resource size */
    jbyte * pRsrcData;          /* Buffer for resource data */
    int iResult;                /* Result of library call */
    jobject pRecordObject = NULL;
    /* Get "enough" memory for incoming resource data */
    if ((pRsrcData = (jbyte *)malloc(MAX_RESOURCE_SIZE * sizeof(jbyte))) != NULL) {
        /* Invoke C library function */
        iResult = dlp_ReadResourceByIndex(iSockHandle, iDBHandle, iRsrcIndex,
            (pi_buffer_t*)pRsrcData, &iRsrcType, &iRsrcID);
        if (iResult >= 0) {
            jclass pRecordClass;
            jmethodID pRecordConstructor;
            /* Look up class and constructor method */
            if ((pRecordClass = env->FindClass("org/gnu/pilotlink/RawRecord")) != NULL &&
                (pRecordConstructor = env->GetMethodID(pRecordClass, "<init>",
                "([BJIII)V")) != NULL ) {
                /* Fill a Java array with resource data && invoke constructor */
                jbyteArray pJavaArray = env->NewByteArray(iRsrcSize);
                env->SetByteArrayRegion(pJavaArray, 0, iRsrcSize, pRsrcData);
                pRecordObject = env->NewObject(pRecordClass, pRecordConstructor,
                    pJavaArray, (jlong)iRsrcID, (jint)iRsrcSize, (jint)0, (jint)iRsrcType);
            }
        } else {
            postPilotLinkException(env, "Unable to read resource by index", iResult, errno);
        }
        free(pRsrcData);
    } else {
        postJavaException(env,
            "org/gnu/pilotlink/PilotLinkException",
            "Unable to allocate buffer for copy of resource");
    }
    return pRecordObject;
}
References dlp_ReadResourceByIndex(), MAX_RESOURCE_SIZE, postJavaException(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_openConduit()
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_openConduit (JNIEnv * env, jobject obj, jint handle)
{
  int iResult = dlp_OpenConduit(handle);
  if (iResult < 0) postPilotLinkException(env, "Unable to open conduit", iResult, errno);
}
References dlp_OpenConduit(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_openDB()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_openDB (JNIEnv * env, jobject obj, jint handle, jstring jdbname)
{
    jint db = 0;
    /* Get working copy of database name */
    const char* dbname = env->GetStringUTFChars(jdbname,NULL);
    char* dbn = (char*)malloc(strlen(dbname)+1);
    if (dbn != NULL) strcpy(dbn,dbname);
    env->ReleaseStringUTFChars(jdbname, dbname);
    if (dbn != NULL) {
        int ret=dlp_OpenDB(handle,0,dlpOpenReadWrite,dbn,&db);
        if (ret < 0) {
/*
            printf("Error opening db %s: %d\n",dbn, ret);
*/
            postPilotLinkException(env, "Could not open database",
                ret, errno);
            return (jint)ret;
        }
    } else {
        /* Unable to create copy - memory heap may be corrupted */
        postJavaException(env,
            "org/gnu/pilotlink/PilotLinkException",
            "Unable to create working copy of database name");
    }
    return db;
}
References dlp_OpenDB(), postJavaException(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_readAppInfo()
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readAppInfo (JNIEnv * env, jobject obj, jint handle, jint db)
{
/*
    unsigned char buffer[MAX_RESOURCE_SIZE];
    int size=dlp_ReadAppBlock(handle,db, 0,buffer,MAX_RESOURCE_SIZE);
    //printf("STill alive...\n");
    //fflush(stdout);
    jclass appinfo_cls=env->FindClass("org/gnu/pilotlink/RawAppInfo");
    if (appinfo_cls==NULL) {
        printf("Class not found! Sysinfo!\n");
        return NULL;
    }
    //printf("STill alive...\n");
    fflush(stdout);
    jmethodID appinfo_mid=env->GetMethodID(appinfo_cls, "<init>","([B)V");
    if (appinfo_mid==NULL) {
        printf("Problem mid!\n");
        fflush(stdout);
        return NULL;
    }
    //printf("STill alive...\n");
    //fflush(stdout);
    jbyteArray array=env->NewByteArray(size);
    env->SetByteArrayRegion(array,0,(jint)size,(jbyte*)buffer);
    jobject appinfo=env->NewObject(appinfo_cls, appinfo_mid, array);
    return appinfo;
*/
    jclass      jClass_appInfo = NULL;
    jobject     jObject_appInfo = NULL;
    jmethodID   jMethod_appInfo = NULL;
    jbyte * pBuffer = NULL;
    int bProceed = 1;
    int iNumBytesRead = 0;
    if (bProceed) {
        /* Allocate memory for maximum data size */
        pBuffer = (jbyte *)malloc(MAX_RESOURCE_SIZE);
        if (pBuffer == NULL) {
            postJavaException(env,
                "org/gnu/pilotlink/PilotLinkException",
                "Unable to allocate buffer for app-info block");
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Read app-info block && verify successful read */
        iNumBytesRead = dlp_ReadAppBlock(handle, db, 0, MAX_RESOURCE_SIZE, (pi_buffer_t*)pBuffer);
        if (iNumBytesRead < 0) {
            /* Throw Java exception, iNumBytesRead is actually an error code */
            postPilotLinkException(env, "Unable to read app-block", iNumBytesRead, errno);
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Look up RawAppInfo class */
        jClass_appInfo = env->FindClass("org/gnu/pilotlink/RawAppInfo");
        if (jClass_appInfo == NULL) {
            /* pending ClassNotFoundException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Look up constructor method with byte array argument */
        jMethod_appInfo = env->GetMethodID(jClass_appInfo, "<init>","([B)V");
        if (jMethod_appInfo == NULL) {
            /* pending NoSuchMethodException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        jbyteArray jArray_buffer = env->NewByteArray(iNumBytesRead);
        env->SetByteArrayRegion(jArray_buffer, 0, (jint)iNumBytesRead, pBuffer);
        jObject_appInfo = env->NewObject(jClass_appInfo, jMethod_appInfo, jArray_buffer);
    }
    if (pBuffer != NULL) free(pBuffer);
    return jObject_appInfo;
}
References dlp_ReadAppBlock(), MAX_RESOURCE_SIZE, postJavaException(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_readDBList()
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readDBList (JNIEnv * env, jobject , jint iSockHandle, jint cardno, jint flags, jint start)
{
    int iResult = 0;
    struct DBInfo rInfoDB;
    jobject pDBInfoObject = NULL;
    /* Execute low-level library call... */
    iResult = dlp_ReadDBList(iSockHandle, cardno, flags, start, (pi_buffer_t*)&rInfoDB);
    if (iResult >= 0) {
        jclass pDBInfoClass = NULL;
        jmethodID pDBInfoMethod = NULL;
        int bProceed = 1;
        /* Find class for DBInfo - throws ClassNotFoundException if not found */
        if (bProceed) {
            pDBInfoClass = env->FindClass("org/gnu/pilotlink/DBInfo");
            if (pDBInfoClass == NULL) bProceed = 0;
        }
        /* Find constructor method for class DBInfo */
        if (bProceed) {
            pDBInfoMethod = env->GetMethodID(pDBInfoClass, "<init>",
                "(Ljava/lang/String;IIIIIISSSBB)V");
            if (pDBInfoMethod != NULL && env->ExceptionOccurred() == NULL) {
                /* Build new object, propagate any exception into Java caller */
                jstring jString_nombre = env->NewStringUTF(rInfoDB.name);
                pDBInfoObject = env->NewObject(pDBInfoClass, pDBInfoMethod,
                    jString_nombre, (jint)rInfoDB.createDate, (jint)rInfoDB.modifyDate,
                    (jint)rInfoDB.backupDate, (jint)rInfoDB.type, (jint)rInfoDB.creator,
                    (jint)rInfoDB.modnum, (jshort)rInfoDB.flags, (jshort)rInfoDB.version,
                    (jshort)rInfoDB.index, (jbyte)rInfoDB.miscFlags, (jbyte)rInfoDB.more);
                if (env->ExceptionOccurred() != NULL) bProceed = 0;
            } else {
                /* pending NoSuchMethodException in env */
                bProceed = 0;
            }
        }
    /* "Not Found" error returns null, else throw Java exception to inform problem with listing */
    } else if (iResult != -5) {
        postPilotLinkException(env, "Unable to read DB list entry", iResult, errno);
    }
    return pDBInfoObject;
}
References dlp_ReadDBList(), flags, and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_readSysInfo()
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readSysInfo (JNIEnv * env, jobject obj, jint handle)
{
/*
    struct SysInfo s;
    s.prodID[s.prodIDLength]=0;
    int r=dlp_ReadSysInfo(handle,&s);
    jstring prod=env->NewStringUTF(s.prodID);
    //printf("STill alive...\n");
    fflush(stdout);
    jclass sysinfo_cls=env->FindClass("org/gnu/pilotlink/SysInfo");
    if (sysinfo_cls==NULL) {
        printf("Class not found! Sysinfo!\n");
        return NULL;
    }
    //printf("STill alive...\n");
    fflush(stdout);
    jmethodID sysinfo_mid=env->GetMethodID(sysinfo_cls, "<init>","(Ljava/lang/String;JJSSSSJ)V");
    if (sysinfo_mid==NULL) {
        printf("Problem mid!\n");
        fflush(stdout);
        return NULL;
    }
    //printf("STill alive...\n");
    fflush(stdout);
    jobject sysinfo=env->NewObject(sysinfo_cls, sysinfo_mid, prod, s.romVersion, s.locale, s.dlpMajorVersion, s.dlpMinorVersion,s.compatMajorVersion,s.compatMinorVersion,s.maxRecSize);
    printf("Returning from getsysinfo...\n");
    fflush(stdout);
    return sysinfo;
*/
    jclass      jClass_sysInfo = NULL;
    jobject     jObject_sysInfo = NULL;
    jmethodID   jMethod_sysInfo = NULL;
    struct SysInfo rSysInfo;
    int bProceed = 1;
    if (bProceed) {
        int iResult;
        /* Check that dlp_ReadSysInfo call actually succeeded */
        memset(&rSysInfo, 0, sizeof(struct SysInfo));
        iResult = dlp_ReadSysInfo(handle, &rSysInfo);
        if (iResult < 0) {
            /* Throw Java exception in case of failure */
            postPilotLinkException(env, "Unable to read SysInfo", iResult, errno);
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Look up SysInfo class */
        jClass_sysInfo = env->FindClass("org/gnu/pilotlink/SysInfo");
        if (jClass_sysInfo == NULL) {
            /* pending ClassNotFoundException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Look up constructor method with complete-specification argument */
        jMethod_sysInfo = env->GetMethodID(jClass_sysInfo, "<init>",
            "(Ljava/lang/String;JJSSSSJ)V");
        if (jMethod_sysInfo == NULL) {
            /* pending NoSuchMethodException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Explicit casts to jlong are required because env->NewObject() works
           very similar to (and probably identical) to printf() and related
           procedures which use stdarg.h routines for variable arguments.
           The constructor requires a jlong (64 bits) for some fields, but the
           corresponding fields in the C struct are of a system-dependent size
           (32 bits for an unsigned long in i386). Failure to cast to an appropriate
           size results in a stack misalignment which, at the very least, causes
           incorrect values to be received at the Java side. For the sake of
           completeness, jshort values are explicitly casted too.
         */
        jstring jString_prodID = env->NewStringUTF(rSysInfo.prodID);
        jObject_sysInfo = env->NewObject(jClass_sysInfo, jMethod_sysInfo,
            jString_prodID, (jlong)rSysInfo.romVersion, (jlong)rSysInfo.locale,
            (jshort)rSysInfo.dlpMajorVersion, (jshort)rSysInfo.dlpMinorVersion,
            (jshort)rSysInfo.compatMajorVersion,
            (jshort)rSysInfo.compatMinorVersion, (jlong)rSysInfo.maxRecSize);
    }
    return jObject_sysInfo;
}
References dlp_ReadSysInfo(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_readUserInfo()
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readUserInfo (JNIEnv * env, jobject obj, jint handler)
{
/*
   struct PilotUser U;
   dlp_ReadUserInfo(handler, &U);
   U.username[127]=0;
   U.password[U.passwordLength]=0;
   printf("Last sync-->%ld\n",U.lastSyncDate);
   printf("Last ssync->%ld\n",U.successfulSyncDate);
  jstring str_name=env->NewStringUTF(U.username);
  if (str_name==NULL) {
    return NULL;
 }
  jstring str_pw=env->NewStringUTF(U.password);
  if (str_pw==NULL) {
     return NULL;
  }
  jlong vid=U.viewerID;
  jlong uid=U.userID;
  jlong lspc=U.lastSyncPC;
  jclass calclass=env->FindClass("java/util/Date");
  if (calclass==NULL) {
      return NULL;
  }
  jmethodID cal_mid=env->GetMethodID(calclass,"<init>","(J)V");
  if (cal_mid==NULL){
     return NULL;
  }
  jobject lsd_date=env->NewObject(calclass,cal_mid,U.lastSyncDate*1000);
  jobject sucd_date=env->NewObject(calclass,cal_mid,U.successfulSyncDate*1000);
  jclass usercls=env->FindClass("org/gnu/pilotlink/User");
  if (usercls==NULL) {
    printf("USERCLASS not found!\n");
    return NULL;
  } else {
    printf("ok...\n");
  }
  jmethodID umid=env->GetMethodID(usercls,"<init>","(Ljava/lang/String;Ljava/lang/String;JJJLjava/util/Date;Ljava/util/Date;)V");
  if (umid==NULL) {
     printf("MethodID not found!\n");
     return NULL;
  } else {
     printf("ok...\n");
  }
  //printf("Returning from getuserinfo...\n");
  jobject u=env->NewObject(usercls,umid,str_name,str_pw,uid,vid,lspc,lsd_date, sucd_date);
  return u;
*/
    jclass      jClass_user = NULL;
    jobject     jObject_user = NULL;
    jmethodID   jMethod_user = NULL;
    struct PilotUser rUserInfo;
    int bProceed = 1;
    if (bProceed) {
        int iResult;
        /* Check that dlp_ReadUserInfo call actually succeeded */
        memset(&rUserInfo, 0, sizeof(struct PilotUser));
        iResult = dlp_ReadUserInfo(handler, &rUserInfo);
        if (iResult < 0) {
            /* Throw Java exception in case of failure */
            postPilotLinkException(env, "Unable to read UserInfo", iResult, errno);
            bProceed = 0;
        } else {
            /* This was taken from previous code...  */
            rUserInfo.username[sizeof(rUserInfo.username) - 1] = '\0';
            rUserInfo.password[rUserInfo.passwordLength] = '\0';
        }
    }
    if (bProceed) {
        /* Look up User class */
        jClass_user = env->FindClass("org/gnu/pilotlink/User");
        if (jClass_user == NULL) {
            /* pending ClassNotFoundException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Look up constructor method with complete-specification argument.
           NOTE: a new constructor was provided in User.java in order to
           avoid having to create Date objects in C code, AND to fix a subtle
           bug in which the multiplication of time_t * int (miliseconds since
           Epoch) silently overflows because both time_t and int are 32-bit,
           and the result is NOT promoted to at least 64 bits, required for
           the constructor Date(long).
         */
        jMethod_user = env->GetMethodID(jClass_user, "<init>",
            "(Ljava/lang/String;Ljava/lang/String;JJJJJ)V");
        if (jMethod_user == NULL) {
            /* pending NoSuchMethodException in env */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Explicit casts added - see object creation at
        Java_org_gnu_pilotlink_PilotLink_readSysInfo() for explanation. */
        jstring jString_username = env->NewStringUTF(rUserInfo.username);
        jstring jString_password = env->NewStringUTF(rUserInfo.password);
        jObject_user = env->NewObject(jClass_user, jMethod_user, jString_username,
            jString_password, (jlong)rUserInfo.userID, (jlong)rUserInfo.viewerID,
            (jlong)rUserInfo.lastSyncPC, (jlong)rUserInfo.lastSyncDate,
            (jlong)rUserInfo.successfulSyncDate);
    }
    return jObject_user;
}
References dlp_ReadUserInfo(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_resetSystem()
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_resetSystem (JNIEnv * env, jobject , jint iSockHandle)
{
    int iResult = dlp_ResetSystem(iSockHandle);
    if (iResult < 0) {
        postPilotLinkException(env, "Unable to reset system", iResult, errno);
    }
}
References dlp_ResetSystem(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_writeAppBlock()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_writeAppBlock (JNIEnv * env, jobject obj, jint handle, jint dbhandle, jbyteArray data, jint length)
{
/*
        char buffer[MAX_RESOURCE_SIZE];
        env->GetByteArrayRegion(data,0,length,(jbyte*)buffer);
        return dlp_WriteAppBlock(handle,dbhandle,buffer,length);
*/
    jbyte * buffer;
    int iResult = 0;
    /* Allocate memory for copy of app block */
    if ((buffer = (jbyte *)malloc(length * sizeof(jbyte))) != NULL) {
        env->GetByteArrayRegion(data, 0, length, buffer);
        iResult = dlp_WriteAppBlock(handle, dbhandle, buffer, length);
        if (iResult < 0) {
            /* Throw Java exception to signal error */
            postPilotLinkException(env, "Unable to write app-block", iResult, errno);
        }
        free(buffer);
    } else {
        postJavaException(env,
            "org/gnu/pilotlink/PilotLinkException",
            "Unable to allocate memory for app block");
    }
    return iResult;
}
References buffer, dlp_WriteAppBlock(), postJavaException(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_writeRecord()
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_writeRecord (JNIEnv * env, jobject obj, jint handle, jint db, jobject record)
{
      jlong id=0;
      jclass cls=env->GetObjectClass(record);
      jmethodID mid=env->GetMethodID(cls,"getCategory","()I");
      if (mid==NULL) { printf("Error getting mid!"); return -1; }
      jint cat=env->CallIntMethod(record,mid);
      jmethodID mid2=env->GetMethodID(cls,"getId","()J");
      id=env->CallLongMethod(record,mid2, NULL);
      if (id==0) {
          printf("Creating new entry!\n");
      }
      mid=env->GetMethodID(cls,"getAttribs","()I");
      jint attr=env->CallIntMethod(record,mid);
      mid=env->GetMethodID(cls,"getSize","()I");
      jint size=env->CallIntMethod(record,mid);
      printf("Got size: %d\n",size);
      char buffer[MAX_RESOURCE_SIZE];
      mid=env->GetMethodID(cls,"getBuffer","()[B");
      jbyteArray arr=(jbyteArray)env->CallObjectMethod(record,mid);
      env->GetByteArrayRegion(arr,0,size,(jbyte*)buffer);
      recordid_t i=0;
      int ret=dlp_WriteRecord(handle,db,attr, id, cat, buffer,size,&i);
      if (id==0 && ret>0) {
          mid=env->GetMethodID(cls,"setId","(J)V");
          env->CallVoidMethod(record,mid,(jlong)i);
      }
      return ret;
}
References buffer, dlp_WriteRecord(), MAX_RESOURCE_SIZE, and size.
Java_org_gnu_pilotlink_PilotLink_writeResource()
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_writeResource (JNIEnv * env, jobject obj, jint iSockHandle, jint iDBHandle, jobject pRecord)
{
    jlong iRsrcID;              /* Resource ID for record */
    jint iRsrcType;             /* Resource type for record */
    jint iRsrcSize;             /* Actual resource size */
    jbyte * pRsrcData = NULL;   /* Buffer for resource data */
    jclass pRecordClass;        /* Java class for record */
    jmethodID pRecordMethod;    /* Java instance method for record */
    jbyteArray pDataArray;      /* Java array for resource data */
    jint iResult = -1;          /* Result of library call */
    int bProceed = 1;
    /* Get reference to record class */
    pRecordClass = env->GetObjectClass(pRecord);
    /* Find out required attributes for resource write */
    if (bProceed) {
        /* Find out category (resource type) */
        if ((pRecordMethod = env->GetMethodID(pRecordClass, "getCategory", "()I")) != NULL) {
            iRsrcType = env->CallIntMethod(pRecord, pRecordMethod);
        } else {
            /* Method lookup failed */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Find out resource ID */
        if ((pRecordMethod = env->GetMethodID(pRecordClass, "getId", "()J")) != NULL) {
            iRsrcID = env->CallLongMethod(pRecord, pRecordMethod);
        } else {
            /* Method lookup failed */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Find out resource size && allocate memory */
        if ((pRecordMethod = env->GetMethodID(pRecordClass, "getSize", "()I")) != NULL) {
            iRsrcSize = env->CallIntMethod(pRecord, pRecordMethod);
            if (iRsrcSize > 0) pRsrcData = (jbyte *)malloc(iRsrcSize * sizeof(char));
            if (pRsrcData == NULL) {
                postJavaException(env,
                    "org/gnu/pilotlink/PilotLinkException",
                    "Unable to allocate buffer for copy of resource");
                bProceed = 0;
            }
        } else {
            /* Method lookup failed */
            bProceed = 0;
        }
    }
    if (bProceed) {
        /* Get copy of resource data in allocated memory */
        if ((pRecordMethod = env->GetMethodID(pRecordClass, "getBuffer", "()[B")) != NULL) {
            pDataArray = (jbyteArray)env->CallObjectMethod(pRecord, pRecordMethod);
            env->GetByteArrayRegion(pDataArray, 0, iRsrcSize, pRsrcData);
            iResult = dlp_WriteResource(iSockHandle, iDBHandle, iRsrcType, iRsrcID,
                pRsrcData, iRsrcSize);
            if (iResult < 0) {
                postPilotLinkException(env, "Unable to write resource", iResult, errno);
            }
        } else {
            /* Method lookup failed */
            bProceed = 0;
        }
    }
    if (pRsrcData != NULL) free(pRsrcData);
}
References dlp_WriteResource(), postJavaException(), and postPilotLinkException().
Java_org_gnu_pilotlink_PilotLink_writeUserInfo()
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_writeUserInfo (JNIEnv * env, jobject obj, jint so, jobject user)
{
/*
    printf("Not implemented yet...sorry\n");
*/
    /* Now it IS implemented... ;-) */
    jclass      jClass_user = NULL;
    jmethodID   jMethod_user = NULL;
    struct PilotUser rUserInfo;
    jlong       jTempValue;
    jstring     jTempString;
    int bProceed = 1;
    /* Set everything not explicitly assigned to blanks */
    memset(&rUserInfo, 0, sizeof(struct PilotUser));
    /* Get object class for user... this should not fail */
    jClass_user = env->GetObjectClass(user);
    /* Assign all of the basic fields */
    if (bProceed) {
        bProceed = getBasicTypeField(env, jClass_user, user,
            "J", "userid", &jTempValue);
        rUserInfo.userID = jTempValue;
    }
    if (bProceed) {
        bProceed = getBasicTypeField(env, jClass_user, user,
            "J", "viewerid", &jTempValue);
        rUserInfo.viewerID = jTempValue;
    }
    if (bProceed) {
        bProceed = getBasicTypeField(env, jClass_user, user,
            "J", "lastSyncPC", &jTempValue);
        rUserInfo.lastSyncPC = jTempValue;
    }
    if (bProceed) {
        jTempString = NULL;
        bProceed = getBasicTypeField(env, jClass_user, user,
            "Ljava/lang/String;", "name", &jTempString);
        if (bProceed && jTempString != NULL) {
            const char * sTempString = env->GetStringUTFChars(jTempString, 0);
            strncpy(rUserInfo.username, sTempString, sizeof(rUserInfo.username) - 1);
            rUserInfo.username[sizeof(rUserInfo.username) - 1] = '\0';
            env->ReleaseStringUTFChars(jTempString, sTempString);
        }
    }
    if (bProceed) {
        jTempString = NULL;
        bProceed = getBasicTypeField(env, jClass_user, user,
            "Ljava/lang/String;", "password", &jTempString);
        if (bProceed && jTempString != NULL) {
            const char * sTempString = env->GetStringUTFChars(jTempString, 0);
            strncpy(rUserInfo.password, sTempString, sizeof(rUserInfo.password) - 1);
            rUserInfo.password[sizeof(rUserInfo.password) - 1] = '\0';
            rUserInfo.passwordLength = strlen(rUserInfo.password);
            env->ReleaseStringUTFChars(jTempString, sTempString);
        }
    }
    /* In order to get the correct time_t, a function call is needed. The methods
       User.getLastSyncDate_time_t() and User.getLastSuccessfulSyncDate_time_t()
       were created for this purpose.
     */
    if (bProceed) {
        jMethod_user = env->GetMethodID(jClass_user, "getLastSyncDate_time_t",
            "()J");
        if (jMethod_user == NULL) {
            /* pending NoSuchMethodException in env */
            bProceed = 0;
        } else {
            /* Use Date.getTime() in Java side and divide by 1000 */
            rUserInfo.lastSyncDate = env->CallLongMethod(user, jMethod_user);
        }
    }
    if (bProceed) {
        jMethod_user = env->GetMethodID(jClass_user, "getLastSuccessfulSyncDate_time_t",
            "()J");
        if (jMethod_user == NULL) {
            /* pending NoSuchMethodException in env */
            bProceed = 0;
        } else {
            /* Use Date.getTime() in Java side and divide by 1000 */
            rUserInfo.successfulSyncDate = env->CallLongMethod(user, jMethod_user);
        }
    }
    /* Write user info if all assignments were successful */
    if (bProceed) {
        int iResult = dlp_WriteUserInfo(so, &rUserInfo);
        if (iResult < 0) {
            postPilotLinkException(env, "Unable to write UserInfo", iResult, errno);
        }
    }
}
References dlp_WriteUserInfo(), getBasicTypeField(), postPilotLinkException(), and user.