pilot-link: libpisock/linuxusb.c File Reference
linuxusb.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "pi-debug.h"
#include "pi-source.h"
#include "pi-usb.h"
#include "pi-error.h"
Macros
#define O_NONBLOCK 0
Functions
void pi_usb_impl_init (struct pi_usb_impl *impl)
static int u_close (pi_socket_t *ps)
static int u_flush (pi_socket_t *ps, int flags)
static int u_open (pi_socket_t *ps, struct pi_sockaddr *addr, size_t addrlen)
static int u_poll (pi_socket_t *ps, int timeout)
static int u_read (pi_socket_t *ps, pi_buffer_t *buf, size_t len, int flags)
static int u_read_buf (pi_socket_t *ps, pi_buffer_t *buf, size_t len, int flags)
static int u_write (pi_socket_t *ps, unsigned char *buf, size_t len, int flags)
Macro Definition Documentation
O_NONBLOCK
#define O_NONBLOCK 0
Referenced by u_flush(), and u_open().
Function Documentation
pi_usb_impl_init()
void pi_usb_impl_init (struct pi_usb_impl * impl)
{
    impl->open      = u_open;
    impl->close         = u_close;
    impl->write         = u_write;
    impl->read      = u_read;
    impl->flush     = u_flush;
    impl->poll      = u_poll;
    impl->wait_for_device   = NULL;     /* not implemented in linuxusb yet */
    impl->changebaud    = NULL;     /* we don't need this one on linuxusb
                         * as USB serial adapters redirect to serial ports
                         */
    impl->control_request   = NULL;
}
References u_close(), u_flush(), u_open(), u_poll(), u_read(), and u_write().
u_close()
static int u_close (pi_socket_t * ps) static
{
    LOG((PI_DBG_DEV, PI_DBG_LVL_INFO,
        "DEV CLOSE linuxusb fd: %d\n", ps->sd));
    return close(ps->sd);
}
Referenced by pi_usb_impl_init().
u_flush()
static int u_flush (pi_socket_t * ps, int flags) static
{
    char buf[256];
    int fl;
    struct pi_usb_data *data = (struct pi_usb_data *) ps->device->data;
    if (flags & PI_FLUSH_INPUT) {
        /* clear internal buffer */
        data->buf_size = 0;
        /* flush pending data */
        if ((fl = fcntl(ps->sd, F_GETFL, 0)) != -1) {
            fcntl(ps->sd, F_SETFL, fl | O_NONBLOCK);
            while (recv(ps->sd, buf, sizeof(buf), 0) > 0)
                ;
            fcntl(ps->sd, F_SETFL, 0);
        }
        LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
            "DEV FLUSH linuxusb flushed input buffer\n"));
    }
    return 0;
}
References buf, flags, and O_NONBLOCK.
Referenced by pi_usb_impl_init().
u_open()
static int u_open (pi_socket_t * ps, struct pi_sockaddr * addr, size_t addrlen) static
{
    int     fd,
        i;
    char    *tty    = addr->pi_device;
    if ((fd = open(tty, O_RDWR | O_NONBLOCK)) < 0) {
        ps->last_error = PI_ERR_GENERIC_SYSTEM;
        return PI_ERR_GENERIC_SYSTEM;   /* errno already set */
    }
    if (!isatty(fd)) {
        close(fd);
        errno = EINVAL;
        ps->last_error = PI_ERR_GENERIC_SYSTEM;
        return PI_ERR_GENERIC_SYSTEM;
    }
    if ((i = fcntl(fd, F_GETFL, 0)) != -1) {
        i &= ~O_NONBLOCK;
        fcntl(fd, F_SETFL, i);
    }
    if ((i = pi_socket_setsd(ps, fd)) < 0)
        return i;
    return fd;
}
References O_NONBLOCK, pi_socket_setsd(), and tty.
Referenced by pi_usb_impl_init().
u_poll()
static int u_poll (pi_socket_t * ps, int timeout) static
{
    struct  timeval t;
    fd_set  ready;
    FD_ZERO(&ready);
    FD_SET(ps->sd, &ready);
    /* If timeout == 0, wait forever for packet, otherwise wait till
       timeout milliseconds */
    if (timeout == 0)
        select(ps->sd + 1, &ready, 0, 0, 0);
    else {
        t.tv_sec    = timeout / 1000;
        t.tv_usec   = (timeout % 1000) * 1000;
        select(ps->sd + 1, &ready, 0, 0, &t);
    }
    if (!FD_ISSET(ps->sd, &ready)) {
        /* otherwise throw out any current packet and return */
        LOG((PI_DBG_DEV, PI_DBG_LVL_WARN,
             "DEV POLL linuxusb timeout\n"));
        errno = ETIMEDOUT;
        return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
    }
    LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
        "DEV POLL linuxusb found data on fd: %d\n", ps->sd));
    return 1;
}
References pi_set_error().
Referenced by pi_usb_impl_init().
u_read()
static int u_read (pi_socket_t * ps, pi_buffer_t * buf, size_t len, int flags) static
{
    ssize_t rbuf = 0,
        bytes;
    struct  pi_usb_data *data = (struct pi_usb_data *)ps->device->data;
    struct  timeval t;
    fd_set  ready;
    /* check whether we have at least partial data in store */
    if (data->buf_size) {
        rbuf = u_read_buf(ps, buf, len, flags);
        if (rbuf < 0)
            return rbuf;
        len -= rbuf;
        if (len == 0)
            return rbuf;
    }
    /* If timeout == 0, wait forever for packet, otherwise wait till
       timeout milliseconds */
    FD_ZERO(&ready);
    FD_SET(ps->sd, &ready);
    if (data->timeout == 0)
        select(ps->sd + 1, &ready, 0, 0, 0);
    else {
        t.tv_sec    = data->timeout / 1000;
        t.tv_usec   = (data->timeout % 1000) * 1000;
        if (select(ps->sd + 1, &ready, 0, 0, &t) == 0) {
            LOG((PI_DBG_DEV, PI_DBG_LVL_WARN,
                "DEV RX linuxusb timeout\n"));
            errno = ETIMEDOUT;
            return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
        }
    }
    /* If data is available in time, read it */
    if (FD_ISSET(ps->sd, &ready)) {
        if (flags == PI_MSG_PEEK && len > 256)
            len = 256;
        if (pi_buffer_expect (buf, len) == NULL) {
            errno = ENOMEM;
            return pi_set_error(ps->sd, PI_ERR_GENERIC_MEMORY);
        }
        bytes = read(ps->sd, buf->data + buf->used, len);
        if (bytes > 0) {
            if (flags == PI_MSG_PEEK) {
                memcpy(data->buf + data->buf_size, buf->data + buf->used, bytes);
                data->buf_size += bytes;
            }
            buf->used += bytes;
            rbuf += bytes;
            LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
                "DEV RX linuxusb read %d bytes\n", bytes));
        }
    } else {
        LOG((PI_DBG_DEV, PI_DBG_LVL_WARN,
            "DEV RX linuxusb timeout\n"));
        errno = ETIMEDOUT;
        return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
    }
    return rbuf;
}
References buf, flags, pi_buffer_expect(), pi_set_error(), and u_read_buf().
Referenced by pi_usb_impl_init().
u_read_buf()
static int u_read_buf (pi_socket_t * ps, pi_buffer_t * buf, size_t len, int flags) static
{
    struct  pi_usb_data *data = (struct pi_usb_data *)ps->device->data;
    size_t rbuf = data->buf_size;
    if (rbuf > len)
        rbuf = len;
    if (pi_buffer_append (buf, data->buf, rbuf) == NULL) {
        errno = ENOMEM;
        return pi_set_error(ps->sd, PI_ERR_GENERIC_MEMORY);
    }
    if (flags != PI_MSG_PEEK) {
        data->buf_size -= rbuf;
        if (data->buf_size > 0)
            memmove(data->buf, &data->buf[rbuf], data->buf_size);
    }
    LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
        "DEV RX linuxusb read %d bytes from read-ahead buffer\n", rbuf));
    return rbuf;
}
References buf, flags, pi_buffer_append(), and pi_set_error().
Referenced by u_read().
u_write()
static int u_write (pi_socket_t * ps, unsigned char * buf, size_t len, int flags) static
{
    int     total,
        nwrote;
    struct  pi_usb_data *data = (struct pi_usb_data *)ps->device->data;
    struct  timeval t;
    fd_set  ready;
    FD_ZERO(&ready);
    FD_SET(ps->sd, &ready);
    total = len;
    while (total > 0) {
        if (data->timeout == 0)
            select(ps->sd + 1, 0, &ready, 0, 0);
        else {
            t.tv_sec    = data->timeout / 1000;
            t.tv_usec   = (data->timeout % 1000) * 1000;
            if (select(ps->sd + 1, 0, &ready, 0, &t))
                return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
        }
        if (!FD_ISSET(ps->sd, &ready)) {
            ps->state = PI_SOCK_CONN_BREAK;
            return pi_set_error(ps->sd, PI_ERR_SOCK_DISCONNECTED);
        }
        nwrote = write(ps->sd, buf, len);
        if (nwrote < 0) {
            ps->state = PI_SOCK_CONN_BREAK;
            return pi_set_error(ps->sd, PI_ERR_SOCK_DISCONNECTED);
        }
        total -= nwrote;
    }
    LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
        "DEV TX linuxusb wrote %d bytes\n", len));
    return len;
}
References buf, and pi_set_error().
Referenced by pi_usb_impl_init().