pilot-link: libpisock/memo.c File Reference
memo.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pi-macros.h"
#include "pi-memo.h"
Functions
void free_Memo (Memo_t *memo)
int pack_Memo (const Memo_t *memo, pi_buffer_t *record, memoType type)
int pack_MemoAppInfo (const MemoAppInfo_t *appinfo, unsigned char *record, size_t len)
int unpack_Memo (Memo_t *memo, const pi_buffer_t *record, memoType type)
int unpack_MemoAppInfo (struct MemoAppInfo *appinfo, const unsigned char *record, size_t len)
Function Documentation
free_Memo()
void free_Memo (Memo_t * memo)
{
    if (memo->text != NULL) {
        free(memo->text);
        memo->text = NULL;
    }
}
Referenced by memos(), and MemoUnpackCmd().
pack_Memo()
int pack_Memo (const Memo_t * memo, pi_buffer_t * record, memoType type)
{
    size_t destlen = (memo->text ? strlen(memo->text) : 0) + 1;
    if (type != memo_v1)
        /* Don't support anything else yet */
        return -1;
    if (record == NULL)
        return -1;
    pi_buffer_expect(record, destlen);
    record->used = destlen;
    if (memo->text)
        strcpy((char *) record->data, memo->text);
    else
        record->data[0] = 0;
    return 0;
}
References record::data, and pi_buffer_expect().
Referenced by MemoPackCmd(), and memos().
pack_MemoAppInfo()
int pack_MemoAppInfo (const MemoAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int     i;
    unsigned char *start = record;
    i = pack_CategoryAppInfo(&appinfo->category, record, len);
    if (!record)
        return i + 4;
    if (i == 0)             /* category pack failed */
        return 0;
    record += i;
    len -= i;
    if (len < 4)
        return (record - start);
    set_short(record, 0);           /* gapfill new for 2.0  */
    record += 2;
    set_byte(record, appinfo->sortByAlpha); /* new for 2.0      */
    record++;
    set_byte(record, 0);            /* gapfill new for 2.0  */
    record++;
    return (record - start);
}
References pack_CategoryAppInfo().
unpack_Memo()
int unpack_Memo (Memo_t * memo, const pi_buffer_t * record, memoType type)
{
    if (type != memo_v1)
        /* Don't support anything else yet */
        return -1;
    if (record == NULL || record->data == NULL || record->used < 1)
        return -1;
    memo->text = strdup((char *) record->data);
    return 0;
}
References record::data, and strdup().
Referenced by main(), memos(), and MemoUnpackCmd().
unpack_MemoAppInfo()
int unpack_MemoAppInfo (struct MemoAppInfo * appinfo, const unsigned char * record, size_t len)
{
    int     i = unpack_CategoryAppInfo(&appinfo->category, record, len);
    unsigned char *start = record;
    appinfo->type = memo_v1;
    if (!i)
        return i;
    record += i;
    len -= i;
    if (len >= 4) {
        record += 2;
        appinfo->sortByAlpha = get_byte(record);
        record += 2;
    } else {
        appinfo->sortByAlpha = 0;
    }
    return (record - start);
}
References unpack_CategoryAppInfo().
Referenced by main(), and main().