pilot-link: pisock Namespace Reference
pisock Namespace Reference
Data Structures
class _object
class CardInfo
class CardInfoPtr
class DBInfo
class DBInfoPtr
class DBSizeInfo
class DBSizeInfoPtr
class NetSyncInfo
class NetSyncInfoPtr
class pi_socket_list_t
class pi_socket_list_tPtr
class pi_socket_t
class pi_socket_tPtr
class PilotUser
class PilotUserPtr
class SysInfo
class SysInfoPtr
class VFSAnyMountParam
class VFSAnyMountParamPtr
class VFSDirInfo
class VFSDirInfoPtr
class VFSInfo
class VFSInfoPtr
class VFSSlotMountParam
class VFSSlotMountParamPtr
Functions
_swig_getattr (self, class_type, name)
_swig_setattr (self, class_type, name, value)
_swig_setattr_nondynamic (self, class_type, name, value, static=1)
Variables
int _newclass = 1
_object = types.ObjectType
dlp_AbortSync = _pisock.dlp_AbortSync
dlp_AddSyncLogEntry = _pisock.dlp_AddSyncLogEntry
dlp_CallApplication = _pisock.dlp_CallApplication
dlp_CleanUpDatabase = _pisock.dlp_CleanUpDatabase
dlp_CloseDB = _pisock.dlp_CloseDB
dlp_CloseDB_All = _pisock.dlp_CloseDB_All
dlp_CreateDB = _pisock.dlp_CreateDB
dlp_DeleteCategory = _pisock.dlp_DeleteCategory
dlp_DeleteDB = _pisock.dlp_DeleteDB
dlp_DeleteRecord = _pisock.dlp_DeleteRecord
dlp_DeleteResource = _pisock.dlp_DeleteResource
dlp_EndOfSync = _pisock.dlp_EndOfSync
dlp_ExpCardInfo = _pisock.dlp_ExpCardInfo
dlp_ExpCardPresent = _pisock.dlp_ExpCardPresent
dlp_ExpSlotEnumerate = _pisock.dlp_ExpSlotEnumerate
dlp_ExpSlotMediaType = _pisock.dlp_ExpSlotMediaType
dlp_FindDBByName = _pisock.dlp_FindDBByName
dlp_FindDBByOpenHandle = _pisock.dlp_FindDBByOpenHandle
dlp_FindDBByTypeCreator = _pisock.dlp_FindDBByTypeCreator
dlp_FindDBInfo = _pisock.dlp_FindDBInfo
dlp_GetROMToken = _pisock.dlp_GetROMToken
dlp_GetSysDateTime_ = _pisock.dlp_GetSysDateTime_
dlp_htopdate = _pisock.dlp_htopdate
dlp_MoveCategory = _pisock.dlp_MoveCategory
dlp_OpenConduit = _pisock.dlp_OpenConduit
dlp_OpenDB = _pisock.dlp_OpenDB
dlp_ptohdate = _pisock.dlp_ptohdate
dlp_ReadAppBlock = _pisock.dlp_ReadAppBlock
dlp_ReadAppPreference = _pisock.dlp_ReadAppPreference
dlp_ReadDBList_ = _pisock.dlp_ReadDBList_
dlp_ReadFeature = _pisock.dlp_ReadFeature
dlp_ReadNetSyncInfo = _pisock.dlp_ReadNetSyncInfo
dlp_ReadNextModifiedRec = _pisock.dlp_ReadNextModifiedRec
dlp_ReadNextModifiedRecInCategory = _pisock.dlp_ReadNextModifiedRecInCategory
dlp_ReadNextRecInCategory = _pisock.dlp_ReadNextRecInCategory
dlp_ReadOpenDBInfo = _pisock.dlp_ReadOpenDBInfo
dlp_ReadRecordById = _pisock.dlp_ReadRecordById
dlp_ReadRecordByIndex = _pisock.dlp_ReadRecordByIndex
dlp_ReadRecordIDList = _pisock.dlp_ReadRecordIDList
dlp_ReadResourceByIndex = _pisock.dlp_ReadResourceByIndex
dlp_ReadResourceByType = _pisock.dlp_ReadResourceByType
dlp_ReadSortBlock = _pisock.dlp_ReadSortBlock
dlp_ReadStorageInfo = _pisock.dlp_ReadStorageInfo
dlp_ReadSysInfo = _pisock.dlp_ReadSysInfo
dlp_ReadUserInfo = _pisock.dlp_ReadUserInfo
dlp_ResetDBIndex = _pisock.dlp_ResetDBIndex
dlp_ResetLastSyncPC = _pisock.dlp_ResetLastSyncPC
dlp_ResetSyncFlags = _pisock.dlp_ResetSyncFlags
dlp_ResetSystem = _pisock.dlp_ResetSystem
dlp_set_protocol_version = _pisock.dlp_set_protocol_version
dlp_SetDBInfo = _pisock.dlp_SetDBInfo
dlp_SetSysDateTime = _pisock.dlp_SetSysDateTime
dlp_VFSDirCreate = _pisock.dlp_VFSDirCreate
dlp_VFSDirEntryEnumerate = _pisock.dlp_VFSDirEntryEnumerate
dlp_VFSExportDatabaseToFile = _pisock.dlp_VFSExportDatabaseToFile
dlp_VFSFileClose = _pisock.dlp_VFSFileClose
dlp_VFSFileCreate = _pisock.dlp_VFSFileCreate
dlp_VFSFileDelete = _pisock.dlp_VFSFileDelete
dlp_VFSFileEOF = _pisock.dlp_VFSFileEOF
dlp_VFSFileGetAttributes = _pisock.dlp_VFSFileGetAttributes
dlp_VFSFileGetDate = _pisock.dlp_VFSFileGetDate
dlp_VFSFileOpen = _pisock.dlp_VFSFileOpen
dlp_VFSFileRead = _pisock.dlp_VFSFileRead
dlp_VFSFileRename = _pisock.dlp_VFSFileRename
dlp_VFSFileResize = _pisock.dlp_VFSFileResize
dlp_VFSFileSeek = _pisock.dlp_VFSFileSeek
dlp_VFSFileSetAttributes = _pisock.dlp_VFSFileSetAttributes
dlp_VFSFileSetDate = _pisock.dlp_VFSFileSetDate
dlp_VFSFileSize = _pisock.dlp_VFSFileSize
dlp_VFSFileTell = _pisock.dlp_VFSFileTell
dlp_VFSFileWrite = _pisock.dlp_VFSFileWrite
dlp_VFSGetDefaultDir = _pisock.dlp_VFSGetDefaultDir
dlp_VFSImportDatabaseFromFile = _pisock.dlp_VFSImportDatabaseFromFile
dlp_VFSVolumeEnumerate = _pisock.dlp_VFSVolumeEnumerate
dlp_VFSVolumeFormat = _pisock.dlp_VFSVolumeFormat
dlp_VFSVolumeGetLabel = _pisock.dlp_VFSVolumeGetLabel
dlp_VFSVolumeInfo = _pisock.dlp_VFSVolumeInfo
dlp_VFSVolumeSetLabel = _pisock.dlp_VFSVolumeSetLabel
dlp_VFSVolumeSize = _pisock.dlp_VFSVolumeSize
dlp_WriteAppBlock = _pisock.dlp_WriteAppBlock
dlp_WriteAppPreference = _pisock.dlp_WriteAppPreference
dlp_WriteNetSyncInfo = _pisock.dlp_WriteNetSyncInfo
dlp_WriteRecord = _pisock.dlp_WriteRecord
dlp_WriteResource = _pisock.dlp_WriteResource
dlp_WriteSortBlock = _pisock.dlp_WriteSortBlock
dlp_WriteUserInfo = _pisock.dlp_WriteUserInfo
dlpDBFlagAppInfoDirty = _pisock.dlpDBFlagAppInfoDirty
dlpDBFlagBackup = _pisock.dlpDBFlagBackup
dlpDBFlagBundle = _pisock.dlpDBFlagBundle
dlpDBFlagCopyPrevention = _pisock.dlpDBFlagCopyPrevention
dlpDBFlagExtended = _pisock.dlpDBFlagExtended
dlpDBFlagFixedUp = _pisock.dlpDBFlagFixedUp
dlpDBFlagHidden = _pisock.dlpDBFlagHidden
dlpDBFlagLaunchable = _pisock.dlpDBFlagLaunchable
dlpDBFlagNewer = _pisock.dlpDBFlagNewer
dlpDBFlagOpen = _pisock.dlpDBFlagOpen
dlpDBFlagReadOnly = _pisock.dlpDBFlagReadOnly
dlpDBFlagRecyclable = _pisock.dlpDBFlagRecyclable
dlpDBFlagReset = _pisock.dlpDBFlagReset
dlpDBFlagResource = _pisock.dlpDBFlagResource
dlpDBFlagSchema = _pisock.dlpDBFlagSchema
dlpDBFlagSecure = _pisock.dlpDBFlagSecure
dlpDBFlagStream = _pisock.dlpDBFlagStream
dlpDBListMultiple = _pisock.dlpDBListMultiple
dlpDBListRAM = _pisock.dlpDBListRAM
dlpDBListROM = _pisock.dlpDBListROM
dlpDBMiscFlagExcludeFromSync = _pisock.dlpDBMiscFlagExcludeFromSync
dlpDBMiscFlagRamBased = _pisock.dlpDBMiscFlagRamBased
dlpEndCodeNormal = _pisock.dlpEndCodeNormal
dlpEndCodeOther = _pisock.dlpEndCodeOther
dlpEndCodeOutOfMemory = _pisock.dlpEndCodeOutOfMemory
dlpEndCodeUserCan = _pisock.dlpEndCodeUserCan
dlpErrAlreadyOpen = _pisock.dlpErrAlreadyOpen
dlpErrArgument = _pisock.dlpErrArgument
dlpErrBusy = _pisock.dlpErrBusy
dlpErrDeleted = _pisock.dlpErrDeleted
dlpErrExists = _pisock.dlpErrExists
dlpErrIllegalReq = _pisock.dlpErrIllegalReq
dlpErrLimit = _pisock.dlpErrLimit
dlpErrMemory = _pisock.dlpErrMemory
dlpErrNoError = _pisock.dlpErrNoError
dlpErrNoneOpen = _pisock.dlpErrNoneOpen
dlpErrNotFound = _pisock.dlpErrNotFound
dlpErrNotSupp = _pisock.dlpErrNotSupp
dlpErrOpen = _pisock.dlpErrOpen
dlpErrParam = _pisock.dlpErrParam
dlpErrReadOnly = _pisock.dlpErrReadOnly
dlpErrSize = _pisock.dlpErrSize
dlpErrSpace = _pisock.dlpErrSpace
dlpErrSync = _pisock.dlpErrSync
dlpErrSystem = _pisock.dlpErrSystem
dlpErrTooManyOpen = _pisock.dlpErrTooManyOpen
dlpErrUnknown = _pisock.dlpErrUnknown
dlpErrUnused1 = _pisock.dlpErrUnused1
dlpErrWrapper = _pisock.dlpErrWrapper
dlpExpCapabilityHasStorage = _pisock.dlpExpCapabilityHasStorage
dlpExpCapabilityReadOnly = _pisock.dlpExpCapabilityReadOnly
dlpExpCapabilitySerial = _pisock.dlpExpCapabilitySerial
dlpFindDBOptFlagGetAttributes = _pisock.dlpFindDBOptFlagGetAttributes
dlpFindDBOptFlagGetSize = _pisock.dlpFindDBOptFlagGetSize
dlpFindDBOptFlagMaxRecSize = _pisock.dlpFindDBOptFlagMaxRecSize
dlpFindDBSrchFlagNewSearch = _pisock.dlpFindDBSrchFlagNewSearch
dlpFindDBSrchFlagOnlyLatest = _pisock.dlpFindDBSrchFlagOnlyLatest
dlpOpenExclusive = _pisock.dlpOpenExclusive
dlpOpenRead = _pisock.dlpOpenRead
dlpOpenReadWrite = _pisock.dlpOpenReadWrite
dlpOpenSecret = _pisock.dlpOpenSecret
dlpOpenWrite = _pisock.dlpOpenWrite
dlpRecAttrArchived = _pisock.dlpRecAttrArchived
dlpRecAttrBusy = _pisock.dlpRecAttrBusy
dlpRecAttrDeleted = _pisock.dlpRecAttrDeleted
dlpRecAttrDirty = _pisock.dlpRecAttrDirty
dlpRecAttrSecret = _pisock.dlpRecAttrSecret
dlpVFSOpenExclusive = _pisock.dlpVFSOpenExclusive
dlpVFSOpenRead = _pisock.dlpVFSOpenRead
dlpVFSOpenReadWrite = _pisock.dlpVFSOpenReadWrite
dlpVFSOpenWrite = _pisock.dlpVFSOpenWrite
error = _pisock.error
pi_accept = _pisock.pi_accept
pi_accept_to = _pisock.pi_accept_to
PI_AF_PILOT = _pisock.PI_AF_PILOT
pi_bind = _pisock.pi_bind
pi_close = _pisock.pi_close
PI_CMD_CMP = _pisock.PI_CMD_CMP
PI_CMD_NET = _pisock.PI_CMD_NET
PI_CMD_SYS = _pisock.PI_CMD_SYS
PI_CMP_BAUD = _pisock.PI_CMP_BAUD
PI_CMP_FLAGS = _pisock.PI_CMP_FLAGS
PI_CMP_TYPE = _pisock.PI_CMP_TYPE
PI_CMP_VERS = _pisock.PI_CMP_VERS
pi_connect = _pisock.pi_connect
PI_DEV_ESTRATE = _pisock.PI_DEV_ESTRATE
PI_DEV_HIGHRATE = _pisock.PI_DEV_HIGHRATE
PI_DEV_RATE = _pisock.PI_DEV_RATE
PI_DEV_TIMEOUT = _pisock.PI_DEV_TIMEOUT
PI_DLP_VERSION_MAJOR = _pisock.PI_DLP_VERSION_MAJOR
PI_DLP_VERSION_MINOR = _pisock.PI_DLP_VERSION_MINOR
PI_ERR_DLP_BUFSIZE = _pisock.PI_ERR_DLP_BUFSIZE
PI_ERR_DLP_COMMAND = _pisock.PI_ERR_DLP_COMMAND
PI_ERR_DLP_DATASIZE = _pisock.PI_ERR_DLP_DATASIZE
PI_ERR_DLP_PALMOS = _pisock.PI_ERR_DLP_PALMOS
PI_ERR_DLP_SOCKET = _pisock.PI_ERR_DLP_SOCKET
PI_ERR_DLP_UNSUPPORTED = _pisock.PI_ERR_DLP_UNSUPPORTED
PI_ERR_FILE_ABORTED = _pisock.PI_ERR_FILE_ABORTED
PI_ERR_FILE_ALREADY_EXISTS = _pisock.PI_ERR_FILE_ALREADY_EXISTS
PI_ERR_FILE_ERROR = _pisock.PI_ERR_FILE_ERROR
PI_ERR_FILE_INVALID = _pisock.PI_ERR_FILE_INVALID
PI_ERR_FILE_NOT_FOUND = _pisock.PI_ERR_FILE_NOT_FOUND
PI_ERR_GENERIC_ARGUMENT = _pisock.PI_ERR_GENERIC_ARGUMENT
PI_ERR_GENERIC_MEMORY = _pisock.PI_ERR_GENERIC_MEMORY
PI_ERR_GENERIC_SYSTEM = _pisock.PI_ERR_GENERIC_SYSTEM
PI_ERR_PROT_ABORTED = _pisock.PI_ERR_PROT_ABORTED
PI_ERR_PROT_BADPACKET = _pisock.PI_ERR_PROT_BADPACKET
PI_ERR_PROT_INCOMPATIBLE = _pisock.PI_ERR_PROT_INCOMPATIBLE
PI_ERR_SOCK_CANCELED = _pisock.PI_ERR_SOCK_CANCELED
PI_ERR_SOCK_DISCONNECTED = _pisock.PI_ERR_SOCK_DISCONNECTED
PI_ERR_SOCK_INVALID = _pisock.PI_ERR_SOCK_INVALID
PI_ERR_SOCK_IO = _pisock.PI_ERR_SOCK_IO
PI_ERR_SOCK_LISTENER = _pisock.PI_ERR_SOCK_LISTENER
PI_ERR_SOCK_TIMEOUT = _pisock.PI_ERR_SOCK_TIMEOUT
pi_error = _pisock.pi_error
pi_file_install = _pisock.pi_file_install
pi_file_retrieve = _pisock.pi_file_retrieve
pi_flush = _pisock.pi_flush
pi_getsockname = _pisock.pi_getsockname
pi_getsockopt = _pisock.pi_getsockopt
pi_getsockpeer = _pisock.pi_getsockpeer
PI_LEVEL_CMP = _pisock.PI_LEVEL_CMP
PI_LEVEL_DEV = _pisock.PI_LEVEL_DEV
PI_LEVEL_DLP = _pisock.PI_LEVEL_DLP
PI_LEVEL_NET = _pisock.PI_LEVEL_NET
PI_LEVEL_PADP = _pisock.PI_LEVEL_PADP
PI_LEVEL_SLP = _pisock.PI_LEVEL_SLP
PI_LEVEL_SOCK = _pisock.PI_LEVEL_SOCK
PI_LEVEL_SYS = _pisock.PI_LEVEL_SYS
pi_listen = _pisock.pi_listen
pi_maxrecsize = _pisock.pi_maxrecsize
PI_MSG_PEEK = _pisock.PI_MSG_PEEK
PI_NET_SPLIT_WRITES = _pisock.PI_NET_SPLIT_WRITES
PI_NET_TYPE = _pisock.PI_NET_TYPE
PI_NET_WRITE_CHUNKSIZE = _pisock.PI_NET_WRITE_CHUNKSIZE
PI_PADP_FREEZE_TXID = _pisock.PI_PADP_FREEZE_TXID
PI_PADP_LASTTYPE = _pisock.PI_PADP_LASTTYPE
PI_PADP_TYPE = _pisock.PI_PADP_TYPE
PI_PADP_USE_LONG_FORMAT = _pisock.PI_PADP_USE_LONG_FORMAT
pi_palmos_error = _pisock.pi_palmos_error
PI_PF_DEV = _pisock.PI_PF_DEV
PI_PF_DLP = _pisock.PI_PF_DLP
PI_PF_NET = _pisock.PI_PF_NET
PI_PF_PADP = _pisock.PI_PF_PADP
PI_PF_SLP = _pisock.PI_PF_SLP
PI_PF_SYS = _pisock.PI_PF_SYS
pi_protocol = _pisock.pi_protocol
pi_protocol_next = _pisock.pi_protocol_next
pi_read = _pisock.pi_read
pi_recv = _pisock.pi_recv
pi_reset_errors = _pisock.pi_reset_errors
pi_send = _pisock.pi_send
pi_set_error = _pisock.pi_set_error
pi_set_palmos_error = _pisock.pi_set_palmos_error
pi_setsockopt = _pisock.pi_setsockopt
PI_SLP_DEST = _pisock.PI_SLP_DEST
PI_SLP_LASTDEST = _pisock.PI_SLP_LASTDEST
PI_SLP_LASTSRC = _pisock.PI_SLP_LASTSRC
PI_SLP_LASTTXID = _pisock.PI_SLP_LASTTXID
PI_SLP_LASTTYPE = _pisock.PI_SLP_LASTTYPE
PI_SLP_SRC = _pisock.PI_SLP_SRC
PI_SLP_TXID = _pisock.PI_SLP_TXID
PI_SLP_TYPE = _pisock.PI_SLP_TYPE
PI_SOCK_HONOR_RX_TIMEOUT = _pisock.PI_SOCK_HONOR_RX_TIMEOUT
PI_SOCK_RAW = _pisock.PI_SOCK_RAW
PI_SOCK_STATE = _pisock.PI_SOCK_STATE
PI_SOCK_STREAM = _pisock.PI_SOCK_STREAM
pi_socket = _pisock.pi_socket
pi_socket_connected = _pisock.pi_socket_connected
pi_socket_setsd = _pisock.pi_socket_setsd
pi_tickle = _pisock.pi_tickle
pi_version = _pisock.pi_version
pi_watchdog = _pisock.pi_watchdog
pi_write = _pisock.pi_write
vfsFileAttrArchive = _pisock.vfsFileAttrArchive
vfsFileAttrDirectory = _pisock.vfsFileAttrDirectory
vfsFileAttrHidden = _pisock.vfsFileAttrHidden
vfsFileAttrLink = _pisock.vfsFileAttrLink
vfsFileAttrReadOnly = _pisock.vfsFileAttrReadOnly
vfsFileAttrSystem = _pisock.vfsFileAttrSystem
vfsFileAttrVolumeLabel = _pisock.vfsFileAttrVolumeLabel
vfsFileDateAccessed = _pisock.vfsFileDateAccessed
vfsFileDateCreated = _pisock.vfsFileDateCreated
vfsFileDateModified = _pisock.vfsFileDateModified
vfsInvalidFileRef = _pisock.vfsInvalidFileRef
vfsInvalidVolRef = _pisock.vfsInvalidVolRef
vfsIteratorStart = _pisock.vfsIteratorStart
vfsIteratorStop = _pisock.vfsIteratorStop
vfsMAXFILENAME = _pisock.vfsMAXFILENAME
vfsModeCreate = _pisock.vfsModeCreate
vfsModeExclusive = _pisock.vfsModeExclusive
vfsModeLeaveOpen = _pisock.vfsModeLeaveOpen
vfsModeRead = _pisock.vfsModeRead
vfsModeReadWrite = _pisock.vfsModeReadWrite
vfsModeTruncate = _pisock.vfsModeTruncate
vfsModeWrite = _pisock.vfsModeWrite
vfsMountFlagsUseThisFileSystem = _pisock.vfsMountFlagsUseThisFileSystem
vfsOriginBeginning = _pisock.vfsOriginBeginning
vfsOriginCurrent = _pisock.vfsOriginCurrent
vfsOriginEnd = _pisock.vfsOriginEnd
vfsVolAttrHidden = _pisock.vfsVolAttrHidden
vfsVolAttrReadOnly = _pisock.vfsVolAttrReadOnly
vfsVolAttrSlotBased = _pisock.vfsVolAttrSlotBased
Function Documentation
_swig_getattr()
_swig_getattr (self, class_type, name) protected
def _swig_getattr(self,class_type,name):
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name
_swig_setattr()
_swig_setattr (self, class_type, name, value) protected
def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)
References _swig_setattr_nondynamic().
Referenced by CardInfo.__init__(), CardInfoPtr.__init__(), DBInfo.__init__(), DBInfoPtr.__init__(), DBSizeInfo.__init__(), DBSizeInfoPtr.__init__(), NetSyncInfo.__init__(), NetSyncInfoPtr.__init__(), pi_socket_list_t.__init__(), pi_socket_list_tPtr.__init__(), pi_socket_t.__init__(), pi_socket_tPtr.__init__(), PilotUser.__init__(), PilotUserPtr.__init__(), SysInfo.__init__(), SysInfoPtr.__init__(), VFSAnyMountParam.__init__(), VFSAnyMountParamPtr.__init__(), VFSDirInfo.__init__(), VFSDirInfoPtr.__init__(), VFSInfo.__init__(), VFSInfoPtr.__init__(), VFSSlotMountParam.__init__(), and VFSSlotMountParamPtr.__init__().
_swig_setattr_nondynamic()
_swig_setattr_nondynamic (self, class_type, name, value, static = 1) protected
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "this"):
        if isinstance(value, class_type):
            self.__dict__[name] = value.this
            if hasattr(value,"thisown"): self.__dict__["thisown"] = value.thisown
            del value.thisown
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name) or (name == "thisown"):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)
Referenced by _swig_setattr().
Variable Documentation
_newclass
int _newclass = 1 protected
_object
_object = types.ObjectType protected
dlp_AbortSync
dlp_AbortSync = _pisock.dlp_AbortSync
dlp_AddSyncLogEntry
dlp_AddSyncLogEntry = _pisock.dlp_AddSyncLogEntry
Referenced by OnlineTestCase.testAddSyncLogEntry().
dlp_CallApplication
dlp_CallApplication = _pisock.dlp_CallApplication
dlp_CleanUpDatabase
dlp_CleanUpDatabase = _pisock.dlp_CleanUpDatabase
dlp_CloseDB
dlp_CloseDB = _pisock.dlp_CloseDB
Referenced by OnlineTestCase.testDatabaseCreationAndSearch().
dlp_CloseDB_All
dlp_CloseDB_All = _pisock.dlp_CloseDB_All
dlp_CreateDB
dlp_CreateDB = _pisock.dlp_CreateDB
Referenced by OnlineTestCase.testDatabaseCreationAndSearch().
dlp_DeleteCategory
dlp_DeleteCategory = _pisock.dlp_DeleteCategory
dlp_DeleteDB
dlp_DeleteDB = _pisock.dlp_DeleteDB
Referenced by OnlineTestCase.setUp(), and OnlineTestCase.testDatabaseCreationAndSearch().
dlp_DeleteRecord
dlp_DeleteRecord = _pisock.dlp_DeleteRecord
dlp_DeleteResource
dlp_DeleteResource = _pisock.dlp_DeleteResource
dlp_EndOfSync
dlp_EndOfSync = _pisock.dlp_EndOfSync
dlp_ExpCardInfo
dlp_ExpCardInfo = _pisock.dlp_ExpCardInfo
dlp_ExpCardPresent
dlp_ExpCardPresent = _pisock.dlp_ExpCardPresent
dlp_ExpSlotEnumerate
dlp_ExpSlotEnumerate = _pisock.dlp_ExpSlotEnumerate
dlp_ExpSlotMediaType
dlp_ExpSlotMediaType = _pisock.dlp_ExpSlotMediaType
dlp_FindDBByName
dlp_FindDBByName = _pisock.dlp_FindDBByName
dlp_FindDBByOpenHandle
dlp_FindDBByOpenHandle = _pisock.dlp_FindDBByOpenHandle
Referenced by OnlineTestCase.testDatabaseCreationAndSearch().
dlp_FindDBByTypeCreator
dlp_FindDBByTypeCreator = _pisock.dlp_FindDBByTypeCreator
dlp_FindDBInfo
dlp_FindDBInfo = _pisock.dlp_FindDBInfo
dlp_GetROMToken
dlp_GetROMToken = _pisock.dlp_GetROMToken
dlp_GetSysDateTime_
dlp_GetSysDateTime_ = _pisock.dlp_GetSysDateTime_
Referenced by pisockextras.dlp_GetSysDateTime().
dlp_htopdate
dlp_htopdate = _pisock.dlp_htopdate
dlp_MoveCategory
dlp_MoveCategory = _pisock.dlp_MoveCategory
dlp_OpenConduit
dlp_OpenConduit = _pisock.dlp_OpenConduit
dlp_OpenDB
dlp_OpenDB = _pisock.dlp_OpenDB
Referenced by OnlineTestCase.testDatabaseCreationAndSearch().
dlp_ptohdate
dlp_ptohdate = _pisock.dlp_ptohdate
dlp_ReadAppBlock
dlp_ReadAppBlock = _pisock.dlp_ReadAppBlock
dlp_ReadAppPreference
dlp_ReadAppPreference = _pisock.dlp_ReadAppPreference
dlp_ReadDBList_
dlp_ReadDBList_ = _pisock.dlp_ReadDBList_
Referenced by pisockextras.dlp_ReadDBList().
dlp_ReadFeature
dlp_ReadFeature = _pisock.dlp_ReadFeature
Referenced by OnlineTestCase.testReadFeature().
dlp_ReadNetSyncInfo
dlp_ReadNetSyncInfo = _pisock.dlp_ReadNetSyncInfo
Referenced by OnlineTestCase.testReadNetSyncInfo().
dlp_ReadNextModifiedRec
dlp_ReadNextModifiedRec = _pisock.dlp_ReadNextModifiedRec
dlp_ReadNextModifiedRecInCategory
dlp_ReadNextModifiedRecInCategory = _pisock.dlp_ReadNextModifiedRecInCategory
dlp_ReadNextRecInCategory
dlp_ReadNextRecInCategory = _pisock.dlp_ReadNextRecInCategory
dlp_ReadOpenDBInfo
dlp_ReadOpenDBInfo = _pisock.dlp_ReadOpenDBInfo
dlp_ReadRecordById
dlp_ReadRecordById = _pisock.dlp_ReadRecordById
dlp_ReadRecordByIndex
dlp_ReadRecordByIndex = _pisock.dlp_ReadRecordByIndex
dlp_ReadRecordIDList
dlp_ReadRecordIDList = _pisock.dlp_ReadRecordIDList
dlp_ReadResourceByIndex
dlp_ReadResourceByIndex = _pisock.dlp_ReadResourceByIndex
dlp_ReadResourceByType
dlp_ReadResourceByType = _pisock.dlp_ReadResourceByType
dlp_ReadSortBlock
dlp_ReadSortBlock = _pisock.dlp_ReadSortBlock
dlp_ReadStorageInfo
dlp_ReadStorageInfo = _pisock.dlp_ReadStorageInfo
Referenced by OnlineTestCase.testReadStorageInfo().
dlp_ReadSysInfo
dlp_ReadSysInfo = _pisock.dlp_ReadSysInfo
Referenced by OnlineTestCase.testReadSysInfo().
dlp_ReadUserInfo
dlp_ReadUserInfo = _pisock.dlp_ReadUserInfo
Referenced by OnlineTestCase.testReadUserInfo().
dlp_ResetDBIndex
dlp_ResetDBIndex = _pisock.dlp_ResetDBIndex
dlp_ResetLastSyncPC
dlp_ResetLastSyncPC = _pisock.dlp_ResetLastSyncPC
dlp_ResetSyncFlags
dlp_ResetSyncFlags = _pisock.dlp_ResetSyncFlags
dlp_ResetSystem
dlp_ResetSystem = _pisock.dlp_ResetSystem
dlp_set_protocol_version
dlp_set_protocol_version = _pisock.dlp_set_protocol_version
dlp_SetDBInfo
dlp_SetDBInfo = _pisock.dlp_SetDBInfo
Referenced by OnlineTestCase.testDatabaseCreationAndSearch().
dlp_SetSysDateTime
dlp_SetSysDateTime = _pisock.dlp_SetSysDateTime
dlp_VFSDirCreate
dlp_VFSDirCreate = _pisock.dlp_VFSDirCreate
dlp_VFSDirEntryEnumerate
dlp_VFSDirEntryEnumerate = _pisock.dlp_VFSDirEntryEnumerate
dlp_VFSExportDatabaseToFile
dlp_VFSExportDatabaseToFile = _pisock.dlp_VFSExportDatabaseToFile
dlp_VFSFileClose
dlp_VFSFileClose = _pisock.dlp_VFSFileClose
dlp_VFSFileCreate
dlp_VFSFileCreate = _pisock.dlp_VFSFileCreate
dlp_VFSFileDelete
dlp_VFSFileDelete = _pisock.dlp_VFSFileDelete
dlp_VFSFileEOF
dlp_VFSFileEOF = _pisock.dlp_VFSFileEOF
dlp_VFSFileGetAttributes
dlp_VFSFileGetAttributes = _pisock.dlp_VFSFileGetAttributes
dlp_VFSFileGetDate
dlp_VFSFileGetDate = _pisock.dlp_VFSFileGetDate
dlp_VFSFileOpen
dlp_VFSFileOpen = _pisock.dlp_VFSFileOpen
dlp_VFSFileRead
dlp_VFSFileRead = _pisock.dlp_VFSFileRead
dlp_VFSFileRename
dlp_VFSFileRename = _pisock.dlp_VFSFileRename
dlp_VFSFileResize
dlp_VFSFileResize = _pisock.dlp_VFSFileResize
dlp_VFSFileSeek
dlp_VFSFileSeek = _pisock.dlp_VFSFileSeek
dlp_VFSFileSetAttributes
dlp_VFSFileSetAttributes = _pisock.dlp_VFSFileSetAttributes
dlp_VFSFileSetDate
dlp_VFSFileSetDate = _pisock.dlp_VFSFileSetDate
dlp_VFSFileSize
dlp_VFSFileSize = _pisock.dlp_VFSFileSize
dlp_VFSFileTell
dlp_VFSFileTell = _pisock.dlp_VFSFileTell
dlp_VFSFileWrite
dlp_VFSFileWrite = _pisock.dlp_VFSFileWrite
dlp_VFSGetDefaultDir
dlp_VFSGetDefaultDir = _pisock.dlp_VFSGetDefaultDir
dlp_VFSImportDatabaseFromFile
dlp_VFSImportDatabaseFromFile = _pisock.dlp_VFSImportDatabaseFromFile
dlp_VFSVolumeEnumerate
dlp_VFSVolumeEnumerate = _pisock.dlp_VFSVolumeEnumerate
dlp_VFSVolumeFormat
dlp_VFSVolumeFormat = _pisock.dlp_VFSVolumeFormat
dlp_VFSVolumeGetLabel
dlp_VFSVolumeGetLabel = _pisock.dlp_VFSVolumeGetLabel
dlp_VFSVolumeInfo
dlp_VFSVolumeInfo = _pisock.dlp_VFSVolumeInfo
dlp_VFSVolumeSetLabel
dlp_VFSVolumeSetLabel = _pisock.dlp_VFSVolumeSetLabel
dlp_VFSVolumeSize
dlp_VFSVolumeSize = _pisock.dlp_VFSVolumeSize
dlp_WriteAppBlock
dlp_WriteAppBlock = _pisock.dlp_WriteAppBlock
dlp_WriteAppPreference
dlp_WriteAppPreference = _pisock.dlp_WriteAppPreference
dlp_WriteNetSyncInfo
dlp_WriteNetSyncInfo = _pisock.dlp_WriteNetSyncInfo
dlp_WriteRecord
dlp_WriteRecord = _pisock.dlp_WriteRecord
dlp_WriteResource
dlp_WriteResource = _pisock.dlp_WriteResource
dlp_WriteSortBlock
dlp_WriteSortBlock = _pisock.dlp_WriteSortBlock
dlp_WriteUserInfo
dlp_WriteUserInfo = _pisock.dlp_WriteUserInfo
dlpDBFlagAppInfoDirty
dlpDBFlagAppInfoDirty = _pisock.dlpDBFlagAppInfoDirty
dlpDBFlagBackup
dlpDBFlagBackup = _pisock.dlpDBFlagBackup
dlpDBFlagBundle
dlpDBFlagBundle = _pisock.dlpDBFlagBundle
dlpDBFlagCopyPrevention
dlpDBFlagCopyPrevention = _pisock.dlpDBFlagCopyPrevention
dlpDBFlagExtended
dlpDBFlagExtended = _pisock.dlpDBFlagExtended
dlpDBFlagFixedUp
dlpDBFlagFixedUp = _pisock.dlpDBFlagFixedUp
dlpDBFlagHidden
dlpDBFlagHidden = _pisock.dlpDBFlagHidden
dlpDBFlagLaunchable
dlpDBFlagLaunchable = _pisock.dlpDBFlagLaunchable
dlpDBFlagNewer
dlpDBFlagNewer = _pisock.dlpDBFlagNewer
dlpDBFlagOpen
dlpDBFlagOpen = _pisock.dlpDBFlagOpen
dlpDBFlagReadOnly
dlpDBFlagReadOnly = _pisock.dlpDBFlagReadOnly
dlpDBFlagRecyclable
dlpDBFlagRecyclable = _pisock.dlpDBFlagRecyclable
dlpDBFlagReset
dlpDBFlagReset = _pisock.dlpDBFlagReset
dlpDBFlagResource
dlpDBFlagResource = _pisock.dlpDBFlagResource
dlpDBFlagSchema
dlpDBFlagSchema = _pisock.dlpDBFlagSchema
dlpDBFlagSecure
dlpDBFlagSecure = _pisock.dlpDBFlagSecure
dlpDBFlagStream
dlpDBFlagStream = _pisock.dlpDBFlagStream
dlpDBListMultiple
dlpDBListMultiple = _pisock.dlpDBListMultiple
dlpDBListRAM
dlpDBListRAM = _pisock.dlpDBListRAM
dlpDBListROM
dlpDBListROM = _pisock.dlpDBListROM
dlpDBMiscFlagExcludeFromSync
dlpDBMiscFlagExcludeFromSync = _pisock.dlpDBMiscFlagExcludeFromSync
dlpDBMiscFlagRamBased
dlpDBMiscFlagRamBased = _pisock.dlpDBMiscFlagRamBased
dlpEndCodeNormal
dlpEndCodeNormal = _pisock.dlpEndCodeNormal
dlpEndCodeOther
dlpEndCodeOther = _pisock.dlpEndCodeOther
dlpEndCodeOutOfMemory
dlpEndCodeOutOfMemory = _pisock.dlpEndCodeOutOfMemory
dlpEndCodeUserCan
dlpEndCodeUserCan = _pisock.dlpEndCodeUserCan
dlpErrAlreadyOpen
dlpErrAlreadyOpen = _pisock.dlpErrAlreadyOpen
dlpErrArgument
dlpErrArgument = _pisock.dlpErrArgument
dlpErrBusy
dlpErrBusy = _pisock.dlpErrBusy
dlpErrDeleted
dlpErrDeleted = _pisock.dlpErrDeleted
dlpErrExists
dlpErrExists = _pisock.dlpErrExists
dlpErrIllegalReq
dlpErrIllegalReq = _pisock.dlpErrIllegalReq
dlpErrLimit
dlpErrLimit = _pisock.dlpErrLimit
dlpErrMemory
dlpErrMemory = _pisock.dlpErrMemory
dlpErrNoError
dlpErrNoError = _pisock.dlpErrNoError
dlpErrNoneOpen
dlpErrNoneOpen = _pisock.dlpErrNoneOpen
dlpErrNotFound
dlpErrNotFound = _pisock.dlpErrNotFound
dlpErrNotSupp
dlpErrNotSupp = _pisock.dlpErrNotSupp
dlpErrOpen
dlpErrOpen = _pisock.dlpErrOpen
dlpErrParam
dlpErrParam = _pisock.dlpErrParam
dlpErrReadOnly
dlpErrReadOnly = _pisock.dlpErrReadOnly
dlpErrSize
dlpErrSize = _pisock.dlpErrSize
dlpErrSpace
dlpErrSpace = _pisock.dlpErrSpace
dlpErrSync
dlpErrSync = _pisock.dlpErrSync
dlpErrSystem
dlpErrSystem = _pisock.dlpErrSystem
dlpErrTooManyOpen
dlpErrTooManyOpen = _pisock.dlpErrTooManyOpen
dlpErrUnknown
dlpErrUnknown = _pisock.dlpErrUnknown
dlpErrUnused1
dlpErrUnused1 = _pisock.dlpErrUnused1
dlpErrWrapper
dlpErrWrapper = _pisock.dlpErrWrapper
dlpExpCapabilityHasStorage
dlpExpCapabilityHasStorage = _pisock.dlpExpCapabilityHasStorage
dlpExpCapabilityReadOnly
dlpExpCapabilityReadOnly = _pisock.dlpExpCapabilityReadOnly
dlpExpCapabilitySerial
dlpExpCapabilitySerial = _pisock.dlpExpCapabilitySerial
dlpFindDBOptFlagGetAttributes
dlpFindDBOptFlagGetAttributes = _pisock.dlpFindDBOptFlagGetAttributes
dlpFindDBOptFlagGetSize
dlpFindDBOptFlagGetSize = _pisock.dlpFindDBOptFlagGetSize
dlpFindDBOptFlagMaxRecSize
dlpFindDBOptFlagMaxRecSize = _pisock.dlpFindDBOptFlagMaxRecSize
dlpFindDBSrchFlagNewSearch
dlpFindDBSrchFlagNewSearch = _pisock.dlpFindDBSrchFlagNewSearch
dlpFindDBSrchFlagOnlyLatest
dlpFindDBSrchFlagOnlyLatest = _pisock.dlpFindDBSrchFlagOnlyLatest
dlpOpenExclusive
dlpOpenExclusive = _pisock.dlpOpenExclusive
dlpOpenRead
dlpOpenRead = _pisock.dlpOpenRead
dlpOpenReadWrite
dlpOpenReadWrite = _pisock.dlpOpenReadWrite
dlpOpenSecret
dlpOpenSecret = _pisock.dlpOpenSecret
dlpOpenWrite
dlpOpenWrite = _pisock.dlpOpenWrite
dlpRecAttrArchived
dlpRecAttrArchived = _pisock.dlpRecAttrArchived
dlpRecAttrBusy
dlpRecAttrBusy = _pisock.dlpRecAttrBusy
dlpRecAttrDeleted
dlpRecAttrDeleted = _pisock.dlpRecAttrDeleted
dlpRecAttrDirty
dlpRecAttrDirty = _pisock.dlpRecAttrDirty
dlpRecAttrSecret
dlpRecAttrSecret = _pisock.dlpRecAttrSecret
dlpVFSOpenExclusive
dlpVFSOpenExclusive = _pisock.dlpVFSOpenExclusive
dlpVFSOpenRead
dlpVFSOpenRead = _pisock.dlpVFSOpenRead
dlpVFSOpenReadWrite
dlpVFSOpenReadWrite = _pisock.dlpVFSOpenReadWrite
dlpVFSOpenWrite
dlpVFSOpenWrite = _pisock.dlpVFSOpenWrite
error
error = _pisock.error
pi_accept
pi_accept = _pisock.pi_accept
pi_accept_to
pi_accept_to = _pisock.pi_accept_to
PI_AF_PILOT
PI_AF_PILOT = _pisock.PI_AF_PILOT
pi_bind
pi_bind = _pisock.pi_bind
pi_close
pi_close = _pisock.pi_close
PI_CMD_CMP
PI_CMD_CMP = _pisock.PI_CMD_CMP
PI_CMD_NET
PI_CMD_NET = _pisock.PI_CMD_NET
PI_CMD_SYS
PI_CMD_SYS = _pisock.PI_CMD_SYS
PI_CMP_BAUD
PI_CMP_BAUD = _pisock.PI_CMP_BAUD
PI_CMP_FLAGS
PI_CMP_FLAGS = _pisock.PI_CMP_FLAGS
PI_CMP_TYPE
PI_CMP_TYPE = _pisock.PI_CMP_TYPE
PI_CMP_VERS
PI_CMP_VERS = _pisock.PI_CMP_VERS
pi_connect
pi_connect = _pisock.pi_connect
PI_DEV_ESTRATE
PI_DEV_ESTRATE = _pisock.PI_DEV_ESTRATE
PI_DEV_HIGHRATE
PI_DEV_HIGHRATE = _pisock.PI_DEV_HIGHRATE
PI_DEV_RATE
PI_DEV_RATE = _pisock.PI_DEV_RATE
PI_DEV_TIMEOUT
PI_DEV_TIMEOUT = _pisock.PI_DEV_TIMEOUT
PI_DLP_VERSION_MAJOR
PI_DLP_VERSION_MAJOR = _pisock.PI_DLP_VERSION_MAJOR
PI_DLP_VERSION_MINOR
PI_DLP_VERSION_MINOR = _pisock.PI_DLP_VERSION_MINOR
PI_ERR_DLP_BUFSIZE
PI_ERR_DLP_BUFSIZE = _pisock.PI_ERR_DLP_BUFSIZE
PI_ERR_DLP_COMMAND
PI_ERR_DLP_COMMAND = _pisock.PI_ERR_DLP_COMMAND
PI_ERR_DLP_DATASIZE
PI_ERR_DLP_DATASIZE = _pisock.PI_ERR_DLP_DATASIZE
PI_ERR_DLP_PALMOS
PI_ERR_DLP_PALMOS = _pisock.PI_ERR_DLP_PALMOS
PI_ERR_DLP_SOCKET
PI_ERR_DLP_SOCKET = _pisock.PI_ERR_DLP_SOCKET
PI_ERR_DLP_UNSUPPORTED
PI_ERR_DLP_UNSUPPORTED = _pisock.PI_ERR_DLP_UNSUPPORTED
PI_ERR_FILE_ABORTED
PI_ERR_FILE_ABORTED = _pisock.PI_ERR_FILE_ABORTED
PI_ERR_FILE_ALREADY_EXISTS
PI_ERR_FILE_ALREADY_EXISTS = _pisock.PI_ERR_FILE_ALREADY_EXISTS
PI_ERR_FILE_ERROR
PI_ERR_FILE_ERROR = _pisock.PI_ERR_FILE_ERROR
PI_ERR_FILE_INVALID
PI_ERR_FILE_INVALID = _pisock.PI_ERR_FILE_INVALID
PI_ERR_FILE_NOT_FOUND
PI_ERR_FILE_NOT_FOUND = _pisock.PI_ERR_FILE_NOT_FOUND
PI_ERR_GENERIC_ARGUMENT
PI_ERR_GENERIC_ARGUMENT = _pisock.PI_ERR_GENERIC_ARGUMENT
PI_ERR_GENERIC_MEMORY
PI_ERR_GENERIC_MEMORY = _pisock.PI_ERR_GENERIC_MEMORY
PI_ERR_GENERIC_SYSTEM
PI_ERR_GENERIC_SYSTEM = _pisock.PI_ERR_GENERIC_SYSTEM
PI_ERR_PROT_ABORTED
PI_ERR_PROT_ABORTED = _pisock.PI_ERR_PROT_ABORTED
PI_ERR_PROT_BADPACKET
PI_ERR_PROT_BADPACKET = _pisock.PI_ERR_PROT_BADPACKET
PI_ERR_PROT_INCOMPATIBLE
PI_ERR_PROT_INCOMPATIBLE = _pisock.PI_ERR_PROT_INCOMPATIBLE
PI_ERR_SOCK_CANCELED
PI_ERR_SOCK_CANCELED = _pisock.PI_ERR_SOCK_CANCELED
PI_ERR_SOCK_DISCONNECTED
PI_ERR_SOCK_DISCONNECTED = _pisock.PI_ERR_SOCK_DISCONNECTED
PI_ERR_SOCK_INVALID
PI_ERR_SOCK_INVALID = _pisock.PI_ERR_SOCK_INVALID
PI_ERR_SOCK_IO
PI_ERR_SOCK_IO = _pisock.PI_ERR_SOCK_IO
PI_ERR_SOCK_LISTENER
PI_ERR_SOCK_LISTENER = _pisock.PI_ERR_SOCK_LISTENER
PI_ERR_SOCK_TIMEOUT
PI_ERR_SOCK_TIMEOUT = _pisock.PI_ERR_SOCK_TIMEOUT
pi_error
pi_error = _pisock.pi_error
pi_file_install
pi_file_install = _pisock.pi_file_install
pi_file_retrieve
pi_file_retrieve = _pisock.pi_file_retrieve
pi_flush
pi_flush = _pisock.pi_flush
pi_getsockname
pi_getsockname = _pisock.pi_getsockname
pi_getsockopt
pi_getsockopt = _pisock.pi_getsockopt
pi_getsockpeer
pi_getsockpeer = _pisock.pi_getsockpeer
PI_LEVEL_CMP
PI_LEVEL_CMP = _pisock.PI_LEVEL_CMP
PI_LEVEL_DEV
PI_LEVEL_DEV = _pisock.PI_LEVEL_DEV
PI_LEVEL_DLP
PI_LEVEL_DLP = _pisock.PI_LEVEL_DLP
PI_LEVEL_NET
PI_LEVEL_NET = _pisock.PI_LEVEL_NET
PI_LEVEL_PADP
PI_LEVEL_PADP = _pisock.PI_LEVEL_PADP
PI_LEVEL_SLP
PI_LEVEL_SLP = _pisock.PI_LEVEL_SLP
PI_LEVEL_SOCK
PI_LEVEL_SOCK = _pisock.PI_LEVEL_SOCK
PI_LEVEL_SYS
PI_LEVEL_SYS = _pisock.PI_LEVEL_SYS
pi_listen
pi_listen = _pisock.pi_listen
pi_maxrecsize
pi_maxrecsize = _pisock.pi_maxrecsize
PI_MSG_PEEK
PI_MSG_PEEK = _pisock.PI_MSG_PEEK
PI_NET_SPLIT_WRITES
PI_NET_SPLIT_WRITES = _pisock.PI_NET_SPLIT_WRITES
PI_NET_TYPE
PI_NET_TYPE = _pisock.PI_NET_TYPE
PI_NET_WRITE_CHUNKSIZE
PI_NET_WRITE_CHUNKSIZE = _pisock.PI_NET_WRITE_CHUNKSIZE
PI_PADP_FREEZE_TXID
PI_PADP_FREEZE_TXID = _pisock.PI_PADP_FREEZE_TXID
PI_PADP_LASTTYPE
PI_PADP_LASTTYPE = _pisock.PI_PADP_LASTTYPE
PI_PADP_TYPE
PI_PADP_TYPE = _pisock.PI_PADP_TYPE
PI_PADP_USE_LONG_FORMAT
PI_PADP_USE_LONG_FORMAT = _pisock.PI_PADP_USE_LONG_FORMAT
pi_palmos_error
pi_palmos_error = _pisock.pi_palmos_error
Referenced by pisockextras.dlp_ReadDBList().
PI_PF_DEV
PI_PF_DEV = _pisock.PI_PF_DEV
PI_PF_DLP
PI_PF_DLP = _pisock.PI_PF_DLP
PI_PF_NET
PI_PF_NET = _pisock.PI_PF_NET
PI_PF_PADP
PI_PF_PADP = _pisock.PI_PF_PADP
PI_PF_SLP
PI_PF_SLP = _pisock.PI_PF_SLP
PI_PF_SYS
PI_PF_SYS = _pisock.PI_PF_SYS
pi_protocol
pi_protocol = _pisock.pi_protocol
pi_protocol_next
pi_protocol_next = _pisock.pi_protocol_next
pi_read
pi_read = _pisock.pi_read
pi_recv
pi_recv = _pisock.pi_recv
pi_reset_errors
pi_reset_errors = _pisock.pi_reset_errors
pi_send
pi_send = _pisock.pi_send
pi_set_error
pi_set_error = _pisock.pi_set_error
pi_set_palmos_error
pi_set_palmos_error = _pisock.pi_set_palmos_error
pi_setsockopt
pi_setsockopt = _pisock.pi_setsockopt
PI_SLP_DEST
PI_SLP_DEST = _pisock.PI_SLP_DEST
PI_SLP_LASTDEST
PI_SLP_LASTDEST = _pisock.PI_SLP_LASTDEST
PI_SLP_LASTSRC
PI_SLP_LASTSRC = _pisock.PI_SLP_LASTSRC
PI_SLP_LASTTXID
PI_SLP_LASTTXID = _pisock.PI_SLP_LASTTXID
PI_SLP_LASTTYPE
PI_SLP_LASTTYPE = _pisock.PI_SLP_LASTTYPE
PI_SLP_SRC
PI_SLP_SRC = _pisock.PI_SLP_SRC
PI_SLP_TXID
PI_SLP_TXID = _pisock.PI_SLP_TXID
PI_SLP_TYPE
PI_SLP_TYPE = _pisock.PI_SLP_TYPE
PI_SOCK_HONOR_RX_TIMEOUT
PI_SOCK_HONOR_RX_TIMEOUT = _pisock.PI_SOCK_HONOR_RX_TIMEOUT
PI_SOCK_RAW
PI_SOCK_RAW = _pisock.PI_SOCK_RAW
PI_SOCK_STATE
PI_SOCK_STATE = _pisock.PI_SOCK_STATE
PI_SOCK_STREAM
PI_SOCK_STREAM = _pisock.PI_SOCK_STREAM
pi_socket
pi_socket = _pisock.pi_socket
pi_socket_connected
pi_socket_connected = _pisock.pi_socket_connected
pi_socket_setsd
pi_socket_setsd = _pisock.pi_socket_setsd
pi_tickle
pi_tickle = _pisock.pi_tickle
pi_version
pi_version = _pisock.pi_version
pi_watchdog
pi_watchdog = _pisock.pi_watchdog
pi_write
pi_write = _pisock.pi_write
vfsFileAttrArchive
vfsFileAttrArchive = _pisock.vfsFileAttrArchive
vfsFileAttrDirectory
vfsFileAttrDirectory = _pisock.vfsFileAttrDirectory
vfsFileAttrHidden
vfsFileAttrHidden = _pisock.vfsFileAttrHidden
vfsFileAttrLink
vfsFileAttrLink = _pisock.vfsFileAttrLink
vfsFileAttrReadOnly
vfsFileAttrReadOnly = _pisock.vfsFileAttrReadOnly
vfsFileAttrSystem
vfsFileAttrSystem = _pisock.vfsFileAttrSystem
vfsFileAttrVolumeLabel
vfsFileAttrVolumeLabel = _pisock.vfsFileAttrVolumeLabel
vfsFileDateAccessed
vfsFileDateAccessed = _pisock.vfsFileDateAccessed
vfsFileDateCreated
vfsFileDateCreated = _pisock.vfsFileDateCreated
vfsFileDateModified
vfsFileDateModified = _pisock.vfsFileDateModified
vfsInvalidFileRef
vfsInvalidFileRef = _pisock.vfsInvalidFileRef
vfsInvalidVolRef
vfsInvalidVolRef = _pisock.vfsInvalidVolRef
vfsIteratorStart
vfsIteratorStart = _pisock.vfsIteratorStart
vfsIteratorStop
vfsIteratorStop = _pisock.vfsIteratorStop
vfsMAXFILENAME
vfsMAXFILENAME = _pisock.vfsMAXFILENAME
vfsModeCreate
vfsModeCreate = _pisock.vfsModeCreate
vfsModeExclusive
vfsModeExclusive = _pisock.vfsModeExclusive
vfsModeLeaveOpen
vfsModeLeaveOpen = _pisock.vfsModeLeaveOpen
vfsModeRead
vfsModeRead = _pisock.vfsModeRead
vfsModeReadWrite
vfsModeReadWrite = _pisock.vfsModeReadWrite
vfsModeTruncate
vfsModeTruncate = _pisock.vfsModeTruncate
vfsModeWrite
vfsModeWrite = _pisock.vfsModeWrite
vfsMountFlagsUseThisFileSystem
vfsMountFlagsUseThisFileSystem = _pisock.vfsMountFlagsUseThisFileSystem
vfsOriginBeginning
vfsOriginBeginning = _pisock.vfsOriginBeginning
vfsOriginCurrent
vfsOriginCurrent = _pisock.vfsOriginCurrent
vfsOriginEnd
vfsOriginEnd = _pisock.vfsOriginEnd
vfsVolAttrHidden
vfsVolAttrHidden = _pisock.vfsVolAttrHidden
vfsVolAttrReadOnly
vfsVolAttrReadOnly = _pisock.vfsVolAttrReadOnly
vfsVolAttrSlotBased
vfsVolAttrSlotBased = _pisock.vfsVolAttrSlotBased