pilot-link: libpisock/notepad.c File Reference
notepad.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "pi-macros.h"
#include "pi-notepad.h"
Functions
void free_NotePad (NotePad_t *a)
int pack_NotePad (NotePad_t *notepad, unsigned char *buf, size_t len)
int pack_NotePadAppInfo (NotePadAppInfo_t *appinfo, unsigned char *record, size_t len)
int unpack_NotePad (NotePad_t *notepad, unsigned char *buffer, size_t len)
int unpack_NotePadAppInfo (NotePadAppInfo_t *appinfo, unsigned char *record, size_t len)
Function Documentation
free_NotePad()
void free_NotePad (NotePad_t * a)
{
   if( a->flags & NOTEPAD_FLAG_NAME )
     {
/*  fprintf(stderr, "Freeing name: %s\n", a->name); */
    free(a->name);
     }
   if( a->flags & NOTEPAD_FLAG_BODY )
     {
/*  fprintf(stderr, "Freeing data\n"); */
    free(a->data);
     }
}
Referenced by output_picture().
pack_NotePad()
int pack_NotePad (NotePad_t * notepad, unsigned char * buf, size_t len)
{
   return( 0 );
}
pack_NotePadAppInfo()
int pack_NotePadAppInfo (NotePadAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int     i;
    unsigned char *start = record;
    i = pack_CategoryAppInfo(&appinfo->category, record, len);
    if (!record)
        return i + 4;
    if (!i)
        return 0;
    record += i;
    len -= i;
    if (len < 4)
        return 0;
    set_short(record, appinfo->dirty);
    set_byte(record + 2, appinfo->sortByPriority);
    set_byte(record + 3, 0);    /* gapfill */
    record += 4;
    return (record - start);
}
References pack_CategoryAppInfo().
unpack_NotePad()
int unpack_NotePad (NotePad_t * notepad, unsigned char * buffer, size_t len)
{
   unsigned char *start = buffer;
   notepad->createDate.sec = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->createDate.min = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->createDate.hour = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->createDate.day = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->createDate.month = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->createDate.year = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->createDate.s = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->changeDate.sec = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->changeDate.min = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->changeDate.hour = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->changeDate.day = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->changeDate.month = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->changeDate.year = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->changeDate.s = (unsigned short int) get_short(buffer);
   buffer += 2;
   notepad->flags = (unsigned short int) get_short(buffer);
   buffer += 2;
/*   fprintf(stderr, "flags: 0x%x\n", notepad->flags); */
   if( notepad->flags & NOTEPAD_FLAG_ALARM )
     {
/*  fprintf(stderr, "Getting Alarm\n"); */
    notepad->alarmDate.sec = (unsigned short int) get_short(buffer);
    buffer += 2;
    notepad->alarmDate.min = (unsigned short int) get_short(buffer);
    buffer += 2;
    notepad->alarmDate.hour = (unsigned short int) get_short(buffer);
    buffer += 2;
    notepad->alarmDate.day = (unsigned short int) get_short(buffer);
    buffer += 2;
    notepad->alarmDate.month = (unsigned short int) get_short(buffer);
    buffer += 2;
    notepad->alarmDate.year = (unsigned short int) get_short(buffer);
    buffer += 2;
    notepad->alarmDate.s = (unsigned short int) get_short(buffer);
    buffer += 2;
     }
   if( notepad->flags & NOTEPAD_FLAG_NAME )
     {
/*  fprintf(stderr, "Getting Name\n"); */
    notepad->name = strdup((char *) buffer);
    buffer += strlen( notepad->name ) + 1;
    if( (strlen( notepad->name ) + 1)%2 == 1)
      buffer++;
     }
   else
     {
    notepad->name = NULL;
     }
   if( notepad->flags & NOTEPAD_FLAG_BODY )
     {
/*  fprintf(stderr, "Getting Body\n"); */
    notepad->body.bodyLen = get_long( buffer );
    buffer += 4;
    notepad->body.width = get_long( buffer );
    buffer += 4;
    notepad->body.height = get_long( buffer );
    buffer += 4;
    notepad->body.l1 = get_long( buffer );
    buffer += 4;
    notepad->body.dataType = get_long( buffer );
    buffer += 4;
    notepad->body.dataLen = get_long( buffer );
    buffer += 4;
    notepad->data = malloc( notepad->body.dataLen );
    if( notepad->data == NULL )
      {
         fprintf( stderr, "Body data alloc failed\n" );
         return( 0 );
      }
    memcpy( notepad->data, buffer, notepad->body.dataLen );
     }
   return ( buffer - start );   /* FIXME: return real length */
}
References buffer, and strdup().
Referenced by main().
unpack_NotePadAppInfo()
int unpack_NotePadAppInfo (NotePadAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int     i;
    unsigned char *start = record;
    i = unpack_CategoryAppInfo( &appinfo->category, record, len );
    if (!i)
        return 0;
    record += i;
    len -= i;
    if (len < 4)
        return 0;
    appinfo->dirty = get_short(record);
    record += 2;
    appinfo->sortByPriority = get_byte(record);
    record += 2;
    return (record - start);
}
References unpack_CategoryAppInfo().
Referenced by main().