pilot-link: libpisock/pi-buffer.c File Reference
pi-buffer.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pi-buffer.h"
Functions
pi_buffer_t * pi_buffer_append (pi_buffer_t *buf, const void *data, size_t len)
pi_buffer_t * pi_buffer_append_buffer (pi_buffer_t *dest, const pi_buffer_t *src)
void pi_buffer_clear (pi_buffer_t *buf)
pi_buffer_t * pi_buffer_expect (pi_buffer_t *buf, size_t expect)
void pi_buffer_free (pi_buffer_t *buf)
pi_buffer_t * pi_buffer_new (size_t capacity)
Function Documentation
pi_buffer_append()
pi_buffer_t * pi_buffer_append (pi_buffer_t * buf, const void * data, size_t len)
{
    if (pi_buffer_expect (buf, len) == NULL)
        return NULL;
    memcpy (buf->data + buf->used, data, len);
    buf->used += len;
    return buf;
}
References buf, and pi_buffer_expect().
Referenced by dlp_CallApplication(), dlp_ReadAppBlock(), dlp_ReadDBList(), dlp_ReadNextModifiedRec(), dlp_ReadNextModifiedRecInCategory(), dlp_ReadNextRecInCategory(), dlp_ReadRecordById(), dlp_ReadRecordByIndex(), dlp_ReadResourceByIndex(), dlp_ReadResourceByType(), dlp_ReadSortBlock(), main(), pack_ContactAppInfo(), padp_rx(), pi_buffer_append_buffer(), pi_file_append_record(), pi_file_append_resource(), s_read_buf(), slp_rx(), u_read(), u_read(), u_read_buf(), and u_read_i().
pi_buffer_append_buffer()
pi_buffer_t * pi_buffer_append_buffer (pi_buffer_t * dest, const pi_buffer_t * src)
{
    return pi_buffer_append (dest, src->data, src->used);
}
References pi_buffer_append().
pi_buffer_clear()
void pi_buffer_clear (pi_buffer_t * buf)
{
    buf->used = 0;
    if (buf->allocated > (size_t)65535)
    {
        buf->data = (unsigned char *) realloc (buf->data, 65535);
        buf->allocated = (buf->data == NULL) ? 0 : 65535;
    }
}
References buf.
Referenced by dlp_CallApplication(), dlp_ReadAppBlock(), dlp_ReadDBList(), dlp_ReadNextModifiedRec(), dlp_ReadNextModifiedRecInCategory(), dlp_ReadNextRecInCategory(), dlp_ReadRecordById(), dlp_ReadRecordByIndex(), dlp_ReadResourceByIndex(), dlp_ReadResourceByType(), dlp_ReadSortBlock(), dlp_VFSFileRead(), main(), pi_file_retrieve_VFS(), pi_file_retrieve_VFS(), and protocol_queue_build().
pi_buffer_expect()
pi_buffer_t * pi_buffer_expect (pi_buffer_t * buf, size_t expect)
{
    if ((buf->allocated - buf->used) >= expect)
        return buf;
    if (buf->data)
        buf->data = (unsigned char *) realloc (buf->data, buf->used + expect);
    else
        buf->data = (unsigned char *) malloc (expect);
    if (buf->data == NULL) {
        buf->allocated = 0;
        buf->used = 0;
        return NULL;
    }
    buf->allocated = buf->used + expect;
    return buf;
}
References buf.
Referenced by pack_Address(), pack_Appointment(), pack_Blob(), pack_CalendarAppInfo(), pack_CalendarEvent(), pack_Contact(), pack_ContactAppInfo(), pack_DST(), pack_Location(), pack_Memo(), pack_Timezone(), pack_ToDo(), pi_bluetooth_read(), pi_buffer_append(), pi_inet_read(), s_read(), u_read(), u_read(), and u_read().
pi_buffer_free()
void pi_buffer_free (pi_buffer_t * buf)
{
    if (buf) {
        if (buf->data)
            free (buf->data);
        free (buf);
    }
}
References buf.
Referenced by _wrap_dlp_CallApplication(), _wrap_dlp_ReadAppBlock(), _wrap_dlp_ReadDBList_(), _wrap_dlp_ReadNextModifiedRec(), _wrap_dlp_ReadNextModifiedRecInCategory(), _wrap_dlp_ReadNextRecInCategory(), _wrap_dlp_ReadRecordById(), _wrap_dlp_ReadRecordByIndex(), _wrap_dlp_ReadResourceByIndex(), _wrap_dlp_ReadResourceByType(), _wrap_dlp_ReadSortBlock(), _wrap_dlp_VFSFileRead(), _wrap_pi_read(), _wrap_pi_recv(), addresses(), cmp_rx_handshake(), DeDupe(), dlp_FindDBInfo(), dlp_ReadAppPreference(), dlp_response_read(), do_delete(), do_fetch(), do_list(), Fetch(), fetch_wavs(), GetPicData(), install_ToDo(), install_ToDos(), ls_fn(), main(), main(), main(), MemoPackCmd(), MemoUnpackCmd(), net_rx(), net_rx_handshake(), net_tx_handshake(), padp_rx(), padp_tx(), palm_backup(), palm_list_internal(), palm_purge(), pi_file_free(), pi_file_retrieve(), pi_file_retrieve_VFS(), pi_file_retrieve_VFS(), protocol_queue_build(), read_file(), read_pilot(), slp_rx(), sync_CopyFromPilot(), sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), sync_MergeToPilot_slow(), sys_Find(), sys_GetTrapBreaks(), sys_ReadMemory(), sys_RPC(), sys_SetBreakpoints(), sys_SetTrapBreaks(), sys_ToggleDbgBreaks(), sys_WriteMemory(), write_file(), WritePicture(), and WritePictures().
pi_buffer_new()
pi_buffer_t * pi_buffer_new (size_t capacity)
{
    pi_buffer_t* buf;
    buf = (struct pi_buffer_t *) malloc (sizeof (struct pi_buffer_t));
    if (buf == NULL)
        return NULL;
    if (capacity <= 0)
        capacity = 16;  /* allocating 0 byte is illegal - use a small value instead */
    buf->data = (unsigned char *) malloc (capacity);
    if (buf->data == NULL) {
        free (buf);
        return NULL;
    }
    buf->allocated = capacity;
    buf->used = 0;
    return buf;
}
References buf.
Referenced by _wrap_dlp_CallApplication(), _wrap_dlp_ReadAppBlock(), _wrap_dlp_ReadDBList_(), _wrap_dlp_ReadNextModifiedRec(), _wrap_dlp_ReadNextModifiedRecInCategory(), _wrap_dlp_ReadNextRecInCategory(), _wrap_dlp_ReadRecordById(), _wrap_dlp_ReadRecordByIndex(), _wrap_dlp_ReadResourceByIndex(), _wrap_dlp_ReadResourceByType(), _wrap_dlp_ReadSortBlock(), _wrap_dlp_VFSFileRead(), _wrap_pi_read(), _wrap_pi_recv(), addresses(), cmp_rx_handshake(), DeDupe(), dlp_FindDBInfo(), dlp_ReadAppPreference(), dlp_response_read(), do_delete(), do_fetch(), do_list(), Fetch(), fetch_wavs(), GetPicData(), install_ToDo(), install_ToDos(), ls_fn(), main(), main(), main(), MemoPackCmd(), MemoUnpackCmd(), net_rx(), net_rx_handshake(), net_tx_handshake(), padp_rx(), padp_tx(), palm_backup(), palm_list_internal(), palm_purge(), pi_file_create(), pi_file_retrieve(), pi_file_retrieve_VFS(), pi_file_retrieve_VFS(), protocol_queue_build(), read_file(), read_pilot(), slp_rx(), sync_CopyFromPilot(), sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), sync_MergeToPilot_slow(), sys_Find(), sys_GetTrapBreaks(), sys_ReadMemory(), sys_RPC(), sys_SetBreakpoints(), sys_SetTrapBreaks(), sys_ToggleDbgBreaks(), sys_WriteMemory(), write_file(), WritePicture(), and WritePictures().