pilot-link: src/pilot-read-palmpix.c File Reference
pilot-read-palmpix.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <utime.h>
#include "pi-file.h"
#include "pi-socket.h"
#include "pi-header.h"
#include "pi-palmpix.h"
#include "pi-userland.h"
Data Structures
struct PalmPixState_pi_file
struct PalmPixState_pi_socket
Functions
static int fail (const char *func)
static const char * fmt_date (const struct PalmPixHeader *h)
static int getrecord_pi_file (struct PalmPixState *vstate, int recno, void **buf, size_t *bufsize)
static int getrecord_pi_socket (struct PalmPixState *vstate, int recno, void **buf, size_t *bufsize)
void init_for_ppm (struct PalmPixState *state)
static int list (const struct PalmPixHeader *h, struct PalmPixState *state, int recno, const char *ignored)
int main (int argc, const char **argv)
void read_db (struct PalmPixState *state, int n, int(*action)(const struct PalmPixHeader *, struct PalmPixState *, int, const char *), const char *action_arg)
static int write_all (const struct PalmPixHeader *header, struct PalmPixState *state, int recno, const char *ignored)
static int write_one (const struct PalmPixHeader *header, struct PalmPixState *state, int recno, const char *pixname)
void write_ppm (FILE *f, const struct PalmPixState *state, const struct PalmPixHeader *header)
Variables
const char * progname
Function Documentation
fail()
static int fail (const char * func) static
{
    perror (func);
    return -1;
}
Referenced by _wrap_CardInfo_card_get(), _wrap_CardInfo_card_set(), _wrap_CardInfo_creation_get(), _wrap_CardInfo_creation_set(), _wrap_CardInfo_manufacturer_get(), _wrap_CardInfo_manufacturer_set(), _wrap_CardInfo_more_get(), _wrap_CardInfo_more_set(), _wrap_CardInfo_name_get(), _wrap_CardInfo_name_set(), _wrap_CardInfo_ramFree_get(), _wrap_CardInfo_ramFree_set(), _wrap_CardInfo_ramSize_get(), _wrap_CardInfo_ramSize_set(), _wrap_CardInfo_romSize_get(), _wrap_CardInfo_romSize_set(), _wrap_CardInfo_version_get(), _wrap_CardInfo_version_set(), _wrap_DBInfo_backupDate_get(), _wrap_DBInfo_backupDate_set(), _wrap_DBInfo_createDate_get(), _wrap_DBInfo_createDate_set(), _wrap_DBInfo_creator_get(), _wrap_DBInfo_creator_set(), _wrap_DBInfo_flags_get(), _wrap_DBInfo_flags_set(), _wrap_DBInfo_index_get(), _wrap_DBInfo_index_set(), _wrap_DBInfo_miscFlags_get(), _wrap_DBInfo_miscFlags_set(), _wrap_DBInfo_modifyDate_get(), _wrap_DBInfo_modifyDate_set(), _wrap_DBInfo_modnum_get(), _wrap_DBInfo_modnum_set(), _wrap_DBInfo_more_get(), _wrap_DBInfo_more_set(), _wrap_DBInfo_name_get(), _wrap_DBInfo_name_set(), _wrap_DBInfo_type_get(), _wrap_DBInfo_type_set(), _wrap_DBInfo_version_get(), _wrap_DBInfo_version_set(), _wrap_DBSizeInfo_appBlockSize_get(), _wrap_DBSizeInfo_appBlockSize_set(), _wrap_DBSizeInfo_dataBytes_get(), _wrap_DBSizeInfo_dataBytes_set(), _wrap_DBSizeInfo_maxRecSize_get(), _wrap_DBSizeInfo_maxRecSize_set(), _wrap_DBSizeInfo_numRecords_get(), _wrap_DBSizeInfo_numRecords_set(), _wrap_DBSizeInfo_sortBlockSize_get(), _wrap_DBSizeInfo_sortBlockSize_set(), _wrap_DBSizeInfo_totalBytes_get(), _wrap_DBSizeInfo_totalBytes_set(), _wrap_delete_CardInfo(), _wrap_delete_DBInfo(), _wrap_delete_DBSizeInfo(), _wrap_delete_NetSyncInfo(), _wrap_delete_pi_socket_list_t(), _wrap_delete_pi_socket_t(), _wrap_delete_PilotUser(), _wrap_delete_SysInfo(), _wrap_delete_VFSAnyMountParam(), _wrap_delete_VFSDirInfo(), _wrap_delete_VFSInfo(), _wrap_delete_VFSSlotMountParam(), _wrap_dlp_AbortSync(), _wrap_dlp_AddSyncLogEntry(), _wrap_dlp_CallApplication(), _wrap_dlp_CleanUpDatabase(), _wrap_dlp_CloseDB(), _wrap_dlp_CloseDB_All(), _wrap_dlp_CreateDB(), _wrap_dlp_DeleteCategory(), _wrap_dlp_DeleteDB(), _wrap_dlp_DeleteRecord(), _wrap_dlp_DeleteResource(), _wrap_dlp_EndOfSync(), _wrap_dlp_ExpCardInfo(), _wrap_dlp_ExpCardPresent(), _wrap_dlp_ExpSlotEnumerate(), _wrap_dlp_ExpSlotMediaType(), _wrap_dlp_FindDBByName(), _wrap_dlp_FindDBByOpenHandle(), _wrap_dlp_FindDBByTypeCreator(), _wrap_dlp_FindDBInfo(), _wrap_dlp_GetROMToken(), _wrap_dlp_GetSysDateTime_(), _wrap_dlp_htopdate(), _wrap_dlp_MoveCategory(), _wrap_dlp_OpenConduit(), _wrap_dlp_OpenDB(), _wrap_dlp_ptohdate(), _wrap_dlp_ReadAppBlock(), _wrap_dlp_ReadAppPreference(), _wrap_dlp_ReadDBList_(), _wrap_dlp_ReadFeature(), _wrap_dlp_ReadNetSyncInfo(), _wrap_dlp_ReadNextModifiedRec(), _wrap_dlp_ReadNextModifiedRecInCategory(), _wrap_dlp_ReadNextRecInCategory(), _wrap_dlp_ReadOpenDBInfo(), _wrap_dlp_ReadRecordById(), _wrap_dlp_ReadRecordByIndex(), _wrap_dlp_ReadResourceByIndex(), _wrap_dlp_ReadResourceByType(), _wrap_dlp_ReadSortBlock(), _wrap_dlp_ReadStorageInfo(), _wrap_dlp_ReadSysInfo(), _wrap_dlp_ReadUserInfo(), _wrap_dlp_ResetDBIndex(), _wrap_dlp_ResetLastSyncPC(), _wrap_dlp_ResetSyncFlags(), _wrap_dlp_ResetSystem(), _wrap_dlp_set_protocol_version(), _wrap_dlp_SetDBInfo(), _wrap_dlp_SetSysDateTime(), _wrap_dlp_VFSDirCreate(), _wrap_dlp_VFSDirEntryEnumerate(), _wrap_dlp_VFSExportDatabaseToFile(), _wrap_dlp_VFSFileClose(), _wrap_dlp_VFSFileCreate(), _wrap_dlp_VFSFileDelete(), _wrap_dlp_VFSFileEOF(), _wrap_dlp_VFSFileGetAttributes(), _wrap_dlp_VFSFileGetDate(), _wrap_dlp_VFSFileOpen(), _wrap_dlp_VFSFileRead(), _wrap_dlp_VFSFileRename(), _wrap_dlp_VFSFileResize(), _wrap_dlp_VFSFileSeek(), _wrap_dlp_VFSFileSetAttributes(), _wrap_dlp_VFSFileSetDate(), _wrap_dlp_VFSFileSize(), _wrap_dlp_VFSFileTell(), _wrap_dlp_VFSFileWrite(), _wrap_dlp_VFSGetDefaultDir(), _wrap_dlp_VFSImportDatabaseFromFile(), _wrap_dlp_VFSVolumeEnumerate(), _wrap_dlp_VFSVolumeFormat(), _wrap_dlp_VFSVolumeGetLabel(), _wrap_dlp_VFSVolumeInfo(), _wrap_dlp_VFSVolumeSetLabel(), _wrap_dlp_VFSVolumeSize(), _wrap_dlp_WriteAppBlock(), _wrap_dlp_WriteAppPreference(), _wrap_dlp_WriteNetSyncInfo(), _wrap_dlp_WriteRecord(), _wrap_dlp_WriteResource(), _wrap_dlp_WriteSortBlock(), _wrap_dlp_WriteUserInfo(), _wrap_NetSyncInfo_hostAddress_get(), _wrap_NetSyncInfo_hostAddress_set(), _wrap_NetSyncInfo_hostName_get(), _wrap_NetSyncInfo_hostName_set(), _wrap_NetSyncInfo_hostSubnetMask_get(), _wrap_NetSyncInfo_hostSubnetMask_set(), _wrap_NetSyncInfo_lanSync_get(), _wrap_NetSyncInfo_lanSync_set(), _wrap_new_CardInfo(), _wrap_new_DBInfo(), _wrap_new_DBSizeInfo(), _wrap_new_NetSyncInfo(), _wrap_new_pi_socket_list_t(), _wrap_new_pi_socket_t(), _wrap_new_PilotUser(), _wrap_new_SysInfo(), _wrap_new_VFSAnyMountParam(), _wrap_new_VFSDirInfo(), _wrap_new_VFSInfo(), _wrap_new_VFSSlotMountParam(), _wrap_pi_accept(), _wrap_pi_accept_to(), _wrap_pi_bind(), _wrap_pi_close(), _wrap_pi_connect(), _wrap_pi_error(), _wrap_pi_flush(), _wrap_pi_getsockname(), _wrap_pi_getsockopt(), _wrap_pi_getsockpeer(), _wrap_pi_listen(), _wrap_pi_maxrecsize(), _wrap_pi_palmos_error(), _wrap_pi_protocol(), _wrap_pi_protocol_next(), _wrap_pi_read(), _wrap_pi_recv(), _wrap_pi_reset_errors(), _wrap_pi_send(), _wrap_pi_set_error(), _wrap_pi_set_palmos_error(), _wrap_pi_setsockopt(), _wrap_pi_socket(), _wrap_pi_socket_connected(), _wrap_pi_socket_list_t_next_get(), _wrap_pi_socket_list_t_next_set(), _wrap_pi_socket_list_t_ps_get(), _wrap_pi_socket_list_t_ps_set(), _wrap_pi_socket_setsd(), _wrap_pi_socket_t_accept_to_get(), _wrap_pi_socket_t_accept_to_set(), _wrap_pi_socket_t_cmd_get(), _wrap_pi_socket_t_cmd_len_get(), _wrap_pi_socket_t_cmd_len_set(), _wrap_pi_socket_t_cmd_queue_get(), _wrap_pi_socket_t_cmd_queue_set(), _wrap_pi_socket_t_cmd_set(), _wrap_pi_socket_t_command_get(), _wrap_pi_socket_t_command_set(), _wrap_pi_socket_t_device_get(), _wrap_pi_socket_t_device_set(), _wrap_pi_socket_t_dlprecord_get(), _wrap_pi_socket_t_dlprecord_set(), _wrap_pi_socket_t_dlpversion_get(), _wrap_pi_socket_t_dlpversion_set(), _wrap_pi_socket_t_honor_rx_to_get(), _wrap_pi_socket_t_honor_rx_to_set(), _wrap_pi_socket_t_laddr_get(), _wrap_pi_socket_t_laddr_set(), _wrap_pi_socket_t_laddrlen_get(), _wrap_pi_socket_t_laddrlen_set(), _wrap_pi_socket_t_last_error_get(), _wrap_pi_socket_t_last_error_set(), _wrap_pi_socket_t_maxrecsize_get(), _wrap_pi_socket_t_maxrecsize_set(), _wrap_pi_socket_t_palmos_error_get(), _wrap_pi_socket_t_palmos_error_set(), _wrap_pi_socket_t_protocol_get(), _wrap_pi_socket_t_protocol_queue_get(), _wrap_pi_socket_t_protocol_queue_set(), _wrap_pi_socket_t_protocol_set(), _wrap_pi_socket_t_queue_len_get(), _wrap_pi_socket_t_queue_len_set(), _wrap_pi_socket_t_raddr_get(), _wrap_pi_socket_t_raddr_set(), _wrap_pi_socket_t_raddrlen_get(), _wrap_pi_socket_t_raddrlen_set(), _wrap_pi_socket_t_sd_get(), _wrap_pi_socket_t_sd_set(), _wrap_pi_socket_t_state_get(), _wrap_pi_socket_t_state_set(), _wrap_pi_socket_t_type_get(), _wrap_pi_socket_t_type_set(), _wrap_pi_tickle(), _wrap_pi_version(), _wrap_pi_watchdog(), _wrap_pi_write(), _wrap_PilotUser_lastSyncDate_get(), _wrap_PilotUser_lastSyncDate_set(), _wrap_PilotUser_lastSyncPC_get(), _wrap_PilotUser_lastSyncPC_set(), _wrap_PilotUser_password_get(), _wrap_PilotUser_password_set(), _wrap_PilotUser_passwordLength_get(), _wrap_PilotUser_passwordLength_set(), _wrap_PilotUser_successfulSyncDate_get(), _wrap_PilotUser_successfulSyncDate_set(), _wrap_PilotUser_userID_get(), _wrap_PilotUser_userID_set(), _wrap_PilotUser_username_get(), _wrap_PilotUser_username_set(), _wrap_PilotUser_viewerID_get(), _wrap_PilotUser_viewerID_set(), _wrap_SysInfo_compatMajorVersion_get(), _wrap_SysInfo_compatMajorVersion_set(), _wrap_SysInfo_compatMinorVersion_get(), _wrap_SysInfo_compatMinorVersion_set(), _wrap_SysInfo_dlpMajorVersion_get(), _wrap_SysInfo_dlpMajorVersion_set(), _wrap_SysInfo_dlpMinorVersion_get(), _wrap_SysInfo_dlpMinorVersion_set(), _wrap_SysInfo_locale_get(), _wrap_SysInfo_locale_set(), _wrap_SysInfo_maxRecSize_get(), _wrap_SysInfo_maxRecSize_set(), _wrap_SysInfo_prodID_get(), _wrap_SysInfo_prodID_set(), _wrap_SysInfo_prodIDLength_get(), _wrap_SysInfo_prodIDLength_set(), _wrap_SysInfo_romVersion_get(), _wrap_SysInfo_romVersion_set(), _wrap_VFSAnyMountParam_mountClass_get(), _wrap_VFSAnyMountParam_mountClass_set(), _wrap_VFSAnyMountParam_reserved_get(), _wrap_VFSAnyMountParam_reserved_set(), _wrap_VFSAnyMountParam_volRefNum_get(), _wrap_VFSAnyMountParam_volRefNum_set(), _wrap_VFSDirInfo_attr_get(), _wrap_VFSDirInfo_attr_set(), _wrap_VFSDirInfo_name_get(), _wrap_VFSDirInfo_name_set(), _wrap_VFSInfo_attributes_get(), _wrap_VFSInfo_attributes_set(), _wrap_VFSInfo_fsCreator_get(), _wrap_VFSInfo_fsCreator_set(), _wrap_VFSInfo_fsType_get(), _wrap_VFSInfo_fsType_set(), _wrap_VFSInfo_mediaType_get(), _wrap_VFSInfo_mediaType_set(), _wrap_VFSInfo_mountClass_get(), _wrap_VFSInfo_mountClass_set(), _wrap_VFSInfo_reserved_get(), _wrap_VFSInfo_reserved_set(), _wrap_VFSInfo_slotLibRefNum_get(), _wrap_VFSInfo_slotLibRefNum_set(), _wrap_VFSInfo_slotRefNum_get(), _wrap_VFSInfo_slotRefNum_set(), _wrap_VFSSlotMountParam_slotLibRefNum_get(), _wrap_VFSSlotMountParam_slotLibRefNum_set(), _wrap_VFSSlotMountParam_slotRefNum_get(), _wrap_VFSSlotMountParam_slotRefNum_set(), _wrap_VFSSlotMountParam_vfsMountParam_get(), _wrap_VFSSlotMountParam_vfsMountParam_set(), main(), pi_file_install(), pi_file_merge(), pi_file_retrieve(), pi_inet_accept(), pi_inet_connect(), pi_serial_accept(), pi_serial_connect(), pi_usb_connect(), pi_usb_getsockopt(), and pi_usb_setsockopt().
fmt_date()
static const char * fmt_date (const struct PalmPixHeader * h) static
{
    static char buf[24];
    sprintf (buf, "%d-%02d-%02d %02d:%02d:%02d", h->year, h->month,
        h->day, h->hour, h->min, h->sec);
    return buf;
}
References buf.
Referenced by list(), and write_ppm().
getrecord_pi_file()
static int getrecord_pi_file (struct PalmPixState * vstate, int recno, void ** buf, size_t * bufsize) static
{
    struct PalmPixState_pi_file *state =
        (struct PalmPixState_pi_file *) vstate;
    return pi_file_read_record (state->f, recno, buf, bufsize, NULL,
        NULL, NULL) < 0 ? -1 : 0;
}
References buf, pi_file_read_record(), and state.
Referenced by main().
getrecord_pi_socket()
static int getrecord_pi_socket (struct PalmPixState * vstate, int recno, void ** buf, size_t * bufsize) static
{
    static char buffer[65536];
    static pi_buffer_t fakebuf;
    struct PalmPixState_pi_socket *state =
        (struct PalmPixState_pi_socket *) vstate;
    *buf = buffer;
    fakebuf.data = buffer;
    fakebuf.allocated = 0;
    fakebuf.used = 0;
    return dlp_ReadRecordByIndex (state->sd, state->db, recno, &fakebuf,
        NULL, NULL, NULL) < 0 ? 1 : 0;
}
References buf, buffer, dlp_ReadRecordByIndex(), and state.
Referenced by main().
init_for_ppm()
void init_for_ppm (struct PalmPixState * state)
{
    state->offset_r = 0;
    state->offset_g = 1;
    state->offset_b = 2;
}
References state.
Referenced by write_all(), and write_one().
list()
static int list (const struct PalmPixHeader * h, struct PalmPixState * state, int recno, const char * ignored) static
{
    if (unpack_PalmPix (state, h, recno, pixName) != 0) {
        printf ("%d x %d\t%d\t%s\t%s\n",
            h->w, h->h, h->num, fmt_date (h), state->pixname);
        recno = state->highest_recno;
    }
    return recno;
}
References fmt_date(), state, and unpack_PalmPix().
main()
int main (int argc, const char ** argv)
{
    int     c,  /* switch */
    sd  = -1,
    output_type = PALMPIX_OUT_PPM,
    bias = 50,
    flags = 0;
    int (*action) (const struct PalmPixHeader *, struct PalmPixState *,
        int, const char *) = write_all;
    const   char *pixname   = NULL;
    const char
            *file_arg   = NULL,
            *type_str   = NULL;
    struct  PilotUser User;
    poptContext pc;
    struct poptOption options[] = {
        USERLAND_RESERVED_OPTIONS
        {"stretch", 's', POPT_ARG_VAL | POPT_ARGFLAG_OR, &flags, PALMPIX_HISTOGRAM_STRETCH, "Do a histogram stretch on the colour planes", NULL},
        {"colour", 'c', POPT_ARG_VAL | POPT_ARGFLAG_OR, &flags,  PALMPIX_COLOUR_CORRECTION, "Do a simple colour correction", NULL},
        {"type", 't', POPT_ARG_STRING, &type_str, 't', "Specify picture output type (ppm or png)", "[ppm|png]"},
        {"bias", 'b', POPT_ARG_INT,    &bias,      0 , "lighten or darken the image (0..49 darken, 51..100 lighten)", "bias"},
        {"list", 'l', POPT_ARG_NONE,   NULL,      'l', "List picture information instead of converting", NULL},
        {"name", 'n', POPT_ARG_STRING, &pixname,  'n', "Convert only <name>, and output to STDOUT as type", "name"},
        POPT_TABLEEND
    };
    pc = poptGetContext("read-palmpix", argc, argv, options, 0);
    poptSetOtherOptionHelp(pc,"[file] ...\n\n"
        "   Convert all pictures in the files given, or found via connecting to a\n"
        "   Palm handheld if no files are given, writing each to <pixname>.ppm\n\n");
    if (argc < 2) {
        poptPrintUsage(pc,stderr,0);
        return 1;
    }
    while ((c = poptGetNextOpt(pc)) >= 0) {
            switch (c) {
            /* Normally, l would be handled by popt magic, but since action
               is a _function_pointer_, not an enum or something, it needs
               special treatment. */
        case 'l':
            action = list;
            case 'n':
                action = write_one;
                break;
            case 't':
                if( !strncmp( "png", type_str, 3 )) {
#ifdef HAVE_PNG
                    output_type = PALMPIX_OUT_PNG;
#else
                    fprintf( stderr, "   ERROR: read-palmpix was built without png support\n" );
#endif
                } else if( !strncmp( "ppm", type_str, 3 )) {
                    output_type = PALMPIX_OUT_PPM;
                } else {
                    fprintf( stderr, "   ERROR: Unknown output type defaulting to ppm\n" );
                    output_type = PALMPIX_OUT_PPM;
                }
                break;
            default:
            fprintf(stderr,"   ERROR: Unhandled option %d.\n",c);
            return 1;
                }
        }
    if (c < -1) {
        plu_badoption(pc,c);
    }
    if( bias < 0 || bias > 100 ) {
        fprintf( stderr, "   ERROR: Bad bias valud %d, defaulting to 50.\n", bias );
        bias=50;
    }
    if(poptPeekArg(pc) != NULL) {
        int i = 0;
        while((file_arg = poptGetArg(pc)) != NULL) {
            struct pi_file *f = pi_file_open (file_arg);
            i++;
            if (f) {
                struct DBInfo info;
                if ((poptPeekArg(pc) != NULL || i > 1)
                    && action != write_one)
                    printf ("%s:\n", file_arg);
                pi_file_get_info (f, &info);
                if (info.flags & dlpDBFlagResource) {
                struct PalmPixState_pi_file s;
                int n = 0;
                s.state.output_type = output_type;
                pi_file_get_entries (f, &n);
                s.state.getrecord = getrecord_pi_file;
                s.f = f;
                read_db (&s.state, n, action, pixname);
                } else {
                fprintf (stderr,
                    "   ERROR: %s is not a valid record database\n",
                        file_arg);
                }
                pi_file_close (f);
            } else {
                fprintf (stderr, "   ERROR: can't open %s\n",
                    file_arg);
            }
            }
    } else  {
        int db;
        sd = plu_connect();
        if (sd < 0)
            return fail ("pi_socket");
        if (dlp_ReadUserInfo(sd, &User) < 0)
            return fail( "Read user info" );
        dlp_OpenConduit (sd);
        dlp_ReadUserInfo (sd, &User);
        if (dlp_OpenDB (sd, 0, dlpOpenRead, PalmPix_DB, &db) >= 0) {
            struct PalmPixState_pi_socket s;
            int n = 0;
            s.state.output_type = output_type;
            s.state.bias = bias;
            s.state.flags = flags;
            dlp_ReadOpenDBInfo (sd, db, &n);
            s.state.getrecord = getrecord_pi_socket;
            s.sd = sd;
            s.db = db;
            read_db (&s.state, n, action, pixname);
            dlp_CloseDB (sd, db);
            dlp_AddSyncLogEntry (sd,
                "Read PalmPix images from Palm.\n");
            User.lastSyncPC = 0x00010000;
            User.lastSyncDate = User.successfulSyncDate = time (NULL);
            dlp_WriteUserInfo (sd, &User);
        } else {
            fprintf (stderr, "   ERROR: can't open database %s\n",
                PalmPix_DB);
        }
        dlp_EndOfSync (sd, dlpEndCodeNormal);
        pi_close (sd);
    }
    return 0;
}
References PalmPixState_pi_socket::db, dlp_AddSyncLogEntry(), dlp_CloseDB(), dlp_EndOfSync(), dlp_OpenConduit(), dlp_OpenDB(), dlp_ReadOpenDBInfo(), dlp_ReadUserInfo(), dlp_WriteUserInfo(), PalmPixState_pi_file::f, fail(), flags, getrecord_pi_file(), getrecord_pi_socket(), list, options, pi_close(), pi_file_close(), pi_file_get_entries(), pi_file_get_info(), pi_file_open(), plu_badoption(), plu_connect(), read_db(), PalmPixState_pi_socket::sd, sd, PalmPixState_pi_file::state, PalmPixState_pi_socket::state, write_all(), and write_one().
read_db()
void read_db (struct PalmPixState * state, int n, int(* action)(const struct PalmPixHeader *, struct PalmPixState *, int, const char *), const char * action_arg)
{
    int i;
    for (i = 0; i < n; i++) {
        void *buffer;
        size_t bufsize;
        struct PalmPixHeader header;
        if (state->getrecord (state, i, &buffer, &bufsize) == 0
            && unpack_PalmPixHeader (&header, buffer, bufsize) != 0)
        i = action (&header, state, i, action_arg);
    }
}
References buffer, state, and unpack_PalmPixHeader().
Referenced by main().
write_all()
static int write_all (const struct PalmPixHeader * header, struct PalmPixState * state, int recno, const char * ignored) static
{
    char fname[FILENAME_MAX], ext[10];
    FILE *f;
    init_for_ppm (state);
    if (!unpack_PalmPix (state, header, recno, pixName | pixPixmap)) {
        /* bail */
        return recno;
    }
    sprintf( fname, "%s", state->pixname );
    if( state->output_type == PALMPIX_OUT_PPM )
        sprintf( ext, "_pp.ppm" );
    else if( state->output_type == PALMPIX_OUT_PNG )
        sprintf( ext, "_pp.png" );
    if (plu_protect_files( fname, ext, sizeof(fname) ) < 1) {
        return recno;
    }
    printf ("Generating %s...\n", fname);
    f = fopen (fname, "wb");
    if (f) {
                struct  utimbuf timep   ;
                struct  tm      timeptr ;
#ifdef HAVE_PNG
        if( state->output_type == PALMPIX_OUT_PPM )
            write_ppm(f, state, header);
        else if( state->output_type == PALMPIX_OUT_PNG )
            write_png(f, state, header);
#else
            write_ppm (f, state, header);
#endif
            fclose (f);
                        /* Keep file date the same date as the photo */
                        timeptr.tm_year = header->year - 1900;
                        timeptr.tm_mon  = header->month -1;
                        timeptr.tm_mday = header->day;
                        timeptr.tm_hour = header->hour;
                        timeptr.tm_min  = header->min;
                        timeptr.tm_sec  = header->sec;
                        timep.actime    = timep.modtime = mktime(&timeptr);
                        utime (fname,&timep);
    } else {
        fprintf (stderr, "%s: can't write to %s\n",
            progname, fname);
    }
        free_PalmPix_data (state);
        recno = state->highest_recno;
    return recno;
}
References free_PalmPix_data(), init_for_ppm(), plu_protect_files(), progname, state, unpack_PalmPix(), and write_ppm().
Referenced by main().
write_one()
static int write_one (const struct PalmPixHeader * header, struct PalmPixState * state, int recno, const char * pixname) static
{
    if (unpack_PalmPix (state, header, recno, pixName) != 0) {
    init_for_ppm (state);
    if (strcmp (state->pixname, pixname) == 0
        && unpack_PalmPix (state, header, recno,
        pixName | pixPixmap) != 0) {
#ifdef HAVE_PNG
        if( state->output_type == PALMPIX_OUT_PPM )
            write_ppm( stdout, state, header);
        else if( state->output_type == PALMPIX_OUT_PNG )
            write_png( stdout, state, header);
#else
        write_ppm (stdout, state, header);
#endif
        free_PalmPix_data (state);
        }
        recno = state->highest_recno;
    }
    return recno;
}
References free_PalmPix_data(), init_for_ppm(), state, unpack_PalmPix(), and write_ppm().
Referenced by main().
write_ppm()
void write_ppm (FILE * f, const struct PalmPixState * state, const struct PalmPixHeader * header)
{
    fprintf (f, "P6\n# %s (taken at %s)\n%d %d\n255\n",
        state->pixname, fmt_date (header), header->w, header->h);
    fwrite (state->pixmap, header->w * header->h * 3, 1, f);
}
References fmt_date(), and state.
Referenced by write_all(), and write_one().
Variable Documentation
progname
const char* progname
Referenced by write_all().