pilot-link: src/pilot-read-notepad.c File Reference
pilot-read-notepad.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "pi-source.h"
#include "pi-notepad.h"
#include "pi-file.h"
#include "pi-header.h"
#include "pi-userland.h"
Functions
static const char * fmt_date (noteDate_t d)
int main (int argc, const char *argv[])
void output_picture (int type, struct NotePad n)
void print_note_info (struct NotePad n, struct NotePadAppInfo nai, int category)
void write_png_v2 (FILE *f, struct NotePad *n)
void write_ppm (FILE *f, struct NotePad *n)
Variables
const char * progname
Function Documentation
fmt_date()
static const char * fmt_date (noteDate_t d) static
{
   static char buf[24];
   sprintf (buf, "%d-%02d-%02d %02d:%02d:%02d",
        d.year, d.month, d.day, d.hour, d.min, d.sec);
   return buf;
}
References buf.
Referenced by print_note_info(), and write_ppm().
main()
int main (int argc, const char * argv[])
{
   int  c,  /* switch */
     db,
     i,
     sd = -1,
     action     = NOTEPAD_ACTION_OUTPUT;
   int type = NOTE_OUT_PPM;
   const char
    *typename   =
#ifdef HAVE_PNG
    "png"
#else
    "ppm"
#endif
    ;
   struct   PilotUser User;
   struct   NotePadAppInfo nai;
   pi_buffer_t *buffer;
   poptContext pc;
   struct poptOption options[] = {
    USERLAND_RESERVED_OPTIONS
        {"list", 'l', POPT_ARG_VAL, &action, NOTEPAD_ACTION_LIST, "List Notes on device", NULL},
        {"type", 't', POPT_ARG_STRING, &typename, 0, "Specify picture output type, either \"ppm\" or \"png\"", "type"},
        POPT_TABLEEND
   };
    pc = poptGetContext("read-notepad", argc, argv, options, 0);
    poptSetOtherOptionHelp(pc,"\n\n"
        "   Copy or list your NotePad database.\n\n");
    if (argc<2) {
        poptPrintUsage(pc,stderr,0);
        return 1;
    }
    while ((c = poptGetNextOpt(pc)) >= 0) {
        fprintf(stderr,"   ERROR: Unhandled option %d.\n",c);
        return 1;
    }
    if (c < -1) {
        plu_badoption(pc,c);
    }
    if( !strncmp( "png", typename, 3 ))
    {
#ifdef HAVE_PNG
        type = NOTE_OUT_PNG;
#else
        fprintf( stderr, "   WARNING: read-notepad was built without png support,\n"
            "            using ppm instead.\n" );
        type = NOTE_OUT_PPM;
#endif
    }
    else if( !strncmp( "ppm", typename, 3 ))
    {
        type = NOTE_OUT_PPM;
    }
    else
    {
        fprintf( stderr, "   WARNING: Unknown output type defaulting to ppm\n" );
        type = NOTE_OUT_PPM;
    }
    sd = plu_connect();
   if( sd < 0 )
     goto error;
   if (dlp_ReadUserInfo(sd, &User) < 0)
     goto error_close;
   /* Open the NotePad database, store access handle in db */
   if( dlp_OpenDB(sd, 0, 0x80 | 0x40, "npadDB", &db ) < 0)
     {
    fprintf(stderr,"   ERROR: Unable to open NotePadDB on Palm.\n");
    dlp_AddSyncLogEntry(sd, "Unable to open NotePadDB.\n");
    exit(EXIT_FAILURE);
     }
   buffer = pi_buffer_new (0xffff);
   dlp_ReadAppBlock(sd, db, 0, 0xffff, buffer);
   unpack_NotePadAppInfo( &nai, buffer->data, buffer->used);
   for (i = 0;; i++)
     {
    int     attr,
        category,
        len = 0;
    struct  NotePad n;
    if( sd )
      {
         len = dlp_ReadRecordByIndex(sd, db, i, buffer, 0,
                       &attr, &category);
         if (len < 0)
           break;
      }
    else
        pi_buffer_clear(buffer);
    /* Skip deleted records */
    if ((attr & dlpRecAttrDeleted) || (attr & dlpRecAttrArchived))
      continue;
    unpack_NotePad( &n, buffer->data, buffer->used);
    switch( action )
      {
       case NOTEPAD_ACTION_LIST:
         print_note_info( n, nai, category );
         printf( "\n" );
         break;
       case NOTEPAD_ACTION_OUTPUT:
         if (!plu_quiet) {
            print_note_info( n, nai, category );
         }
         output_picture( type, n );
         if (!plu_quiet) {
            printf( "\n" );
         }
         break;
      }
     }
   if( sd ) {
    /* Close the database */
    dlp_CloseDB( sd, db );
    dlp_AddSyncLogEntry( sd, "Successfully read NotePad from Palm.\n\n"
                "Thank you for using pilot-link.");
    dlp_EndOfSync( sd, 0 );
    pi_close(sd);
     }
   pi_buffer_free (buffer);
   return 0;
error_close:
    pi_close(sd);
error:
    return -1;
}
References buffer, dlp_AddSyncLogEntry(), dlp_CloseDB(), dlp_EndOfSync(), dlp_OpenDB(), dlp_ReadAppBlock(), dlp_ReadRecordByIndex(), dlp_ReadUserInfo(), options, output_picture(), pi_buffer_clear(), pi_buffer_free(), pi_buffer_new(), pi_close(), plu_badoption(), plu_connect(), plu_quiet, print_note_info(), sd, unpack_NotePad(), and unpack_NotePadAppInfo().
output_picture()
void output_picture (int type, struct NotePad n)
{
   char fname[FILENAME_MAX];
   FILE *f;
   char extension[8];
   static int i = 1;
   if( n.body.dataType == NOTEPAD_DATA_PNG )
     type = NOTE_OUT_PNG;
   if( n.flags & NOTEPAD_FLAG_NAME )
     {
    if( type == NOTE_OUT_PNG )
      sprintf( extension, ".png" );
    else if( type == NOTE_OUT_PPM )
      sprintf( extension, ".ppm" );
    sprintf( fname, "%s", n.name );
     }
   else
     {
    if( type == NOTE_OUT_PNG )
      sprintf( extension, "_np.png" );
    else if( type == NOTE_OUT_PPM )
      sprintf( extension, "_np.ppm" );
    sprintf( fname, "%4.4d", i++ );
     }
    if (plu_protect_files( fname, extension, sizeof(fname) ) < 1) {
        goto cleanup;
    }
   printf ("Generating %s...\n", fname);
   f = fopen (fname, "wb");
   if( f )
     {
    switch( n.body.dataType )
      {
       case NOTEPAD_DATA_PNG:
         fprintf( stderr, "Notepad data version 2 defaulting to png output.\n" );
         write_png_v2( f, &n );
         break;
       case NOTEPAD_DATA_BITS:
       case NOTEPAD_DATA_UNCOMPRESSED:
         switch( type )
           {
        case NOTE_OUT_PPM:
          write_ppm( f, &n );
          break;
        case NOTE_OUT_PNG:
#ifdef HAVE_PNG
          write_png( f, &n );
#else
          fprintf( stderr, "read-notepad was built without png support\n" );
#endif
          break;
           }
         break;
       default:
         fprintf( stderr, "Picture version is unknown - unable to convert\n" );
      }
    fclose (f);
     }
    else {
        fprintf (stderr, "Can't write to %s\n", fname);
    }
cleanup:
    free_NotePad( &n );
}
References free_NotePad(), plu_protect_files(), write_png_v2(), and write_ppm().
Referenced by main().
print_note_info()
void print_note_info (struct NotePad n, struct NotePadAppInfo nai, int category)
{
   if( n.flags & NOTEPAD_FLAG_NAME )
     printf( "Name: %s\n", n.name );
   printf( "Category: %s\n", nai.category.name[category] );
   printf( "Created: %s\n", fmt_date( n.createDate ));
   printf( "Changed: %s\n", fmt_date( n.changeDate ));
   if( n.flags & NOTEPAD_FLAG_ALARM )
     printf( "Alarm set for: %s\n", fmt_date( n.alarmDate ));
   else
     printf( "Alarm set for: none\n" );
   printf( "Picture: " );
   if( n.flags & NOTEPAD_FLAG_BODY )
     printf( "yes\n" );
   else
     printf( "no\n" );
   printf( "Picture version: %ld\n", n.body.dataType );
}
References fmt_date().
Referenced by main().
write_png_v2()
void write_png_v2 (FILE * f, struct NotePad * n)
{
   if( n->body.dataType != NOTEPAD_DATA_PNG )
     {
    fprintf( stderr, "Bad data Type" );
    return;
     }
   fwrite( n->data, n->body.dataLen, 1, f );
   fflush( f );
}
Referenced by output_picture().
write_ppm()
void write_ppm (FILE * f, struct NotePad * n)
{
   int i,j,k,datapoints = 0;
   unsigned long black = 0;
   unsigned long white = 0xFFFFFFFF;
   fprintf( f, "P6\n# " );
   if( n->name != NULL )
     fprintf( f, "%s (created on %s)\n", n->name, fmt_date( n->createDate ));
   else
     fprintf( f, "%s\n", fmt_date( n->createDate ));
   /* NotePad says that the width is only 152 but it encodes 160 bits */
   /* of data! - AA */
   fprintf( f, "%ld %ld\n255\n",
        n->body.width+8, n->body.height );
   if( n->body.dataType == NOTEPAD_DATA_BITS )
     for( i=0; i<n->body.dataLen/2; i++ )
       {
      datapoints += n->data[i].repeat;
      for( j=0; j<n->data[i].repeat; j++ )
        {
           for( k=0; k<8; k++ )
         {
            if( n->data[i].data & 1<<(7-k) )
              fwrite( &black, 3, 1, f );
            else
              fwrite( &white, 3, 1, f );
         }
        }
       }
   else
     for( i=0; i<n->body.dataLen/2; i++ )
       {
      for( k=0; k<8; k++ )
        {
           if( n->data[i].repeat & 1<<(7-k) )
         fwrite( &black, 3, 1, f );
           else
         fwrite( &white, 3, 1, f );
        }
      for( k=0; k<8; k++ )
        {
           if( n->data[i].data & 1<<(7-k) )
         fwrite( &black, 3, 1, f );
           else
         fwrite( &white, 3, 1, f );
        }
       }
}
References fmt_date().
Referenced by output_picture().
Variable Documentation
progname
const char* progname
Referenced by main(), print_splash(), write_memo_in_directory(), and WritePicture().