pilot-link: libpisock/socket.c File Reference
socket.c File Reference
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <fcntl.h>
#include <string.h>
#include "pi-source.h"
#include "pi-serial.h"
#include "pi-bluetooth.h"
#include "pi-inet.h"
#include "pi-slp.h"
#include "pi-sys.h"
#include "pi-padp.h"
#include "pi-cmp.h"
#include "pi-net.h"
#include "pi-dlp.h"
#include "pi-syspkt.h"
#include "pi-debug.h"
#include "pi-error.h"
#include "pi-threadsafe.h"
Functions
static void env_dbgcheck (void)
pi_socket_t * find_pi_socket (int pi_sd)
static void installexit (void)
static int is_connected (pi_socket_t *ps)
static int is_listener (pi_socket_t *ps)
static RETSIGTYPE onalarm (int signo)
static void onexit (void)
int pi_accept (int pi_sd, struct sockaddr *addr, size_t *addrlen)
int pi_accept_to (int pi_sd, struct sockaddr *addr, size_t *addrlen, int timeout)
int pi_bind (int pi_sd, const char *port)
int pi_close (int pi_sd)
int pi_connect (int pi_sd, const char *port)
static pi_socket_t * pi_devsocket (int pi_sd, const char *port, struct pi_sockaddr *addr)
int pi_error (int pi_sd)
void pi_flush (int pi_sd, int flags)
int pi_getsockname (int pi_sd, struct sockaddr *addr, size_t *namelen)
int pi_getsockopt (int pi_sd, int level, int option_name, void *option_value, size_t *option_len)
int pi_getsockpeer (int pi_sd, struct sockaddr *addr, size_t *namelen)
int pi_listen (int pi_sd, int backlog)
unsigned long pi_maxrecsize (int pi_sd)
static PI_MUTEX_DEFINE (psl_mutex)
static PI_MUTEX_DEFINE (watch_list_mutex)
int pi_palmos_error (int pi_sd)
pi_protocol_t * pi_protocol (int pi_sd, int level)
pi_protocol_t * pi_protocol_next (int pi_sd, int level)
ssize_t pi_read (int pi_sd, pi_buffer_t *msg, size_t len)
ssize_t pi_recv (int pi_sd, pi_buffer_t *msg, size_t len, int flags)
void pi_reset_errors (int pi_sd)
int pi_send (int pi_sd, const void *msg, size_t len, int flags)
int pi_set_error (int pi_sd, int error_code)
int pi_set_palmos_error (int pi_sd, int error_code)
int pi_setsockopt (int pi_sd, int level, int option_name, const void *option_value, size_t *option_len)
int pi_socket (int domain, int type, int protocol)
int pi_socket_connected (int pi_sd)
int pi_socket_init (pi_socket_t *ps)
pi_socket_list_t * pi_socket_recognize (pi_socket_t *ps)
int pi_socket_setsd (pi_socket_t *ps, int pi_sd)
int pi_tickle (int pi_sd)
int pi_version (int pi_sd)
int pi_watchdog (int pi_sd, int newinterval)
ssize_t pi_write (int pi_sd, const void *msg, size_t len)
static void protocol_cmd_queue_add (pi_socket_t *ps, pi_protocol_t *prot)
static void protocol_queue_add (pi_socket_t *ps, pi_protocol_t *prot)
static void protocol_queue_build (pi_socket_t *ps, int autodetect)
static void protocol_queue_destroy (pi_socket_t *ps)
static pi_protocol_t * protocol_queue_find (pi_socket_t *ps, int level)
static pi_protocol_t * protocol_queue_find_next (pi_socket_t *ps, int level)
static pi_socket_list_t * ps_list_append (pi_socket_list_t *list, pi_socket_t *ps)
static pi_socket_list_t * ps_list_copy (pi_socket_list_t *list)
static pi_socket_t * ps_list_find (pi_socket_list_t *list, int pi_sd)
static void ps_list_free (pi_socket_list_t *list)
static pi_socket_list_t * ps_list_remove (pi_socket_list_t *list, int pi_sd)
Variables
static unsigned int interval = 0
int pi_sock_installedexit = 0
static pi_socket_list_t * psl = NULL
static pi_socket_list_t * watch_list = NULL
Function Documentation
env_dbgcheck()
static void env_dbgcheck (void) static
{
    if (getenv("PILOT_DEBUG")) {
        int     types = 0,
            done;
        char    *debug,
            *b,
            *e;
        debug = strdup(getenv("PILOT_DEBUG"));
        b   = debug;
        done    = 0;
        while (!done) {
            e = strchr(b, ' ');
            if (e)
                *e = '\0';
            else
                done = 1;
            if (!strcmp(b, "SYS"))
                types |= PI_DBG_SYS;
            else if (!strcmp(b, "DEV"))
                types |= PI_DBG_DEV;
            else if (!strcmp(b, "SLP"))
                types |= PI_DBG_SLP;
            else if (!strcmp(b, "PADP"))
                types |= PI_DBG_PADP;
            else if (!strcmp(b, "DLP"))
                types |= PI_DBG_DLP;
            else if (!strcmp(b, "NET"))
                types |= PI_DBG_NET;
            else if (!strcmp(b, "CMP"))
                types |= PI_DBG_CMP;
            else if (!strcmp(b, "SOCK"))
                types |= PI_DBG_SOCK;
            else if (!strcmp(b, "API"))
                types |= PI_DBG_API;
            else if (!strcmp(b, "USER"))
                types |= PI_DBG_USER;
            else if (!strcmp(b, "ALL"))
                types |= PI_DBG_ALL;
            e++;
            b = e;
        }
        pi_debug_set_types(types);
        free(debug);
    }
    /* PILOT Debug Level */
    if (getenv("PILOT_DEBUG_LEVEL")) {
        int     level = 0;
        const char *debug;
        debug = getenv("PILOT_DEBUG_LEVEL");
        if (!strcmp(debug, "NONE"))
            level |= PI_DBG_LVL_NONE;
        else if (!strcmp(debug, "ERR"))
            level |= PI_DBG_LVL_ERR;
        else if (!strcmp(debug, "WARN"))
            level |= PI_DBG_LVL_WARN;
        else if (!strcmp(debug, "INFO"))
            level |= PI_DBG_LVL_INFO;
        else if (!strcmp(debug, "DEBUG"))
            level |= PI_DBG_LVL_DEBUG;
        pi_debug_set_level (level);
    }
    /* log file name */
    if (getenv("PILOT_LOG") && atoi(getenv("PILOT_LOG"))) {
        const char *logfile;
        logfile = getenv("PILOT_LOGFILE");
        if (logfile == NULL)
            pi_debug_set_file("pilot-link.debug");
        else
            pi_debug_set_file(logfile);
    }
}
References done, pi_debug_set_file(), pi_debug_set_level(), pi_debug_set_types(), and strdup().
Referenced by pi_socket().
find_pi_socket()
pi_socket_t * find_pi_socket (int pi_sd)
{
    pi_socket_t *result;
    pi_mutex_lock(&psl_mutex);
    result = ps_list_find (psl, pi_sd);
    pi_mutex_unlock(&psl_mutex);
    return result;
}
References pi_mutex_lock(), pi_mutex_unlock(), ps_list_find(), and psl.
Referenced by dlp_AbortSync(), dlp_EndOfSync(), dlp_ReadNextRecInCategory(), dlp_ReadSysInfo(), dlp_ResetDBIndex(), main(), pi_accept_to(), pi_close(), pi_devsocket(), pi_error(), pi_flush(), pi_getsockname(), pi_getsockopt(), pi_getsockpeer(), pi_listen(), pi_maxrecsize(), pi_palmos_error(), pi_protocol(), pi_protocol_next(), pi_recv(), pi_reset_errors(), pi_send(), pi_set_error(), pi_set_palmos_error(), pi_setsockopt(), pi_socket_connected(), pi_tickle(), pi_version(), and pi_watchdog().
installexit()
static void installexit (void) static
{
    if (!pi_sock_installedexit) {
        atexit(onexit);
        pi_sock_installedexit = 1;
    }
}
References onexit(), and pi_sock_installedexit.
Referenced by pi_socket().
is_connected()
static int is_connected (pi_socket_t * ps) static
{
    return (ps->state == PI_SOCK_CONN_INIT || ps->state == PI_SOCK_CONN_ACCEPT) ? 1 : 0;
}
Referenced by onalarm(), pi_close(), pi_flush(), pi_recv(), pi_send(), pi_socket_connected(), and pi_tickle().
is_listener()
static int is_listener (pi_socket_t * ps) static
{
    return (ps->state == PI_SOCK_LISTEN) ? 1 : 0;
}
Referenced by pi_accept_to().
onalarm()
static RETSIGTYPE onalarm (int signo) static
{
    pi_socket_list_t *l;
    signal(signo, onalarm);
    pi_mutex_lock(&watch_list_mutex);
    for (l = watch_list; l != NULL; l = l->next) {
        pi_socket_t *ps = l->ps;
        if (!is_connected(ps))
            continue;
        if (pi_tickle(ps->sd) < 0) {
            LOG((PI_DBG_SOCK, PI_DBG_LVL_INFO,
                "SOCKET Socket %d is busy during tickle\n",
                ps->sd));
            alarm(1);
        } else {
            LOG((PI_DBG_SOCK, PI_DBG_LVL_INFO,
                "SOCKET Tickling socket %d\n", ps->sd));
            alarm(interval);
        }
    }
    pi_mutex_unlock(&watch_list_mutex);
}
References interval, is_connected(), onalarm(), pi_mutex_lock(), pi_mutex_unlock(), pi_tickle(), and watch_list.
Referenced by onalarm(), and pi_watchdog().
onexit()
static void onexit (void) static
{
    pi_socket_list_t *l,
             *list;
    pi_mutex_lock(&psl_mutex);
    list = ps_list_copy (psl);
    pi_mutex_unlock(&psl_mutex);
    for (l = list; l != NULL; l = l->next)
        pi_close(l->ps->sd);
    ps_list_free (list);
}
References list, pi_close(), pi_mutex_lock(), pi_mutex_unlock(), ps_list_copy(), ps_list_free(), and psl.
Referenced by installexit().
pi_accept()
int pi_accept (int pi_sd, struct sockaddr * addr, size_t * addrlen)
{
    return pi_accept_to(pi_sd, addr, addrlen, 0);
}
References pi_accept_to().
Referenced by _wrap_pi_accept(), pilot_connect(), and PisockAccept().
pi_accept_to()
int pi_accept_to (int pi_sd, struct sockaddr * addr, size_t * addrlen, int timeout)
{
    pi_socket_t *ps;
    int result;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (!is_listener (ps))
        return PI_ERR_SOCK_LISTENER;
    ps->accept_to = timeout;
    result = ps->device->accept(ps, addr, addrlen);
    if (result < 0) {
        LOG((PI_DBG_SOCK, PI_DBG_LVL_DEBUG,
            "pi_accept_to: ps->device->accept returned %d, calling pi_close()\n",
            result));
        pi_close(pi_sd);
    }
    return result;
}
References find_pi_socket(), is_listener(), and pi_close().
Referenced by _wrap_pi_accept_to(), pi_accept(), pilot_connect(), and plu_connect().
pi_bind()
int pi_bind (int pi_sd, const char * port)
{
    int bind_return;
    pi_socket_t *ps;
    struct  pi_sockaddr addr;
    ps = pi_devsocket(pi_sd, port, &addr);
    if (!ps)
        return PI_ERR_SOCK_INVALID;
    bind_return =
        ps->device->bind (ps, (struct sockaddr *)&addr, sizeof(addr));
    if (bind_return < 0) {
        ps->device->free (ps->device);
        ps->device = NULL;
    }
    return bind_return;
}
References pi_devsocket(), and port.
Referenced by _wrap_pi_bind(), pilot_connect(), pilot_connect(), plu_connect(), and proc_port().
pi_close()
int pi_close (int pi_sd)
{
    int         result = 0;
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (ps->type == PI_SOCK_STREAM && ps->cmd != PI_CMD_SYS) {
        if (is_connected (ps)) {
                ps->command = 1;
                /* then end sync, with clean status */
                result = dlp_EndOfSync(ps->sd, 0);
                ps->command = 0;
        }
    }
    if (result == 0) {
        /* we need to remove the entry from the list prior to
         * closing it, because closing it will reset the pi_sd */
        pi_mutex_lock(&psl_mutex);
        psl = ps_list_remove (psl, pi_sd);
        pi_mutex_unlock(&psl_mutex);
        pi_mutex_lock(&watch_list_mutex);
        watch_list = ps_list_remove (watch_list, pi_sd);
        pi_mutex_unlock(&watch_list_mutex);
        if (ps->device != NULL)
            result = ps->device->close (ps);
        protocol_queue_destroy(ps);
        if (ps->device != NULL)
            ps->device->free(ps->device);
        if (ps->sd > 0)
            close(ps->sd);
        free(ps);
    }
    return result;
}
References dlp_EndOfSync(), find_pi_socket(), is_connected(), pi_mutex_lock(), pi_mutex_unlock(), protocol_queue_destroy(), ps_list_remove(), psl, and watch_list.
Referenced by _wrap_pi_close(), do_fetch(), exit_fn(), handle_single_command(), Java_org_gnu_pilotlink_PilotLink_close(), main(), main(), main(), onexit(), pi_accept_to(), pi_bluetooth_connect(), pi_connect(), pilot_connect(), pilot_connect(), PisockCloseProc(), plu_connect(), proc_port(), and reopen_fn().
pi_connect()
int pi_connect (int pi_sd, const char * port)
{
    pi_socket_t *ps;
    struct  pi_sockaddr addr;
    int result;
    ps = pi_devsocket(pi_sd, port, &addr);
    if (!ps)
        return PI_ERR_SOCK_INVALID;
    /* Build the protocol queue */
    protocol_queue_build (ps, 0);
    result = ps->device->connect (ps, (struct sockaddr *)&addr, sizeof(addr));
    if (result < 0)
        pi_close(pi_sd);
    return result;
}
References pi_close(), pi_devsocket(), port, and protocol_queue_build().
Referenced by _wrap_pi_connect(), main(), and main().
pi_devsocket()
static pi_socket_t * pi_devsocket (int pi_sd, const char * port, struct pi_sockaddr * addr) static
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return NULL;
    }
    if (port == NULL && (port = getenv("PILOTPORT")) == NULL) {
        errno = ENXIO;
        return NULL;
    }
    /* Create the device and sockaddr */
    addr->pi_family = PI_AF_PILOT;
    if (!strncmp (port, "serial:", 7)) {
        strncpy(addr->pi_device, port + 7, sizeof(addr->pi_device));
        ps->device = pi_serial_device (PI_SERIAL_DEV);
#ifdef HAVE_USB
    } else if (!strncmp (port, "usb:", 4)) {
        strncpy(addr->pi_device, port + 4, sizeof(addr->pi_device));
        ps->device = pi_usb_device (PI_USB_DEV);
#endif
    } else if (!strncmp (port, "net:", 4)) {
        strncpy(addr->pi_device, port + 4, sizeof(addr->pi_device));
        ps->device = pi_inet_device (PI_NET_DEV);
#ifdef HAVE_BLUEZ
    } else if (!strncmp (port, "bluetooth:", 10) || !strncmp (port, "bt:", 3)) {
        strncpy(addr->pi_device, strchr(port, ':') + 1, sizeof(addr->pi_device));
        ps->device = pi_bluetooth_device (PI_BLUETOOTH_DEV);
#endif
    } else {
        /* No prefix assumed to be serial: (for compatibility) */
        strncpy(addr->pi_device, port, sizeof(addr->pi_device));
        ps->device = pi_serial_device (PI_SERIAL_DEV);
    }
    return ps;
}
References find_pi_socket(), pi_bluetooth_device(), pi_inet_device(), pi_serial_device(), pi_usb_device(), and port.
Referenced by pi_bind(), and pi_connect().
pi_error()
int pi_error (int pi_sd)
{
    pi_socket_t *ps;
    if ((ps = find_pi_socket(pi_sd)) == NULL) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    return ps->last_error;
}
References find_pi_socket().
Referenced by _wrap_pi_error(), dlp_ReadAppPreference(), dlp_WriteAppPreference(), palm_install_internal(), pi_file_install(), pi_file_merge(), pi_file_retrieve(), and RPC().
pi_flush()
void pi_flush (int pi_sd, int flags)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return;
    }
    if (!is_connected (ps))
        return;
    ps->protocol_queue[0]->flush (ps, flags);
}
References find_pi_socket(), flags, and is_connected().
Referenced by _wrap_pi_flush(), dlp_request_write(), and padp_tx().
pi_getsockname()
int pi_getsockname (int pi_sd, struct sockaddr * addr, size_t * namelen)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (*namelen > ps->laddrlen)
        *namelen = ps->laddrlen;
    memcpy(addr, &ps->laddr, *namelen);
    return 0;
}
References find_pi_socket().
Referenced by _wrap_pi_getsockname().
pi_getsockopt()
int pi_getsockopt (int pi_sd, int level, int option_name, void * option_value, size_t * option_len)
{
    pi_socket_t *ps;
    pi_protocol_t *prot;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    /* handle getsockopt at socket level */
    if (level == PI_LEVEL_SOCK) {
        switch (option_name) {
            case PI_SOCK_STATE:
                if (*option_len != sizeof (ps->state))
                    goto argerr;
                memcpy (option_value, &ps->state, sizeof (ps->state));
                break;
            case PI_SOCK_HONOR_RX_TIMEOUT:
                if (*option_len != sizeof (ps->honor_rx_to))
                    goto argerr;
                memcpy (option_value, &ps->honor_rx_to, sizeof (ps->honor_rx_to));
                break;
            default:
                goto argerr;
        }
        return 0;
    }
    /* find the protocol at the requested level and forward it the getsockopt request */
    prot = protocol_queue_find (ps, level);
    if (prot == NULL || prot->level != level) {
        errno = EINVAL;
        return pi_set_error(pi_sd, PI_ERR_SOCK_INVALID);
    }
    return prot->getsockopt (ps, level, option_name, option_value, option_len);
argerr:
    errno = EINVAL;
    return pi_set_error(pi_sd, PI_ERR_GENERIC_ARGUMENT);
}
References find_pi_socket(), pi_set_error(), and protocol_queue_find().
Referenced by _wrap_pi_getsockopt(), dlp_CallApplication(), net_rx(), padp_rx(), padp_tx(), pi_inet_accept(), pi_serial_accept(), pi_serial_connect(), pi_tickle(), pi_usb_accept(), pi_usb_connect(), and pi_version().
pi_getsockpeer()
int pi_getsockpeer (int pi_sd, struct sockaddr * addr, size_t * namelen)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (*namelen > ps->raddrlen)
        *namelen = ps->raddrlen;
    memcpy(addr, &ps->raddr, *namelen);
    return 0;
}
References find_pi_socket().
Referenced by _wrap_pi_getsockpeer().
pi_listen()
int pi_listen (int pi_sd, int backlog)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    return ps->device->listen (ps, backlog);
}
References find_pi_socket().
Referenced by _wrap_pi_listen(), CreateSocket(), pilot_connect(), pilot_connect(), and plu_connect().
pi_maxrecsize()
unsigned long pi_maxrecsize (int pi_sd)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return 0;
    }
    /* pi_version will read necessary info from device */
    if (pi_version(pi_sd) == 0)
        return DLP_BUF_SIZE;
    return ps->maxrecsize;
}
References find_pi_socket(), and pi_version().
Referenced by _wrap_pi_maxrecsize(), dlp_ReadRecordById(), dlp_ReadRecordByIndex(), dlp_ReadResourceByIndex(), dlp_ReadResourceByType(), pi_file_install(), and pi_file_merge().
PI_MUTEX_DEFINE() [1/2]
static PI_MUTEX_DEFINE (psl_mutex) static
PI_MUTEX_DEFINE() [2/2]
static PI_MUTEX_DEFINE (watch_list_mutex) static
pi_palmos_error()
int pi_palmos_error (int pi_sd)
{
    pi_socket_t *ps;
    if ((ps = find_pi_socket(pi_sd)) == NULL) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    return ps->palmos_error;
}
References find_pi_socket().
Referenced by _wrap_pi_palmos_error(), dlp_ReadAppPreference(), dlp_VFSFileWrite(), dlp_WriteAppPreference(), ls_fn(), palm_install_internal(), pi_file_install(), pi_file_merge(), pi_file_retrieve(), pythonWrapper_handlePiErr(), and rm_fn().
pi_protocol()
pi_protocol_t * pi_protocol (int pi_sd, int level)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return NULL;
    }
    return protocol_queue_find(ps, level);
}
References find_pi_socket(), and protocol_queue_find().
Referenced by _wrap_pi_protocol(), _wrap_pi_protocol_next(), _wrap_pi_socket_t_cmd_queue_get(), _wrap_pi_socket_t_cmd_queue_set(), _wrap_pi_socket_t_protocol_queue_get(), _wrap_pi_socket_t_protocol_queue_set(), cmp_abort(), cmp_flush(), cmp_getsockopt(), cmp_init(), cmp_rx(), cmp_rx_handshake(), cmp_setsockopt(), cmp_tx(), cmp_tx_handshake(), cmp_wakeup(), net_flush(), net_getsockopt(), net_rx(), net_setsockopt(), net_tx(), padp_flush(), padp_getsockopt(), padp_rx(), padp_sendack(), padp_setsockopt(), padp_tx(), slp_flush(), slp_getsockopt(), slp_rx(), slp_setsockopt(), slp_tx(), sys_flush(), sys_rx(), and sys_tx().
pi_protocol_next()
pi_protocol_t * pi_protocol_next (int pi_sd, int level)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return NULL;
    }
    return protocol_queue_find_next(ps, level);
}
References find_pi_socket(), and protocol_queue_find_next().
Referenced by _wrap_pi_protocol_next(), cmp_flush(), cmp_rx(), cmp_tx(), net_flush(), net_rx(), net_tx(), padp_flush(), padp_rx(), padp_sendack(), padp_tx(), slp_flush(), slp_rx(), slp_tx(), sys_flush(), sys_rx(), and sys_tx().
pi_read()
ssize_t pi_read (int pi_sd, pi_buffer_t * msg, size_t len)
{
    return pi_recv(pi_sd, msg, len, 0);
}
References pi_recv().
Referenced by _wrap_pi_read(), dlp_response_read(), dlp_VFSFileRead(), main(), Read_Pilot(), read_pilot(), sys_Find(), sys_GetTrapBreaks(), sys_ReadMemory(), sys_RPC(), sys_SetBreakpoints(), sys_SetTrapBreaks(), sys_ToggleDbgBreaks(), and sys_WriteMemory().
pi_recv()
ssize_t pi_recv (int pi_sd, pi_buffer_t * msg, size_t len, int flags)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (!is_connected (ps))
        return PI_ERR_SOCK_DISCONNECTED;
    return ps->protocol_queue[0]->read (ps, msg, len, flags);
}
References find_pi_socket(), flags, and is_connected().
Referenced by _wrap_pi_recv(), pi_read(), and PisockInputProc().
pi_reset_errors()
void pi_reset_errors (int pi_sd)
{
    pi_socket_t *ps;
    if ((ps = find_pi_socket(pi_sd))) {
        ps->last_error = 0;
        ps->palmos_error = 0;
    } else
        errno = ESRCH;
}
References find_pi_socket().
Referenced by _wrap_pi_reset_errors(), dlp_AbortSync(), dlp_AddSyncLogEntry(), dlp_CallApplication(), dlp_CleanUpDatabase(), dlp_CloseDB(), dlp_CloseDB_All(), dlp_CreateDB(), dlp_DeleteCategory(), dlp_DeleteDB(), dlp_DeleteRecord(), dlp_DeleteResource(), dlp_EndOfSync(), dlp_ExpCardInfo(), dlp_ExpCardPresent(), dlp_ExpSlotEnumerate(), dlp_ExpSlotMediaType(), dlp_FindDBByName(), dlp_FindDBByOpenHandle(), dlp_FindDBByTypeCreator(), dlp_FindDBInfo(), dlp_GetROMToken(), dlp_GetSysDateTime(), dlp_MoveCategory(), dlp_OpenConduit(), dlp_OpenDB(), dlp_ReadAppBlock(), dlp_ReadAppPreference(), dlp_ReadDBList(), dlp_ReadNetSyncInfo(), dlp_ReadNextModifiedRec(), dlp_ReadNextModifiedRecInCategory(), dlp_ReadNextRecInCategory(), dlp_ReadOpenDBInfo(), dlp_ReadRecordById(), dlp_ReadRecordByIndex(), dlp_ReadRecordIDList(), dlp_ReadResourceByIndex(), dlp_ReadResourceByType(), dlp_ReadSortBlock(), dlp_ReadStorageInfo(), dlp_ReadSysInfo(), dlp_ReadUserInfo(), dlp_ResetDBIndex(), dlp_ResetSyncFlags(), dlp_ResetSystem(), dlp_SetDBInfo(), dlp_SetSysDateTime(), dlp_VFSDirCreate(), dlp_VFSDirEntryEnumerate(), dlp_VFSExportDatabaseToFile(), dlp_VFSFileClose(), dlp_VFSFileCreate(), dlp_VFSFileDelete(), dlp_VFSFileEOF(), dlp_VFSFileGetAttributes(), dlp_VFSFileGetDate(), dlp_VFSFileOpen(), dlp_VFSFileRead(), dlp_VFSFileRename(), dlp_VFSFileResize(), dlp_VFSFileSeek(), dlp_VFSFileSetAttributes(), dlp_VFSFileSetDate(), dlp_VFSFileSize(), dlp_VFSFileTell(), dlp_VFSFileWrite(), dlp_VFSGetDefaultDir(), dlp_VFSImportDatabaseFromFile(), dlp_VFSVolumeEnumerate(), dlp_VFSVolumeFormat(), dlp_VFSVolumeGetLabel(), dlp_VFSVolumeInfo(), dlp_VFSVolumeSetLabel(), dlp_VFSVolumeSize(), dlp_WriteAppBlock(), dlp_WriteAppPreference(), dlp_WriteNetSyncInfo(), dlp_WriteRecord(), dlp_WriteResource(), dlp_WriteSortBlock(), dlp_WriteUserInfo(), and pi_file_retrieve().
pi_send()
int pi_send (int pi_sd, const void * msg, size_t len, int flags)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (!is_connected (ps))
        return PI_ERR_SOCK_DISCONNECTED;
    if (interval)
        alarm(interval);
    return ps->protocol_queue[0]->write (ps, (void *)msg, len, flags);
}
References find_pi_socket(), flags, interval, and is_connected().
Referenced by _wrap_pi_send(), pi_write(), and PisockOutputProc().
pi_set_error()
int pi_set_error (int pi_sd, int error_code)
{
    pi_socket_t *ps;
    if ((ps = find_pi_socket(pi_sd)))
        ps->last_error = error_code;
    else
        errno = ESRCH;
    /* also update errno if makes sense */
    if (error_code == PI_ERR_GENERIC_MEMORY)
        errno = ENOMEM;
    return error_code;
}
References find_pi_socket().
Referenced by _wrap_pi_set_error(), cmp_abort(), cmp_flush(), cmp_getsockopt(), cmp_init(), cmp_rx(), cmp_rx_handshake(), cmp_setsockopt(), cmp_tx(), cmp_tx_handshake(), cmp_wakeup(), dlp_AddSyncLogEntry(), dlp_CallApplication(), dlp_CleanUpDatabase(), dlp_CloseDB(), dlp_CloseDB_All(), dlp_CreateDB(), dlp_DeleteCategory(), dlp_DeleteDB(), dlp_DeleteRecord(), dlp_DeleteResource(), dlp_EndOfSync(), dlp_exec(), dlp_ExpCardInfo(), dlp_ExpCardPresent(), dlp_ExpSlotEnumerate(), dlp_ExpSlotMediaType(), dlp_FindDBByName(), dlp_FindDBByOpenHandle(), dlp_FindDBByTypeCreator(), dlp_FindDBInfo(), dlp_GetSysDateTime(), dlp_MoveCategory(), dlp_OpenConduit(), dlp_OpenDB(), dlp_ReadAppBlock(), dlp_ReadAppPreference(), dlp_ReadDBList(), dlp_ReadNetSyncInfo(), dlp_ReadNextModifiedRec(), dlp_ReadNextModifiedRecInCategory(), dlp_ReadNextRecInCategory(), dlp_ReadOpenDBInfo(), dlp_ReadRecordById(), dlp_ReadRecordByIndex(), dlp_ReadRecordIDList(), dlp_ReadResourceByIndex(), dlp_ReadResourceByType(), dlp_ReadSortBlock(), dlp_ReadStorageInfo(), dlp_ReadSysInfo(), dlp_ReadUserInfo(), dlp_request_write(), dlp_ResetDBIndex(), dlp_ResetSyncFlags(), dlp_ResetSystem(), dlp_response_read(), dlp_SetDBInfo(), dlp_SetSysDateTime(), dlp_VFSDirCreate(), dlp_VFSDirEntryEnumerate(), dlp_VFSExportDatabaseToFile(), dlp_VFSFileClose(), dlp_VFSFileCreate(), dlp_VFSFileDelete(), dlp_VFSFileEOF(), dlp_VFSFileGetAttributes(), dlp_VFSFileGetDate(), dlp_VFSFileOpen(), dlp_VFSFileRead(), dlp_VFSFileRename(), dlp_VFSFileResize(), dlp_VFSFileSeek(), dlp_VFSFileSetAttributes(), dlp_VFSFileSetDate(), dlp_VFSFileSize(), dlp_VFSFileTell(), dlp_VFSFileWrite(), dlp_VFSGetDefaultDir(), dlp_VFSImportDatabaseFromFile(), dlp_VFSVolumeEnumerate(), dlp_VFSVolumeFormat(), dlp_VFSVolumeGetLabel(), dlp_VFSVolumeInfo(), dlp_VFSVolumeSetLabel(), dlp_VFSVolumeSize(), dlp_WriteAppBlock(), dlp_WriteAppPreference(), dlp_WriteNetSyncInfo(), dlp_WriteRecord(), dlp_WriteResource(), dlp_WriteSortBlock(), dlp_WriteUserInfo(), net_flush(), net_getsockopt(), net_rx(), net_rx_handshake(), net_setsockopt(), net_tx(), net_tx_handshake(), padp_flush(), padp_getsockopt(), padp_rx(), padp_sendack(), padp_setsockopt(), padp_tx(), pi_bluetooth_accept(), pi_bluetooth_accept_rfcomm(), pi_bluetooth_bind(), pi_bluetooth_getsockopt(), pi_bluetooth_read(), pi_bluetooth_setsockopt(), pi_bluetooth_write(), pi_file_install(), pi_file_install_VFS(), pi_file_merge(), pi_file_retrieve(), pi_file_retrieve_VFS(), pi_getsockopt(), pi_inet_accept(), pi_inet_bind(), pi_inet_connect(), pi_inet_getsockopt(), pi_inet_read(), pi_inet_setsockopt(), pi_inet_write(), pi_serial_getsockopt(), pi_serial_setsockopt(), pi_setsockopt(), pi_socket_setsd(), pi_usb_getsockopt(), pi_usb_setsockopt(), s_changebaud(), s_poll(), s_read(), s_read_buf(), s_write(), slp_flush(), slp_getsockopt(), slp_rx(), slp_setsockopt(), slp_tx(), sys_Find(), sys_flush(), sys_GetTrapBreaks(), sys_ReadMemory(), sys_RPC(), sys_rx(), sys_SetBreakpoints(), sys_SetTrapBreaks(), sys_ToggleDbgBreaks(), sys_tx(), sys_WriteMemory(), u_open(), u_open(), u_poll(), u_read(), u_read(), u_read(), u_read_buf(), u_write(), u_write(), and u_write().
pi_set_palmos_error()
int pi_set_palmos_error (int pi_sd, int error_code)
{
    pi_socket_t *ps;
    if ((ps = find_pi_socket(pi_sd)))
        ps->palmos_error = error_code;
    else
        errno = ESRCH;
    return error_code;
}
References find_pi_socket().
Referenced by _wrap_pi_set_palmos_error(), dlp_exec(), dlp_ReadAppPreference(), dlp_response_read(), dlp_VFSFileWrite(), dlp_WriteAppPreference(), pi_file_install(), pi_file_merge(), and pi_file_retrieve().
pi_setsockopt()
int pi_setsockopt (int pi_sd, int level, int option_name, const void * option_value, size_t * option_len)
{
    pi_socket_t *ps;
    pi_protocol_t *prot;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    /* handle setsockopt at socket level */
    if (level == PI_LEVEL_SOCK) {
        switch (option_name) {
            case PI_SOCK_STATE:
                if (*option_len != sizeof (ps->state))
                    goto argerr;
                memcpy (&ps->state, option_value, sizeof (ps->state));
                break;
            case PI_SOCK_HONOR_RX_TIMEOUT:
                if (*option_len != sizeof (ps->honor_rx_to))
                    goto argerr;
                memcpy (&ps->honor_rx_to, option_value, sizeof (ps->honor_rx_to));
                break;
            default:
                goto argerr;
        }
        return 0;
    }
    /* find the protocol at the requested level and forward it the setsockopt request */
    prot = protocol_queue_find (ps, level);
    if (prot == NULL || prot->level != level) {
        errno = EINVAL;
        return PI_ERR_SOCK_INVALID;
    }
    return prot->setsockopt (ps, level, option_name, option_value, option_len);
argerr:
    errno = EINVAL;
    return pi_set_error(pi_sd, PI_ERR_GENERIC_ARGUMENT);
}
References find_pi_socket(), pi_set_error(), and protocol_queue_find().
Referenced by _wrap_pi_setsockopt(), cmp_tx(), dlp_CallApplication(), dlp_VFSFileRead(), main(), net_rx(), padp_rx(), padp_sendack(), padp_tx(), pi_inet_accept(), pi_serial_accept(), pi_tickle(), pi_usb_accept(), pilot_connect(), and sys_tx().
pi_socket()
int pi_socket (int domain, int type, int protocol)
{
    pi_socket_t *ps;
    pi_socket_list_t *list;
    env_dbgcheck ();
    if (protocol == 0) {
        if (type == PI_SOCK_STREAM)
            protocol = PI_PF_DLP;
        else if (type == PI_SOCK_RAW)
            protocol = PI_PF_DEV;
    }
    ps = calloc(1, sizeof(pi_socket_t));
    if (ps == NULL) {
        errno = ENOMEM;
        return -1;
    }
    /* Create unique socket descriptor */
    if ((ps->sd = open(NULL_DEVICE, O_RDWR)) == -1) {
        int     err = errno;    /* Save errno of open */
        free(ps);
        errno = err;
        return -1;
    }
    /* Initialize the rest of the fields (calloc zeroes out
       all the fields we don't touch) */
    ps->type    = type;
    ps->protocol    = protocol;
    ps->state       = PI_SOCK_CLOSE;
    ps->honor_rx_to = 1;
    ps->command     = 1;
    /* post the new socket to the list */
    list = pi_socket_recognize(ps);
    if (list == NULL) {
        close (ps->sd);
        free(ps);
        errno = ENOMEM;
        return -1;
    }
    installexit();
    return ps->sd;
}
References env_dbgcheck(), installexit(), list, and pi_socket_recognize().
Referenced by _wrap_pi_socket(), CreateSocket(), main(), main(), pilot_connect(), pilot_connect(), plu_connect(), and socketCmd().
pi_socket_connected()
int pi_socket_connected (int pi_sd)
{
    pi_socket_t *ps;
    if ((ps = find_pi_socket(pi_sd)))
        return is_connected(ps);
    errno = ESRCH;
    return 0;
}
References find_pi_socket(), and is_connected().
Referenced by _wrap_pi_socket_connected(), fetch_progress(), install_progress(), palm_backup(), pi_file_install(), pi_file_merge(), and pi_file_retrieve().
pi_socket_init()
int pi_socket_init (pi_socket_t * ps)
{
    protocol_queue_build (ps, 1);
    return 0;
}
References protocol_queue_build().
Referenced by pi_bluetooth_accept(), pi_inet_accept(), pi_serial_accept(), and pi_usb_accept().
pi_socket_recognize()
pi_socket_list_t * pi_socket_recognize (pi_socket_t * ps)
{
    pi_mutex_lock(&psl_mutex);
    psl = ps_list_append(psl, ps);
    pi_mutex_unlock(&psl_mutex);
    return psl;
}
References pi_mutex_lock(), pi_mutex_unlock(), ps_list_append(), and psl.
Referenced by pi_socket().
pi_socket_setsd()
int pi_socket_setsd (pi_socket_t * ps, int pi_sd)
{
#ifdef HAVE_DUP2
    ps->sd = dup2(pi_sd, ps->sd);
#else
    close(ps->sd);
    #ifdef F_DUPFD
        ps->sd = fcntl(pi_sd, F_DUPFD, ps->sd);
    #else
        ps->sd = dup(pi_sd);
    #endif
#endif
    if (ps->sd == -1)
        return pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
    if (ps->sd != pi_sd)
        close(pi_sd);
    return 0;
}
References pi_set_error().
Referenced by _wrap_pi_socket_setsd(), pi_bluetooth_accept(), pi_bluetooth_open(), pi_inet_accept(), pi_inet_bind(), pi_inet_connect(), s_open(), u_open(), and u_open().
pi_tickle()
int pi_tickle (int pi_sd)
{
    int     result=0,
        type,
        oldtype;
    size_t  len = 0,
        size;
    unsigned char   msg[1];
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (!is_connected (ps))
        return PI_ERR_SOCK_DISCONNECTED;
    LOG((PI_DBG_SOCK, PI_DBG_LVL_INFO,
            "SOCKET Tickling socket %d\n", pi_sd));
    switch (ps->cmd) {
        case PI_CMD_CMP:
            /* save previous packet type */
            size = sizeof(type);
            pi_getsockopt(ps->sd, PI_LEVEL_PADP, PI_PADP_TYPE, &oldtype, &size);
            /* set packet type to "tickle" */
            type = padTickle;
            size = sizeof(type);
            pi_setsockopt(ps->sd, PI_LEVEL_PADP, PI_PADP_TYPE, &type, &size);
            /* send packet */
            result = ps->protocol_queue[0]->write (ps, msg, len, 0);
            /* restore previous packet type */
            size = sizeof(type);
            pi_setsockopt(ps->sd, PI_LEVEL_PADP, PI_PADP_TYPE, &oldtype, &size);
            break;
        case PI_CMD_NET:
            /* Enter command state */
            ps->command = 1;
            /* Set the type to "tickle" */
            type = PI_NET_TYPE_TCKL;
            size = sizeof(type);
            pi_setsockopt(ps->sd, PI_LEVEL_NET, PI_NET_TYPE, &type, &size);
            /* send packet */
            result = ps->cmd_queue[0]->write (ps, msg, len, 0);
            /* Exit command state */
            ps->command = 0;
            break;
    }
    return result;
}
References find_pi_socket(), is_connected(), pi_getsockopt(), pi_setsockopt(), and size.
Referenced by _wrap_pi_tickle(), and onalarm().
pi_version()
int pi_version (int pi_sd)
{
    size_t  size;
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    if (ps->dlpversion)
        return ps->dlpversion;
    if (ps->cmd == PI_CMD_CMP) {
        /* Enter command state */
        ps->command = 1;
        /* Get the version */
        size = sizeof(ps->dlpversion);
        pi_getsockopt(ps->sd, PI_LEVEL_CMP, PI_CMP_VERS, &ps->dlpversion, &size);
        ps->maxrecsize = DLP_BUF_SIZE;
        /* Exit command state */
        ps->command = 0;
    }
    return ps->dlpversion;
}
References find_pi_socket(), pi_getsockopt(), and size.
Referenced by _wrap_pi_version(), dlp_CallApplication(), dlp_DeleteCategory(), dlp_FindDBByName(), dlp_FindDBByOpenHandle(), dlp_FindDBByTypeCreator(), dlp_OpenConduit(), dlp_ReadAppPreference(), dlp_ReadDBList(), dlp_ReadNetSyncInfo(), dlp_ReadNextModifiedRecInCategory(), dlp_ReadNextRecInCategory(), dlp_ReadRecordByIndex(), dlp_ReadResourceByIndex(), dlp_response_read(), dlp_SetDBInfo(), dlp_WriteAppPreference(), dlp_WriteNetSyncInfo(), dlp_WriteRecord(), dlp_WriteResource(), invalid_socket(), pi_file_install(), pi_file_merge(), and pi_maxrecsize().
pi_watchdog()
int pi_watchdog (int pi_sd, int newinterval)
{
    pi_socket_t *ps;
    if (!(ps = find_pi_socket(pi_sd))) {
        errno = ESRCH;
        return PI_ERR_SOCK_INVALID;
    }
    pi_mutex_lock(&watch_list_mutex);
    watch_list = ps_list_append (watch_list, ps);
    pi_mutex_unlock(&watch_list_mutex);
    signal(SIGALRM, onalarm);
    interval = newinterval;
    alarm(interval);
    return 0;
}
References find_pi_socket(), interval, onalarm(), pi_mutex_lock(), pi_mutex_unlock(), ps_list_append(), and watch_list.
Referenced by _wrap_pi_watchdog(), and handle_user_commands().
pi_write()
ssize_t pi_write (int pi_sd, const void * msg, size_t len)
{
    return pi_send(pi_sd, msg, len, 0);
}
References pi_send().
Referenced by _wrap_pi_write(), dlp_request_write(), dlp_VFSFileWrite(), main(), proc_transmit(), sys_Continue(), sys_Find(), sys_GetTrapBreaks(), sys_QueryState(), sys_ReadMemory(), sys_RemoteEvent(), sys_RPC(), sys_SetBreakpoints(), sys_SetTrapBreaks(), sys_Step(), sys_ToggleDbgBreaks(), and sys_WriteMemory().
protocol_cmd_queue_add()
static void protocol_cmd_queue_add (pi_socket_t * ps, pi_protocol_t * prot) static
{
    ps->cmd_queue = realloc(ps->cmd_queue,
        (sizeof(pi_protocol_t *)) * (ps->cmd_len + 1));
    if (ps->cmd_queue != NULL) {
        ps->cmd_queue[ps->cmd_len] = prot;
        ps->cmd_len++;
    } else {
        errno = ENOMEM;
        ps->cmd_len = 0;
    }
}
Referenced by protocol_queue_build().
protocol_queue_add()
static void protocol_queue_add (pi_socket_t * ps, pi_protocol_t * prot) static
{
    ps->protocol_queue = realloc(ps->protocol_queue,
        (sizeof(pi_protocol_t *)) * (ps->queue_len + 1));
    if (ps->protocol_queue != NULL) {
        ps->protocol_queue[ps->queue_len] = prot;
        ps->queue_len++;
    } else {
        errno = ENOMEM;
        ps->queue_len = 0;
    }
}
Referenced by protocol_queue_build().
protocol_queue_build()
static void protocol_queue_build (pi_socket_t * ps, int autodetect) static
{
    int protocol,
        result;
    pi_protocol_t
        *dev_prot,
        *dev_cmd_prot;
    LOG((PI_DBG_SOCK,PI_DBG_LVL_DEBUG, "SOCK fd=%d auto=%d\n",ps->sd,autodetect));
    /* The device protocol */
    dev_prot    = ps->device->protocol (ps->device);
    dev_cmd_prot    = ps->device->protocol (ps->device);
    /* When opening the device in RAW mode, we stay low-level */
    if (ps->type == PI_SOCK_RAW) {
        LOG((PI_DBG_SOCK,PI_DBG_LVL_DEBUG, "RAW mode, no protocol\n",ps->sd,autodetect));
        protocol_queue_add (ps, dev_prot);
        protocol_cmd_queue_add (ps, dev_cmd_prot);
        return;
    }
    protocol = ps->protocol;
    LOG((PI_DBG_SOCK,PI_DBG_LVL_DEBUG, "SOCK proto=%s (%d)\n",
        protocol == PI_PF_DEV ? "DEV" :
        protocol == PI_PF_SLP ? "SLP" :
        protocol == PI_PF_SYS ? "SYS" :
        protocol == PI_PF_PADP? "PADP" :
        protocol == PI_PF_NET ? "NET" :
        protocol == PI_PF_DLP ? "DLP" :
        "unknown", protocol));
    if (protocol == PI_PF_DLP && autodetect) {
        int skipped_bytes = 0,
            bytes_to_skip;
        pi_buffer_t
            *detect_buf = pi_buffer_new(64);
        for (;;) {
            /* try to peek a header start from the input sent by the device */
            result = dev_prot->read (ps, detect_buf, 10, PI_MSG_PEEK);
            if (result < 0)
                break;
            if (result != 10) {
                pi_buffer_clear(detect_buf);
                continue;
            }
            bytes_to_skip = 1;
            /* detect a valid PADP header packet */
            if (detect_buf->data[0] == PI_SLP_SIG_BYTE1 &&
                detect_buf->data[1] == PI_SLP_SIG_BYTE2 &&
                detect_buf->data[2] == PI_SLP_SIG_BYTE3)
            {
                /* compute the checksum */
                int i;
                unsigned char header_checksum;
                for (header_checksum = i = 0; i < 9; i++)
                    header_checksum += detect_buf->data[i];
                if (header_checksum == detect_buf->data[9]) {       /* sum  */
                    if (detect_buf->data[3] == PI_SLP_SOCK_DLP &&   /* src  */
                        detect_buf->data[4] == PI_SLP_SOCK_DLP &&   /* dest */
                        detect_buf->data[5] == PI_SLP_TYPE_PADP &&  /* type */
                        detect_buf->data[8] == 0xff)        /* txid */
                    {
                        protocol = PI_PF_PADP;
                        LOG((PI_DBG_SOCK, PI_DBG_LVL_INFO,
                            "\nusing PADP/SLP protocol (skipped %d bytes)\n",
                            skipped_bytes));
                        break;
                    }
                    else {
                        /* valid but not what we're looking for, skip it altogether */
                        bytes_to_skip = 10;
                    }
                } else {
                    /* skip the SLP SIG bytes */
                    bytes_to_skip = 3;
                }
            }
            /* detect NET header packets */
            else if (detect_buf->data[0] == 0x01 && /* NET packet */
                     detect_buf->data[2] == 0x00 && /* length byte 0 */
                 detect_buf->data[3] == 0x00 && /* length byte 1 */
                 detect_buf->data[4] == 0x00 && /* length byte 2 */
                     detect_buf->data[5] >  0    && /* length byte 3 */
                 detect_buf->data[6] == 0x90)   /* PI_NET_SIG_BYTE1 */
            {
                protocol = PI_PF_NET;
                LOG((PI_DBG_SOCK, PI_DBG_LVL_INFO,
                    "\nusing NET protocol (skipped %d bytes)\n",
                    skipped_bytes));
                break;
            }
            /* detect NET packet for cases where we lost the first 6 bytes
             * (this unfortunately happens on Linux with unixserial, and the
             * correct way to cope with this is to recognize the second
             * part of the NET handshake packet)
             */
            else if (detect_buf->data[0] == 0x90 && /* PI_NET_SIG_BYTE1 */
                 detect_buf->data[1] == 0x01 &&
                 detect_buf->data[2] == 0x00 &&
                 detect_buf->data[3] == 0x00 &&
                 detect_buf->data[4] == 0x00 &&
                 detect_buf->data[5] == 0x00 &&
                 detect_buf->data[6] == 0x00 &&
                 detect_buf->data[7] == 0x00 &&
                 detect_buf->data[8] == 0x00 &&
                 detect_buf->data[9] == 0x20)
            {
                protocol = PI_PF_NET;
                LOG((PI_DBG_SOCK, PI_DBG_LVL_INFO,
                    "\nusing NET protocol (skipped %d bytes)\n",
                    skipped_bytes));
                break;
            }
            /* eliminate one byte from the input, trying to frame a proper header */
            result = dev_prot->read (ps, detect_buf, bytes_to_skip, 0);
            if (result < 0)
                break;
            skipped_bytes += bytes_to_skip;
            pi_buffer_clear(detect_buf);
        }
        pi_buffer_free(detect_buf);
        if (result < 0) {
            /* if there was an error (i.e. disconnect), temporarily fallback
             * on PADP protocol. In further releases, we should really make
             * this function return an error if there was a problem. -- fpillet
             */
                LOG((PI_DBG_SOCK, PI_DBG_LVL_DEBUG,
                "Error: last read returned %d; switching to PADP by default\n",
                result));
            protocol = PI_PF_PADP;
        }
    } else if (protocol == PI_PF_DLP) {
        protocol = PI_PF_PADP;
    }
    /* The connected protocol queue */
    switch (protocol) {
        case PI_PF_PADP:
            protocol_queue_add (ps, padp_protocol ());
        case PI_PF_SLP:
            protocol_queue_add (ps, slp_protocol ());
            break;
        case PI_PF_NET:
            protocol_queue_add (ps, net_protocol ());
            break;
        case PI_PF_SYS:
            protocol_queue_add (ps, sys_protocol ());
            protocol_queue_add (ps, slp_protocol ());
            break;
    }
    /* The command protocol queue */
    switch (protocol) {
        case PI_PF_PADP:
        case PI_PF_SLP:
            protocol_cmd_queue_add (ps, cmp_protocol ());
            protocol_cmd_queue_add (ps, padp_protocol ());
            protocol_cmd_queue_add (ps, slp_protocol ());
            ps->cmd = PI_CMD_CMP;
            break;
        case PI_PF_NET:
            protocol_cmd_queue_add (ps, net_protocol ());
            ps->cmd = PI_CMD_NET;
            break;
        case PI_PF_SYS:
            ps->cmd = PI_CMD_SYS;
            break;
        default:
            LOG((PI_DBG_SOCK, PI_DBG_LVL_ERR, "invalid protocol (%d)", protocol));
            break;
    }
    protocol_queue_add (ps, dev_prot);
    protocol_cmd_queue_add (ps, dev_cmd_prot);
}
References cmp_protocol(), net_protocol(), padp_protocol(), pi_buffer_clear(), pi_buffer_free(), pi_buffer_new(), protocol_cmd_queue_add(), protocol_queue_add(), slp_protocol(), and sys_protocol().
Referenced by pi_connect(), and pi_socket_init().
protocol_queue_destroy()
static void protocol_queue_destroy (pi_socket_t * ps) static
{
    int     i;
    for (i = 0; i < ps->queue_len; i++)
        ps->protocol_queue[i]->free(ps->protocol_queue[i]);
    for (i = 0; i < ps->cmd_len; i++)
        ps->cmd_queue[i]->free(ps->cmd_queue[i]);
    if (ps->queue_len > 0)
        free(ps->protocol_queue);
    if (ps->cmd_len > 0)
        free(ps->cmd_queue);
}
Referenced by pi_close().
protocol_queue_find()
static pi_protocol_t * protocol_queue_find (pi_socket_t * ps, int level) static
{
    int     i;
    if (ps->command) {
        for (i = 0; i < ps->cmd_len; i++) {
            if (ps->cmd_queue[i]->level == level)
                return ps->cmd_queue[i];
        }
    } else {
        for (i = 0; i < ps->queue_len; i++) {
            if (ps->protocol_queue[i]->level == level)
                return ps->protocol_queue[i];
        }
    }
    return NULL;
}
Referenced by pi_getsockopt(), pi_protocol(), and pi_setsockopt().
protocol_queue_find_next()
static pi_protocol_t * protocol_queue_find_next (pi_socket_t * ps, int level) static
{
    int     i;
    if (ps->command && ps->cmd_len == 0)
        return NULL;
    if (!ps->command && ps->queue_len == 0)
        return NULL;
    if (ps->command && level == 0)
        return ps->cmd_queue[0];
    if (!ps->command && level == 0)
        return ps->protocol_queue[0];
    if (ps->command) {
        for (i = 0; i < ps->cmd_len - 1; i++) {
            if (ps->cmd_queue[i]->level == level)
                return ps->cmd_queue[i + 1];
        }
    } else {
        for (i = 0; i < ps->queue_len - 1; i++) {
            if (ps->protocol_queue[i]->level == level)
                return ps->protocol_queue[i + 1];
        }
    }
    return NULL;
}
Referenced by pi_protocol_next().
ps_list_append()
static pi_socket_list_t * ps_list_append (pi_socket_list_t * list, pi_socket_t * ps) static
{
    pi_socket_list_t *elem, *new_elem;
    ASSERT (ps != NULL);
    new_elem = (pi_socket_list_t *) malloc (sizeof(pi_socket_list_t));
    if (new_elem == NULL)
        return list;
    new_elem->ps    = ps;
    new_elem->next  = NULL;
    if (list == NULL)
        return new_elem;
    elem = list;
    while (elem->next != NULL)
        elem = elem->next;
    elem->next = new_elem;
    return list;
}
References list.
Referenced by pi_socket_recognize(), pi_watchdog(), and ps_list_copy().
ps_list_copy()
static pi_socket_list_t * ps_list_copy (pi_socket_list_t * list) static
{
    pi_socket_list_t *l, *new_list = NULL;
    for (l = list; l != NULL; l = l->next)
        new_list = ps_list_append (new_list, l->ps);
    return new_list;
}
References list, and ps_list_append().
Referenced by onexit().
ps_list_find()
static pi_socket_t * ps_list_find (pi_socket_list_t * list, int pi_sd) static
{
    pi_socket_list_t *elem;
    for (elem = list; elem != NULL; elem = elem->next)
        if (elem->ps != NULL && elem->ps->sd == pi_sd)
            return elem->ps;
    return NULL;
}
References list.
Referenced by find_pi_socket().
ps_list_free()
static void ps_list_free (pi_socket_list_t * list) static
{
    pi_socket_list_t *l, *next;
    if (list == NULL)
        return;
    l = list;
    do {
        next = l->next;
        free(l);
        l = next;
    } while (l != NULL);
}
References list.
Referenced by onexit().
ps_list_remove()
static pi_socket_list_t * ps_list_remove (pi_socket_list_t * list, int pi_sd) static
{
    pi_socket_list_t *elem,
        *new_list = list,
        *prev_elem = NULL;
    for (elem = list; elem != NULL; elem = elem->next) {
        if (elem->ps == NULL)
            continue;
        else if (elem->ps->sd == pi_sd) {
            if (prev_elem == NULL)
                new_list = elem->next;
            else
                prev_elem->next = elem->next;
            free(elem);
            break;
        }
        prev_elem = elem;
    }
    return new_list;
}
References list.
Referenced by pi_close().
Variable Documentation
interval
unsigned int interval = 0 static
Referenced by find_interfaces(), onalarm(), pi_send(), and pi_watchdog().
pi_sock_installedexit
int pi_sock_installedexit = 0
Referenced by installexit().
psl
pi_socket_list_t* psl = NULL static
Referenced by find_pi_socket(), onexit(), pi_close(), and pi_socket_recognize().
watch_list
pi_socket_list_t* watch_list = NULL static
Referenced by onalarm(), pi_close(), and pi_watchdog().