pilot-link: swig_globalvar Struct Reference
swig_globalvar Struct Reference
Data Fields
PyObject *(* get_attr)(void)
char * name
struct swig_globalvar * next
int(* set_attr)(PyObject *)
Detailed Description
Field Documentation
get_attr
PyObject *(* get_attr) (void)
Referenced by SWIG_Python_addvarlink(), and swig_varlink_getattr().
name
char* name
Referenced by SWIG_Python_addvarlink(), swig_varlink_getattr(), swig_varlink_print(), and swig_varlink_setattr().
next
struct swig_globalvar* next
Referenced by SWIG_Python_addvarlink(), swig_varlink_getattr(), swig_varlink_print(), and swig_varlink_setattr().
set_attr
int(* set_attr) (PyObject *)
Referenced by SWIG_Python_addvarlink(), and swig_varlink_setattr().
The documentation for this struct was generated from the following file:
bindings/Python/src/pisock_wrap.c