pilot-link: libpisync/sync.c File Reference
sync.c File Reference
#include <stdlib.h>
#include <string.h>
#include "pi-dlp.h"
#include "pi-sync.h"
Data Structures
struct _RecordQueue
struct _RecordQueueList
Macros
#define DesktopCheck(func) if (rec_mod == DESKTOP || rec_mod == BOTH) if ((result = func) < 0) return result;
#define ErrorCheck(func) if ((result = func) < 0) return result;
#define PilotCheck(func) if (rec_mod == PILOT || rec_mod == BOTH) if ((result = func) < 0) return result;
Typedefs
typedef struct _RecordQueue RecordQueue
typedef struct _RecordQueueList RecordQueueList
Enumerations
enum RecordModifier { PILOT , DESKTOP , BOTH }
Functions
static void add_record_queue (RecordQueue *rq, PilotRecord *precord, DesktopRecord *drecord)
static int close_db (SyncHandler *sh, int dbhandle)
static int delete_both (SyncHandler *sh, int dbhandle, DesktopRecord *drecord, PilotRecord *precord, RecordModifier rec_mod)
static int free_record_queue_list (SyncHandler *sh, RecordQueueList *rql)
static int open_db (SyncHandler *sh, int *dbhandle)
static int store_record_on_pilot (SyncHandler *sh, int dbhandle, DesktopRecord *drecord, RecordModifier rec_mod)
DesktopRecord * sync_CopyDesktopRecord (const DesktopRecord *drecord)
int sync_CopyFromPilot (SyncHandler *sh)
PilotRecord * sync_CopyPilotRecord (const PilotRecord *precord)
int sync_CopyToPilot (SyncHandler *sh)
void sync_FreeDesktopRecord (DesktopRecord *drecord)
void sync_FreePilotRecord (PilotRecord *precord)
int sync_MergeFromPilot (SyncHandler *sh)
static int sync_MergeFromPilot_fast (SyncHandler *sh, int dbhandle, RecordModifier rec_mod)
static int sync_MergeFromPilot_process (SyncHandler *sh, int dbhandle, RecordQueue *rq, RecordModifier rec_mod)
static int sync_MergeFromPilot_slow (SyncHandler *sh, int dbhandle, RecordModifier rec_mod)
int sync_MergeToPilot (SyncHandler *sh)
static int sync_MergeToPilot_fast (SyncHandler *sh, int dbhandle, RecordModifier rec_mod)
static int sync_MergeToPilot_slow (SyncHandler *sh, int dbhandle, RecordModifier rec_mod)
DesktopRecord * sync_NewDesktopRecord (void)
PilotRecord * sync_NewPilotRecord (int buf_size)
static int sync_record (SyncHandler *sh, int dbhandle, DesktopRecord *drecord, PilotRecord *precord, RecordQueue *rq, RecordModifier rec_mod)
int sync_Synchronize (SyncHandler *sh)
Macro Definition Documentation
DesktopCheck
#define DesktopCheck (func) if (rec_mod == DESKTOP || rec_mod == BOTH) if ((result = func) < 0) return result;
Referenced by delete_both(), store_record_on_pilot(), and sync_record().
ErrorCheck
#define ErrorCheck (func) if ((result = func) < 0) return result;
Referenced by free_record_queue_list(), sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), sync_MergeToPilot_slow(), and sync_record().
PilotCheck
#define PilotCheck (func) if (rec_mod == PILOT || rec_mod == BOTH) if ((result = func) < 0) return result;
Referenced by delete_both(), store_record_on_pilot(), sync_MergeFromPilot_process(), sync_MergeToPilot_fast(), sync_MergeToPilot_slow(), and sync_record().
Typedef Documentation
RecordQueue
typedef struct _RecordQueue RecordQueue
RecordQueueList
typedef struct _RecordQueueList RecordQueueList
Enumeration Type Documentation
RecordModifier
enum RecordModifier
Enumerator
PILOT
DESKTOP
BOTH
             {
    PILOT,
    DESKTOP,
    BOTH
} RecordModifier;
Function Documentation
add_record_queue()
static void add_record_queue (RecordQueue * rq, PilotRecord * precord, DesktopRecord * drecord) static
{
    RecordQueueList *item;
    item = malloc(sizeof(RecordQueueList));
    if (drecord != NULL) {
        item->drecord = drecord;
        item->precord = NULL;
    } else {
        item->drecord = NULL;
        item->precord = sync_CopyPilotRecord(precord);
    }
    if (rq) {
        item->next = rq->rql;
        rq->rql = item;
    } else {
        item->next = NULL;
    }
    rq->count++;
}
References _RecordQueue::count, _RecordQueueList::drecord, _RecordQueueList::next, _RecordQueueList::precord, _RecordQueue::rql, and sync_CopyPilotRecord().
Referenced by sync_record().
close_db()
static int close_db (SyncHandler * sh, int dbhandle) static
{
    dlp_CleanUpDatabase(sh->sd, dbhandle);
    dlp_ResetSyncFlags(sh->sd, dbhandle);
    dlp_CloseDB(sh->sd, dbhandle);
    return 0;
}
References dlp_CleanUpDatabase(), dlp_CloseDB(), and dlp_ResetSyncFlags().
Referenced by sync_CopyFromPilot(), sync_CopyToPilot(), sync_MergeFromPilot(), sync_MergeToPilot(), and sync_Synchronize().
delete_both()
static int delete_both (SyncHandler * sh, int dbhandle, DesktopRecord * drecord, PilotRecord * precord, RecordModifier rec_mod) static
{
    int result = 0;
    if (drecord != NULL)
        DesktopCheck(sh->DeleteRecord(sh, drecord));
    if (precord != NULL)
        PilotCheck(dlp_DeleteRecord
               (sh->sd, dbhandle, 0, precord->recID));
    return result;
}
References DesktopCheck, dlp_DeleteRecord(), and PilotCheck.
Referenced by sync_record().
free_record_queue_list()
static int free_record_queue_list (SyncHandler * sh, RecordQueueList * rql) static
{
    int     result = 0;
    RecordQueueList *item;
    while (rql != NULL) {
        item = rql;
        rql = rql->next;
        if (item->drecord)
            ErrorCheck(sh->FreeMatch(sh, item->drecord));
        if (item->precord)
            sync_FreePilotRecord(item->precord);
        free(item);
    }
    return 0;
}
References _RecordQueueList::drecord, ErrorCheck, _RecordQueueList::next, _RecordQueueList::precord, and sync_FreePilotRecord().
Referenced by sync_MergeFromPilot_process().
open_db()
static int open_db (SyncHandler * sh, int * dbhandle) static
{
    if (sh->secret)
        return dlp_OpenDB(sh->sd, 0, dlpOpenReadWrite
                  && dlpOpenSecret, sh->name, dbhandle);
    else
        return dlp_OpenDB(sh->sd, 0, dlpOpenReadWrite, sh->name,
                  dbhandle);
}
References dlp_OpenDB().
Referenced by sync_CopyFromPilot(), sync_CopyToPilot(), sync_MergeFromPilot(), sync_MergeToPilot(), and sync_Synchronize().
store_record_on_pilot()
static int store_record_on_pilot (SyncHandler * sh, int dbhandle, DesktopRecord * drecord, RecordModifier rec_mod) static
{
    int     result = 0;
    PilotRecord precord;
    recordid_t id_;
    memset(&precord, 0, sizeof(PilotRecord));
    result = sh->Prepare(sh, drecord, &precord);
    if (result != 0)
        return result;
    PilotCheck(dlp_WriteRecord(sh->sd, dbhandle, precord.flags & dlpRecAttrSecret,
                   precord.recID, precord.catID,
                   precord.buffer, precord.len, &id_));
    DesktopCheck(sh->SetPilotID(sh, drecord, id_));
    return result;
}
References DesktopCheck, dlp_WriteRecord(), and PilotCheck.
Referenced by sync_CopyToPilot(), and sync_MergeFromPilot_process().
sync_CopyDesktopRecord()
DesktopRecord * sync_CopyDesktopRecord (const DesktopRecord * drecord)
{
    DesktopRecord *new_record;
    new_record  = sync_NewDesktopRecord();
    *new_record     = *drecord;
    return new_record;
}
References sync_NewDesktopRecord().
sync_CopyFromPilot()
int sync_CopyFromPilot (SyncHandler * sh)
{
    int     dbhandle,
        i,
        slow    = 0,
        result  = 0;
    pi_buffer_t *recbuf;
    DesktopRecord *drecord = NULL;
    PilotRecord *precord = sync_NewPilotRecord(DLP_BUF_SIZE);
    result = open_db(sh, &dbhandle);
    if (result < 0)
        goto cleanup;
    result = sh->Pre(sh, dbhandle, &slow);
    if (result < 0)
        goto cleanup;
    while (sh->ForEach(sh, &drecord) == 0 && drecord) {
        result = sh->DeleteRecord(sh, drecord);
        if (result < 0)
            goto cleanup;
    }
    i = 0;
    recbuf = pi_buffer_new(DLP_BUF_SIZE);
    while (dlp_ReadRecordByIndex(sh->sd, dbhandle, i, recbuf, &precord->recID,
           &precord->flags, &precord->catID) > 0) {
        precord->len = recbuf->used;
        if (precord->len > DLP_BUF_SIZE)
            precord->len = DLP_BUF_SIZE;
        memcpy(precord->buffer, recbuf->data, precord->len);
        result = sh->AddRecord(sh, precord);
        if (result < 0) {
            pi_buffer_free(recbuf);
            goto cleanup;
        }
        i++;
    }
    pi_buffer_free (recbuf);
    result = sh->Post(sh, dbhandle);
cleanup:
    close_db(sh, dbhandle);
    sync_FreePilotRecord (precord);
    return result;
}
References close_db(), dlp_ReadRecordByIndex(), open_db(), pi_buffer_free(), pi_buffer_new(), sync_FreePilotRecord(), and sync_NewPilotRecord().
sync_CopyPilotRecord()
PilotRecord * sync_CopyPilotRecord (const PilotRecord * precord)
{
    PilotRecord *new_record;
    new_record = sync_NewPilotRecord(sizeof(precord->buffer));
    new_record->recID   = precord->recID;
    new_record->catID   = precord->catID;
    new_record->flags   = precord->flags;
    memcpy(new_record->buffer, precord->buffer, precord->len);
    new_record->len     = precord->len;
    return new_record;
}
References sync_NewPilotRecord().
Referenced by add_record_queue().
sync_CopyToPilot()
int sync_CopyToPilot (SyncHandler * sh)
{
    int     dbhandle,
        slow    = 0,
        result  = 0;
    DesktopRecord *drecord = NULL;
    result = open_db(sh, &dbhandle);
    if (result < 0)
        goto cleanup;
    result = sh->Pre(sh, dbhandle, &slow);
    if (result < 0)
        goto cleanup;
    result = dlp_DeleteRecord(sh->sd, dbhandle, 1, 0);
    if (result < 0)
        goto cleanup;
    while (sh->ForEach(sh, &drecord) == 0 && drecord) {
        result =
            store_record_on_pilot(sh, dbhandle, drecord, BOTH);
        if (result < 0)
            goto cleanup;
    }
    result = sh->Post(sh, dbhandle);
      cleanup:
    close_db(sh, dbhandle);
    return result;
}
References BOTH, close_db(), dlp_DeleteRecord(), open_db(), and store_record_on_pilot().
sync_FreeDesktopRecord()
void sync_FreeDesktopRecord (DesktopRecord * drecord)
{
    free(drecord);
}
sync_FreePilotRecord()
void sync_FreePilotRecord (PilotRecord * precord)
{
    if (precord->buffer)
        free(precord->buffer);
    free(precord);
}
Referenced by free_record_queue_list(), sync_CopyFromPilot(), sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), and sync_MergeToPilot_slow().
sync_MergeFromPilot()
int sync_MergeFromPilot (SyncHandler * sh)
{
    int     dbhandle,
        slow    = 0,
        result  = 0;
    result = open_db(sh, &dbhandle);
    if (result < 0)
        goto cleanup;
    result = sh->Pre(sh, dbhandle, &slow);
    if (result < 0)
        goto cleanup;
    if (!slow) {
        result = sync_MergeFromPilot_fast(sh, dbhandle, DESKTOP);
        if (result < 0)
            goto cleanup;
    } else {
        result = sync_MergeFromPilot_slow(sh, dbhandle, DESKTOP);
        if (result < 0)
            goto cleanup;
    }
    result = sh->Post(sh, dbhandle);
      cleanup:
    close_db(sh, dbhandle);
    return result;
}
References close_db(), DESKTOP, open_db(), sync_MergeFromPilot_fast(), and sync_MergeFromPilot_slow().
sync_MergeFromPilot_fast()
static int sync_MergeFromPilot_fast (SyncHandler * sh, int dbhandle, RecordModifier rec_mod) static
{
    int     result = 0;
    PilotRecord *precord    = sync_NewPilotRecord(DLP_BUF_SIZE);
    DesktopRecord *drecord  = NULL;
    RecordQueue rq      = { 0, NULL };
    pi_buffer_t *recbuf = pi_buffer_new(DLP_BUF_SIZE);
    while (dlp_ReadNextModifiedRec(sh->sd, dbhandle, recbuf,
                       &precord->recID, NULL,
                       &precord->flags,
                       &precord->catID) >= 0) {
        int count = rq.count;
        precord->len = recbuf->used;
        if (precord->len > DLP_BUF_SIZE)
            precord->len = DLP_BUF_SIZE;
        memcpy(precord->buffer, recbuf->data, precord->len);
        ErrorCheck(sh->Match(sh, precord, &drecord));
        ErrorCheck(sync_record
               (sh, dbhandle, drecord, precord, &rq, rec_mod));
        if (drecord && rq.count == count)
            ErrorCheck(sh->FreeMatch(sh, drecord));
    }
    pi_buffer_free(recbuf);
    sync_FreePilotRecord(precord);
    result = sync_MergeFromPilot_process(sh, dbhandle, &rq, rec_mod);
    return result;
}
References _RecordQueue::count, dlp_ReadNextModifiedRec(), ErrorCheck, pi_buffer_free(), pi_buffer_new(), sync_FreePilotRecord(), sync_MergeFromPilot_process(), sync_NewPilotRecord(), and sync_record().
Referenced by sync_MergeFromPilot(), and sync_Synchronize().
sync_MergeFromPilot_process()
static int sync_MergeFromPilot_process (SyncHandler * sh, int dbhandle, RecordQueue * rq, RecordModifier rec_mod) static
{
    int     result = 0;
    RecordQueueList *item;
    for (item = rq->rql; item != NULL; item = item->next) {
        if (item->drecord != NULL) {
            store_record_on_pilot(sh, dbhandle, item->drecord,
                          rec_mod);
        } else {
            PilotCheck(dlp_WriteRecord(sh->sd, dbhandle, 0, 0,
                           item->precord->catID,
                           item->precord->buffer,
                           item->precord->len,
                           &item->precord->recID));
        }
    }
    free_record_queue_list(sh, rq->rql);
    return result;
}
References dlp_WriteRecord(), _RecordQueueList::drecord, free_record_queue_list(), _RecordQueueList::next, PilotCheck, _RecordQueueList::precord, _RecordQueue::rql, and store_record_on_pilot().
Referenced by sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), and sync_MergeToPilot_slow().
sync_MergeFromPilot_slow()
static int sync_MergeFromPilot_slow (SyncHandler * sh, int dbhandle, RecordModifier rec_mod) static
{
    int     i,
        parch,
        psecret,
        result = 0;
    pi_buffer_t *recbuf;
    PilotRecord *precord    = sync_NewPilotRecord(DLP_BUF_SIZE);
    DesktopRecord *drecord  = NULL;
    RecordQueue rq      = { 0, NULL };
    i = 0;
    recbuf = pi_buffer_new(DLP_BUF_SIZE);
    while (dlp_ReadRecordByIndex
           (sh->sd, dbhandle, i, recbuf, &precord->recID,
            &precord->flags, &precord->catID) > 0) {
        int     count = rq.count;
        precord->len = recbuf->used;
        if (precord->len > DLP_BUF_SIZE)
            precord->len = DLP_BUF_SIZE;
        memcpy(precord->buffer, recbuf->data, precord->len);
        ErrorCheck(sh->Match(sh, precord, &drecord));
        /* Since this is a slow sync, we must calculate the flags */
        parch = precord->flags & dlpRecAttrArchived;
        psecret = precord->flags & dlpRecAttrSecret;
        precord->flags = 0;
        if (drecord == NULL) {
            precord->flags = precord->flags | dlpRecAttrDirty;
        } else {
            int comp;
            comp = sh->Compare(sh, precord, drecord);
            if (comp != 0) {
                precord->flags =
                    precord->flags | dlpRecAttrDirty;
            }
        }
        if (parch)
            precord->flags =
                precord->flags | dlpRecAttrArchived;
        if (psecret)
            precord->flags = precord->flags | dlpRecAttrSecret;
        ErrorCheck(sync_record
               (sh, dbhandle, drecord, precord, &rq, rec_mod));
        if (drecord && rq.count == count)
            ErrorCheck(sh->FreeMatch(sh, drecord));
        i++;
    }
    pi_buffer_free(recbuf);
    sync_FreePilotRecord(precord);
    result = sync_MergeFromPilot_process(sh, dbhandle, &rq, rec_mod);
    return result;
}
References _RecordQueue::count, dlp_ReadRecordByIndex(), ErrorCheck, pi_buffer_free(), pi_buffer_new(), sync_FreePilotRecord(), sync_MergeFromPilot_process(), sync_NewPilotRecord(), and sync_record().
Referenced by sync_MergeFromPilot(), and sync_Synchronize().
sync_MergeToPilot()
int sync_MergeToPilot (SyncHandler * sh)
{
    int     dbhandle,
        slow    = 0,
        result  = 0;
    result = open_db(sh, &dbhandle);
    if (result < 0)
        goto cleanup;
    result = sh->Pre(sh, dbhandle, &slow);
    if (result < 0)
        goto cleanup;
    if (!slow) {
        sync_MergeToPilot_fast(sh, dbhandle, PILOT);
        if (result < 0)
            goto cleanup;
    } else {
        sync_MergeToPilot_slow(sh, dbhandle, PILOT);
        if (result < 0)
            goto cleanup;
    }
    result = sh->Post(sh, dbhandle);
      cleanup:
    close_db(sh, dbhandle);
    return result;
}
References close_db(), open_db(), PILOT, sync_MergeToPilot_fast(), and sync_MergeToPilot_slow().
sync_MergeToPilot_fast()
static int sync_MergeToPilot_fast (SyncHandler * sh, int dbhandle, RecordModifier rec_mod) static
{
    int     result      = 0;
    PilotRecord *precord    = NULL;
    DesktopRecord *drecord  = NULL;
    RecordQueue rq      = { 0, NULL };
    pi_buffer_t *recbuf = pi_buffer_new(DLP_BUF_SIZE);
    while (sh->ForEachModified(sh, &drecord) == 0 && drecord) {
        if (drecord->recID != 0) {
            precord = sync_NewPilotRecord(DLP_BUF_SIZE);
            precord->recID = drecord->recID;
            PilotCheck(dlp_ReadRecordById(sh->sd, dbhandle,
                              precord->recID,
                              recbuf,
                              NULL,
                              &precord->flags,
                              &precord->catID));
            precord->len = recbuf->used;
            if (precord->len > DLP_BUF_SIZE)
                precord->len = DLP_BUF_SIZE;
            memcpy(precord->buffer, recbuf->data, precord->len);
        }
        ErrorCheck(sync_record
               (sh, dbhandle, drecord, precord, &rq, rec_mod));
        if (precord)
            sync_FreePilotRecord (precord);
        precord = NULL;
    }
    pi_buffer_free(recbuf);
    result = sync_MergeFromPilot_process(sh, dbhandle, &rq, rec_mod);
    return result;
}
References dlp_ReadRecordById(), ErrorCheck, pi_buffer_free(), pi_buffer_new(), PilotCheck, sync_FreePilotRecord(), sync_MergeFromPilot_process(), sync_NewPilotRecord(), and sync_record().
Referenced by sync_MergeToPilot(), and sync_Synchronize().
sync_MergeToPilot_slow()
static int sync_MergeToPilot_slow (SyncHandler * sh, int dbhandle, RecordModifier rec_mod) static
{
    int     darch,
        dsecret,
        result      = 0;
    PilotRecord *precord    = NULL;
    DesktopRecord *drecord  = NULL;
    RecordQueue rq      = { 0, NULL };
    pi_buffer_t *recbuf = pi_buffer_new(DLP_BUF_SIZE);
    while (sh->ForEach(sh, &drecord) == 0 && drecord) {
        if (drecord->recID != 0) {
            precord = sync_NewPilotRecord(DLP_BUF_SIZE);
            precord->recID = drecord->recID;
            PilotCheck(dlp_ReadRecordById(sh->sd, dbhandle,
                              precord->recID,
                              recbuf,
                              NULL,
                              &precord->flags,
                              &precord->catID));
            precord->len = recbuf->used;
            if (precord->len > DLP_BUF_SIZE)
                precord->len = DLP_BUF_SIZE;
            memcpy(precord->buffer, recbuf->data, precord->len);
        }
        /* Since this is a slow sync, we must calculate the flags */
        darch = drecord->flags & dlpRecAttrArchived;
        dsecret = drecord->flags & dlpRecAttrSecret;
        drecord->flags = 0;
        if (precord == NULL) {
            drecord->flags = drecord->flags | dlpRecAttrDirty;
        } else {
            int comp;
            comp = sh->Compare(sh, precord, drecord);
            if (comp != 0) {
                drecord->flags =
                    drecord->flags | dlpRecAttrDirty;
            }
        }
        if (darch)
            drecord->flags =
                drecord->flags | dlpRecAttrArchived;
        if (dsecret)
            drecord->flags = drecord->flags | dlpRecAttrSecret;
        ErrorCheck(sync_record
               (sh, dbhandle, drecord, precord, &rq, rec_mod));
        if (precord)
            sync_FreePilotRecord (precord);
        precord = NULL;
    }
    pi_buffer_free(recbuf);
    result = sync_MergeFromPilot_process(sh, dbhandle, &rq, rec_mod);
    return result;
}
References dlp_ReadRecordById(), ErrorCheck, pi_buffer_free(), pi_buffer_new(), PilotCheck, sync_FreePilotRecord(), sync_MergeFromPilot_process(), sync_NewPilotRecord(), and sync_record().
Referenced by sync_MergeToPilot(), and sync_Synchronize().
sync_NewDesktopRecord()
DesktopRecord * sync_NewDesktopRecord (void)
{
    DesktopRecord *drecord;
    drecord = (DesktopRecord *) malloc(sizeof(DesktopRecord));
    memset(drecord, 0, sizeof(DesktopRecord));
    return drecord;
}
Referenced by sync_CopyDesktopRecord().
sync_NewPilotRecord()
PilotRecord * sync_NewPilotRecord (int buf_size)
{
    PilotRecord *precord;
    precord = (PilotRecord *) malloc(sizeof(PilotRecord));
    memset(precord, 0, sizeof(PilotRecord));
    precord->buffer = malloc(buf_size);
    return precord;
}
Referenced by sync_CopyFromPilot(), sync_CopyPilotRecord(), sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), and sync_MergeToPilot_slow().
sync_record()
static int sync_record (SyncHandler * sh, int dbhandle, DesktopRecord * drecord, PilotRecord * precord, RecordQueue * rq, RecordModifier rec_mod) static
{
    int     parch   = 0,
        pdel    = 0,
        pchange = 0,
        darch   = 0,
        ddel    = 0,
        dchange = 0,
        result  = 0;
    /* The state is calculated like this because the deleted and dirty
       pilot flags are not mutually exclusive */
    if (precord) {
        parch = precord->flags & dlpRecAttrArchived;
        pdel = precord->flags & dlpRecAttrDeleted;
        pchange = (precord->flags & dlpRecAttrDirty) && (!pdel);
    }
    if (drecord) {
        darch = drecord->flags & dlpRecAttrArchived;
        ddel = drecord->flags & dlpRecAttrDeleted;
        dchange = (drecord->flags & dlpRecAttrDirty) && (!ddel);
    }
    /* Bail if the pilot record was created and deleted between syncs */
    if (drecord == NULL && !parch && pdel)
        return 0;
    /* Sync logic */
    if (precord != NULL && !parch && !pdel && drecord == NULL) {
        DesktopCheck(sh->AddRecord(sh, precord));
    } else if (precord == NULL && drecord != NULL) {
        add_record_queue(rq, NULL, drecord);
    } else if (parch && ddel) {
        DesktopCheck(sh->ReplaceRecord(sh, drecord, precord));
        DesktopCheck(sh->ArchiveRecord(sh, drecord, 1));
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (parch && !darch && !dchange && drecord != NULL) {
        DesktopCheck(sh->ArchiveRecord(sh, drecord, 1));
    } else if (parch && drecord == NULL) {
        DesktopCheck(sh->AddRecord(sh, precord));
        ErrorCheck(sh->Match(sh, precord, &drecord));
        if (drecord == NULL)
            return -1;
        DesktopCheck(sh->ArchiveRecord(sh, drecord, 1));
        ErrorCheck(sh->FreeMatch(sh, drecord));
    } else if (parch && pchange && !darch && dchange) {
        int comp;
        comp = sh->Compare(sh, precord, drecord);
        if (comp == 0) {
            DesktopCheck(sh->ArchiveRecord(sh, drecord, 1));
            PilotCheck(dlp_DeleteRecord
                   (sh->sd, dbhandle, 0, precord->recID));
            DesktopCheck(sh->SetStatusCleared(sh, drecord));
        } else {
            PilotCheck(dlp_WriteRecord(sh->sd, dbhandle, 0, 0,
                           precord->catID,
                           precord->buffer,
                           precord->len,
                           &precord->recID));
            DesktopCheck(sh->AddRecord(sh, precord));
            add_record_queue(rq, NULL, drecord);
            DesktopCheck(sh->SetStatusCleared(sh, drecord));
        }
    } else if (parch && !pchange && !darch && dchange) {
        PilotCheck(dlp_DeleteRecord
               (sh->sd, dbhandle, 0, precord->recID));
        add_record_queue(rq, NULL, drecord);
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (pchange && darch && dchange) {
        int comp;
        comp = sh->Compare(sh, precord, drecord);
        if (comp == 0) {
            PilotCheck(dlp_DeleteRecord
                   (sh->sd, dbhandle, 0, precord->recID));
        } else {
            DesktopCheck(sh->ArchiveRecord(sh, drecord, 0));
            DesktopCheck(sh->
                     ReplaceRecord(sh, drecord, precord));
        }
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (pchange && darch && !dchange) {
        DesktopCheck(sh->ArchiveRecord(sh, drecord, 0));
        DesktopCheck(sh->ReplaceRecord(sh, drecord, precord));
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (pchange && dchange) {
        int comp;
        comp = sh->Compare(sh, precord, drecord);
        if (comp != 0) {
            DesktopCheck(sh->AddRecord(sh, precord));
            drecord->recID = 0;
            add_record_queue(rq, NULL, drecord);
        }
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (pchange && ddel) {
        DesktopCheck(sh->ReplaceRecord(sh, drecord, precord));
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (pchange && !dchange) {
        DesktopCheck(sh->ReplaceRecord(sh, drecord, precord));
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (pdel && dchange) {
        add_record_queue(rq, NULL, drecord);
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (pdel && !dchange) {
        DesktopCheck(delete_both
                 (sh, dbhandle, drecord, precord, rec_mod));
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (!pchange && darch) {
        PilotCheck(dlp_DeleteRecord
               (sh->sd, dbhandle, 0, precord->recID));
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (!pchange && dchange) {
        PilotCheck(dlp_DeleteRecord
               (sh->sd, dbhandle, 0, precord->recID));
        add_record_queue(rq, NULL, drecord);
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    } else if (!pchange && ddel) {
        DesktopCheck(delete_both
                 (sh, dbhandle, drecord, precord, rec_mod));
        DesktopCheck(sh->SetStatusCleared(sh, drecord));
    }
    return result;
}
References add_record_queue(), delete_both(), DesktopCheck, dlp_DeleteRecord(), dlp_WriteRecord(), ErrorCheck, and PilotCheck.
Referenced by sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), and sync_MergeToPilot_slow().
sync_Synchronize()
int sync_Synchronize (SyncHandler * sh)
{
    int     dbhandle,
        slow    = 0,
        result  = 0;
    result = open_db(sh, &dbhandle);
    if (result < 0)
        goto cleanup;
    result = sh->Pre(sh, dbhandle, &slow);
    if (result != 0)
        goto cleanup;
    if (!slow) {
        result = sync_MergeFromPilot_fast(sh, dbhandle, BOTH);
        if (result < 0)
            goto cleanup;
        result = sync_MergeToPilot_fast(sh, dbhandle, BOTH);
        if (result < 0)
            goto cleanup;
    } else {
        result = sync_MergeFromPilot_slow(sh, dbhandle, BOTH);
        if (result < 0)
            goto cleanup;
        result = sync_MergeToPilot_slow(sh, dbhandle, BOTH);
        if (result < 0)
            goto cleanup;
    }
    result = sh->Post(sh, dbhandle);
      cleanup:
    close_db(sh, dbhandle);
    return result;
}
References BOTH, close_db(), open_db(), sync_MergeFromPilot_fast(), sync_MergeFromPilot_slow(), sync_MergeToPilot_fast(), and sync_MergeToPilot_slow().