pilot-link: libpisock/sys.c File Reference
sys.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include "pi-debug.h"
#include "pi-source.h"
#include "pi-slp.h"
#include "pi-sys.h"
#include "pi-error.h"
Functions
void sys_dump (const unsigned char *data, size_t len)
void sys_dump_header (const unsigned char *data, int rxtx)
static int sys_flush (pi_socket_t *ps, int flags)
static int sys_getsockopt (pi_socket_t *ps, int level, int option_name, void *option_value, size_t *option_len)
pi_protocol_t * sys_protocol (void)
static pi_protocol_t * sys_protocol_dup (pi_protocol_t *prot)
static void sys_protocol_free (pi_protocol_t *prot)
ssize_t sys_rx (pi_socket_t *ps, pi_buffer_t *buf, size_t len, int flags)
static int sys_setsockopt (pi_socket_t *ps, int level, int option_name, const void *option_value, size_t *option_len)
ssize_t sys_tx (pi_socket_t *ps, const unsigned char *buf, size_t len, int flags)
Function Documentation
sys_dump()
void sys_dump (const unsigned char * data, size_t len)
{
    pi_dumpdata((char *)&data[PI_SYS_HEADER_LEN], len);
}
References pi_dumpdata().
Referenced by sys_rx(), and sys_tx().
sys_dump_header()
void sys_dump_header (const unsigned char * data, int rxtx)
{
    LOG((PI_DBG_SYS, PI_DBG_LVL_NONE,
        "SYS %s\n", rxtx ? "TX" : "RX"));
}
Referenced by sys_rx(), and sys_tx().
sys_flush()
static int sys_flush (pi_socket_t * ps, int flags) static
{
    pi_protocol_t   *prot,
            *next;
    prot = pi_protocol(ps->sd, PI_LEVEL_SYS);
    if (prot == NULL)
        return pi_set_error(ps->sd, PI_ERR_SOCK_INVALID);
    next = pi_protocol_next(ps->sd, PI_LEVEL_SYS);
    if (next == NULL)
        return pi_set_error(ps->sd, PI_ERR_SOCK_INVALID);
    return next->flush(ps, flags);
}
References flags, pi_protocol(), pi_protocol_next(), and pi_set_error().
Referenced by sys_protocol().
sys_getsockopt()
static int sys_getsockopt (pi_socket_t * ps, int level, int option_name, void * option_value, size_t * option_len) static
{
    return 0;
}
Referenced by sys_protocol().
sys_protocol()
pi_protocol_t * sys_protocol (void)
{
    pi_protocol_t *prot = NULL;
    pi_sys_data_t *data = NULL;
    prot    = (pi_protocol_t *)malloc (sizeof (pi_protocol_t));
    if (prot != NULL) {
        data = (pi_sys_data_t *)malloc (sizeof (pi_sys_data_t));
        if (data == NULL) {
            free(prot);
            prot = NULL;
        }
    }
    if (prot != NULL && data != NULL) {
        prot->level     = PI_LEVEL_SYS;
        prot->dup   = sys_protocol_dup;
        prot->free  = sys_protocol_free;
        prot->read  = sys_rx;
        prot->write     = sys_tx;
        prot->flush = sys_flush;
        prot->getsockopt = sys_getsockopt;
        prot->setsockopt = sys_setsockopt;
        data->txid  = 0x00;
        prot->data  = data;
    }
    return prot;
}
References sys_flush(), sys_getsockopt(), sys_protocol_dup(), sys_protocol_free(), sys_rx(), sys_setsockopt(), and sys_tx().
Referenced by protocol_queue_build().
sys_protocol_dup()
static pi_protocol_t * sys_protocol_dup (pi_protocol_t * prot) static
{
    pi_protocol_t *new_prot = NULL;
    pi_sys_data_t   *data = NULL,
            *new_data = NULL;
    new_prot = (pi_protocol_t *)malloc (sizeof (pi_protocol_t));
    if (new_prot != NULL) {
        new_data = (pi_sys_data_t *)malloc (sizeof (pi_sys_data_t));
        if (new_data == NULL) {
            free(new_prot);
            new_prot = NULL;
        }
    }
    if (new_prot != NULL && new_data != NULL) {
        new_prot->level = prot->level;
        new_prot->dup   = prot->dup;
        new_prot->free  = prot->free;
        new_prot->read  = prot->read;
        new_prot->write = prot->write;
        new_prot->flush = prot->flush;
        new_prot->getsockopt    = prot->getsockopt;
        new_prot->setsockopt    = prot->setsockopt;
        data    = (pi_sys_data_t *)prot->data;
        new_data->txid  = data->txid;
        new_prot->data  = new_data;
    }
    return new_prot;
}
Referenced by sys_protocol().
sys_protocol_free()
static void sys_protocol_free (pi_protocol_t * prot) static
{
    ASSERT (prot != NULL);
    if (prot != NULL) {
        if (prot->data != NULL)
            free(prot->data);
        free(prot);
    }
}
Referenced by sys_protocol().
sys_rx()
ssize_t sys_rx (pi_socket_t * ps, pi_buffer_t * buf, size_t len, int flags)
{
    pi_protocol_t   *next,
            *prot;
    pi_sys_data_t *data;
    size_t  data_len;
    prot = pi_protocol(ps->sd, PI_LEVEL_SYS);
    if (prot == NULL)
        return pi_set_error(ps->sd, PI_ERR_SOCK_INVALID);
    data = (pi_sys_data_t *)prot->data;
    next = pi_protocol_next(ps->sd, PI_LEVEL_SYS);
    if (next == NULL)
        return pi_set_error(ps->sd, PI_ERR_SOCK_INVALID);
    data_len = next->read(ps, buf, len, flags);
    CHECK(PI_DBG_SYS, PI_DBG_LVL_INFO, sys_dump_header(buf->data, 0));
    CHECK(PI_DBG_SYS, PI_DBG_LVL_DEBUG, sys_dump(buf->data, data_len));
    return data_len;
}
References buf, flags, pi_protocol(), pi_protocol_next(), pi_set_error(), sys_dump(), and sys_dump_header().
Referenced by sys_protocol().
sys_setsockopt()
static int sys_setsockopt (pi_socket_t * ps, int level, int option_name, const void * option_value, size_t * option_len) static
{
    return 0;
}
Referenced by sys_protocol().
sys_tx()
ssize_t sys_tx (pi_socket_t * ps, const unsigned char * buf, size_t len, int flags)
{
    pi_protocol_t   *prot,
            *next;
    pi_sys_data_t *data;
    int     type,
        socket;
    size_t  size;
    prot = pi_protocol(ps->sd, PI_LEVEL_SYS);
    if (prot == NULL)
        return pi_set_error(ps->sd, PI_ERR_SOCK_INVALID);
    data = (pi_sys_data_t *)prot->data;
    next = pi_protocol_next(ps->sd, PI_LEVEL_SYS);
    if (next == NULL)
        return pi_set_error(ps->sd, PI_ERR_SOCK_INVALID);
    if (!data->txid || data->txid == 0xff)
        data->txid = 0x11;  /* some random # */
    data->txid++;
    if (!data->txid || data->txid == 0xff)
        data->txid = 0x11;  /* some random # */
    type    = PI_SLP_TYPE_RDCP;
    /* Fix me, allow socket type */
    socket  = PI_SLP_SOCK_CON;
    size    = sizeof(type);
    pi_setsockopt(ps->sd, PI_LEVEL_SLP, PI_SLP_TYPE,
              &type, &size);
    pi_setsockopt(ps->sd, PI_LEVEL_SLP, PI_SLP_DEST,
              &socket, &size);
    pi_setsockopt(ps->sd, PI_LEVEL_SLP, PI_SLP_SRC,
              &socket, &size);
    size = sizeof(data->txid);
    pi_setsockopt(ps->sd, PI_LEVEL_SLP, PI_SLP_TXID,
              &data->txid, &size);
    len = next->write(ps, buf, len, flags);
    if (len >= 0) {
        CHECK(PI_DBG_SYS, PI_DBG_LVL_INFO, sys_dump_header(buf, 1));
        CHECK(PI_DBG_SYS, PI_DBG_LVL_DEBUG, sys_dump(buf, len));
    }
    return len;
}
References buf, flags, pi_protocol(), pi_protocol_next(), pi_set_error(), pi_setsockopt(), size, sys_dump(), and sys_dump_header().
Referenced by sys_protocol().