pilot-link: libpisock/syspkt.c File Reference
syspkt.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include "pi-source.h"
#include "pi-syspkt.h"
#include "pi-slp.h"
#include "pi-serial.h"
#include "pi-error.h"
Functions
unsigned long DoRPC (int sd, int sockaddr, struct RPC_params *p, int *error)
void InvertRPC (struct RPC_params *p)
int PackRPC (struct RPC_params *p, int trap, int reply,...)
int RPC (int sd, int sockaddr, int trap, int reply,...)
int RPC_Int_Void (int sd, int trap)
int RPC_Ptr_Void (int sd, int trap)
int sys_Continue (int sd, struct Pilot_registers *r, struct Pilot_watch *w)
int sys_Find (int sd, unsigned long startaddr, unsigned long stopaddr, size_t len, int caseinsensitive, void *data, unsigned long *found)
int sys_GetTrapBreaks (int sd, int *traps)
static int sys_PackRegisters (void *data, struct Pilot_registers *r)
int sys_QueryState (int sd)
int sys_ReadMemory (int sd, unsigned long addr, unsigned long len, void *dest)
int sys_RemoteEvent (int sd, int penDown, int x, int y, int keypressed, int keymod, int keyasc, int keycode)
int sys_RPC (int sd, int sockaddr, int trap, long *D0, long *A0, int params, struct RPC_param *param, int reply)
int sys_SetBreakpoints (int sd, struct Pilot_breakpoint *b)
int sys_SetTrapBreaks (int sd, int *traps)
int sys_Step (int sd)
int sys_ToggleDbgBreaks (int sd)
int sys_UnpackRegisters (void *data, struct Pilot_registers *r)
int sys_UnpackState (void *buffer, struct Pilot_state *s)
int sys_WriteMemory (int sd, unsigned long addr, unsigned long len, void *src)
void UninvertRPC (struct RPC_params *p)
Function Documentation
DoRPC()
unsigned long DoRPC (int sd, int sockaddr, struct RPC_params * p, int * error)
{
    int     err;
    long    D0 = 0,
        A0 = 0;
    InvertRPC(p);
    err =
        sys_RPC(sd, sockaddr, p->trap, &D0, &A0, p->args, &p->param[0],
            p->reply);
    UninvertRPC(p);
    if (error)
        *error = err;
    if (p->reply == RPC_PtrReply)
        return A0;
    else if (p->reply == RPC_IntReply)
        return D0;
    else
        return err;
}
References InvertRPC(), sd, sys_RPC(), and UninvertRPC().
Referenced by DbgAttach(), DbgAttachConsole(), DbgGetDeviceVersion(), and DbgRPC().
InvertRPC()
void InvertRPC (struct RPC_params * p)
{
    int     j;
    for (j = 0; j < p->args; j++) {
        if (p->param[j].invert) {
            void *c = p->param[j].data;
            if ((p->param[j].invert == 2)
                && (p->param[j].size == 2)) {
                int *s = c;
                *s = ntohs(*s) >> 8;
            } else if (p->param[j].size == 2) {
                int *s = c;
                *s = ntohs(*s);
            } else {
                long *l = c;
                *l = ntohl((unsigned) *l);
            }
        }
    }
}
Referenced by DoRPC().
PackRPC()
int PackRPC (struct RPC_params * p, int trap, int reply, ...)
{
    int     idx = 0;
    va_list ap;
    p->trap = trap;
    p->reply = reply;
    va_start(ap, reply);
    for (;;) {
        int type = (int) va_arg(ap, int);
        if (type == 0)
            break;
        if (type < 0) {
            p->param[idx].byRef     = 0;
            p->param[idx].size  = -type;
            p->param[idx].arg   = (int) va_arg(ap, int);
            p->param[idx].data  = &p->param[idx].arg;
            p->param[idx].invert    = 0;
        } else {
            void *c = (void *) va_arg(ap, void *);
            p->param[idx].byRef     = 1;
            p->param[idx].size  = type;
            p->param[idx].data  = c;
            p->param[idx].invert    = (int) va_arg(ap, int);
        }
        idx++;
    }
    p->args = idx;
    va_end(ap);
    return 0;
}
Referenced by DbgAttach(), DbgAttachConsole(), DbgGetDeviceVersion(), dlp_GetROMToken(), do_get_ram(), do_get_rom(), GetClip(), proc_battery(), proc_coldboot(), proc_feature(), proc_getdisplay(), proc_mirror(), proc_pushbutton(), proc_sendscreen(), proc_updatedisplay(), proc_warmboot(), and SetClip().
RPC()
int RPC (int sd, int sockaddr, int trap, int reply, ...)
{
    int     idx     = 0,
        j,
        RPC_arg[20];
    va_list ap;
    struct  RPC_param p[20];
    long    D0  = 0,
        A0  = 0;
    va_start(ap, reply);
    for (;;) {
        int type = va_arg(ap, int);
        if (type == 0)
            break;
        if (type < 0) {
            p[idx].byRef    = 0;
            p[idx].size     = -type;
            RPC_arg[idx]    = va_arg(ap, int);
            p[idx].data     = &RPC_arg[idx];
            p[idx].invert   = 0;
        } else {
            void *c = va_arg(ap, void *);
            p[idx].byRef    = 1;
            p[idx].size     = type;
            p[idx].data     = c;
            p[idx].invert   = va_arg(ap, int);
            if (p[idx].invert) {
                if (p[idx].size == 2) {
                    int *s = c;
                    *s = htons(*s);
                } else {
                    int *l = c;
                    *l = htonl(*l);
                }
            }
        }
        idx++;
    }
    va_end(ap);
    if (sys_RPC(sd, sockaddr, trap, &D0, &A0, idx, p, reply != 2) < 0)
        return pi_error(sd);
    for (j = 0; j < idx; j++) {
        if (p[j].invert) {
            void *c = p[j].data;
            if (p[j].size == 2) {
                int *s = c;
                *s = htons(*s);
            } else {
                int *l = c;
                *l = htonl(*l);
            }
        }
    }
    if (reply)
        return A0;
    return D0;
}
References pi_error(), sd, size, and sys_RPC().
Referenced by read_user(), RPC_Int_Void(), and RPC_Ptr_Void().
RPC_Int_Void()
int RPC_Int_Void (int sd, int trap)
{
    return RPC(sd, 1, trap, 0, RPC_End);
}
References RPC(), and sd.
RPC_Ptr_Void()
int RPC_Ptr_Void (int sd, int trap)
{
    return RPC(sd, 1, trap, 1, RPC_End);
}
References RPC(), and sd.
sys_Continue()
int sys_Continue (int sd, struct Pilot_registers * r, struct Pilot_watch * w)
{
    char    buf[94];
    buf[0]  = 0;
    buf[1]  = 0;
    buf[2]  = 0;
    buf[3]  = 0;
    buf[4]  = 0x07;
    buf[5]  = 0;        /* gapfill */
    if (!r)
        return pi_write(sd, buf, 6);
    sys_PackRegisters(buf + 6, r);
    set_byte(buf + 80, (w != 0) ? 1 : 0);
    set_byte(buf + 81, 0);
    set_long(buf + 82, w ? w->address : 0);
    set_long(buf + 86, w ? w->length : 0);
    set_long(buf + 90, w ? w->checksum : 0);
    return pi_write(sd, buf, 94);
}
References buf, pi_write(), sd, and sys_PackRegisters().
Referenced by proc_g(), and proc_t().
sys_Find()
int sys_Find (int sd, unsigned long startaddr, unsigned long stopaddr, size_t len, int caseinsensitive, void * data, unsigned long * found)
{
    int     result;
    unsigned char byte;
    pi_buffer_t *buf;
    buf = pi_buffer_new (len + 17);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    buf->data[0] = 0;
    buf->data[1] = 0;
    buf->data[2] = 0;
    buf->data[3] = 0;
    buf->data[4] = 0x11;
    buf->data[5] = 0;       /* gapfill */
    set_long(buf->data + 6, startaddr);
    set_long(buf->data + 10, stopaddr);
    set_short(buf->data + 14, len);
    set_byte(buf->data + 16, caseinsensitive);
    memcpy(buf->data + 17, data, len);
    pi_write(sd, buf->data, len + 17);
    result = pi_read(sd, buf, 12);
    if (result < 0) {
        pi_buffer_free (buf);
        return result;
    }
    if (found)
        *found = get_long(buf->data + 6);
    byte = get_byte(buf->data + 10);
    pi_buffer_free (buf);
    return byte;
}
References buf, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), and sd.
sys_GetTrapBreaks()
int sys_GetTrapBreaks (int sd, int * traps)
{
    int     idx;
    pi_buffer_t *buf;
    buf = pi_buffer_new (32);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    buf->data[0] = 0;
    buf->data[1] = 0;
    buf->data[2] = 0;
    buf->data[3] = 0;
    buf->data[4] = 0x10;
    buf->data[5] = 0;       /* gapfill */
    pi_write(sd, buf->data, 6);
    idx = pi_read(sd, buf, 16);
    if ((idx < 16) || (buf->data[4] != (unsigned char) 0x90)) {
        pi_buffer_free (buf);
        return 0;
    }
    for (idx = 0; idx < 5; idx++) {
        traps[idx] = get_short(buf->data + 6 + idx * 2);
    }
    pi_buffer_free (buf);
    return 1;
}
References buf, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), and sd.
sys_PackRegisters()
static int sys_PackRegisters (void * data, struct Pilot_registers * r) static
{
    int     idx;
    unsigned char *buffer = data;
    for (idx = 0; idx < 8; idx++)
        set_long(buffer + idx * 4, r->D[idx]);
    for (idx = 0; idx < 7; idx++)
        set_long(buffer + 32 + idx * 4, r->A[idx]);
    set_long(buffer + 60, r->USP);
    set_long(buffer + 64, r->SSP);
    set_long(buffer + 68, r->PC);
    set_short(buffer + 72, r->SR);
    return 0;
}
References buffer.
Referenced by sys_Continue().
sys_QueryState()
int sys_QueryState (int sd)
{
    char    buf[6];
    buf[0] = 0;
    buf[1] = 0;
    buf[2] = 0;
    buf[3] = 0;
    buf[4] = 0;
    buf[5] = 0;     /* gapfill */
    return pi_write(sd, buf, 2);
}
References buf, pi_write(), and sd.
Referenced by DbgAttach(), and DbgAttachDebugger().
sys_ReadMemory()
int sys_ReadMemory (int sd, unsigned long addr, unsigned long len, void * dest)
{
    int     result;
    unsigned long todo, done;
    pi_buffer_t *buf;
    buf = pi_buffer_new (0xFFFF);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    done = 0;
    do {
        todo    = len;
        if (todo > 256)
            todo = 256;
        buf->data[0] = 0;
        buf->data[1] = 0;
        buf->data[2] = 0;
        buf->data[3] = 0;
        buf->data[4] = 0x01;
        buf->data[5] = 0;   /* gapfill */
        set_long(buf->data + 6, addr + done);
        set_short(buf->data + 10, todo);
        pi_write(sd, buf->data, 12);
        result = pi_read(sd, buf, todo + 6);
        if (result < 0) {
            pi_buffer_free (buf);
            return done;
        }
        if ((buf->data[4] == 0x81)
            && ((unsigned int) result == todo + 6)) {
            memcpy(((char *) dest) + done, buf->data + 6, todo);
            done += todo;
        } else {
            pi_buffer_free (buf);
            return done;
        }
    } while (done < len);
    pi_buffer_free (buf);
    return done;
}
References buf, done, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), and sd.
Referenced by proc_getdisplay().
sys_RemoteEvent()
int sys_RemoteEvent (int sd, int penDown, int x, int y, int keypressed, int keymod, int keyasc, int keycode)
{
    char    buf[16];
    /* Offset 1, 3 and 9 are padding */
    set_byte(&buf[0], 0x0D); /* RemoteEvtCommand    */
    set_byte(&buf[1], 0);
    set_byte(&buf[2], penDown);
    set_byte(&buf[3], 0);
    set_short(&buf[4], x);
    set_short(&buf[6], y);
    set_byte(&buf[8], keypressed);
    set_byte(&buf[9], 0);
    set_short(&buf[10], keymod);
    set_short(&buf[12], keyasc);
    set_short(&buf[14], keycode);
    return pi_write(sd, buf, 16);
}
References buf, pi_write(), and sd.
Referenced by proc_key(), proc_pen(), and read_user().
sys_RPC()
int sys_RPC (int sd, int sockaddr, int trap, long * D0, long * A0, int params, struct RPC_param * param, int reply)
{
    int     idx;
    unsigned char *c;
    pi_buffer_t *buf;
    buf = pi_buffer_new (4096);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    buf->data[0] = sockaddr;    /* 0 for debug, 1 for console */
    buf->data[1] = sockaddr;
    buf->data[2] = 0;
    buf->data[4] = 0x0a;
    buf->data[5] = 0;
    set_short(buf->data + 6, trap);
    set_long(buf->data + 8, *D0);
    set_long(buf->data + 12, *A0);
    set_short(buf->data + 16, params);
    c = buf->data + 18;
    for (idx = params - 1; idx >= 0; idx--) {
        set_byte(c, param[idx].byRef);
        c++;
        set_byte(c, param[idx].size);
        c++;
        if (param[idx].data)
            memcpy(c, param[idx].data, param[idx].size);
        c += param[idx].size;
        if (param[idx].size & 1)
            *c++ = 0;
    }
    if (sockaddr == 3)
        set_short(buf->data + 4, c - buf->data - 6);
    pi_write(sd, buf->data + 4,(size_t)(c - buf->data - 4));
    if (reply) {
        int l = pi_read(sd, buf, 4096);
        if (l < 0) {
            pi_buffer_free (buf);
            return l;
        }
        if (buf->data[0] != (unsigned char)0x8a) {
            pi_buffer_free (buf);
            return pi_set_error(sd, -2);
        }
        *D0 = get_long(buf->data + 4);
        *A0 = get_long(buf->data + 8);
        c = buf->data + 14;
        for (idx = params - 1; idx >= 0; idx--) {
            if (param[idx].byRef && param[idx].data)
                memcpy(param[idx].data, c + 2,
                       param[idx].size);
            c += 2 + ((get_byte(c + 1) + 1) & ~1);
        }
    }
    pi_buffer_free (buf);
    return 0;
}
References buf, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), sd, and size.
Referenced by DoRPC(), and RPC().
sys_SetBreakpoints()
int sys_SetBreakpoints (int sd, struct Pilot_breakpoint * b)
{
    int     idx;
    pi_buffer_t *buf;
    buf = pi_buffer_new (94);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    buf->data[0] = 0;
    buf->data[1] = 0;
    buf->data[2] = 0;
    buf->data[3] = 0;
    buf->data[4] = 0x0c;
    buf->data[5] = 0;       /* gapfill */
    for (idx = 0; idx < 6; idx++) {
        set_long(buf->data + 6 + idx * 6, b[idx].address);
        set_byte(buf->data + 10 + idx * 6, b[idx].enabled);
        set_byte(buf->data + 11 + idx * 6, 0);
    }
    pi_write(sd, buf->data, 42);
    idx = pi_read(sd, buf, 6);
    if (idx <= 0 || buf->data[4] != (unsigned char) 0x8c) {
        pi_buffer_free (buf);
        return 0;
    }
    pi_buffer_free (buf);
    return 1;
}
References buf, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), and sd.
Referenced by SetBreakpoint().
sys_SetTrapBreaks()
int sys_SetTrapBreaks (int sd, int * traps)
{
    int     idx;
    pi_buffer_t *buf;
    buf = pi_buffer_new (32);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    buf->data[0] = 0;
    buf->data[1] = 0;
    buf->data[2] = 0;
    buf->data[3] = 0;
    buf->data[4] = 0x11;
    buf->data[5] = 0;       /* gapfill */
    for (idx = 0; idx < 5; idx++) {
        set_short(buf->data + 6 + idx * 2, traps[idx]);
    }
    pi_write(sd, buf->data, 16);
    idx = pi_read(sd, buf, 6);
    if ((idx <= 0) || (buf->data[4] != (unsigned char) 0x91)) {
        pi_buffer_free (buf);
        return 0;
    }
    pi_buffer_free (buf);
    return 1;
}
References buf, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), and sd.
sys_Step()
int sys_Step (int sd)
{
    char    buf[94];
    buf[0] = 0;
    buf[1] = 0;
    buf[2] = 0;
    buf[3] = 0;
    buf[4] = 0x03;
    buf[5] = 0;     /* gapfill */
    return pi_write(sd, buf, 6);
}
References buf, pi_write(), and sd.
sys_ToggleDbgBreaks()
int sys_ToggleDbgBreaks (int sd)
{
    int     idx;
    pi_buffer_t *buf;
    unsigned char byte;
    buf = pi_buffer_new (32);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    buf->data[0] = 0;
    buf->data[1] = 0;
    buf->data[2] = 0;
    buf->data[3] = 0;
    buf->data[4] = 0x0d;
    buf->data[5] = 0;       /* gapfill */
    pi_write(sd, buf->data, 6);
    idx = pi_read(sd, buf, 7);
    if ((idx < 7) || (buf->data[4] != (unsigned char) 0x8d)) {
        pi_buffer_free (buf);
        return 0;
    }
    byte = get_byte(buf->data + 6);
    pi_buffer_free (buf);
    return byte;
}
References buf, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), and sd.
sys_UnpackRegisters()
int sys_UnpackRegisters (void * data, struct Pilot_registers * r)
{
    unsigned char *buffer = data;
    r->D[0] = get_long(buffer + 0);
    r->D[1] = get_long(buffer + 4);
    r->D[2] = get_long(buffer + 8);
    r->D[3] = get_long(buffer + 12);
    r->D[4] = get_long(buffer + 16);
    r->D[5] = get_long(buffer + 20);
    r->D[6] = get_long(buffer + 24);
    r->D[7] = get_long(buffer + 28);
    r->A[0] = get_long(buffer + 32);
    r->A[1] = get_long(buffer + 36);
    r->A[2] = get_long(buffer + 40);
    r->A[3] = get_long(buffer + 44);
    r->A[4] = get_long(buffer + 48);
    r->A[5] = get_long(buffer + 52);
    r->A[6] = get_long(buffer + 56);
    r->USP  = get_long(buffer + 60);
    r->SSP  = get_long(buffer + 64);
    r->PC   = get_long(buffer + 68);
    r->SR   = get_short(buffer + 72);
    return 0;
}
References buffer.
Referenced by sys_UnpackState().
sys_UnpackState()
int sys_UnpackState (void * buffer, struct Pilot_state * s)
{
    int     idx;
    unsigned char *data = buffer;
    s->reset        = get_short(data);
    s->exception        = get_short(data + 2);
    memcpy(s->func_name, data + 152, 32);
    memcpy(s->instructions, data + 78, 30);
    s->func_name[32 - 1]    = 0;
    s->func_start       = get_long(data + 144);
    s->func_end         = get_long(data + 148);
    sys_UnpackRegisters(data + 4, &s->regs);
    for (idx = 0; idx < 6; idx++) {
        s->breakpoint[idx].address = get_long(data + 108 + idx * 6);
        s->breakpoint[idx].enabled = get_byte(data + 112 + idx * 6);
    }
    s->trap_rev = get_short(data + 184);
    return 0;
}
References buffer, and sys_UnpackRegisters().
Referenced by Read_Pilot().
sys_WriteMemory()
int sys_WriteMemory (int sd, unsigned long addr, unsigned long len, void * src)
{
    int     result;
    unsigned long todo, done;
    pi_buffer_t *buf;
    buf = pi_buffer_new (0xFFFF);
    if (buf == NULL) {
        errno = ENOMEM;
        return pi_set_error(sd, PI_ERR_GENERIC_MEMORY);
    }
    done = 0;
    do {
        todo = len;
        if (todo > 256)
            todo = 256;
        buf->data[0] = 0;
        buf->data[1] = 0;
        buf->data[2] = 0;
        buf->data[3] = 0;
        buf->data[4] = 0x02;
        buf->data[5] = 0;   /* gapfill */
        set_long(buf->data + 6, addr);
        set_short(buf->data + 10, len);
        memcpy(buf->data + 12, (char *)src + done, todo);
        pi_write(sd, buf->data, len + 12);
        result = pi_read(sd, buf, 6);
        if (result < 0) {
            pi_buffer_free (buf);
            return done;
        }
        if ((buf->data[4] == (unsigned char)0x82)
            && ((unsigned long) result == todo + 6)) {
            ;
        } else {
            pi_buffer_free (buf);
            return done;
        }
    } while (done < len);
    pi_buffer_free (buf);
    return done;
}
References buf, done, pi_buffer_free(), pi_buffer_new(), pi_read(), pi_set_error(), pi_write(), and sd.
UninvertRPC()
void UninvertRPC (struct RPC_params * p)
{
    int     j;
    for (j = 0; j < p->args; j++) {
        if (p->param[j].invert) {
            void *c = p->param[j].data;
            if ((p->param[j].invert == 2)
                && (p->param[j].size == 2)) {
                int *s = c;
                *s = htons(*s) >> 8;
            } else if (p->param[j].size == 2) {
                int *s = c;
                *s = htons(*s);
            } else {
                long *l = c;
                *l = htonl(*l);
            }
        }
    }
}
Referenced by DoRPC().