pilot-link: libpisock/threadsafe.c File Reference
threadsafe.c File Reference
#include "pi-threadsafe.h"
Functions
int pi_mutex_lock (pi_mutex_t *mutex)
int pi_mutex_trylock (pi_mutex_t *mutex)
int pi_mutex_unlock (pi_mutex_t *mutex)
unsigned long pi_thread_id ()
Function Documentation
pi_mutex_lock()
int pi_mutex_lock (pi_mutex_t * mutex)
{
#if HAVE_PTHREAD
    return pthread_mutex_lock(mutex);
#else
    return 0;
#endif
}
Referenced by find_pi_socket(), onalarm(), onexit(), pi_close(), pi_debug_set_file(), pi_debug_set_level(), pi_log(), pi_socket_recognize(), and pi_watchdog().
pi_mutex_trylock()
int pi_mutex_trylock (pi_mutex_t * mutex)
{
#if HAVE_PTHREAD
    return pthread_mutex_trylock(mutex);
#else
    return 0;
#endif
}
pi_mutex_unlock()
int pi_mutex_unlock (pi_mutex_t * mutex)
{
#if HAVE_PTHREAD
    return pthread_mutex_unlock(mutex);
#else
    return 0;
#endif
}
Referenced by find_pi_socket(), onalarm(), onexit(), pi_close(), pi_debug_set_file(), pi_debug_set_level(), pi_log(), pi_socket_recognize(), and pi_watchdog().
pi_thread_id()
unsigned long pi_thread_id ()
{
#if HAVE_PTHREAD
    return (unsigned long)pthread_self();
#else
    return 0;
#endif
}
Referenced by pi_log().