pilot-link: bindings/Tcl/tkAppInit.c File Reference
tkAppInit.c File Reference
#include "tk.h"
Functions
EXTERN int Pitcl_Init _ANSI_ARGS_ ((Tcl_Interp *interp))
int main (int argc, char **argv)
int matherr ()
int Tcl_AppInit (Tcl_Interp *interp)
Variables
int * tclDummyMathPtr = (int *) matherr
Function Documentation
_ANSI_ARGS_()
EXTERN int Pitcl_Init _ANSI_ARGS_ ((Tcl_Interp *interp))
main()
int main (int argc, char ** argv)
{
    Tk_Main(argc, argv, Tcl_AppInit);
    return 0;           /* Needed only to prevent compiler warning. */
}
References Tcl_AppInit().
matherr()
int matherr () extern
Tcl_AppInit()
int Tcl_AppInit (Tcl_Interp * interp)
{
    if (Tcl_Init(interp) == TCL_ERROR) {
    return TCL_ERROR;
    }
    if (Tk_Init(interp) == TCL_ERROR) {
    return TCL_ERROR;
    }
    if (Pitcl_Init(interp) == TCL_ERROR) {
        return TCL_ERROR;
    }
    Tcl_StaticPackage(interp, "Tk", Tk_Init, (Tcl_PackageInitProc *) NULL);
#ifdef TK_TEST
    if (Tktest_Init(interp) == TCL_ERROR) {
    return TCL_ERROR;
    }
    Tcl_StaticPackage(interp, "Tktest", Tktest_Init,
            (Tcl_PackageInitProc *) NULL);
#endif /* TK_TEST */
    /*
     * Call the init procedures for included packages.  Each call should
     * look like this:
     *
     * if (Mod_Init(interp) == TCL_ERROR) {
     *     return TCL_ERROR;
     * }
     *
     * where "Mod" is the name of the module.
     */
    /*
     * Call Tcl_CreateCommand for application-specific commands, if
     * they weren't already created by the init procedures called above.
     */
    /*
     * Specify a user-specific startup file to invoke if the application
     * is run interactively.  Typically the startup file is "~/.apprc"
     * where "app" is the name of the application.  If this line is deleted
     * then no user-specific startup file will be run under any conditions.
     */
    Tcl_SetVar(interp, "tcl_rcFileName", "~/.piwishrc", TCL_GLOBAL_ONLY);
    return TCL_OK;
}
References interp, and Pitcl_Init().
Referenced by main().
Variable Documentation
tclDummyMathPtr
int* tclDummyMathPtr = (int *) matherr