pilot-link: libpisock/todo.c File Reference
todo.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "pi-macros.h"
#include "pi-todo.h"
Macros
#define DescMaxLength 256
#define NoteMaxLength 4096
Functions
void free_ToDo (ToDo_t *todo)
int pack_ToDo (const ToDo_t *todo, pi_buffer_t *buf, todoType type)
int pack_ToDoAppInfo (const ToDoAppInfo_t *appinfo, unsigned char *record, size_t len)
int unpack_ToDo (ToDo_t *todo, const pi_buffer_t *buf, todoType type)
int unpack_ToDoAppInfo (ToDoAppInfo_t *appinfo, const unsigned char *record, size_t len)
Macro Definition Documentation
DescMaxLength
#define DescMaxLength 256
NoteMaxLength
#define NoteMaxLength 4096
Function Documentation
free_ToDo()
void free_ToDo (ToDo_t * todo)
{
    if (todo->description != NULL) {
        free(todo->description);
        todo->description = NULL;
    }
    if (todo->note != NULL) {
        free(todo->note);
        todo->note = NULL;
    }
}
Referenced by main(), and todos().
pack_ToDo()
int pack_ToDo (const ToDo_t * todo, pi_buffer_t * buf, todoType type)
{
    int pos;
    size_t destlen = 3;
    if (todo == NULL || buf == NULL)
        return -1;
    if (type != todo_v1)
        return -1;
    if (todo->description)
        destlen += strlen(todo->description);
    destlen++;
    if (todo->note)
        destlen += strlen(todo->note);
    destlen++;
    pi_buffer_expect (buf, destlen);
    buf->used = destlen;
    if (todo->indefinite) {
        buf->data[0] = 0xff;
        buf->data[1] = 0xff;
    } else {
        set_short(buf->data,
              ((todo->due.tm_year - 4) << 9) | ((todo->due.tm_mon +
                              1) << 5) | todo->
              due.tm_mday);
    }
    buf->data[2] = todo->priority;
    if (todo->complete) {
        buf->data[2] |= 0x80;
    }
    pos = 3;
    if (todo->description) {
        strcpy((char *) buf->data + pos, todo->description);
        pos += strlen(todo->description) + 1;
    } else {
        buf->data[pos++] = 0;
    }
    if (todo->note) {
        strcpy((char *) buf->data + pos, todo->note);
        pos += strlen(todo->note) + 1;
    } else {
        buf->data[pos++] = 0;
    }
    return 0;
}
References buf, and pi_buffer_expect().
Referenced by install_ToDo(), install_ToDos(), and todos().
pack_ToDoAppInfo()
int pack_ToDoAppInfo (const ToDoAppInfo_t * appinfo, unsigned char * record, size_t len)
{
    int i;
    unsigned char *start = record;
    i = pack_CategoryAppInfo(&appinfo->category, record, len);
    if (!record)
        return i + 4;
    if (!i)
        return 0;
    record += i;
    len -= i;
    if (len < 4)
        return 0;
    set_short(record, appinfo->dirty);
    set_byte(record + 2, appinfo->sortByPriority);
    set_byte(record + 3, 0);    /* gapfill */
    record += 4;
    return (record - start);
}
References pack_CategoryAppInfo().
unpack_ToDo()
int unpack_ToDo (ToDo_t * todo, const pi_buffer_t * buf, todoType type)
{
    unsigned long d;
    int ofs;
    /* Note: There are possible timezone conversion problems related to
       the use of the due member of a struct ToDo. As it is kept in
       local (wall) time in struct tm's, the timezone of the Palm is
       irrelevant, _assuming_ that any UNIX program keeping time in
       time_t's converts them to the correct local time. If the Palm is
       in a different timezone than the UNIX box, it may not be simple
       to deduce that correct (desired) timezone.
       The easiest solution is to keep apointments in struct tm's, and
       out of time_t's. Of course, this might not actually be a help if
       you are constantly darting across timezones and trying to keep
       appointments.
       -- KJA */
    if (type != todo_v1)
        return -1;
    if (buf == NULL || buf->data == NULL || buf->used < 3)
        return -1;
    d = (unsigned short int) get_short(buf->data);
    if (d != 0xffff) {
        todo->due.tm_year = (d >> 9) + 4;
        todo->due.tm_mon = ((d >> 5) & 15) - 1;
        todo->due.tm_mday = d & 31;
        todo->due.tm_hour = 0;
        todo->due.tm_min = 0;
        todo->due.tm_sec = 0;
        todo->due.tm_isdst = -1;
        mktime(&todo->due);
        todo->indefinite = 0;
    } else {
        todo->indefinite = 1;   /* todo->due is invalid */
    }
    todo->priority = get_byte(buf->data + 2);
    if (todo->priority & 0x80) {
        todo->complete = 1;
        todo->priority &= 0x7f;
    } else {
        todo->complete = 0;
    }
    ofs = 3;
    if (buf->used - ofs < 1)
        return -1;
    todo->description = strdup((char *) buf->data + ofs);
    ofs += strlen(todo->description) + 1;
    if (buf->used - ofs < 1) {
        free(todo->description);
        todo->description = 0;
        return -1;
    }
    todo->note = strdup((char *) buf->data + ofs);
    return 0;
}
References buf, and strdup().
Referenced by main(), and todos().
unpack_ToDoAppInfo()
int unpack_ToDoAppInfo (ToDoAppInfo_t * appinfo, const unsigned char * record, size_t len)
{
    int i;
    unsigned char *start = record;
    appinfo->type = todo_v1;
    i = unpack_CategoryAppInfo(&appinfo->category, record, len);
    if (!i)
        return 0;
    record += i;
    len -= i;
    if (len < 4)
        return 0;
    appinfo->dirty = get_short(record);
    record += 2;
    appinfo->sortByPriority = get_byte(record);
    record += 2;
    return (record - start);
}
References unpack_CategoryAppInfo().
Referenced by main().