pilot-link: libpisock/unixserial.c File Reference
unixserial.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
#include <string.h>
#include "pi-debug.h"
#include "pi-source.h"
#include "pi-serial.h"
#include "pi-error.h"
Macros
#define cfmakeraw(ptr)
#define O_NONBLOCK 0
Functions
static speed_t calcrate (int baudrate)
static int cfsetspeed (struct termios *t, int speed)
void pi_serial_impl_init (struct pi_serial_impl *impl)
static int s_changebaud (pi_socket_t *ps)
static int s_close (pi_socket_t *ps)
static int s_flush (pi_socket_t *ps, int flags)
static int s_open (pi_socket_t *ps, struct pi_sockaddr *addr, size_t addrlen)
static int s_poll (pi_socket_t *ps, int timeout)
static ssize_t s_read (pi_socket_t *ps, pi_buffer_t *buf, size_t len, int flags)
static size_t s_read_buf (pi_socket_t *ps, pi_buffer_t *buf, size_t len, int flags)
static ssize_t s_write (pi_socket_t *ps, const unsigned char *buf, size_t len, int flags)
Macro Definition Documentation
cfmakeraw
#define cfmakeraw (ptr)
Value:
                     (ptr)->c_iflag &= ~(IGNBRK|BRKINT|PARMRK|ISTRIP|INLCR\
                     |IGNCR|ICRNL|IXON);\
                       (ptr)->c_oflag &= ~OPOST;\
                       (ptr)->c_lflag &= ~(ECHO|ECHONL|ICANON|ISIG|IEXTEN);\
                       (ptr)->c_cflag &= ~(CSIZE|PARENB);\
                       (ptr)->c_cflag |= CS8
#define cfmakeraw(ptr) (ptr)->c_iflag &= ~(IGNBRK|BRKINT|PARMRK|ISTRIP|INLCR\
                     |IGNCR|ICRNL|IXON);\
                       (ptr)->c_oflag &= ~OPOST;\
                       (ptr)->c_lflag &= ~(ECHO|ECHONL|ICANON|ISIG|IEXTEN);\
                       (ptr)->c_cflag &= ~(CSIZE|PARENB);\
                       (ptr)->c_cflag |= CS8
Referenced by s_open().
O_NONBLOCK
#define O_NONBLOCK 0
Referenced by s_flush(), and s_open().
Function Documentation
calcrate()
static speed_t calcrate (int baudrate) static
{
#ifdef B50
    if (baudrate == 50)
        return B50;
#endif
#ifdef B75
    if (baudrate == 75)
        return B75;
#endif
#ifdef B110
    if (baudrate == 110)
        return B110;
#endif
#ifdef B134
    if (baudrate == 134)
        return B134;
#endif
#ifdef B150
    if (baudrate == 150)
        return B150;
#endif
#ifdef B200
    if (baudrate == 200)
        return B200;
#endif
#ifdef B300
    if (baudrate == 300)
        return B300;
#endif
#ifdef B600
    if (baudrate == 600)
        return B600;
#endif
#ifdef B1200
    if (baudrate == 1200)
        return B1200;
#endif
#ifdef B1800
    if (baudrate == 1800)
        return B1800;
#endif
#ifdef B2400
    if (baudrate == 2400)
        return B2400;
#endif
#ifdef B4800
    if (baudrate == 4800)
        return B4800;
#endif
#ifdef B9600
    if (baudrate == 9600)
        return B9600;
#endif
#ifdef B19200
    else if (baudrate == 19200)
        return B19200;
#endif
#ifdef B38400
    else if (baudrate == 38400)
        return B38400;
#endif
#ifdef B57600
    else if (baudrate == 57600)
        return B57600;
#endif
#ifdef B76800
    else if (baudrate == 76800)
        return B76800;
#endif
#ifdef B115200
    else if (baudrate == 115200)
        return B115200;
#endif
#ifdef B230400
    else if (baudrate == 230400)
        return B230400;
#endif
#ifdef B460800
    else if (baudrate == 460800)
        return B460800;
#endif
    LOG((PI_DBG_DEV, PI_DBG_LVL_ERR,
        "DEV Serial CHANGEBAUD Unable to set baud rate %d\n",
        baudrate));
    abort();    /* invalid baud rate */
    return 0;
}
Referenced by s_changebaud(), and s_open().
cfsetspeed()
static int cfsetspeed (struct termios * t, int speed) static
{
#ifdef HAVE_TERMIOS_CSPEED
    t->c_ispeed = speed;
    t->c_ospeed = speed;
#else
    t->c_cflag |= speed;
#endif
    return 0;
}
Referenced by s_changebaud(), and s_open().
pi_serial_impl_init()
void pi_serial_impl_init (struct pi_serial_impl * impl)
{
    impl->open      = s_open;
    impl->close         = s_close;
    impl->changebaud    = s_changebaud;
    impl->write         = s_write;
    impl->read      = s_read;
    impl->flush     = s_flush;
    impl->poll      = s_poll;
}
References s_changebaud(), s_close(), s_flush(), s_open(), s_poll(), s_read(), and s_write().
Referenced by pi_serial_device().
s_changebaud()
static int s_changebaud (pi_socket_t * ps) static
{
    struct  pi_serial_data *data =
        (struct pi_serial_data *)ps->device->data;
#ifndef SGTTY
    struct  termios tcn;
    LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
        "DEV SPEED unixserial switch to %d bps\n", (int)data->rate));
#ifdef sleeping_beauty
    s_delay(0, 200000);
#endif
    /* Set the tty to the new speed */
    if (tcgetattr(ps->sd, &tcn))
        return pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
    tcn.c_cflag     = CREAD | CLOCAL | CS8;
    cfsetspeed(&tcn, calcrate(data->rate));
    if (tcsetattr(ps->sd, TCSADRAIN, &tcn))
        return pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
#else
    struct sgttyb tcn;
    if (ioctl(ps->sd, TIOCGETP, &tcn))
        return pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
    tcn.sg_ispeed   = calcrate(data->rate);
    tcn.sg_ospeed   = calcrate(data->rate);
    if (ioctl(ps->sd, TIOCSETN, &tcn))
        return pi_set_error(ps->sd, PI_ERR_GENERIC_SYSTEM);
#endif
#ifdef sleeping_beauty
    s_delay(0, 200000);
#endif
    return 0;
}
References calcrate(), cfsetspeed(), and pi_set_error().
Referenced by pi_serial_impl_init().
s_close()
static int s_close (pi_socket_t * ps) static
{
#ifdef sleeping_beauty
    s_delay(2, 0);
#endif
#if 0       /* previous test would never allow this code to execute */
 #ifndef SGTTY
    tcsetattr(ps->sd, TCSADRAIN, &data->tco);
 #else
    ioctl(ps->sd, TIOCSETP, &data->tco);
 #endif
#endif
    LOG((PI_DBG_DEV, PI_DBG_LVL_INFO,
        "DEV CLOSE unixserial fd: %d\n", ps->sd));
    return close(ps->sd);
}
Referenced by pi_serial_impl_init().
s_flush()
static int s_flush (pi_socket_t * ps, int flags) static
{
    int fl;
    char buf[256];
    struct pi_serial_data *data = (struct pi_serial_data *) ps->device->data;
    if (flags & PI_FLUSH_INPUT) {
        /* clear internal buffer */
        data->buf_size = 0;
        /* flush pending data (we assume the socket is in blocking mode) */
        if ((fl = fcntl(ps->sd, F_GETFL, 0)) != -1)
        {
            fcntl(ps->sd, F_SETFL, fl | O_NONBLOCK);
            while (recv(ps->sd, buf, sizeof(buf), 0) > 0)
                ;
            fcntl(ps->sd, F_SETFL, fl);
        }
        LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
            "DEV FLUSH unixserial flushed input buffer\n"));
    }
    return 0;
}
References buf, flags, and O_NONBLOCK.
Referenced by pi_serial_impl_init().
s_open()
int s_open (pi_socket_t * ps, struct pi_sockaddr * addr, size_t addrlen) static
{
    int     fd,
        i;
    char    *tty    = addr->pi_device;
    struct pi_serial_data *data =
        (struct pi_serial_data *)ps->device->data;
#ifndef SGTTY
    struct termios tcn;
#else
    struct sgttyb tcn;
#endif
    if ((fd = open(tty, O_RDWR | O_NONBLOCK)) < 0) {
        ps->last_error = PI_ERR_GENERIC_SYSTEM;
        return PI_ERR_GENERIC_SYSTEM;   /* errno already set */
    }
    if (!isatty(fd)) {
        close(fd);
        errno = EINVAL;
        ps->last_error = PI_ERR_GENERIC_SYSTEM;
        return PI_ERR_GENERIC_SYSTEM;
    }
#ifndef SGTTY
    /* Set the tty to raw and to the correct speed */
    tcgetattr(fd, &tcn);
    data->tco   = tcn;
    tcn.c_oflag     = 0;
    tcn.c_iflag     = IGNBRK | IGNPAR;
    tcn.c_cflag     = CREAD | CLOCAL | CS8;
    cfsetspeed(&tcn, calcrate(data->rate));
    tcn.c_lflag = NOFLSH;
    cfmakeraw(&tcn);
    for (i = 0; i < 16; i++)
        tcn.c_cc[i] = 0;
    tcn.c_cc[VMIN]  = 1;
    tcn.c_cc[VTIME] = 0;
    tcsetattr(fd, TCSANOW, &tcn);
#else
    /* Set the tty to raw and to the correct speed */
    ioctl(fd, TIOCGETP, &tcn);
    data->tco = tcn;
    tcn.sg_flags = RAW;
    tcn.sg_ispeed = calcrate(data->rate);
    tcn.sg_ospeed = calcrate(data->rate);
    ioctl(fd, TIOCSETN, &tcn);
#endif
    if ((i = fcntl(fd, F_GETFL, 0)) != -1) {
        i &= ~O_NONBLOCK;
        fcntl(fd, F_SETFL, i);
    }
    if ((i = pi_socket_setsd(ps, fd)) < 0)
        return i;
    return fd;
}
References calcrate(), cfmakeraw, cfsetspeed(), O_NONBLOCK, pi_socket_setsd(), and tty.
Referenced by pi_serial_impl_init().
s_poll()
static int s_poll (pi_socket_t * ps, int timeout) static
{
    struct  pi_serial_data *data =
         (struct pi_serial_data *)ps->device->data;
    struct  timeval t;
    fd_set  ready;
    FD_ZERO(&ready);
    FD_SET(ps->sd, &ready);
    /* If timeout == 0, wait forever for packet, otherwise wait till
       timeout milliseconds */
    if (timeout == 0)
        select(ps->sd + 1, &ready, 0, 0, 0);
    else {
        t.tv_sec    = timeout / 1000;
        t.tv_usec   = (timeout % 1000) * 1000;
        if (select(ps->sd + 1, &ready, 0, 0, &t) == 0)
            return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
    }
    if (!FD_ISSET(ps->sd, &ready)) {
        /* otherwise throw out any current packet and return */
        LOG((PI_DBG_DEV, PI_DBG_LVL_WARN,
            "DEV POLL unixserial timeout\n"));
        data->rx_errors++;
        errno = ETIMEDOUT;
        return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
    }
    LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
        "DEV POLL unixserial found data on fd: %d\n", ps->sd));
    return 0;
}
References pi_set_error().
Referenced by pi_serial_impl_init().
s_read()
static ssize_t s_read (pi_socket_t * ps, pi_buffer_t * buf, size_t len, int flags) static
{
    ssize_t rbuf = 0,
        bytes;
    struct  pi_serial_data *data =
        (struct pi_serial_data *)ps->device->data;
    struct  timeval t;
    fd_set  ready;
    /* check whether we have at least partial data in store */
    if (data->buf_size) {
        rbuf = s_read_buf(ps, buf, len, flags);
        if (rbuf < 0)
            return rbuf;
        len -= rbuf;
        if (len == 0)
            return rbuf;
    }
    /* If timeout == 0, wait forever for packet, otherwise wait till
       timeout milliseconds */
    FD_ZERO(&ready);
    FD_SET(ps->sd, &ready);
    if (data->timeout == 0)
        select(ps->sd + 1, &ready, 0, 0, 0);
    else {
        t.tv_sec    = data->timeout / 1000;
        t.tv_usec   = (data->timeout % 1000) * 1000;
        if (select(ps->sd + 1, &ready, 0, 0, &t) == 0)
            return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
    }
    /* If data is available in time, read it */
    if (FD_ISSET(ps->sd, &ready)) {
        if (flags == PI_MSG_PEEK && len > 256)
            len = 256;
        if (pi_buffer_expect (buf, len) == NULL) {
            errno = ENOMEM;
            return pi_set_error(ps->sd, PI_ERR_GENERIC_MEMORY);
        }
        bytes = read(ps->sd, &buf->data[buf->used], len);
        if (bytes > 0) {
            if (flags == PI_MSG_PEEK) {
                memcpy(data->buf + data->buf_size, buf->data + buf->used, bytes);
                data->buf_size += bytes;
            }
            buf->used += bytes;
            data->rx_bytes += bytes;
            rbuf += bytes;
            LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
                "DEV RX unixserial read %d bytes\n", bytes));
        } else if (bytes < 0) {
            rbuf = bytes;
        }
    } else {
        LOG((PI_DBG_DEV, PI_DBG_LVL_WARN,
            "DEV RX unixserial timeout\n"));
        data->rx_errors++;
        errno = ETIMEDOUT;
        return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
    }
    return rbuf;
}
References buf, flags, pi_buffer_expect(), pi_set_error(), and s_read_buf().
Referenced by pi_serial_impl_init().
s_read_buf()
static size_t s_read_buf (pi_socket_t * ps, pi_buffer_t * buf, size_t len, int flags) static
{
    struct  pi_serial_data *data =
        (struct pi_serial_data *)ps->device->data;
    size_t  rbuf = data->buf_size;
    if (rbuf > len)
        rbuf = len;
    if (pi_buffer_append (buf, data->buf, rbuf) == NULL) {
        errno = ENOMEM;
        return pi_set_error(ps->sd, PI_ERR_GENERIC_MEMORY);
    }
    if (flags != PI_MSG_PEEK) {
        data->buf_size -= rbuf;
        if (data->buf_size > 0)
            memmove(data->buf, &data->buf[rbuf], data->buf_size);
    }
    LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
        "DEV RX unixserial read %d bytes from read-ahead buffer\n", rbuf));
    return rbuf;
}
References buf, flags, pi_buffer_append(), and pi_set_error().
Referenced by s_read().
s_write()
static ssize_t s_write (pi_socket_t * ps, const unsigned char * buf, size_t len, int flags) static
{
    ssize_t total,
        nwrote;
    struct  pi_serial_data *data =
        (struct pi_serial_data *)ps->device->data;
    struct  timeval t;
    fd_set  ready;
    FD_ZERO(&ready);
    FD_SET(ps->sd, &ready);
    total = len;
    while (total > 0) {
        if (data->timeout == 0)
            select(ps->sd + 1, 0, &ready, 0, 0);
        else {
            t.tv_sec    = data->timeout / 1000;
            t.tv_usec   = (data->timeout % 1000) * 1000;
            if (select(ps->sd + 1, 0, &ready, 0, &t) == 0)
                return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
        }
        if (!FD_ISSET(ps->sd, &ready))
            return pi_set_error(ps->sd, PI_ERR_SOCK_TIMEOUT);
        nwrote = write(ps->sd, buf, len);
        if (nwrote < 0) {
            if (errno == EPIPE || errno == EBADF) {
                ps->state = PI_SOCK_CONN_BREAK;
                return pi_set_error(ps->sd, PI_ERR_SOCK_DISCONNECTED);
            }
            return pi_set_error(ps->sd, PI_ERR_SOCK_IO);
        }
        total -= nwrote;
    }
    data->tx_bytes += len;
    /* hack to slow things down so that the Visor will work */
    usleep(10 + len);
    LOG((PI_DBG_DEV, PI_DBG_LVL_DEBUG,
        "DEV TX unixserial wrote %d bytes\n", len));
    return len;
}
References buf, and pi_set_error().
Referenced by pi_serial_impl_init().