pilot-link: src/userland.c File Reference
userland.c File Reference
#include "pi-userland.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "pi-header.h"
#include "pi-socket.h"
#include "pi-dlp.h"
#include "pi-source.h"
Functions
int plu_connect ()
int plu_findcategory (const struct CategoryAppInfo *info, const char *name, int flags)
int plu_getromversion (int sd, plu_romversion_t *d)
int plu_protect_files (char *name, const char *extension, const size_t namelength)
Variables
static const char * env_pilotport = "PILOTPORT"
Function Documentation
plu_connect()
int plu_connect ()
{
    int sd = -1;
    int result;
    struct  SysInfo sys_info;
    /* Determine here for better user feedback on unset port */
    if (plu_port == NULL)
        plu_port = getenv(env_pilotport);
    if (plu_port == NULL) {
        fprintf(stderr, "\n   Unable to determine port to bind\n"
                "   Please use --help for more information\n\n");
        return -1;
    }
    if ((sd = pi_socket(PI_AF_PILOT,
            PI_SOCK_STREAM, PI_PF_DLP)) < 0) {
        fprintf(stderr, "\n   Unable to create socket '%s'\n", plu_port);
        return -1;
    }
    result = pi_bind(sd, plu_port);
    if (result < 0) {
        fprintf(stderr, "   Unable to bind to port: %s\n"
                "   Please use --help for more information\n\n",
                plu_port);
        return result;
    }
    if (!plu_quiet && isatty(fileno(stdout))) {
        printf("\n   Listening for incoming connection on %s... ",
            plu_port);
        fflush(stdout);
    }
    if (pi_listen(sd, 1) < 0) {
        fprintf(stderr, "\n   Error listening on %s\n", plu_port);
        pi_close(sd);
        return -1;
    }
    sd = pi_accept_to(sd, 0, 0, plu_timeout);
    if (sd < 0) {
        fprintf(stderr, "\n   Error accepting data on %s\n", plu_port);
        pi_close(sd);
        return -1;
    }
    if (!plu_quiet && isatty(fileno(stdout))) {
        printf("connected!\n\n");
    }
    if (dlp_ReadSysInfo(sd, &sys_info) < 0) {
        fprintf(stderr, "\n   Error read system info on %s\n", plu_port);
        pi_close(sd);
        return -1;
    }
    dlp_OpenConduit(sd);
    return sd;
}
References dlp_OpenConduit(), dlp_ReadSysInfo(), env_pilotport, pi_accept_to(), pi_bind(), pi_close(), pi_listen(), pi_socket(), plu_port, plu_quiet, plu_timeout, and sd.
Referenced by bindCmd(), CreateSocket(), do_fetch(), main(), main(), and main().
plu_findcategory()
int plu_findcategory (const struct CategoryAppInfo * info, const char * name, int flags)
{
    int cat_index, match_category;
    match_category = -1;
    for (cat_index = 0; cat_index < 16; cat_index += 1) {
        if (info->name[cat_index][0]) {
            if (flags & PLU_CAT_CASE_INSENSITIVE) {
                if (strncasecmp(info->name[cat_index], name, 15) == 0) {
                    match_category = cat_index;
                    break;
                }
            } else {
                if (strncmp(info->name[cat_index],name,15) == 0) {
                    match_category = cat_index;
                    break;
                }
            }
        }
    }
    if ((match_category == -1)  && (flags & PLU_CAT_MATCH_NUMBERS)) {
        while (isspace(*name)) {
            name++;
        }
        if (isdigit(*name)) {
            match_category = atoi(name);
        }
        if ((match_category < 0) || (match_category > 15)) {
            match_category = -1;
        }
    }
    if (flags & PLU_CAT_WARN_UNKNOWN) {
        if (match_category == -1) {
            fprintf(stderr,"   WARNING: Unknown category '%s'%s.\n",
                name,
                (flags & PLU_CAT_DEFAULT_UNFILED) ? ", using 'Unfiled'" : "");
        }
    }
    if (flags & PLU_CAT_DEFAULT_UNFILED) {
        if (match_category == -1) {
            match_category = 0;
        }
    }
    return match_category;
}
References flags, and name.
Referenced by main(), main(), and read_file().
plu_getromversion()
int plu_getromversion (int sd, plu_romversion_t * d)
{
    unsigned long ROMversion;
    if ((sd < 0)  || !d) {
        return -1;
    }
    if (dlp_ReadFeature(sd, makelong("psys"), 1, &ROMversion) < 0) {
        return -1;
    }
    d->major =
        (((ROMversion >> 28) & 0xf) * 10) + ((ROMversion >> 24) & 0xf);
    d->minor = ((ROMversion >> 20) & 0xf);
    d->bugfix = ((ROMversion >> 16) & 0xf);
    d->state = ((ROMversion >> 12) & 0xf);
    d->build =
        (((ROMversion >> 8) & 0xf) * 100) +
        (((ROMversion >> 4) & 0xf) * 10) + (ROMversion & 0xf);
    memset(d->name,0,sizeof(d->name));
    snprintf(d->name, sizeof(d->name),"%d.%d.%d", d->major, d->minor, d->bugfix);
    if (d->state != 3) {
        int len = strlen(d->name);
        snprintf(d->name + len, sizeof(d->name) - len,"-%s%d", (
            (d->state == 0) ? "d" :
            (d->state == 1) ? "a" :
            (d->state == 2) ? "b" : "u"), d->build);
    }
    return 0;
}
References makelong(), and sd.
Referenced by check_romversion().
plu_protect_files()
int plu_protect_files (char * name, const char * extension, const size_t namelength)
{
    char *save_name;
    char c=1;
    save_name = strdup( name );
    if (NULL == save_name) {
        fprintf(stderr,"   ERROR: No memory for filename %s%s\n",name,extension);
        return -1;
    }
    /* 4 byes = _%02d and terminating NUL */
    if (strlen(save_name) + strlen(extension) + 4 > namelength) {
        fprintf(stderr,"   ERROR: Buffer for filename too small.\n");
        free(save_name);
        return -1;
    }
    snprintf(name,namelength,"%s%s",save_name,extension);
    while ( access( name, F_OK ) == 0) {
        snprintf( name, namelength, "%s_%02d%s", save_name, c, extension);
        c++;
        if (c >= 100) {
            fprintf(stderr,"   ERROR: Could not generate filename (tried 100 times).\n");
            free(save_name);
            return 0;
        }
    }
    free(save_name);
    return 1;
}
References name, and strdup().
Referenced by output_picture(), write_all(), WritePicture(), and WritePictures().
Variable Documentation
env_pilotport
const char* env_pilotport = "PILOTPORT" static
Referenced by plu_connect().