pilot-link: libpisync/util.c File Reference
util.c File Reference
#include <stdlib.h>
#include <string.h>
#include "pi-util.h"
Macros
#define PILOT_CHARSET "CP1252"
Functions
int convert_FromPilotChar (const char *charset, const char *ptext, int bytes, char **text)
int convert_FromPilotChar_WithCharset (const char *charset, const char *ptext, int bytes, char **text, const char *pi_charset)
int convert_ToPilotChar (const char *charset, const char *text, int bytes, char **ptext)
int convert_ToPilotChar_WithCharset (const char *charset, const char *text, int bytes, char **ptext, const char *pi_charset)
Macro Definition Documentation
PILOT_CHARSET
#define PILOT_CHARSET "CP1252"
Referenced by convert_FromPilotChar(), convert_FromPilotChar_WithCharset(), convert_ToPilotChar(), and convert_ToPilotChar_WithCharset().
Function Documentation
convert_FromPilotChar()
int convert_FromPilotChar (const char * charset, const char * ptext, int bytes, char ** text)
{
#ifdef HAVE_ICONV
    char*   pcharset;
    if ((pcharset = getenv("PILOT_CHARSET")) == NULL)
        pcharset = PILOT_CHARSET;
    return convert_FromPilotChar_WithCharset(charset, ptext, bytes,
        text, pcharset);
#else
    return -1;
#endif
}
References convert_FromPilotChar_WithCharset(), and PILOT_CHARSET.
convert_FromPilotChar_WithCharset()
int convert_FromPilotChar_WithCharset (const char * charset, const char * ptext, int bytes, char ** text, const char * pi_charset)
{
#ifdef HAVE_ICONV
    char*   ob;
    iconv_t cd;
    size_t  ibl, obl;
    if(NULL==pi_charset){
        pi_charset = PILOT_CHARSET;
    }
    cd = iconv_open(charset, pi_charset);
    if (cd==(iconv_t)-1)
        return -1;
    ibl     = bytes;
    obl     = bytes * 4 + 1;
    *text   = ob = malloc(obl);
    if (iconv(cd, &ptext, &ibl, &ob, &obl) == (size_t)-1)
        return -1;
    *ob = '\0';
    iconv_close(cd);
    return 0;
#else
    return -1;
#endif
}
References PILOT_CHARSET.
Referenced by convert_FromPilotChar().
convert_ToPilotChar()
int convert_ToPilotChar (const char * charset, const char * text, int bytes, char ** ptext)
{
#ifdef HAVE_ICONV
    char*   pcharset;
    if ((pcharset = getenv("PILOT_CHARSET")) == NULL)
        pcharset = PILOT_CHARSET;
    return convert_ToPilotChar_WithCharset(charset, text, bytes,
        ptext, pcharset);
#else
    return -1;
#endif
}
References convert_ToPilotChar_WithCharset(), and PILOT_CHARSET.
convert_ToPilotChar_WithCharset()
int convert_ToPilotChar_WithCharset (const char * charset, const char * text, int bytes, char ** ptext, const char * pi_charset)
{
#ifdef HAVE_ICONV
    char*   ob;
    iconv_t cd;
    size_t  ibl, obl;
    if(NULL==pi_charset){
        pi_charset = PILOT_CHARSET;
    }
    cd = iconv_open(pi_charset, charset);
    if (cd==(iconv_t)-1)
        return -1;
    ibl     = bytes;
    obl     = bytes * 4 + 1;
    *ptext  = ob = malloc(obl);
    if (iconv(cd, &text, &ibl, &ob, &obl) == (size_t)-1)
        return -1;
    *ob = '\0';
    iconv_close(cd);
    return 0;
#else
    return -1;
#endif
}
References PILOT_CHARSET.
Referenced by convert_ToPilotChar().