pilot-link: libpisock/veo.c File Reference
veo.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pi-macros.h"
#include "pi-veo.h"
Functions
void free_Veo (Veo_t *veo)
int pack_Veo (Veo_t *veo, unsigned char *buf, size_t len)
int pack_VeoAppInfo (struct VeoAppInfo *appinfo, unsigned char *record, size_t len)
int unpack_Veo (Veo_t *veo, unsigned char *buffer, size_t len)
int unpack_VeoAppInfo (struct VeoAppInfo *appinfo, unsigned char *record, size_t len)
Function Documentation
free_Veo()
void free_Veo (Veo_t * veo)
{
}
pack_Veo()
int pack_Veo (Veo_t * veo, unsigned char * buf, size_t len)
{
   return( 0 );
}
pack_VeoAppInfo()
int pack_VeoAppInfo (struct VeoAppInfo * appinfo, unsigned char * record, size_t len)
{
    int     i;
    unsigned char *start = record;
    i = pack_CategoryAppInfo(&appinfo->category, record, len);
    if (!record)
        return i + 4;
    if (!i)
        return 0;
    record += i;
    len -= i;
    if (len < 4)
        return 0;
    set_short(record, appinfo->dirty);
    set_byte(record + 2, appinfo->sortByPriority);
    set_byte(record + 3, 0);    /* gapfill */
    record += 4;
    return (record - start);
}
References pack_CategoryAppInfo().
unpack_Veo()
int unpack_Veo (Veo_t * veo, unsigned char * buffer, size_t len)
{
   unsigned char *start = buffer;
   /* consume unknown */
   buffer += 1;
   veo->quality = (unsigned char) get_byte(buffer);
   buffer += 1;
   veo->resolution = (unsigned char) get_byte(buffer);
   buffer += 1;
   /* consume 12 more unknowns */
   buffer += 12;
   veo->picnum = (unsigned long int) get_long(buffer);
   buffer += 4;
   veo->day = (unsigned short int) get_short(buffer);
   buffer += 2;
   veo->month = (unsigned short int) get_short(buffer);
   buffer += 2;
   veo->year = (unsigned short int) get_short(buffer);
   buffer += 2;
   if( veo->resolution == 0 )
     {
    veo->width = 640;
    veo->height = 480;
     }
   else if( veo->resolution == 1 )
     {
    veo->width = 320;
    veo->height = 240;
     }
   else
     fprintf( stderr, "unknown resolution\n" );
   return ( buffer - start );   /* FIXME: return real length */
}
References buffer.
Referenced by WritePicture().
unpack_VeoAppInfo()
int unpack_VeoAppInfo (struct VeoAppInfo * appinfo, unsigned char * record, size_t len)
{
    int     i;
    unsigned char *start = record;
    i = unpack_CategoryAppInfo( &appinfo->category, record, len );
    if (!i)
        return 0;
    record += i;
    len -= i;
    if (len < 4)
        return 0;
    appinfo->dirty = get_short(record);
    record += 2;
    appinfo->sortByPriority = get_byte(record);
    record += 2;
    return (record - start);
}
References unpack_CategoryAppInfo().