#!/bin/sh

PILOT_DATEBOOK='../pilot-datebook -q'
SUCCESS="Passed"
FAILED="Failed"



##########################################################################
IN1_FILE=update_in1.txt
TEST1="endDate=27 oct 1998"
OUT1_FILE=update_out1.txt
EXPECT1_FILE=update_expect1.txt

echo -n "Test1 (${TEST1}): "

cat > ${IN1_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 (Birthday)
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <12 dec 1997 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <13 dec 1997 17:50>:
External Meeting

EOI


cat > ${EXPECT1_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 ()
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <27 oct 1998 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <27 oct 1998 17:50>:
External Meeting

EOI

${PILOT_DATEBOOK} -r longtxt -f ${IN1_FILE} -u "${TEST1}" -w longtxt -f ${OUT1_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
fi
diff ${EXPECT1_FILE} ${OUT1_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
else
	echo "${SUCCESS}"
fi
#rm ${IN1_FILE} ${EXPECT1_FILE} ${OUT1_FILE}
rm ${EXPECT1_FILE} ${OUT1_FILE}


##########################################################################
IN2_FILE=${IN1_FILE}
TEST2="endDate+=21d"
OUT2_FILE=update_out2.txt
EXPECT2_FILE=update_expect2.txt

echo -n "Test2 (${TEST2}): "

cat > ${EXPECT2_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 ()
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <2 jan 1998 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <3 jan 1998 17:50>:
External Meeting

EOI

${PILOT_DATEBOOK} -r longtxt -f ${IN2_FILE} -u "${TEST2}" -w longtxt -f ${OUT2_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
fi
diff ${EXPECT2_FILE} ${OUT2_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
else
	echo "${SUCCESS}"
fi
#rm ${IN2_FILE} ${EXPECT2_FILE} ${OUT2_FILE}
rm ${EXPECT2_FILE} ${OUT2_FILE}


##########################################################################
IN3_FILE=${IN1_FILE}
TEST3="endDate-=23d"
OUT3_FILE=update_out3.txt
EXPECT3_FILE=update_expect3.txt

echo -n "Test3 (${TEST3}): "

cat > ${EXPECT3_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 ()
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <19 nov 1997 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <20 nov 1997 17:50>:
External Meeting

EOI

${PILOT_DATEBOOK} -r longtxt -f ${IN3_FILE} -u "${TEST3}" -w longtxt -f ${OUT3_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
fi
diff ${EXPECT3_FILE} ${OUT3_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
else
	echo "${SUCCESS}"
fi
#rm ${IN3_FILE} ${EXPECT3_FILE} ${OUT3_FILE}
rm ${EXPECT3_FILE} ${OUT3_FILE}


##########################################################################
IN4_FILE=${IN1_FILE}
TEST4="endDate+=27h"
OUT4_FILE=update_out4.txt
EXPECT4_FILE=update_expect4.txt

echo -n "Test4 (${TEST4}): "

cat > ${EXPECT4_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 ()
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <13 dec 1997 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <14 dec 1997 17:50>:
External Meeting

EOI

${PILOT_DATEBOOK} -r longtxt -f ${IN4_FILE} -u "${TEST4}" -w longtxt -f ${OUT4_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
fi
diff ${EXPECT4_FILE} ${OUT4_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
else
	echo "${SUCCESS}"
fi
#rm ${IN4_FILE} ${EXPECT4_FILE} ${OUT4_FILE}
rm ${EXPECT4_FILE} ${OUT4_FILE}


##########################################################################
IN5_FILE=${IN1_FILE}
TEST5="endDate-=1h"
OUT5_FILE=update_out5.txt
EXPECT5_FILE=update_expect5.txt

echo -n "Test5 (${TEST5}): "

cat > ${EXPECT5_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 ()
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <11 dec 1997 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <12 dec 1997 17:50>:
External Meeting

EOI

${PILOT_DATEBOOK} -r longtxt -f ${IN5_FILE} -u "${TEST5}" -w longtxt -f ${OUT5_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
fi
diff ${EXPECT5_FILE} ${OUT5_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
else
	echo "${SUCCESS}"
fi
#rm ${IN5_FILE} ${EXPECT5_FILE} ${OUT5_FILE}
rm ${EXPECT5_FILE} ${OUT5_FILE}


##########################################################################
IN6_FILE=${IN1_FILE}
TEST6="endDate+=2m"
OUT6_FILE=update_out6.txt
EXPECT6_FILE=update_expect6.txt

echo -n "Test6 (${TEST6}): "

cat > ${EXPECT6_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 ()
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <12 dec 1997 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <13 dec 1997 17:50>:
External Meeting

EOI

${PILOT_DATEBOOK} -r longtxt -f ${IN6_FILE} -u "${TEST6}" -w longtxt -f ${OUT6_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
fi
diff ${EXPECT6_FILE} ${OUT6_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
else
	echo "${SUCCESS}"
fi
#rm ${IN6_FILE} ${EXPECT6_FILE} ${OUT6_FILE}
rm ${EXPECT6_FILE} ${OUT6_FILE}


##########################################################################
IN7_FILE=${IN1_FILE}
TEST7="endDate-=3m"
OUT7_FILE=update_out7.txt
EXPECT7_FILE=update_expect7.txt

echo -n "Test7 (${TEST7}): "

cat > ${EXPECT7_FILE} <<EOI
UNTIMED_EVENT <5849139> on <12 may 1997>:
category=2 ()
*1971 Geburtstag
REPEAT from <12 may 1997> until <forever>: <yearly> on <may 12>
ALARM <2 days before>
NOTE:
##@@B@@@@

APPOINTMENT <5849151> from <12 dec 1997 11:00> to <11 dec 1997 12:00>:
Internal Meeting
ALARM <5 min before>

APPOINTMENT <5849146> from <13 dec 1997 16:45> to <12 dec 1997 17:50>:
External Meeting

EOI

${PILOT_DATEBOOK} -r longtxt -f ${IN7_FILE} -u "${TEST7}" -w longtxt -f ${OUT7_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
fi
diff ${EXPECT7_FILE} ${OUT7_FILE}
if [ $? -ne 0 ]; then
	echo "${FAILED}"
	exit 1
else
	echo "${SUCCESS}"
fi
rm ${IN7_FILE} ${EXPECT7_FILE} ${OUT7_FILE}
