.TH install-hinote 1 "Palm Computing Device Tools" "Free Software Foundation" \" -*- nroff -*-

.SH NAME
.B install-hinote 
\- installs a new Hi-Note in a Palm Device

.SH SYNOPSIS
.B install-hinote 
\-p <port> filename [filename filename ...] -c <category>

.SH DESCRIPTION
.B install-hinote
allows the user to write one or more files as a new Hi-Note or into the
Hi-Notes Palm application itself, on the Palm handheld device. Please see
http://www.cyclos.com/ for more information on Hi-Note.

.SS OPTIONS
.TP
.BI \-p\ \--port\  <port> ,
Use device file 
.I <port>
to communicate with the Palm handheld device. If this is not specified, will
look for the $PILOTPORT environment variable. If both are not found, will   
fall back to /dev/pilot

.TP
.BI \-h\ \--help\,
Display help synopsis for 
.B install-hinote

.TP
.BI \-v\ \--version\,
Display version of
.B install-hinote

.TP
.BI \-c\ \--category\ <category>,
Write files to <category> in the Hi-NOte application

.SH USAGE
The program will connect to a target Palm handheld device, and writes the
file or files given on the command line into the Hi-Note application.

.SH KNOWN BUGS
The Palm Device may have a maximum length on Hi-Note sizes.

.SH "REPORTING BUGS"
Report bugs at
.I http://bugs.pilot-link.org/

.SH AUTHOR
.B install-hinote
was written by Bill Goodman <\fIbgoodman@cyclos.com\fP>
