.TH PI-GETRAM 1 "Palm Computing Device Tools" "FSF" \" -*- nroff -*-

.SH NAME
.B pi-getram
\- Retrieves the RAM image from your Palm device

.SH SYNOPSIS
.B pi-getram
\-p <port> [--copilot] [ramfile]

.SH DESCRIPTION
.B pi-getram
is used to fetch the RAM from your Palm handheld device

.SS OPTIONS
.TP
.BI \-p\ \--port\  <port> ,
Use device file
.I port
to communicate with the Palm handheld device. If this is not specified, will
look for the $PILOTPORT environment variable. If both are not found, will
fall back to /dev/pilot.
   
.TP
.BI \-h\ \--help\,
Display help synopsis for
.B pi-getram

.TP
.BI \-v\ \--version\,
Display version of
.B pi-getram

.TP
.BI \--copilot\,
format the RAM for use in the CoPilot application, instead of the POSE format

.TP
.BI filename
Write the RAM to this file

.SH USAGE
Connect to a target Palm handheld device and fetch the RAM from the device.

.SH KNOWN BUGS
.B pi-getram 
has no known bugs

.SH "REPORTING BUGS"
Report bugs at
.I http://bugs.pilot-link.org/

.SH AUTHOR
.B pi-getram
was written by Kenneth Albanowski
