.TH READ-NOTEPAD 1 "Palm Computing Device Tools" "FSF" \" -*- nroff -*-

.SH NAME
.B read-notepad 
\- Connect to the Palm handheld device and list the record information found
in the Notepad application. Alternately, if no options are given, each
record's image will be converted to a Portable Network Graphic (.png) file.

.SH SYNOPSIS
.B read-notepad 
\-p <port> --list

.SH DESCRIPTION
.B read-notepad 
allows a PalmOS 4.0 or later user to read the data stored in the Palm
Notepad application and extract the data into images and convert them to .png
files on their system.

.SS OPTIONS
.TP
.BI \-p\ \--port\  <port> ,
Use device file 
.I port
to communicate with the Palm handheld device. If this is not specified, will
look for the $PILOTPORT environment variable. If both are not found, will
fall back to /dev/pilot.

.TP
.BI \-h\ \--help\,
Display help synopsis

.TP
.BI \-v\ \--version\,
Display version of
.B read-notepad

.TP
.BI \-l\ --list\,
List picture information found on the device instead of converting them to
image files

.SH USAGE
The program will connect to the target Palm handheld device, and list or
convert the records and images found in the Palm Notepad application to
Portable Network Graphic (.png) files.

.SH KNOWN BUGS
.B read-notepad
has no known bugs.

.SH "REPORTING BUGS"
Report bugs at
.I http://bugs.pilot-link.org/

.SH AUTHOR
.B read-notepad 
was written by Angus Ainslie <\fIangusa@deltatee.com\fP>.
