package org.gnu.pdapilot;
public class Constants {
   public static int dlpDBFlagResource = 1;
   public static int dlpDBFlagReadOnly = 2;
   public static int dlpDBFlagAppInfoDirty = 4;
   public static int dlpDBFlagBackup = 8;
   public static int dlpDBFlagOpen = 32768;
   public static int dlpDBFlagNewer = 16;
   public static int dlpDBFlagReset = 32;
   public static int dlpRecAttrDeleted = 128;
   public static int dlpRecAttrDirty = 64;
   public static int dlpRecAttrBusy = 32;
   public static int dlpRecAttrSecret = 16;
   public static int dlpRecAttrArchived = 8;
   public static int dlpOpenRead = 128;
   public static int dlpOpenWrite = 64;
   public static int dlpOpenExclusive = 32;
   public static int dlpOpenSecret = 16;
   public static int dlpOpenReadWrite = 192;
   public static int dlpEndCodeNormal = 0;
   public static int dlpEndCodeOutOfMemory = 1;
   public static int dlpEndCodeUserCan = 2;
   public static int dlpEndCodeOther = 3;
   public static int dlpDBListRAM = 128;
   public static int dlpDBListROM = 64;
   public static int PILOT_LINK_VERSION = 0;
   public static int PILOT_LINK_MAJOR = 10;
   public static int PILOT_LINK_MINOR = 1;
   public static int PI_AF_PILOT = 0;
   public static int PI_PF_DEV = 1;
   public static int PI_PF_SLP = 2;
   public static int PI_PF_PADP = 4;
   public static int PI_PF_NET = 5;
   public static int PI_PF_DLP = 6;
   public static int PI_SOCK_STREAM = 16;
   public static int PI_SOCK_RAW = 48;
   }
